/* ============================================================
   STUTI — Guru / Dattātreya full text
   Śrī Dattātreya Aṣṭottara Śatanāmāvali — the hundred and eight names,
   one to a line, each its own numbered verse. Devanāgarī keyed against
   the traditional pāṭha. `tel` carries the Telugu meaning, not the
   mūla. Title must match STOTRA_INDEX exactly.
   ============================================================ */
export const extra = [{
  deities: ["guru"],
  title: "Śrī Dattātreya Aṣṭottara Śatanāmāvali",
  blurb: "The hundred and eight names of the guru born to Atri and Anasūyā — Brahmā, Viṣṇu and Śiva together in the one ascetic form — each offered with Oṁ and namaḥ.",
  sections: [{ tel: "నామావళి", roman: "The Hundred and Eight Names" }],
  verses: [
    { s: 0, n: "1",
      deva: "ॐ श्रीदत्ताय नमः ।",
      iast: "oṁ śrīdattāya namaḥ ।",
      en: "Gift of Śrī.",
      tel: "శ్రీదేవి వరప్రసాదము." },
    { s: 0, n: "2",
      deva: "ॐ देवदत्ताय नमः ।",
      iast: "oṁ devadattāya namaḥ ।",
      en: "Gift of the gods.",
      tel: "దేవతల వరప్రసాదము." },
    { s: 0, n: "3",
      deva: "ॐ ब्रह्मदत्ताय नमः ।",
      iast: "oṁ brahmadattāya namaḥ ।",
      en: "Gift of Brahmā.",
      tel: "బ్రహ్మ ప్రసాదించినవాడు." },
    { s: 0, n: "4",
      deva: "ॐ विष्णुदत्ताय नमः ।",
      iast: "oṁ viṣṇudattāya namaḥ ।",
      en: "Gift of Viṣṇu.",
      tel: "విష్ణువు ప్రసాదించినవాడు." },
    { s: 0, n: "5",
      deva: "ॐ शिवदत्ताय नमः ।",
      iast: "oṁ śivadattāya namaḥ ।",
      en: "Gift of Śiva.",
      tel: "శివుడు ప్రసాదించినవాడు." },
    { s: 0, n: "6",
      deva: "ॐ अत्रिदत्ताय नमः ।",
      iast: "oṁ atridattāya namaḥ ।",
      en: "Gift to Atri.",
      tel: "అత్రి మహర్షికి ప్రసాదింపబడినవాడు." },
    { s: 0, n: "7",
      deva: "ॐ आत्रेयाय नमः ।",
      iast: "oṁ ātreyāya namaḥ ।",
      en: "Son of Atri.",
      tel: "అత్రిపుత్రుడు (ఆత్రేయుడు)." },
    { s: 0, n: "8",
      deva: "ॐ अत्रिवरदाय नमः ।",
      iast: "oṁ atrivaradāya namaḥ ।",
      en: "Granter of Atri's boon.",
      tel: "అత్రికి వరమిచ్చినవాడు." },
    { s: 0, n: "9",
      deva: "ॐ अनुसूयायै नमः ।",
      iast: "oṁ anusūyāyai namaḥ ।",
      en: "Unto Anasūyā.",
      tel: "అనసూయాదేవికి చెందినవాడు." },
    { s: 0, n: "10",
      deva: "ॐ अनसूयासूनवे नमः ।",
      iast: "oṁ anasūyāsūnave namaḥ ।",
      en: "Son of Anasūyā.",
      tel: "అనసూయాపుత్రుడు." },
    { s: 0, n: "11",
      deva: "ॐ अवधूताय नमः ।",
      iast: "oṁ avadhūtāya namaḥ ।",
      en: "The ever-pure ascetic.",
      tel: "అవధూతుడు (శుద్ధ యోగి)." },
    { s: 0, n: "12",
      deva: "ॐ धर्माय नमः ।",
      iast: "oṁ dharmāya namaḥ ।",
      en: "Righteousness itself.",
      tel: "ధర్మస్వరూపుడు." },
    { s: 0, n: "13",
      deva: "ॐ धर्मपरायणाय नमः ।",
      iast: "oṁ dharmaparāyaṇāya namaḥ ।",
      en: "Devoted to dharma.",
      tel: "ధర్మపరాయణుడు." },
    { s: 0, n: "14",
      deva: "ॐ धर्मपतये नमः ।",
      iast: "oṁ dharmapataye namaḥ ।",
      en: "Lord of dharma.",
      tel: "ధర్మపతి." },
    { s: 0, n: "15",
      deva: "ॐ सिद्धाय नमः ।",
      iast: "oṁ siddhāya namaḥ ।",
      en: "The perfected.",
      tel: "సిద్ధుడు." },
    { s: 0, n: "16",
      deva: "ॐ सिद्धिदाय नमः ।",
      iast: "oṁ siddhidāya namaḥ ।",
      en: "Giver of perfection.",
      tel: "సిద్ధినిచ్చువాడు." },
    { s: 0, n: "17",
      deva: "ॐ सिद्धिपतये नमः ।",
      iast: "oṁ siddhipataye namaḥ ।",
      en: "Lord of the siddhis.",
      tel: "సిద్ధిపతి." },
    { s: 0, n: "18",
      deva: "ॐ सिद्धसेविताय नमः ।",
      iast: "oṁ siddhasevitāya namaḥ ।",
      en: "Served by the siddhas.",
      tel: "సిద్ధులచే సేవింపబడువాడు." },
    { s: 0, n: "19",
      deva: "ॐ गुरवे नमः ।",
      iast: "oṁ gurave namaḥ ।",
      en: "The guru.",
      tel: "గురువు." },
    { s: 0, n: "20",
      deva: "ॐ गुरुगम्याय नमः ।",
      iast: "oṁ gurugamyāya namaḥ ।",
      en: "Reached through the guru.",
      tel: "గురువు ద్వారా చేరదగినవాడు." },
    { s: 0, n: "21",
      deva: "ॐ गुरोर्गुरुतराय नमः ।",
      iast: "oṁ gurorgurutarāya namaḥ ।",
      en: "Greater than the greatest guru.",
      tel: "గురువులకే గురువైనవాడు." },
    { s: 0, n: "22",
      deva: "ॐ गरिष्ठाय नमः ।",
      iast: "oṁ gariṣṭhāya namaḥ ।",
      en: "The most venerable.",
      tel: "అత్యంత గరిష్ఠుడు." },
    { s: 0, n: "23",
      deva: "ॐ वरिष्ठाय नमः ।",
      iast: "oṁ variṣṭhāya namaḥ ।",
      en: "The most excellent.",
      tel: "అత్యంత శ్రేష్ఠుడు." },
    { s: 0, n: "24",
      deva: "ॐ महिष्ठाय नमः ।",
      iast: "oṁ mahiṣṭhāya namaḥ ।",
      en: "The most great.",
      tel: "అత్యంత మహనీయుడు." },
    { s: 0, n: "25",
      deva: "ॐ महात्मने नमः ।",
      iast: "oṁ mahātmane namaḥ ।",
      en: "The great soul.",
      tel: "మహాత్ముడు." },
    { s: 0, n: "26",
      deva: "ॐ योगाय नमः ।",
      iast: "oṁ yogāya namaḥ ।",
      en: "Yoga itself.",
      tel: "యోగస్వరూపుడు." },
    { s: 0, n: "27",
      deva: "ॐ योगगम्याय नमः ।",
      iast: "oṁ yogagamyāya namaḥ ।",
      en: "Reached through yoga.",
      tel: "యోగము ద్వారా చేరదగినవాడు." },
    { s: 0, n: "28",
      deva: "ॐ योगीदेशकराय नमः ।",
      iast: "oṁ yogīdeśakarāya namaḥ ।",
      en: "Guide of yogis.",
      tel: "యోగులకు మార్గదర్శకుడు." },
    { s: 0, n: "29",
      deva: "ॐ योगरतये नमः ।",
      iast: "oṁ yogarataye namaḥ ।",
      en: "Delighting in yoga.",
      tel: "యోగమునందు రమించువాడు." },
    { s: 0, n: "30",
      deva: "ॐ योगीशाय नमः ।",
      iast: "oṁ yogīśāya namaḥ ।",
      en: "Lord of yogis.",
      tel: "యోగీశ్వరుడు." },
    { s: 0, n: "31",
      deva: "ॐ योगाधीशाय नमः ।",
      iast: "oṁ yogādhīśāya namaḥ ।",
      en: "Overlord of yoga.",
      tel: "యోగాధీశుడు." },
    { s: 0, n: "32",
      deva: "ॐ योगपरायणाय नमः ।",
      iast: "oṁ yogaparāyaṇāya namaḥ ।",
      en: "Wholly devoted to yoga.",
      tel: "యోగపరాయణుడు." },
    { s: 0, n: "33",
      deva: "ॐ योगिध्येयाङ्घ्रिपङ्कजाय नमः ।",
      iast: "oṁ yogidhyeyāṅghripaṅkajāya namaḥ ।",
      en: "Whose lotus feet the yogis meditate on.",
      tel: "యోగులు ధ్యానించు పాదపద్మములు గలవాడు." },
    { s: 0, n: "34",
      deva: "ॐ दिगम्बराय नमः ।",
      iast: "oṁ digambarāya namaḥ ।",
      en: "Clad in the directions.",
      tel: "దిగంబరుడు." },
    { s: 0, n: "35",
      deva: "ॐ दिव्याम्बराय नमः ।",
      iast: "oṁ divyāmbarāya namaḥ ।",
      en: "Clad in divine raiment.",
      tel: "దివ్యాంబరధారి." },
    { s: 0, n: "36",
      deva: "ॐ पीताम्बराय नमः ।",
      iast: "oṁ pītāmbarāya namaḥ ।",
      en: "Clad in yellow.",
      tel: "పీతాంబరధారి." },
    { s: 0, n: "37",
      deva: "ॐ श्वेताम्बराय नमः ।",
      iast: "oṁ śvetāmbarāya namaḥ ।",
      en: "Clad in white.",
      tel: "శ్వేతాంబరధారి." },
    { s: 0, n: "38",
      deva: "ॐ चित्राम्बराय नमः ।",
      iast: "oṁ citrāmbarāya namaḥ ।",
      en: "Clad in many colours.",
      tel: "చిత్రాంబరధారి." },
    { s: 0, n: "39",
      deva: "ॐ बालाय नमः ।",
      iast: "oṁ bālāya namaḥ ।",
      en: "The child.",
      tel: "బాలుడు." },
    { s: 0, n: "40",
      deva: "ॐ बालवीर्याय नमः ।",
      iast: "oṁ bālavīryāya namaḥ ।",
      en: "Of a child's vigour.",
      tel: "బాలవీర్యుడు." },
    { s: 0, n: "41",
      deva: "ॐ कुमाराय नमः ।",
      iast: "oṁ kumārāya namaḥ ।",
      en: "The youth.",
      tel: "కుమారుడు." },
    { s: 0, n: "42",
      deva: "ॐ किशोराय नमः ।",
      iast: "oṁ kiśorāya namaḥ ।",
      en: "The boy.",
      tel: "కిశోరుడు." },
    { s: 0, n: "43",
      deva: "ॐ कन्दर्पमोहनाय नमः ।",
      iast: "oṁ kandarpamohanāya namaḥ ।",
      en: "Who bewilders even Kāma.",
      tel: "మన్మథుని మోహింపజేయువాడు." },
    { s: 0, n: "44",
      deva: "ॐ अर्धाङ्गालिङ्गिताङ्गनाय नमः ।",
      iast: "oṁ ardhāṅgāliṅgitāṅganāya namaḥ ।",
      en: "Embracing his consort with half his body.",
      tel: "అర్ధాంగమున దేవిని ఆలింగనము చేసుకున్నవాడు." },
    { s: 0, n: "45",
      deva: "ॐ सुरागाय नमः ।",
      iast: "oṁ surāgāya namaḥ ।",
      en: "Of true passion.",
      tel: "సురాగుడు." },
    { s: 0, n: "46",
      deva: "ॐ विरागाय नमः ।",
      iast: "oṁ virāgāya namaḥ ।",
      en: "Dispassionate.",
      tel: "విరాగుడు." },
    { s: 0, n: "47",
      deva: "ॐ वीतरागाय नमः ।",
      iast: "oṁ vītarāgāya namaḥ ।",
      en: "Free of all passion.",
      tel: "వీతరాగుడు." },
    { s: 0, n: "48",
      deva: "ॐ अमृतवर्षिणे नमः ।",
      iast: "oṁ amṛtavarṣiṇe namaḥ ।",
      en: "A rain of nectar.",
      tel: "అమృతవర్షి." },
    { s: 0, n: "49",
      deva: "ॐ उग्राय नमः ।",
      iast: "oṁ ugrāya namaḥ ।",
      en: "The fierce.",
      tel: "ఉగ్రుడు." },
    { s: 0, n: "50",
      deva: "ॐ अनुग्ररूपाय नमः ।",
      iast: "oṁ anugrarūpāya namaḥ ।",
      en: "Of a gentle, gracious form.",
      tel: "అనుగ్రహరూపుడు." },
    { s: 0, n: "51",
      deva: "ॐ स्थविराय नमः ।",
      iast: "oṁ sthavirāya namaḥ ।",
      en: "The ancient one.",
      tel: "స్థవిరుడు (వృద్ధుడు)." },
    { s: 0, n: "52",
      deva: "ॐ स्थवीयसे नमः ।",
      iast: "oṁ sthavīyase namaḥ ।",
      en: "The most venerable elder.",
      tel: "అత్యంత పూజ్యుడైన వృద్ధుడు." },
    { s: 0, n: "53",
      deva: "ॐ शान्ताय नमः ।",
      iast: "oṁ śāntāya namaḥ ।",
      en: "The tranquil.",
      tel: "శాంతుడు." },
    { s: 0, n: "54",
      deva: "ॐ अघोराय नमः ।",
      iast: "oṁ aghorāya namaḥ ।",
      en: "The un-terrible.",
      tel: "అఘోరుడు." },
    { s: 0, n: "55",
      deva: "ॐ गूढाय नमः ।",
      iast: "oṁ gūḍhāya namaḥ ।",
      en: "The hidden one.",
      tel: "గూఢుడు." },
    { s: 0, n: "56",
      deva: "ॐ ऊर्ध्वरेतसे नमः ।",
      iast: "oṁ ūrdhvaretase namaḥ ।",
      en: "Of upward-drawn seed, the perfect celibate.",
      tel: "ఊర్ధ్వరేతస్కుడు (బ్రహ్మచర్యనిష్ఠుడు)." },
    { s: 0, n: "57",
      deva: "ॐ एकवक्त्राय नमः ।",
      iast: "oṁ ekavaktrāya namaḥ ।",
      en: "One-faced.",
      tel: "ఏకవక్త్రుడు." },
    { s: 0, n: "58",
      deva: "ॐ अनेकवक्त्राय नमः ।",
      iast: "oṁ anekavaktrāya namaḥ ।",
      en: "Many-faced.",
      tel: "అనేకవక్త్రుడు." },
    { s: 0, n: "59",
      deva: "ॐ द्विनेत्राय नमः ।",
      iast: "oṁ dvinetrāya namaḥ ।",
      en: "Two-eyed.",
      tel: "ద్వినేత్రుడు." },
    { s: 0, n: "60",
      deva: "ॐ त्रिनेत्राय नमः ।",
      iast: "oṁ trinetrāya namaḥ ।",
      en: "Three-eyed.",
      tel: "త్రినేత్రుడు." },
    { s: 0, n: "61",
      deva: "ॐ द्विभुजाय नमः ।",
      iast: "oṁ dvibhujāya namaḥ ।",
      en: "Two-armed.",
      tel: "ద్విభుజుడు." },
    { s: 0, n: "62",
      deva: "ॐ षड्भुजाय नमः ।",
      iast: "oṁ ṣaḍbhujāya namaḥ ।",
      en: "Six-armed.",
      tel: "షడ్భుజుడు." },
    { s: 0, n: "63",
      deva: "ॐ अक्षमालिने नमः ।",
      iast: "oṁ akṣamāline namaḥ ।",
      en: "Wearing a rosary.",
      tel: "అక్షమాలధారి." },
    { s: 0, n: "64",
      deva: "ॐ कमण्डलुधारिणे नमः ।",
      iast: "oṁ kamaṇḍaludhāriṇe namaḥ ।",
      en: "Bearing the water-pot.",
      tel: "కమండలుధారి." },
    { s: 0, n: "65",
      deva: "ॐ शूलिने नमः ।",
      iast: "oṁ śūline namaḥ ।",
      en: "Bearing the trident.",
      tel: "శూలధారి." },
    { s: 0, n: "66",
      deva: "ॐ डमरुधारिणे नमः ।",
      iast: "oṁ ḍamarudhāriṇe namaḥ ।",
      en: "Bearing the small drum.",
      tel: "డమరుకధారి." },
    { s: 0, n: "67",
      deva: "ॐ शङ्खिने नमः ।",
      iast: "oṁ śaṅkhine namaḥ ।",
      en: "Bearing the conch.",
      tel: "శంఖధారి." },
    { s: 0, n: "68",
      deva: "ॐ गदिने नमः ।",
      iast: "oṁ gadine namaḥ ।",
      en: "Bearing the mace.",
      tel: "గదాధారి." },
    { s: 0, n: "69",
      deva: "ॐ मुनये नमः ।",
      iast: "oṁ munaye namaḥ ।",
      en: "The sage.",
      tel: "ముని." },
    { s: 0, n: "70",
      deva: "ॐ मौलिने नमः ।",
      iast: "oṁ mauline namaḥ ।",
      en: "The crowned one.",
      tel: "కిరీటధారి." },
    { s: 0, n: "71",
      deva: "ॐ विरूपाय नमः ।",
      iast: "oṁ virūpāya namaḥ ।",
      en: "Of every strange form.",
      tel: "విరూపుడు." },
    { s: 0, n: "72",
      deva: "ॐ स्वरूपाय नमः ।",
      iast: "oṁ svarūpāya namaḥ ।",
      en: "Of his own true form.",
      tel: "స్వరూపుడు." },
    { s: 0, n: "73",
      deva: "ॐ सहस्रशिरसे नमः ।",
      iast: "oṁ sahasraśirase namaḥ ।",
      en: "Of a thousand heads.",
      tel: "సహస్రశిరుడు." },
    { s: 0, n: "74",
      deva: "ॐ सहस्राक्षाय नमः ।",
      iast: "oṁ sahasrākṣāya namaḥ ।",
      en: "A thousand eyes.",
      tel: "సహస్రాక్షుడు." },
    { s: 0, n: "75",
      deva: "ॐ सहस्रबाहवे नमः ।",
      iast: "oṁ sahasrabāhave namaḥ ।",
      en: "A thousand arms.",
      tel: "సహస్రబాహుడు." },
    { s: 0, n: "76",
      deva: "ॐ सहस्रायुधाय नमः ।",
      iast: "oṁ sahasrāyudhāya namaḥ ।",
      en: "A thousand weapons.",
      tel: "సహస్రాయుధుడు." },
    { s: 0, n: "77",
      deva: "ॐ सहस्रपादाय नमः ।",
      iast: "oṁ sahasrapādāya namaḥ ।",
      en: "A thousand feet.",
      tel: "సహస్రపాదుడు." },
    { s: 0, n: "78",
      deva: "ॐ सहस्रपद्मार्चिताय नमः ।",
      iast: "oṁ sahasrapadmārcitāya namaḥ ।",
      en: "Worshipped with a thousand lotuses.",
      tel: "సహస్రపద్మములచే పూజింపబడువాడు." },
    { s: 0, n: "79",
      deva: "ॐ पद्महस्ताय नमः ।",
      iast: "oṁ padmahastāya namaḥ ।",
      en: "Lotus-handed.",
      tel: "పద్మహస్తుడు." },
    { s: 0, n: "80",
      deva: "ॐ पद्मपादाय नमः ।",
      iast: "oṁ padmapādāya namaḥ ।",
      en: "Lotus-footed.",
      tel: "పద్మపాదుడు." },
    { s: 0, n: "81",
      deva: "ॐ पद्मनाभाय नमः ।",
      iast: "oṁ padmanābhāya namaḥ ।",
      en: "Lotus-naveled.",
      tel: "పద్మనాభుడు." },
    { s: 0, n: "82",
      deva: "ॐ पद्ममालिने नमः ।",
      iast: "oṁ padmamāline namaḥ ।",
      en: "Garlanded with lotuses.",
      tel: "పద్మమాలాధారి." },
    { s: 0, n: "83",
      deva: "ॐ पद्मगर्भारुणाक्षाय नमः ।",
      iast: "oṁ padmagarbhāruṇākṣāya namaḥ ।",
      en: "Whose reddish eyes are the lotus's own womb.",
      tel: "పద్మగర్భము వంటి ఎర్రని కన్నులు గలవాడు." },
    { s: 0, n: "84",
      deva: "ॐ पद्मकिञ्जल्कवर्चसे नमः ।",
      iast: "oṁ padmakiñjalkavarcase namaḥ ।",
      en: "Radiant as the lotus's golden filament.",
      tel: "పద్మకేసరము వలె ప్రకాశించువాడు." },
    { s: 0, n: "85",
      deva: "ॐ ज्ञानिने नमः ।",
      iast: "oṁ jñānine namaḥ ।",
      en: "Possessed of knowledge.",
      tel: "జ్ఞాని." },
    { s: 0, n: "86",
      deva: "ॐ ज्ञानगम्याय नमः ।",
      iast: "oṁ jñānagamyāya namaḥ ।",
      en: "Reached through knowledge.",
      tel: "జ్ఞానము ద్వారా చేరదగినవాడు." },
    { s: 0, n: "87",
      deva: "ॐ ज्ञानविज्ञानमूर्तये नमः ।",
      iast: "oṁ jñānavijñānamūrtaye namaḥ ।",
      en: "The very form of knowledge and its realisation.",
      tel: "జ్ఞానవిజ్ఞాన స్వరూపుడు." },
    { s: 0, n: "88",
      deva: "ॐ ध्यानिने नमः ।",
      iast: "oṁ dhyānine namaḥ ।",
      en: "Absorbed in meditation.",
      tel: "ధ్యానపరుడు." },
    { s: 0, n: "89",
      deva: "ॐ ध्याननिष्ठाय नमः ।",
      iast: "oṁ dhyānaniṣṭhāya namaḥ ।",
      en: "Established in meditation.",
      tel: "ధ్యానమునందు నిష్ఠ గలవాడు." },
    { s: 0, n: "90",
      deva: "ॐ ध्यानस्तिमितमूर्तये नमः ।",
      iast: "oṁ dhyānastimitamūrtaye namaḥ ।",
      en: "Whose form is stilled in meditation.",
      tel: "ధ్యానమున నిశ్చలమైన స్వరూపము గలవాడు." },
    { s: 0, n: "91",
      deva: "ॐ धूलिधूसरिताङ्गाय नमः ।",
      iast: "oṁ dhūlidhūsaritāṅgāya namaḥ ।",
      en: "Limbs grey with dust.",
      tel: "ధూళితో ధూసరమైన అంగములు గలవాడు." },
    { s: 0, n: "92",
      deva: "ॐ चन्दनलिप्तमूर्तये नमः ।",
      iast: "oṁ candanaliptamūrtaye namaḥ ।",
      en: "Body anointed with sandal.",
      tel: "చందనము పూయబడిన మూర్తి." },
    { s: 0, n: "93",
      deva: "ॐ भस्मोद्धूलितदेहाय नमः ।",
      iast: "oṁ bhasmoddhūlitadehāya namaḥ ।",
      en: "Form smeared with holy ash.",
      tel: "భస్మముచే అలంకరింపబడిన దేహము గలవాడు." },
    { s: 0, n: "94",
      deva: "ॐ दिव्यगन्धानुलेपिने नमः ।",
      iast: "oṁ divyagandhānulepine namaḥ ।",
      en: "Anointed with divine fragrance.",
      tel: "దివ్యగంధములు పూసినవాడు." },
    { s: 0, n: "95",
      deva: "ॐ प्रसन्नाय नमः ।",
      iast: "oṁ prasannāya namaḥ ।",
      en: "Ever gracious.",
      tel: "ప్రసన్నుడు." },
    { s: 0, n: "96",
      deva: "ॐ प्रमत्ताय नमः ।",
      iast: "oṁ pramattāya namaḥ ।",
      en: "Rapt beyond himself.",
      tel: "ప్రమత్తుడు." },
    { s: 0, n: "97",
      deva: "ॐ प्रकृष्टार्थप्रदाय नमः ।",
      iast: "oṁ prakṛṣṭārthapradāya namaḥ ।",
      en: "Giver of the highest good.",
      tel: "ఉత్కృష్టమైన అర్థమునిచ్చువాడు." },
    { s: 0, n: "98",
      deva: "ॐ अष्टैश्वर्यप्रदाय नमः ।",
      iast: "oṁ aṣṭaiśvaryapradāya namaḥ ।",
      en: "Giver of the eight powers.",
      tel: "అష్టైశ్వర్యములనిచ్చువాడు." },
    { s: 0, n: "99",
      deva: "ॐ वरदाय नमः ।",
      iast: "oṁ varadāya namaḥ ।",
      en: "The boon-giver.",
      tel: "వరదుడు." },
    { s: 0, n: "100",
      deva: "ॐ वरीयसे नमः ।",
      iast: "oṁ varīyase namaḥ ।",
      en: "The most excellent.",
      tel: "అత్యంత శ్రేష్ఠుడు." },
    { s: 0, n: "101",
      deva: "ॐ ब्रह्मणे नमः ।",
      iast: "oṁ brahmaṇe namaḥ ।",
      en: "Brahman itself.",
      tel: "బ్రహ్మస్వరూపుడు." },
    { s: 0, n: "102",
      deva: "ॐ ब्रह्मरूपाय नमः ।",
      iast: "oṁ brahmarūpāya namaḥ ।",
      en: "Of the form of Brahmā.",
      tel: "బ్రహ్మదేవుని రూపము గలవాడు." },
    { s: 0, n: "103",
      deva: "ॐ विष्णवे नमः ।",
      iast: "oṁ viṣṇave namaḥ ।",
      en: "Viṣṇu.",
      tel: "విష్ణుస్వరూపుడు." },
    { s: 0, n: "104",
      deva: "ॐ विश्वरूपिणे नमः ।",
      iast: "oṁ viśvarūpiṇe namaḥ ।",
      en: "Of the form of the universe.",
      tel: "విశ్వరూపుడు." },
    { s: 0, n: "105",
      deva: "ॐ शङ्कराय नमः ।",
      iast: "oṁ śaṅkarāya namaḥ ।",
      en: "Śiva, the bringer of good.",
      tel: "శంకరుడు." },
    { s: 0, n: "106",
      deva: "ॐ आत्मने नमः ।",
      iast: "oṁ ātmane namaḥ ।",
      en: "The self.",
      tel: "ఆత్మ." },
    { s: 0, n: "107",
      deva: "ॐ अन्तरात्मने नमः ।",
      iast: "oṁ antarātmane namaḥ ।",
      en: "The inner self.",
      tel: "అంతరాత్మ." },
    { s: 0, n: "108",
      deva: "ॐ परमात्मने नमः ।",
      iast: "oṁ paramātmane namaḥ ।",
      en: "The supreme self.",
      tel: "పరమాత్మ." },
  ],
},];
