/* ============================================================
   STUTI — Subrahmaṇya full texts (desktop batch, files 17/18/19/22)
   Jaya Skanda · Daṇḍapāṇi Pañcaratnam · Daṇḍāyudhapāṇyaṣṭakam · Ṣaṇmukha Stotram
   Converted verbatim from the user's sourced dossier files —
   Devanāgarī is the source of truth; verses carry en/tel/hi glosses
   inline. Titles must match STOTRA_INDEX exactly.
   ============================================================ */
export const extra = [{
  deities: ["subrahmanya"],
  title: "Jaya Skanda Stotram",
  blurb: "Every pāda opens with the same shout — jaya, victory — one name, one kinship, one exploit at a time.",
  sections: [{ tel: "మంగళాచరణం", roman: "Maṅgalācaraṇam" }, { tel: "స్తోత్రం", roman: "The Hymn" }, { tel: "ఉపసంహారం", roman: "The Close" }],
  verses: [
    { s: 0, n: null,
      deva: "ॐ श्रीगणेशाय नमः ।\n॥ श्रीः ॥",
      iast: "oṁ śrīgaṇeśāya namaḥ |\n|| śrīḥ ||",
      en: "Salutation to Śrī Gaṇeśa — the customary invocation placed before beginning any composition to ensure it is completed without obstacle; the following exclamation \"śrīḥ\" (auspiciousness, prosperity) then marks the formal start of the stotra proper.",
      tel: "ఈ స్తోత్రాన్ని ఆరంభించే ముందు ఆచారబద్ధంగా శ్రీ గణేశునికి నమస్కారం చేయబడింది — ఇది గ్రంథం నిర్విఘ్నంగా పూర్తయ్యేలా చేసే సంప్రదాయం; తరువాతి \"శ్రీః\" అనే ఉద్ఘోషం స్తోత్రం యొక్క లాంఛనప్రారంభాన్ని సూచిస్తుంది.",
      hi: "इस स्तोत्र को आरंभ करने से पूर्व, प्रथा के अनुसार श्री गणेश को नमस्कार किया गया है — ताकि ग्रंथ निर्विघ्न रूप से पूर्ण हो सके; इसके बाद आने वाला \"श्रीः\" शब्द स्तोत्र के औपचारिक आरंभ का सूचक है।" },
    { s: 1, n: "1",
      deva: "जय देवेन्द्रजाकान्त जय मृत्युञ्जयात्मज ।\nजय शैलेन्द्रजासूनो जय शम्भुगणावृत ॥",
      iast: "jaya devendrajākānta jaya mṛtyuñjayātmaja |\njaya śailendrajāsūno jaya śambhugaṇāvṛta ||",
      en: "Victory to you, beloved husband of Devendra's daughter [Devasenā]! Victory to you, son of Mṛtyuñjaya [Śiva, \"conqueror of death\"]! Victory to you, son of the mountain-king's daughter [Pārvatī]! Victory to you, surrounded by Śambhu's [Śiva's] gaṇas [his attendant hosts]!",
      tel: "దేవేంద్రుని కుమార్తె [దేవసేన]కు ప్రియుడవైన వానికి జయము! మృత్యుంజయుని [శివుని] కుమారునికి జయము! పర్వతరాజు కుమార్తె [పార్వతి] కుమారునికి జయము! శంభుని గణాలచే ఆవృతమైన వానికి జయము!",
      hi: "देवेन्द्र की पुत्री [देवसेना] के प्रिय पति को जय हो! मृत्युंजय [शिव] के पुत्र को जय हो! पर्वतराज-पुत्री [पार्वती] के पुत्र को जय हो! शम्भु [शिव] के गणों से घिरे हुए को जय हो!" },
    { s: 1, n: "2",
      deva: "जय तारकदर्पघ्न जय विघ्नेश्वरानुज ।\nजय देवेन्द्र-जामातः जय पङ्कजलोचन ॥",
      iast: "jaya tārakadarpaghna jaya vighneśvarānuja |\njaya devendra-jāmātaḥ jaya paṅkajalocana ||",
      en: "Victory to you, destroyer of Tāraka's pride! Victory to you, younger brother of Vighneśvara [Gaṇeśa]! Victory to you, son-in-law of Devendra [Indra, husband of his daughter Devasenā]! Victory to you, lotus-eyed one!",
      tel: "తారకుని గర్వాన్ని అణచినవానికి జయము! విఘ్నేశ్వరుని [గణేశుని] తమ్మునికి జయము! దేవేంద్రుని అల్లునికి జయము! పద్మనేత్రునికి జయము!",
      hi: "तारक के दर्प को नष्ट करने वाले को जय हो! विघ्नेश्वर [गणेश] के छोटे भाई को जय हो! देवेन्द्र के जामाता को जय हो! कमल-नयन को जय हो!" },
    { s: 1, n: "3",
      deva: "जय शङ्करसम्भूत जय पद्मासनार्चित ।\nजय दाक्षायणीसूनो जय काशवनोद्भव ॥",
      iast: "jaya śaṅkarasambhūta jaya padmāsanārcita |\njaya dākṣāyaṇīsūno jaya kāśavanodbhava ||",
      en: "Victory to you, sprung from Śaṅkara [Śiva]! Victory to you, worshipped by Padmāsana [Brahmā, \"seated on the lotus\"]! Victory to you, son of Dākṣāyaṇī [Pārvatī, daughter of Dakṣa]! Victory to you, arisen from the reed-thicket [the Śaravaṇa forest of reeds where he was born]!",
      tel: "శంకరుని నుండి ఉద్భవించినవానికి జయము! పద్మాసనుడు [బ్రహ్మ]చే పూజింపబడువానికి జయము! దాక్షాయణి [పార్వతి] కుమారునికి జయము! రెల్లుపొద [శరవణము] నుండి ఉద్భవించినవానికి జయము!",
      hi: "शंकर से उत्पन्न हुए को जय हो! पद्मासन [ब्रह्मा] द्वारा पूजित को जय हो! दाक्षायणी [पार्वती] के पुत्र को जय हो! सरकंडों के वन [शरवण] से प्रकट हुए को जय हो!" },
    { s: 1, n: "4",
      deva: "जय भागीरथीसूनो जय पावकसम्भव ।\nजय पद्मजगर्वघ्न जय वैकुण्ठपूजित ॥",
      iast: "jaya bhāgīrathīsūno jaya pāvakasambhava |\njaya padmajagarvaghna jaya vaikuṇṭhapūjita ||",
      en: "Victory to you, son of Bhāgīrathī [the river Gaṅgā]! Victory to you, born of Pāvaka [fire]! Victory to you, humbler of Padmaja's [Brahmā's, \"lotus-born\"] pride! Victory to you, worshipped by Vaikuṇṭha [Viṣṇu]!",
      tel: "భాగీరథి [గంగ] కుమారునికి జయము! పావకుని [అగ్ని] నుండి జన్మించినవానికి జయము! పద్మజుని [బ్రహ్మ] గర్వాన్ని అణచినవానికి జయము! వైకుంఠుడు [విష్ణువు]చే పూజింపబడువానికి జయము!",
      hi: "भागीरथी [गंगा] के पुत्र को जय हो! पावक [अग्नि] से उत्पन्न हुए को जय हो! पद्मज [ब्रह्मा] के गर्व को नष्ट करने वाले को जय हो! वैकुण्ठ [विष्णु] द्वारा पूजित को जय हो!" },
    { s: 1, n: "5",
      deva: "जय भक्तेष्टवरद जय भक्तार्तिभञ्जन ।\nजय भक्तपराधीन जय भक्तप्रपूजित ॥",
      iast: "jaya bhakteṣṭavarada jaya bhaktārtibhañjana |\njaya bhaktaparādhīna jaya bhaktaprapūjita ||",
      en: "Victory to you, granter of what your devotees desire! Victory to you, dispeller of your devotees' distress! Victory to you, ever subject to your devotees' will! Victory to you, greatly worshipped by your devotees!",
      tel: "భక్తుల కోరికలు తీర్చువానికి జయము! భక్తుల బాధలను పోగొట్టువానికి జయము! భక్తులకు వశుడైన వానికి జయము! భక్తులచే చక్కగా పూజింపబడువానికి జయము!",
      hi: "भक्तों की इच्छाएँ पूर्ण करने वाले को जय हो! भक्तों के कष्ट दूर करने वाले को जय हो! भक्तों के अधीन रहने वाले को जय हो! भक्तों द्वारा भलीभाँति पूजित को जय हो!" },
    { s: 1, n: "6",
      deva: "जय धर्मवतां श्रेष्ठ जय दारिद्र्यनाशन ।\nजय बुद्धिमतां श्रेष्ठ जय नारदसन्नुत ॥",
      iast: "jaya dharmavatāṁ śreṣṭha jaya dāridryanāśana |\njaya buddhimatāṁ śreṣṭha jaya nāradasannuta ||",
      en: "Victory to you, best among the righteous! Victory to you, destroyer of poverty! Victory to you, best among the wise! Victory to you, well-praised by Nārada!",
      tel: "ధర్మవంతులలో శ్రేష్ఠునికి జయము! దారిద్ర్యాన్ని నశింపజేయువానికి జయము! బుద్ధిమంతులలో శ్రేష్ఠునికి జయము! నారదునిచే చక్కగా స్తుతింపబడువానికి జయము!",
      hi: "धर्मवानों में श्रेष्ठ को जय हो! दरिद्रता का नाश करने वाले को जय हो! बुद्धिमानों में श्रेष्ठ को जय हो! नारद द्वारा भलीभाँति स्तुत को जय हो!" },
    { s: 1, n: "7",
      deva: "जय भोगीश्वराधीश जय तुम्बुरुसेवित ।\nजय षट्तारकाराध्य जय वल्लीमनोहर ॥",
      iast: "jaya bhogīśvarādhīśa jaya tumburusevita |\njaya ṣaṭtārakārādhya jaya vallīmanohara ||",
      en: "Victory to you, lord over the king of serpents! Victory to you, attended by Tumburu [the celestial gandharva-musician]! Victory to you, worshipped by the six Kṛttikās [the six star-mothers whose milk nursed his six faces]! Victory to you, heart's delight of Vallī [his consort]!",
      tel: "సర్పరాజుకు అధీశ్వరుడైన వానికి జయము! తుంబురుని [గంధర్వగాయకుని] చేత సేవింపబడువానికి జయము! ఆరుగురు కృత్తికల [తారకల]చే పూజింపబడువానికి జయము! వల్లికి మనోహరుడైన వానికి జయము!",
      hi: "सर्पराज के अधीश्वर को जय हो! तुंबुरु [गंधर्व-गायक] द्वारा सेवित को जय हो! छह कृत्तिकाओं [तारकाओं] द्वारा पूजित को जय हो! वल्ली के मनोहर को जय हो!" },
    { s: 1, n: "8",
      deva: "जय योगसमाराध्य जय सुन्दरविग्रह ।\nजय सौन्दर्यकूपार जय वासववन्दित ॥",
      iast: "jaya yogasamārādhya jaya sundaravigraha |\njaya saundaryakūpāra jaya vāsavavandita ||",
      en: "Victory to you, well-worshipped through yoga! Victory to you, of beautiful form! Victory to you, ocean of beauty! Victory to you, saluted by Vāsava [Indra]!",
      tel: "యోగసాధన ద్వారా చక్కగా పూజింపబడువానికి జయము! సుందరమైన స్వరూపం కలవానికి జయము! సౌందర్యసముద్రునికి జయము! వాసవుడు [ఇంద్రుడు]చే వందింపబడువానికి జయము!",
      hi: "योग द्वारा भलीभाँति आराधित को जय हो! सुंदर स्वरूप वाले को जय हो! सौंदर्य के सागर को जय हो! वासव [इंद्र] द्वारा वंदित को जय हो!" },
    { s: 1, n: "9",
      deva: "जय षड्भावरहित जय वेदविदां वर ।\nजय षण्मुखदेवेश जय भो विजयी भव ॥",
      iast: "jaya ṣaḍbhāvarahita jaya vedavidāṁ vara |\njaya ṣaṇmukhadeveśa jaya bho vijayī bhava ||",
      en: "Victory to you, free from the six modifications of being [birth, existence, growth, transformation, decay, and death]! Victory to you, foremost among the knowers of the Veda! Victory to you, six-faced lord of the gods! Victory — O lord, be triumphant!",
      tel: "జన్మ, స్థితి, వృద్ధి, పరిణామం, క్షయం, నాశనం అనే ఆరు వికారాలు లేని వానికి జయము! వేదవిదులలో శ్రేష్ఠునికి జయము! షణ్ముఖుడైన దేవదేవునికి జయము! జయము కలుగుగాక, ఓ ప్రభూ, విజయుడవు కమ్ము!",
      hi: "जन्म, स्थिति, वृद्धि, परिणाम, क्षय, नाश — इन छह विकारों से रहित को जय हो! वेदों के ज्ञाताओं में श्रेष्ठ को जय हो! षण्मुख देवाधिदेव को जय हो! जय हो, हे प्रभु, विजयी बनो!" },
    { s: 2, n: null,
      deva: "ॐ श्रीवल्लीदेवसेनासमेत श्रीसुब्रह्मण्याय नमः ।\nइति श्रीजयस्कन्दस्तोत्रं सम्पूर्णम् ।",
      iast: "oṁ śrīvallīdevasenāsameta śrīsubrahmaṇyāya namaḥ |\niti śrījayaskandastotraṁ sampūrṇam |",
      en: "Salutation to Śrī Subrahmaṇya together with Śrī Vallī and Devasenā, his two consorts; thus the Śrī Jayaskandastotram is complete — a closing dedication to the god in his full triad followed by the standard colophon marking the end of the text.",
      tel: "శ్రీ వల్లీదేవసేనా సమేత శ్రీ సుబ్రహ్మణ్యునికి నమస్కారం; ఇలా శ్రీ జయస్కంద స్తోత్రం సంపూర్ణమైనది — దేవుని పూర్ణరూపానికి (ఇరువురు దేవేరులతో సహా) సమర్పించే ముగింపు నమస్కారం తరువాత గ్రంథాంతమును సూచించే సంప్రదాయ కొలొఫోన్.",
      hi: "श्री वल्ली और देवसेना — इन दोनों पत्नियों सहित — श्री सुब्रह्मण्य को नमस्कार; इस प्रकार श्री जयस्कंद स्तोत्र सम्पूर्ण हुआ — यह देवता के पूर्ण रूप को समर्पित समापन-नमस्कार के पश्चात् ग्रंथ की समाप्ति सूचित करने वाला पारंपरिक कोलोफ़ोन है।\n\n---\nRecension note: Base text is sanskritdocuments.org's doc_subrahmanya edition of the Jayaskandastotram (fetched via its rendered Devanāgarī HTML page and cross-read against the raw .itx source, both retrieved through the browser tools since WebFetch does not surface raw content for this site's .itx files). The nine numbered verses were independently cross-checked against stotranidhi.com's English (IAST) page for the same title and match word-for-word with no variant readings — the sole difference between the two sources is that stotranidhi.com's page presents only the bare nine verses and omits both framing lines (the opening Gaṇeśa-namaskāra/śrīḥ invocation and the closing Vallī-Devasenā-sameta-Subrahmaṇya namaskāra with its \"iti…sampūrṇam\" colophon); those two framing lines are therefore carried here on sanskritdocuments.org's authority alone and are flagged as single-source. vignanam.org, suggested as the primary source in the brief, does not carry this stotra under any of its script variants (English/Devanāgarī/Telugu) — checked directly by search and by browsing its Subrahmaṇya listings — so it could not be used at all for this item. hariome.com, offered as a Telugu-tradition fallback, refused every navigation attempt made through the browser tool, so it likewise contributes nothing to the cross-check here; this leaves the item's verification resting on two sources rather than the three suggested in the brief, which is noted as reduced cross-checking per the brief's own instructions rather than left unstated. The mid-pāda hyphen in verse 2's \"देवेन्द्र-जामातः\" is reproduced exactly as it appears in both the sanskritdocuments.org Devanāgarī rendering and its underlying .itx markup (which encodes it as an explicit word-joiner within the compound); it is treated as a genuine feature of the source's own text rather than an editorial mark introduced here. No numbering irregularities (skipped or repeated verse numbers) were found in either source, and no verse required marking as unverified." },
  ],
},

{
  deities: ["subrahmanya"],
  title: "Daṇḍapāṇi Pañcaratnam",
  blurb: "Five jewels for the staff-bearer of Palani, each verse one unbroken sentence — by the Śṛṅgeri Jagadguru Śivābhinava Nṛsiṁha Bhāratī.",
  colophon: { deva: "इति शृङ्गेरिजगद्गुरु श्रीसच्चिदानन्दशिवाभिनवनृसिंहभारती स्वामिभिः विरचितं श्रीदण्डपाणि पञ्चरत्नम् ॥", iast: "iti śṛṅgerijagadguru śrīsaccidānandaśivābhinavanṛsiṁhabhāratī svāmibhiḥ viracitaṁ śrīdaṇḍapāṇi pañcaratnam ||" },
  verses: [
    { s: 0, n: "1",
      deva: "चण्डपापहरपादसेवनं गण्डशोभिवरकुण्डलद्वयम् ।\nदण्डिताखिलसुरारिमण्डलं दण्डपाणिमनिशं विभावये ॥",
      iast: "caṇḍapāpaharapādasevanaṁ gaṇḍaśobhivarakuṇḍaladvayam |\ndaṇḍitākhilasurārimaṇḍalaṁ daṇḍapāṇimaniśaṁ vibhāvaye ||",
      en: "I constantly contemplate Daṇḍapāṇi — service at whose feet destroys the fiercest sins, whose two cheeks shine with excellent kuṇḍalas (earrings), and who has chastised the entire host of the gods' enemies, the asuras.",
      tel: "భయంకరమైన పాపాలను నశింపజేసే పాదసేవ కలవాడు, శ్రేష్ఠమైన కుండలద్వయంతో ప్రకాశించే చెక్కిళ్లు కలవాడు, దేవతల శత్రువులైన రాక్షససమూహాన్ని సంపూర్ణంగా శిక్షించినవాడు అయిన ఆ దండపాణిని నేను నిత్యం ధ్యానిస్తున్నాను.",
      hi: "जिनके चरणों की सेवा घोर पापों का नाश करती है, जिनके कपोल श्रेष्ठ कुण्डलद्वय से सुशोभित हैं, तथा जिन्होंने देवताओं के शत्रुओं के समस्त समूह को दण्डित किया है, उन दण्डपाणि का मैं निरन्तर ध्यान करता हूँ।" },
    { s: 0, n: "2",
      deva: "कालकालतनुजं कृपालयं बालचन्द्रविलसज्जटाधरम् ।\nचेलधूतशिशुवासरेश्वरं दण्डपाणिमनिशं विभावये ॥",
      iast: "kālakālatanujaṁ kṛpālayaṁ bālacandravilasajjaṭādharam |\nceladhūtaśiśuvāsareśvaraṁ daṇḍapāṇimaniśaṁ vibhāvaye ||",
      en: "I constantly contemplate Daṇḍapāṇi — son of Kālakāla (Śiva, \"death to Death\" itself), the very abode of compassion, wearing matted locks that shine with the crescent moon, the infant (śiśu) whose own garment's radiance outshines vāsareśvara, the lord of the day, the sun.",
      tel: "కాలునికే కాలుడైన శివుని కుమారుడు, కరుణకు నిలయమైనవాడు, బాలచంద్రునితో ప్రకాశించే జటలను ధరించినవాడు, తన వస్త్రకాంతితో సూర్యుని తేజస్సునే మించిపోయే ఆ శిశురూప దండపాణిని నేను నిత్యం ధ్యానిస్తున్నాను.",
      hi: "काल के भी काल शिव के पुत्र, करुणा के आगार, बालचन्द्र से सुशोभित जटाओं को धारण करने वाले, तथा जिनके वस्त्र की कान्ति सूर्यदेव के तेज को भी मात देती है, उन शिशुरूप दण्डपाणि का मैं निरन्तर ध्यान करता हूँ।" },
    { s: 0, n: "3",
      deva: "तारकेशसदृशाननोज्ज्वलं तारकारिमखिलार्थदं जवात् ।\nतारकं निरवधेर्भवाम्बुधेर्दण्डपाणिमनिशं विभावये ॥",
      iast: "tārakeśasadṛśānanojjvalaṁ tārakārimakhilārthadaṁ javāt |\ntārakaṁ niravadherbhavāmbudherdaṇḍapāṇimaniśaṁ vibhāvaye ||",
      en: "I constantly contemplate Daṇḍapāṇi — radiant-faced as tārakeśa, the moon (lord of the stars), the slayer of the demon Tāraka (Tārakāsura) who swiftly grants every desired end, and the tāraka, the ferryman who carries his devotees across the boundless ocean of worldly existence (bhavāmbudhi).",
      tel: "చంద్రుని పోలిన ప్రకాశవంతమైన ముఖం కలవాడు, తారకాసురుని సంహరించి కోరిన కోరికలన్నింటినీ శీఘ్రమే తీర్చేవాడు, అంతులేని ఈ సంసారసముద్రాన్ని దాటించే నావ వంటివాడు అయిన ఆ దండపాణిని నేను నిత్యం ధ్యానిస్తున్నాను.",
      hi: "चन्द्रमा के समान उज्ज्वल मुख वाले, तारकासुर का वध करके समस्त इच्छाओं को शीघ्र पूर्ण करने वाले, तथा इस अनन्त संसार-सागर से पार उतारने वाले उन दण्डपाणि का मैं निरन्तर ध्यान करता हूँ।" },
    { s: 0, n: "4",
      deva: "तापहारिनिजपादसंस्तुतिं कोपकाममुखवैरिवारकम् ।\nप्रापकं निजपदस्य सत्वरं दण्डपाणिमनिशं विभावये ॥",
      iast: "tāpahārinijapādasaṁstutiṁ kopakāmamukhavairivārakam |\nprāpakaṁ nijapadasya satvaraṁ daṇḍapāṇimaniśaṁ vibhāvaye ||",
      en: "I constantly contemplate Daṇḍapāṇi — praising whose own feet removes affliction (tāpa), who wards off the inner enemies (arishaḍvarga) headed by kāma (desire) and kopa (anger), and who swiftly grants the attainment of his own supreme abode (mokṣa).",
      tel: "తన పాదాలను స్తుతిస్తే తాపత్రయాన్ని హరించేవాడు, కామక్రోధాది అంతశ్శత్రువులను నివారించేవాడు, తన దివ్యపదాన్ని శీఘ్రమే ప్రసాదించేవాడు అయిన ఆ దండపాణిని నేను నిత్యం ధ్యానిస్తున్నాను.",
      hi: "जिनके चरणों की स्तुति करने मात्र से ताप का नाश हो जाता है, जो काम-क्रोध आदि अन्तःशत्रुओं का निवारण करते हैं, तथा जो अपने दिव्य पद की प्राप्ति शीघ्र प्रदान करते हैं, उन दण्डपाणि का मैं निरन्तर ध्यान करता हूँ।" },
    { s: 0, n: "5",
      deva: "कामनीयकविनिर्जिताङ्गजं रामलक्ष्मणकराम्बुजार्चितम् ।\nकोमलाङ्गमतिसुन्दराकृतिं दण्डपाणिमनिशं विभावये ॥",
      iast: "kāmanīyakavinirjitāṅgajaṁ rāmalakṣmaṇakarāmbujārcitam |\nkomalāṅgamatisundarākṛtiṁ daṇḍapāṇimaniśaṁ vibhāvaye ||",
      en: "I constantly contemplate Daṇḍapāṇi — whose loveliness has vanquished Aṅgaja (the \"body-born\" one, Kāma the god of love) himself, who was worshipped by the lotus-hands (karāmbuja) of Rāma and Lakṣmaṇa, and whose limbs are tender and whose form is exceedingly beautiful.",
      tel: "తన సౌందర్యంతో మన్మథుడినే జయించినవాడు, రామలక్ష్మణుల కరకమలాలచే పూజింపబడినవాడు, కోమలమైన అవయవాలతో అత్యంత సుందరమైన ఆకృతి కలవాడు అయిన ఆ దండపాణిని నేను నిత్యం ధ్యానిస్తున్నాను.",
      hi: "अपने सौन्दर्य से कामदेव को भी पराजित करने वाले, श्रीराम-लक्ष्मण के करकमलों से पूजित, तथा कोमल अंगों वाले अत्यन्त सुन्दर स्वरूप वाले उन दण्डपाणि का मैं निरन्तर ध्यान करता हूँ।" },
  ],
},

{
  deities: ["subrahmanya"],
  title: "Daṇḍāyudhapāṇyaṣṭakam",
  blurb: "Eight śārdūlavikrīḍita verses to Daṇḍāyudhapāṇi of Palani — a different act of the god remembered in each, beginning with his appearance to Agastya.",
  sections: [{ tel: "అష్టకం", roman: "The Eight Verses" }, { tel: "ఫలశ్రుతి", roman: "The Fruit of Recitation" }],
  verses: [
    { s: 0, n: "1",
      deva: "यः पूर्वं शिवशक्तिनामकगिरिद्वन्द्वे हिडिम्बासुरेणानीते फलिनीस्थलान्तरगते कौमारवेषोज्ज्वलः ।\nआविर्भूय घटोद्भवाय मुनये भूयो वरान् प्रादिशत् श्रीदण्डायुधपाणिरात्तकरुणः पायादपायात्स माम् ॥",
      iast: "yaḥ pūrvaṁ śivaśaktināmakagiridvandve hiḍimbāsureṇānīte phalinīsthalāntaragate kaumāraveṣojjvalaḥ |\nāvirbhūya ghaṭodbhavāya munaye bhūyo varān prādiśat śrīdaṇḍāyudhapāṇirāttakaruṇaḥ pāyādapāyātsa mām ||",
      en: "He who long ago, at the twin hills called Śivagiri and Śaktigiri — which Hiḍimbāsura had carried until they came to rest at the Phalinī (Palani) site — appeared radiant in the garb of a youthful ascetic (kaumāra-veṣa) and, manifesting himself there, once again granted boons to the sage born from a jar (ghaṭodbhava, i.e. Agastya): may that Śrī Daṇḍāyudhapāṇi, his compassion aroused, protect me and ward off calamity.",
      tel: "శివగిరి, శక్తిగిరి అనే జంట కొండలను హిడింబాసురుడు మోసుకువచ్చి ఫలినీ (పళని) క్షేత్రంలో నిలిపిన చోట, పూర్వం కౌమారవేషంతో ప్రకాశించి, ఆవిర్భవించి, కుంభసంభవుడైన మునికి (అగస్త్యునికి) మళ్ళీ వరాలను అనుగ్రహించిన శ్రీ దండాయుధపాణి, కరుణతో నిండినవాడై, నన్ను ఆపదల నుండి రక్షించుగాక.",
      hi: "शिवगिरि और शक्तिगिरि नामक जुड़वाँ पर्वतों को हिडिम्बासुर द्वारा लाकर फलिनी (पलनी) क्षेत्र में स्थापित किए जाने पर, पूर्वकाल में कौमार-वेष में देदीप्यमान होकर प्रकट हुए और घटोद्भव मुनि (अगस्त्य) को पुनः वर प्रदान करने वाले श्री दण्डायुधपाणि, करुणा से भरकर, मेरी आपदाओं से रक्षा करें।" },
    { s: 0, n: "2",
      deva: "श्रीमत्पुष्यरथोत्सवेऽन्नमधुदुग्धाद्यैः पदार्थोत्तमैः नानादेशसमागतैरगणितैर्यः कावडीसम्भृतैः ।\nभक्तौघैरभिषेचितो बहुवरांस्तेभ्यो ददात्यादरात् श्रीदण्डायुधपाणिरात्तकरुणः पायादपायत्स माम् ॥",
      iast: "śrīmatpuṣyarathotsave'nnamadhudugdhādyaiḥ padārthottamaiḥ nānādeśasamāgatairagaṇitairyaḥ kāvaḍīsambhṛtaiḥ |\nbhaktaughairabhiṣecito bahuvarāṁstebhyo dadātyādarāt śrīdaṇḍāyudhapāṇirāttakaruṇaḥ pāyādapāyatsa mām ||",
      en: "At the glorious chariot festival held under the Puṣya asterism, he who is lovingly bathed in abhiṣeka by countless throngs of devotees arriving from many lands, bearing kāvaḍis (yoke-baskets) filled with the finest offerings — rice, honey, milk and the like — and who in turn graciously grants them many boons: may that Śrī Daṇḍāyudhapāṇi, his compassion aroused, protect me and ward off calamity.",
      tel: "పుష్యనక్షత్రాన జరిగే శోభాయమానమైన రథోత్సవంలో, పలు దేశాల నుండి వచ్చిన లెక్కలేనన్ని భక్తసమూహాలు కావడులలో నింపిన అన్నం, తేనె, పాలు మొదలైన శ్రేష్ఠమైన పదార్థాలతో అభిషేకించగా, వారికి ప్రేమతో అనేక వరాలను ఇచ్చే శ్రీ దండాయుధపాణి, కరుణతో నిండినవాడై, నన్ను ఆపదల నుండి రక్షించుగాక.",
      hi: "पुष्य नक्षत्र में होने वाले शोभायमान रथोत्सव में, विभिन्न देशों से आए अगणित भक्तसमूहों द्वारा कावड़ियों में भरे अन्न, मधु, दुग्ध आदि उत्तम पदार्थों से अभिषिक्त होकर, उन्हें प्रेमपूर्वक अनेक वर देने वाले श्री दण्डायुधपाणि, करुणा से भरकर, मेरी आपदाओं से रक्षा करें।" },
    { s: 0, n: "3",
      deva: "नानादिग्भ्य उपागता निजमहावेशान्विताः सुन्दरीः तासामेत्य निशासु यः सुमशरानन्दानुभूतिच्छलात् ।\nगोपीनां यदुनाथवन्निजपरानन्दं तनोति स्फुटं श्रीदण्डायुधपाणिरात्तकरुणः पायादपायात्स माम् ॥",
      iast: "nānādigbhya upāgatā nijamahāveśānvitāḥ sundarīḥ tāsāmetya niśāsu yaḥ sumaśarānandānubhūticchalāt |\ngopīnāṁ yadunāthavannijaparānandaṁ tanoti sphuṭaṁ śrīdaṇḍāyudhapāṇirāttakaruṇaḥ pāyādapāyātsa mām ||",
      en: "He who at night approaches beautiful [celestial] women arrived from every direction, each filled with her own great power, and — under the pretext of granting them the bliss-experience of the flower-arrowed god (Kāma) — openly bestows on them his own supreme bliss, just as Yadunātha (Kṛṣṇa) did among the gopīs: may that Śrī Daṇḍāyudhapāṇi, his compassion aroused, protect me and ward off calamity.",
      tel: "రాత్రివేళ నలుదిక్కుల నుండి వచ్చిన, తమతమ మహాశక్తులతో నిండిన సుందరీమణుల వద్దకు చేరి, మన్మథానంద అనుభూతి నెపంతో యదునాథుడు (కృష్ణుడు) గోపికలకు వలె తన స్వీయ పరమానందాన్ని స్పష్టంగా వారికి పంచే శ్రీ దండాయుధపాణి, కరుణతో నిండినవాడై, నన్ను ఆపదల నుండి రక్షించుగాక.",
      hi: "रात्रि में चारों दिशाओं से आई, अपनी-अपनी महाशक्ति से युक्त सुंदरियों के पास जाकर, मन्मथ-आनंद-अनुभूति के बहाने यदुनाथ (कृष्ण) की भाँति गोपियों को अपना परमानंद स्पष्ट रूप से प्रदान करने वाले श्री दण्डायुधपाणि, करुणा से भरकर, मेरी आपदाओं से रक्षा करें।" },
    { s: 0, n: "4",
      deva: "दुष्टानामिह भूतभाविभवतां दुर्मार्गसञ्चारिणां कष्टाहङ्कृतिजन्यकिल्बिषवशाच्छिष्टप्रविध्वंसिनाम् ।\nशिक्षार्थं निजपाणिनोद्वहति यो दण्डाभिधानायुधं श्रीदण्डायुधपाणिरात्तकरुणः पायादपायात्स माम् ॥",
      iast: "duṣṭānāmiha bhūtabhāvibhavatāṁ durmārgasañcāriṇāṁ kaṣṭāhaṅkṛtijanyakilbiṣavaśācchiṣṭapravidhvaṁsinām |\nśikṣārthaṁ nijapāṇinodvahati yo daṇḍābhidhānāyudhaṁ śrīdaṇḍāyudhapāṇirāttakaruṇaḥ pāyādapāyātsa mām ||",
      en: "He who, in order to discipline the wicked of past, present and future who tread the evil path — and who, under the sway of the sin born of the anguish of their own arrogance (ahaṅkṛti), destroy the virtuous (śiṣṭa) — carries in his own hand the weapon called the daṇḍa (staff): may that Śrī Daṇḍāyudhapāṇi (\"he whose weapon-in-hand is the daṇḍa\"), his compassion aroused, protect me and ward off calamity.",
      tel: "దుర్మార్గంలో సంచరించే గత, వర్తమాన, భవిష్యత్ దుష్టులను, తమ అహంకారజనితమైన పాపవశంతో సజ్జనులను నశింపజేసేవారిని శిక్షించడానికి తన చేతిలో దండం అనే ఆయుధాన్ని ధరించే శ్రీ దండాయుధపాణి, కరుణతో నిండినవాడై, నన్ను ఆపదల నుండి రక్షించుగాక.",
      hi: "दुर्मार्ग में विचरण करने वाले भूत, वर्तमान, भविष्य के दुष्टों को, जो अपने अहंकारजनित पाप के वशीभूत होकर सज्जनों का नाश करते हैं, दंडित करने हेतु अपने हाथ में दंड नामक आयुध धारण करने वाले श्री दण्डायुधपाणि, करुणा से भरकर, मेरी आपदाओं से रक्षा करें।" },
    { s: 0, n: "5",
      deva: "पूर्वं तारकसञ्ज्ञकं दितिसुतं यः शूरपद्मासुरं सिंहास्यं च निहत्य वासवमुखान् देवान् जुगोपाखिलान् ।\nश्रीवल्ल्या सहितश्च निस्तुलयशाः श्रीदेवसेन्या युतः श्रीदण्डायुधपाणिरात्तकरुणः पायादपायात्स माम् ॥",
      iast: "pūrvaṁ tārakasañjñakaṁ ditisutaṁ yaḥ śūrapadmāsuraṁ siṁhāsyaṁ ca nihatya vāsavamukhān devān jugopākhilān |\nśrīvallyā sahitaśca nistulayaśāḥ śrīdevasenyā yutaḥ śrīdaṇḍāyudhapāṇirāttakaruṇaḥ pāyādapāyātsa mām ||",
      en: "He who long ago, having slain the demon-son of Diti named Tāraka, and Śūrapadmāsura, and Siṁhāsya (Siṁhamukha), protected all the gods headed by Vāsava (Indra); of matchless fame, accompanied by Śrī Vallī and united with Śrī Devasenā: may that Śrī Daṇḍāyudhapāṇi, his compassion aroused, protect me and ward off calamity.",
      tel: "పూర్వం తారకుడు అనే దితిపుత్రుని, శూరపద్మాసురుని, సింహాస్యుని (సింహముఖుని) సంహరించి ఇంద్రాది దేవతలందరినీ రక్షించిన, సాటిలేని కీర్తిగలవాడు, శ్రీ వల్లితో కూడి శ్రీ దేవసేనతో కలిసియున్న శ్రీ దండాయుధపాణి, కరుణతో నిండినవాడై, నన్ను ఆపదల నుండి రక్షించుగాక.",
      hi: "पूर्वकाल में तारक नामक दितिपुत्र को, शूरपद्मासुर को तथा सिंहास्य (सिंहमुख) को मारकर इंद्र आदि समस्त देवताओं की रक्षा करने वाले, अतुलनीय यशस्वी, श्री वल्ली सहित तथा श्री देवसेना से युक्त श्री दण्डायुधपाणि, करुणा से भरकर, मेरी आपदाओं से रक्षा करें।" },
    { s: 0, n: "6",
      deva: "यस्याङ्गस्थितरोमकूपनिकरे ब्रह्माण्डकोटिच्छटाः सौधाग्रस्थगवाक्षरन्ध्रविचरत्पीलूपमा एव ताः ।\nलक्ष्यन्ते यमिदृग्भिरात्मनि तथाभूतस्वविश्वाकृतिः श्रीदण्डायुधपाणिरात्तकरुणः पायादपायात्स माम् ॥",
      iast: "yasyāṅgasthitaromakūpanikare brahmāṇḍakoṭicchaṭāḥ saudhāgrasthagavākṣarandhravicaratpīlūpamā eva tāḥ |\nlakṣyante yamidṛgbhirātmani tathābhūtasvaviśvākṛtiḥ śrīdaṇḍāyudhapāṇirāttakaruṇaḥ pāyādapāyātsa mām ||",
      en: "He within the mass of whose body-hair-pores crores of universes are seen by such [seers] within their own selves — like specks of dust drifting through the lattice-window openings atop a mansion — his own true nature thus being the very form of the entire cosmos (viśvākṛti): may that Śrī Daṇḍāyudhapāṇi, his compassion aroused, protect me and ward off calamity.",
      tel: "ఎవని శరీరంలోని రోమకూపాల సమూహంలో కోట్లాది బ్రహ్మాండాలు, మేడమీది కిటికీ రంధ్రాలలో తిరిగే ధూళికణాల వలె, అటువంటి యోగులకు తమలోనే గోచరిస్తాయో, తద్వారా తానే విశ్వరూపుడైన శ్రీ దండాయుధపాణి, కరుణతో నిండినవాడై, నన్ను ఆపదల నుండి రక్షించుగాక.",
      hi: "जिसके शरीर के रोमकूपों के समूह में करोड़ों ब्रह्मांड, अट्टालिका के गवाक्ष-छिद्रों में विचरण करने वाले धूलिकणों के समान, ऐसे योगियों को अपने भीतर ही दिखाई देते हैं, इस प्रकार जिसका अपना स्वरूप ही संपूर्ण विश्व की आकृति है, ऐसे श्री दण्डायुधपाणि, करुणा से भरकर, मेरी आपदाओं से रक्षा करें।" },
    { s: 0, n: "7",
      deva: "सद्योजातमुखैश्च पञ्चवदनैः शम्भोः सहैकं मुखं पार्वत्या मिलितं विभाति सततं यद्वक्त्रषट्कात्मना ।\nतत्तादृक् च्छिवशक्त्यभेदविषयव्यक्त्युज्ज्वलाङ्गं वहन् श्रीदण्डायुधपाणिरात्तकरुणः पायादपायात्स माम् ॥",
      iast: "sadyojātamukhaiśca pañcavadanaiḥ śambhoḥ sahaikaṁ mukhaṁ pārvatyā militaṁ vibhāti satataṁ yadvaktraṣaṭkātmanā |\ntattādṛk cchivaśaktyabhedaviṣayavyaktyujjvalāṅgaṁ vahan śrīdaṇḍāyudhapāṇirāttakaruṇaḥ pāyādapāyātsa mām ||",
      en: "He who ever shines in the form of six faces — the five faces of Śambhu beginning with Sadyojāta, joined with one face from Pārvatī — thus bearing a form radiant with the manifest non-difference (abheda) of Śiva and Śakti: may that Śrī Daṇḍāyudhapāṇi, his compassion aroused, protect me and ward off calamity.",
      tel: "సద్యోజాతాది శంభుని ఐదు ముఖాలతో పార్వతి యొక్క ఒక ముఖం కలిసి, ఆరు ముఖాల రూపంలో ఎప్పుడూ ప్రకాశించే, శివశక్తుల అభేదతత్త్వాన్ని వ్యక్తం చేసే ప్రకాశవంతమైన అంగాన్ని ధరించిన శ్రీ దండాయుధపాణి, కరుణతో నిండినవాడై, నన్ను ఆపదల నుండి రక్షించుగాక.",
      hi: "सद्योजात आदि शंभु के पाँच मुखों के साथ पार्वती के एक मुख के मिलने से बने छह मुखों के रूप में सदैव प्रकाशित होने वाले, शिव-शक्ति के अभेद-तत्त्व को व्यक्त करने वाले देदीप्यमान अंग को धारण करने वाले श्री दण्डायुधपाणि, करुणा से भरकर, मेरी आपदाओं से रक्षा करें।" },
    { s: 0, n: "8",
      deva: "सत्यं ज्ञानमनन्तमद्वयमिति श्रुत्यन्तवाक्योदितं यद्ब्रह्मास्ति तदेव यस्य च विभोर्मूर्तेः स्वरूपं विदुः ।\nयोगीन्द्रा विमलाशया हृदि निजानन्दानुभूत्युन्नताः श्रीदण्डायुधपाणिरात्तकरुणः पायादपायात्स माम् ॥",
      iast: "satyaṁ jñānamanantamadvayamiti śrutyantavākyoditaṁ yadbrahmāsti tadeva yasya ca vibhormūrteḥ svarūpaṁ viduḥ |\nyogīndrā vimalāśayā hṛdi nijānandānubhūtyunnatāḥ śrīdaṇḍāyudhapāṇirāttakaruṇaḥ pāyādapāyātsa mām ||",
      en: "That which the closing words of the Upaniṣads (śrutyanta, i.e. Vedānta) declare — \"truth, knowledge, the infinite, the non-dual\" — that very Brahman, the great yogis of pure heart, uplifted by the experience of their own innate bliss within, know to be the true nature of this all-pervading god's very form: may that Śrī Daṇḍāyudhapāṇi, his compassion aroused, protect me and ward off calamity.",
      tel: "సత్యం, జ్ఞానం, అనంతం, అద్వయం అని ఉపనిషద్వాక్యాలు చెప్పే బ్రహ్మమే, తమ హృదయంలోని ఆత్మానంద అనుభూతితో ఉన్నతమైన నిర్మలచిత్తులైన మహాయోగులు, ఈ సర్వవ్యాపి దేవుని మూర్తి యొక్క స్వరూపంగా తెలుసుకునే శ్రీ దండాయుధపాణి, కరుణతో నిండినవాడై, నన్ను ఆపదల నుండి రక్షించుగాక.",
      hi: "सत्य, ज्ञान, अनंत, अद्वय — ऐसा उपनिषदों के अंतिम वाक्यों में कहा गया जो ब्रह्म है, उसी को निर्मल हृदय वाले, अपने आत्मानंद की अनुभूति से उन्नत महायोगी इस सर्वव्यापी देवता की मूर्ति के स्वरूप के रूप में जानते हैं, ऐसे श्री दण्डायुधपाणि, करुणा से भरकर, मेरी आपदाओं से रक्षा करें।" },
    { s: 1, n: "9",
      deva: "इदं श्रीफलिनीदण्डायुधपाण्यष्टकस्तवम् ।\nपठतामाशु सिद्ध्यन्ति निखिलाश्च मनोरथाः ॥",
      iast: "idaṁ śrīphalinīdaṇḍāyudhapāṇyaṣṭakastavam |\npaṭhatāmāśu siddhyanti nikhilāśca manorathāḥ ||",
      en: "For those who recite this eight-verse hymn to Śrī Daṇḍāyudhapāṇi of Phalinī (Palani), all their heart's desires are swiftly fulfilled.",
      tel: "ఫలినీ (పళని) క్షేత్ర శ్రీ దండాయుధపాణికి సంబంధించిన ఈ అష్టకస్తవాన్ని పఠించేవారికి సకల మనోరథాలు శీఘ్రంగా సిద్ధిస్తాయి.",
      hi: "फलिनी (पलनी) क्षेत्र के श्री दण्डायुधपाणि के इस अष्टक-स्तव का पाठ करने वालों के सभी मनोरथ शीघ्र ही सिद्ध हो जाते हैं।\n\n---\nRecension note: Base text is sanskritdocuments.org's doc_subrahmanya edition (daṇḍāyudhapāṇyaṣṭakam.itx, proofread by Sreenivasa Rao Bhagavatula, whose own header notes it is drawn \"From stotrArNavaH 07-06\"), fetched via the browser tools (WebFetch summarizes rather than quotes raw .itx content, as expected). This was collated word for word against stotranidhi.com's independently maintained Devanāgarī edition (stotranidhi.com/hi/sri-dandayudhapani-ashtakam-in-sanskrit/) and English/IAST edition (stotranidhi.com/en/sri-dandayudhapani-ashtakam-in-english/); the two sources agree exactly, including a shared irregularity in verse 2's refrain (\"pāyādapāyatsa mām,\" lacking the internal ā of the otherwise-identical refrain that closes verses 1 and 3-8, \"pāyādapāyātsa mām\") — reproduced here as found in both, rather than silently regularized to match the other seven verses. vignanam.org, the corpus's default primary source, does not carry this text at all (checked via targeted web search; no vignanam.org page exists under this or related titles), so that leg of the usual vignanam/sanskritdocuments/stotranidhi three-way check is unavailable for this item rather than merely unfetched. This is flagged as reduced cross-checking relative to items that do have a vignanam.org edition, though the sanskritdocuments.org/stotranidhi.com agreement is itself an independent two-source confirmation, and hariome.com was reported by search to carry a Telugu-script edition of the same title but its precise URL could not be located to fetch and add as a third check. IAST anusvāra is rendered ṁ (dot below) and vocalic r as ṛ, matching the diacritics already used throughout files 01-08 in this corpus. No internal numbering irregularities were found beyond the verse 2 refrain noted above; the source numbers its phalaśruti couplet as verse 9 continuously with the eight aṣṭaka verses rather than leaving it unnumbered." },
  ],
},

{
  deities: ["subrahmanya"],
  title: "Ṣaṇmukha Stotram",
  blurb: "Ṣaḍānana enthroned at the shore-shrine of Tiruccentūr — eight dhyāna verses, attributed to Śaṅkara at that very shrine.",
  colophon: { deva: "इति श्रीमच्छङ्करभगवतः कृतौ तिरुचेन्दूर् श्री षण्मुख स्तोत्रम् ।", iast: "iti śrīmacchaṅkarabhagavataḥ kṛtau tirucendūr śrī ṣaṇmukha stotram |" },
  sections: [{ tel: "మంగళాచరణం", roman: "Maṅgalācaraṇam" }, { tel: "షణ్ముఖాష్టకం", roman: "The Eight Verses" }],
  verses: [
    { s: 0, n: null,
      deva: "ॐ श्रीगणेशाय नमः ।\nआदिशङ्कर प्रोक्तम् —",
      iast: "oṁ śrīgaṇeśāya namaḥ |\nādiśaṅkara proktam —",
      en: "Salutation to Śrī Gaṇeśa, the customary opening invocation; the text then notes that the hymn was spoken/composed by Ādi Śaṅkara. This opening line is found only in the sanskritdocuments.org recension of the text — the stotranidhi.com/greatindian.net recension omits it entirely and instead names Śaṅkara in its own closing colophon (given below).",
      tel: "శ్రీ గణేశునికి నమస్కారం — ఇది ఆచారప్రకారమైన మంగళాచరణం; తరువాత ఈ స్తోత్రాన్ని ఆదిశంకరులు రచించారని పాఠం తెలియజేస్తుంది. ఈ ప్రారంభవాక్యం sanskritdocuments.org పాఠంలో మాత్రమే కనిపిస్తుంది — stotranidhi.com/greatindian.net పాఠంలో ఇది లేదు, బదులుగా దాని స్వంత ముగింపు శ్లోకంలో శంకరుల పేరు పేర్కొనబడింది (కింద చూడండి).",
      hi: "श्री गणेश को नमस्कार — यह पारंपरिक मंगलाचरण है; इसके बाद पाठ बताता है कि यह स्तोत्र आदि शंकराचार्य द्वारा रचित है। यह आरंभिक पंक्ति केवल sanskritdocuments.org के पाठ में मिलती है — stotranidhi.com/greatindian.net के पाठ में यह नहीं है, वहाँ इसके स्थान पर अपने ही समापन श्लोक में शंकर का नाम दिया गया है (नीचे देखें)।" },
    { s: 1, n: "1",
      deva: "नारदादिदेवयोगिबृन्दहृन्निकेतनं\nबर्हिवर्यवाहमिन्दुशेखरेष्टनन्दनम् ।\nभक्तलोकरोगदुःखपापसङ्घभञ्जनं\nभावयामि सिन्धुतीरवासिनं षडाननम् ॥",
      iast: "nāradādidevayogibṛndahṛnniketanaṁ\nbarhivaryavāhaminduśekhareṣṭanandanam |\nbhaktalokarogaduḥkhapāpasaṅghabhañjanaṁ\nbhāvayāmi sindhutīravāsinaṁ ṣaḍānanam ||",
      en: "I meditate (bhāvayāmi) on the six-faced one (Ṣaḍānana) who dwells on the ocean's shore — whose abode is the hearts of Nārada and the host of divine sages and yogis, who rides the finest peacock, the beloved son of the moon-crested one (Induśekhara, Śiva), who shatters the host of diseases, sorrows, and sins besetting the world of devotees.",
      tel: "నారదుడు మొదలైన దేవయోగుల సమూహపు హృదయాలే నివాసంగా కలవాడు, శ్రేష్ఠమైన నెమలిని వాహనంగా కలవాడు, చంద్రశేఖరుడైన శివునికి ప్రియమైన పుత్రుడు, భక్తుల రోగాలను దుఃఖాలను పాపసమూహాలను నశింపజేసేవాడు అయిన, సముద్రతీరవాసియైన ఆ షడాననుని ధ్యానిస్తున్నాను.",
      hi: "जिनका निवास नारद आदि देवयोगियों के हृदय हैं, जो श्रेष्ठ मयूर को वाहन बनाते हैं, चंद्रशेखर शिव के प्रिय पुत्र हैं, जो भक्तों के रोग, दुःख और पाप-समूह का नाश करते हैं — सिंधुतीरवासी उस षडानन का मैं ध्यान करता हूँ।" },
    { s: 1, n: "2",
      deva: "तारकारीमिन्द्रमुख्यदेवबृन्दवन्दितं\nचन्द्रचन्दनादि शीतलाङ्कमात्मभावितम् ।\nयक्षसिद्धकिन्नरादिमुख्यदिव्यपूजितं\nभावयामि सिन्धुतीरवासिनं षडाननम् ॥",
      iast: "tārakārīmindramukhyadevabṛndavanditaṁ\ncandracandanādi śītalāṅkamātmabhāvitam |\nyakṣasiddhakinnarādimukhyadivyapūjitaṁ\nbhāvayāmi sindhutīravāsinaṁ ṣaḍānanam ||",
      en: "I meditate on the six-faced one who dwells on the ocean's shore — the slayer of the demon Tāraka, honored by the host of gods headed by Indra, whose embrace is cooler than the moon and sandal-paste, ever absorbed in his own true nature (ātman), foremost worshipped by yakṣas, siddhas, kinnaras and other divine beings.",
      tel: "తారకాసురుని సంహరించినవాడు, ఇంద్రుడు మొదలైన దేవతాసమూహంచే నమస్కరించబడేవాడు, చంద్రుడు చందనం కంటే చల్లని ఒడి కలవాడు, ఆత్మానందంలో మునిగినవాడు, యక్షులు సిద్ధులు కిన్నెరులు మొదలైన దివ్యులచే పూజించబడేవాడు అయిన సముద్రతీరవాసి షడాననుని ధ్యానిస్తున్నాను.",
      hi: "तारकासुर के शत्रु (संहारक), इंद्र आदि देवसमूह द्वारा वंदित, चंद्र-चंदन से भी शीतल अंक (गोद) वाले, अपने आत्मस्वरूप में सदा रमण करने वाले, यक्ष-सिद्ध-किन्नर आदि दिव्य जनों द्वारा पूजित — सिंधुतीरवासी उस षडानन का मैं ध्यान करता हूँ।" },
    { s: 1, n: "3",
      deva: "चम्पकाब्जमालतीसुमादिमाल्यभूषितं\nदिव्यषट्किरीटहारकुण्डलाद्यलङ्कृतम् ।\nकुङ्कुमादियुक्तदिव्यगन्धपङ्कलेपितं\nभावयामि सिन्धुतीरवासिनं षडाननम् ॥",
      iast: "campakābjamālatīsumādimālyabhūṣitaṁ\ndivyaṣaṭkirīṭahārakuṇḍalādyalaṅkṛtam |\nkuṅkumādiyuktadivyagandhapaṅkalepitaṁ\nbhāvayāmi sindhutīravāsinaṁ ṣaḍānanam ||",
      en: "I meditate on the six-faced one who dwells on the ocean's shore — adorned with garlands of campaka, lotus, jasmine and other flowers, decorated with six divine crowns, necklaces, earrings and other ornaments, his body smeared with divine fragrant paste mixed with vermilion (kuṅkuma) and the like.",
      tel: "సంపెంగ, పద్మం, జాజి మొదలైన పూలదండలతో అలంకరించబడినవాడు, దివ్యమైన ఆరు కిరీటాలు హారాలు కుండలాలు మొదలైనవాటితో అలంకృతుడు, కుంకుమాది దివ్య సుగంధలేపనం పూయబడినవాడు అయిన సముద్రతీరవాసి షడాననుని ధ్యానిస్తున్నాను.",
      hi: "चंपक, कमल, मालती आदि पुष्पों की मालाओं से सुसज्जित, दिव्य छह मुकुटों, हारों, कुंडलों आदि से अलंकृत, कुंकुम आदि दिव्य सुगंधित लेप से लिप्त — सिंधुतीरवासी उस षडानन का मैं ध्यान करता हूँ।" },
    { s: 1, n: "4",
      deva: "आश्रिताखिलेष्टलोकरक्षणामराङ्घ्रिपं\nशक्तिपाणिमच्युतेन्द्रपद्मसम्भवाधिपम् ।\nशिष्टलोकचिन्तितार्थसिद्धिदानलोलुपं\nभावयामि सिन्धुतीरवासिनं षडाननम् ॥",
      iast: "āśritākhileṣṭalokarakṣaṇāmarāṅghripaṁ\nśaktipāṇimacyutendrapadmasambhavādhipam |\nśiṣṭalokacintitārthasiddhidānalolupaṁ\nbhāvayāmi sindhutīravāsinaṁ ṣaḍānanam ||",
      en: "I meditate on the six-faced one who dwells on the ocean's shore — a wish-granting tree (kalpavṛkṣa-like amarāṅghripa) in protecting every world that takes refuge in him, holding the śakti-spear in hand, lord even over Acyuta (Viṣṇu), Indra, and Padmasambhava (Brahmā), ever eager to grant the righteous the aims they set their hearts on.",
      tel: "శరణుజొచ్చిన సమస్త లోకాలను రక్షించడంలో కల్పవృక్షం వంటివాడు, చేతిలో శక్త్యాయుధం ధరించినవాడు, అచ్యుతుడు (విష్ణువు), ఇంద్రుడు, పద్మసంభవుడు (బ్రహ్మ) — వీరికి కూడా అధిపతి అయినవాడు, సజ్జనులు కోరిన అర్థాలను సిద్ధింపజేయడంలో ఆసక్తి కలవాడు అయిన సముద్రతీరవాసి షడాననుని ధ్యానిస్తున్నాను.",
      hi: "शरण में आए समस्त लोकों की रक्षा में कल्पवृक्ष के समान, हाथ में शक्ति-आयुध धारण करने वाले, अच्युत (विष्णु), इंद्र और पद्मसंभव (ब्रह्मा) के भी अधिपति, सज्जनों की चिंतित कामनाओं को सिद्ध करने में सदा उत्सुक — सिंधुतीरवासी उस षडानन का मैं ध्यान करता हूँ।" },
    { s: 1, n: "5",
      deva: "वीरबाहु पूर्वकोटिवीरसङ्घसौख्यदं\nशूरपद्ममुख्यलक्षकोटिशूरमुक्तिदम् ।\nइन्द्रपूर्वदेवसङ्घसिद्धनित्यसौख्यदं\nभावयामि सिन्धुतीरवासिनं षडाननम् ॥",
      iast: "vīrabāhu pūrvakoṭivīrasaṅghasaukhyadaṁ\nśūrapadmamukhyalakṣakoṭiśūramuktidam |\nindrapūrvadevasaṅghasiddhanityasaukhyadaṁ\nbhāvayāmi sindhutīravāsinaṁ ṣaḍānanam ||",
      en: "I meditate on the six-faced one who dwells on the ocean's shore — who grants well-being to Vīrabāhu and his crores of warriors, who grants release to Śūrapadma and the countless crores of warrior-demons under him (by slaying them in battle), who grants eternal happiness to Indra and the host of gods and siddhas.",
      tel: "వీరబాహుడు మొదలైన కోట్లాది వీరసమూహాలకు సౌఖ్యాన్ని ఇచ్చేవాడు, శూరపద్ముడు మొదలైన లక్షలకోట్ల శూరులకు (సంహరించి) ముక్తిని ఇచ్చేవాడు, ఇంద్రుడు మొదలైన దేవతాసమూహాలకు సిద్ధులకు నిత్యసౌఖ్యాన్ని ఇచ్చేవాడు అయిన సముద్రతీరవాసి షడాననుని ధ్యానిస్తున్నాను.",
      hi: "वीरबाहु आदि करोड़ों वीरसमूहों को सुख देने वाले, शूरपद्म आदि लाखों-करोड़ों असुरवीरों को (युद्ध में संहार द्वारा) मुक्ति देने वाले, इंद्र आदि देवसमूह तथा सिद्धों को नित्य सौख्य देने वाले — सिंधुतीरवासी उस षडानन का मैं ध्यान करता हूँ।" },
    { s: 1, n: "6",
      deva: "जम्बवैरिकामिनीमनोरथाभिपूरकं\nकुम्भसम्भवाय सर्वधर्मसारदायकम् ।\nतं भवाब्धिपोतमम्बिकेयमाशु सिद्धिदं\nभावयामि सिन्धुतीरवासिनं षडाननम् ॥",
      iast: "jambavairikāminīmanorathābhipūrakaṁ\nkumbhasambhavāya sarvadharmasāradāyakam |\ntaṁ bhavābdhipotamambikeyamāśu siddhidaṁ\nbhāvayāmi sindhutīravāsinaṁ ṣaḍānanam ||",
      en: "I meditate on the six-faced one who dwells on the ocean's shore — who fulfills the heart's desire of Śacī, wife of Indra the foe of Jambha; who gave the essence of all dharma to Agastya, born of the pot (Kumbhasambhava); that very boat that ferries across the ocean of worldly existence (bhavābdhi); son of Ambikā (Pārvatī); swift granter of accomplishment.",
      tel: "జంభాసురుని శత్రువైన ఇంద్రుని భార్య (శచీదేవి) కోరికను తీర్చేవాడు, కుంభసంభవుడైన అగస్త్యమహర్షికి సర్వధర్మసారాన్ని ప్రసాదించినవాడు, సంసారసముద్రాన్ని దాటించే నావ వంటివాడు, అంబికాపుత్రుడు, శీఘ్రంగా సిద్ధిని ఇచ్చేవాడు అయిన సముద్రతీరవాసి షడాననుని ధ్యానిస్తున్నాను.",
      hi: "जंभासुर के शत्रु इंद्र की पत्नी (शची) की मनोकामना पूर्ण करने वाले, कुंभसंभव अगस्त्य मुनि को सर्वधर्म का सार प्रदान करने वाले, संसार-सागर से पार कराने वाली नौका के समान, अंबिका-पुत्र, शीघ्र सिद्धि देने वाले — सिंधुतीरवासी उस षडानन का मैं ध्यान करता हूँ।" },
    { s: 1, n: "7",
      deva: "पूर्णचन्द्रबिम्बकोटितुल्यवक्त्रपङ्कजं\nवर्णनीयसच्चरित्रमिष्टसिद्धिदायकम् ।\nस्वर्णवर्णगात्रमुग्रसिद्धलोकशिक्षकं\nभावयामि सिन्धुतीरवासिनं षडाननम् ॥",
      iast: "pūrṇacandrabimbakoṭitulyavaktrapaṅkajaṁ\nvarṇanīyasaccaritramiṣṭasiddhidāyakam |\nsvarṇavarṇagātramugrasiddhalokaśikṣakaṁ\nbhāvayāmi sindhutīravāsinaṁ ṣaḍānanam ||",
      en: "I meditate on the six-faced one who dwells on the ocean's shore — his lotus face equal to a crore of full moons, his noble conduct fit to be praised, granter of every cherished accomplishment, his body the hue of gold, disciplinarian even of the fierce world of siddhas.",
      tel: "కోట్లకొద్దీ పూర్ణచంద్రబింబాలతో సమానమైన ముఖపద్మం కలవాడు, కీర్తించదగిన సచ్చరిత్రుడు, కోరిన సిద్ధులను ఇచ్చేవాడు, బంగారు వర్ణపు శరీరం కలవాడు, ఉగ్రసిద్ధలోకాన్ని కూడా శాసించగలవాడు అయిన సముద్రతీరవాసి షడాననుని ధ్యానిస్తున్నాను.",
      hi: "करोड़ों पूर्णचंद्र-बिंबों के समान मुखकमल वाले, वर्णन योग्य सच्चरित्र वाले, इष्ट सिद्धियाँ देने वाले, स्वर्णवर्ण शरीर वाले, उग्र सिद्धलोक को भी अनुशासित करने वाले — सिंधुतीरवासी उस षडानन का मैं ध्यान करता हूँ।" },
    { s: 1, n: "8",
      deva: "पूर्वजन्मसञ्चिताघसङ्घभङ्गतत्परं\nसर्वधर्मदानकर्मपूर्वपुण्यसिद्धिदम् ।\nसर्वशत्रुसङ्घभङ्गदक्षमिन्द्रजापतिं\nभावयामि सिन्धुतीरवासिनं षडाननम् ॥",
      iast: "pūrvajanmasañcitāghasaṅghabhaṅgatatparaṁ\nsarvadharmadānakarmapūrvapuṇyasiddhidam |\nsarvaśatrusaṅghabhaṅgadakṣamindrajāpatiṁ\nbhāvayāmi sindhutīravāsinaṁ ṣaḍānanam ||",
      en: "I meditate on the six-faced one who dwells on the ocean's shore — intent on destroying the host of sins accumulated across past births, granter of the fruit of merit earned through every dharma, gift, and good deed, skilled in shattering the host of every enemy, husband of Indrajā (Devasenā, Indra's daughter).",
      tel: "పూర్వజన్మలలో పోగుపడిన పాపసమూహాన్ని నశింపజేయడంలో ఆసక్తి కలవాడు, సర్వధర్మదానకర్మల పూర్వపుణ్యఫలాన్ని ఇచ్చేవాడు, సర్వశత్రుసమూహాన్ని అణచడంలో దక్షుడు, ఇంద్రజ (దేవసేన) పతి అయిన సముద్రతీరవాసి షడాననుని ధ్యానిస్తున్నాను.",
      hi: "पूर्वजन्मों में संचित पाप-समूह के नाश में तत्पर, सर्वधर्म-दान-कर्मों के पूर्वपुण्य का फल देने वाले, समस्त शत्रुसमूह के नाश में दक्ष, इंद्रजा (देवसेना) के पति — सिंधुतीरवासी उस षडानन का मैं ध्यान करता हूँ।" },
  ],
},];
