/* ============================================================
   STUTI — Subrahmaṇya full texts, part 4
   Ṣaṣṭhī Devī Stotram (Brahmavaivarta Purāṇa) · Skanda Stotram
   (Mahābhārata, Āraṇyaka-parvan 233 — Mārkaṇḍeya to Yudhiṣṭhira)
   Devanāgarī keyed from shlokam.org / greatindian.net, checked
   against stotranidhi.com (yaśasvinaṁ normalised in Ṣaṣṭhī 10 to
   match its own v13). `tel` carries the Telugu meaning.
   ============================================================ */
export const extra = [{
  deities: ["subrahmanya"],
  title: "Ṣaṣṭhī Devī Stotram",
  blurb: "To Devasenā — Skanda's consort, the sixth of Prakṛti, guardian of children. Priyavrata's hymn from the Brahmavaivarta Purāṇa, kept wherever a child is prayed for.",
  colophon: { deva: "इति श्रीब्रह्मवैवर्ते षष्ठीदेवीस्तोत्रं सम्पूर्णम् ।", iast: "iti śrī-brahmavaivarte ṣaṣṭhī-devī-stotraṁ sampūrṇam ।" },
  sections: [{ tel: "ధ్యానం", roman: "Dhyānam" }, { tel: "స్తోత్రం", roman: "The Hymn" }, { tel: "ఫలశ్రుతి", roman: "The Fruit of Recitation" }],
  verses: [
    { s: 0, n: "1",
      deva: "श्रीमन्मातरमम्बिकां विधिमनोजातां सदाभीष्टदां\nस्कन्देष्टां च जगत्प्रसूं विजयदां सत्पुत्रसौभाग्यदाम् ।\nसद्रत्नाभरणान्वितां सकरुणां शुभ्रां शुभां सुप्रभां\nषष्ठांशां प्रकृतेः परं भगवतीं श्रीदेवसेनां भजे ॥",
      iast: "śrīman-mātaram ambikāṁ vidhi-manojātāṁ sadābhīṣṭadāṁ\nskandeṣṭāṁ ca jagat-prasūṁ vijaya-dāṁ sat-putra-saubhāgya-dām ।\nsad-ratnābharaṇānvitāṁ sakaruṇāṁ śubhrāṁ śubhāṁ suprabhāṁ\nṣaṣṭhāṁśāṁ prakṛteḥ paraṁ bhagavatīṁ śrī-devasenāṁ bhaje ॥",
      en: "I worship Śrī Devasenā — the gracious Mother, Ambikā, born of Brahmā's mind, ever granting what is wished; beloved of Skanda, mother of the world, giver of victory, of good sons and good fortune; adorned with true gems, compassionate, white-radiant, auspicious — the sixth portion of Prakṛti, the supreme Bhagavatī.",
      tel: "శ్రీమాతను, అంబికను, బ్రహ్మమానసజాతను, సదా అభీష్టములనిచ్చుదానిని; స్కందునికి ప్రియురాలిని, జగత్ప్రసవిత్రిని, విజయమును సత్పుత్రసౌభాగ్యములను ఇచ్చుదానిని; సద్రత్నాభరణాన్వితను, కరుణామయిని, శుభ్రను, శుభను, సుప్రభను — ప్రకృతి షష్ఠాంశ అయిన పరమ భగవతి శ్రీదేవసేనను భజించుచున్నాను." },
    { s: 0, n: "2",
      deva: "षष्ठांशां प्रकृतेः शुद्धां सुप्रतिष्ठां च सुव्रतां\nसुपुत्रदां च शुभदां दयारूपां जगत्प्रसूम् ।\nश्वेतचम्पकवर्णाभां रक्तभूषणभूषितां\nपवित्ररूपां परमं देवसेनां परां भजे ॥",
      iast: "ṣaṣṭhāṁśāṁ prakṛteḥ śuddhāṁ supratiṣṭhāṁ ca suvratāṁ\nsuputra-dāṁ ca śubha-dāṁ dayā-rūpāṁ jagat-prasūm ।\nśveta-campaka-varṇābhāṁ rakta-bhūṣaṇa-bhūṣitāṁ\npavitra-rūpāṁ paramaṁ devasenāṁ parāṁ bhaje ॥",
      en: "The pure sixth portion of Prakṛti, firmly established, true to her vows; giver of good sons and of good itself, compassion embodied, mother of the world; lustrous as the white campaka flower, adorned with red ornaments, of holy form — that supreme Devasenā I worship.",
      tel: "ప్రకృతి షష్ఠాంశను, శుద్ధను, సుప్రతిష్ఠితను, సువ్రతను; సుపుత్రప్రదను, శుభప్రదను, దయాస్వరూపిణిని, జగన్మాతను; తెల్లని సంపెంగ వర్ణకాంతి గలదానిని, ఎర్రని భూషణములతో అలంకృతను, పవిత్రరూపిణిని — ఆ పరమ దేవసేనను భజించుచున్నాను." },
    { s: 1, n: "1",
      deva: "नमो देव्यै महादेव्यै सिद्ध्यै शान्त्यै नमो नमः ।\nशुभायै देवसेनायै षष्ठीदेव्यै नमो नमः ॥",
      iast: "namo devyai mahādevyai siddhyai śāntyai namo namaḥ ।\nśubhāyai devasenāyai ṣaṣṭhī-devyai namo namaḥ ॥",
      en: "Homage to the Goddess, the great Goddess; to Siddhi and to Śānti, homage again and again; to the auspicious one, to Devasenā — to Ṣaṣṭhī Devī, homage upon homage.",
      tel: "దేవికి, మహాదేవికి నమస్కారము; సిద్ధిరూపిణికి, శాంతిరూపిణికి నమో నమః; శుభస్వరూపిణికి, దేవసేనకు — షష్ఠీదేవికి నమో నమః." },
    { s: 1, n: "2",
      deva: "वरदायै पुत्रदायै धनदायै नमो नमः ।\nसुखदायै मोक्षदायै षष्ठीदेव्यै नमो नमः ॥",
      iast: "vara-dāyai putra-dāyai dhana-dāyai namo namaḥ ।\nsukha-dāyai mokṣa-dāyai ṣaṣṭhī-devyai namo namaḥ ॥",
      en: "To the giver of boons, of sons, of wealth, homage again and again; to the giver of happiness, the giver of liberation — to Ṣaṣṭhī Devī, homage upon homage.",
      tel: "వరదకు, పుత్రప్రదకు, ధనప్రదకు నమో నమః; సుఖప్రదకు, మోక్షప్రదకు — షష్ఠీదేవికి నమో నమః." },
    { s: 1, n: "3",
      deva: "सृष्ट्यै षष्ठांशरूपायै सिद्धायै च नमो नमः ।\nमायायै सिद्धयोगिन्यै षष्ठीदेव्यै नमो नमः ॥",
      iast: "sṛṣṭyai ṣaṣṭhāṁśa-rūpāyai siddhāyai ca namo namaḥ ।\nmāyāyai siddha-yoginyai ṣaṣṭhī-devyai namo namaḥ ॥",
      en: "To the creative power in the form of the sixth portion, to the perfected one, homage; to Māyā, to the accomplished yoginī — to Ṣaṣṭhī Devī, homage upon homage.",
      tel: "సృష్టిశక్తికి, షష్ఠాంశరూపిణికి, సిద్ధకు నమో నమః; మాయకు, సిద్ధయోగినికి — షష్ఠీదేవికి నమో నమః." },
    { s: 1, n: "4",
      deva: "सारायै शारदायै च परादेव्यै नमो नमः ।\nबालाधिष्ठातृदेव्यै च षष्ठीदेव्यै नमो नमः ॥",
      iast: "sārāyai śāradāyai ca parā-devyai namo namaḥ ।\nbālādhiṣṭhātṛ-devyai ca ṣaṣṭhī-devyai namo namaḥ ॥",
      en: "To the essence of all, to Śāradā, to the supreme Goddess, homage; to the deity who presides over children — to Ṣaṣṭhī Devī, homage upon homage.",
      tel: "సారస్వరూపిణికి, శారదకు, పరాదేవికి నమో నమః; బాలలకు అధిష్ఠాత్రి యైన దేవికి — షష్ఠీదేవికి నమో నమః." },
    { s: 1, n: "5",
      deva: "कल्याणदायै कल्याण्यै फलदायै च कर्मणाम् ।\nप्रत्यक्षायै सर्वभक्तानां षष्ठीदेव्यै नमो नमः ॥",
      iast: "kalyāṇa-dāyai kalyāṇyai phala-dāyai ca karmaṇām ।\npratyakṣāyai sarva-bhaktānāṁ ṣaṣṭhī-devyai namo namaḥ ॥",
      en: "To the giver of welfare, herself all-auspicious, dispenser of the fruits of deeds; who shows herself before the eyes of all her devotees — to Ṣaṣṭhī Devī, homage upon homage.",
      tel: "కల్యాణప్రదకు, కల్యాణికి, కర్మఫలప్రదకు; సకల భక్తులకు ప్రత్యక్షమగుదానికి — షష్ఠీదేవికి నమో నమః." },
    { s: 1, n: "6",
      deva: "पूज्यायै स्कन्दकान्तायै सर्वेषां सर्वकर्मसु ।\nदेवरक्षणकारिण्यै षष्ठीदेव्यै नमो नमः ॥",
      iast: "pūjyāyai skanda-kāntāyai sarveṣāṁ sarva-karmasu ।\ndeva-rakṣaṇa-kāriṇyai ṣaṣṭhī-devyai namo namaḥ ॥",
      en: "To her whom all must worship in every rite, the beloved of Skanda, protectress even of the gods — to Ṣaṣṭhī Devī, homage upon homage.",
      tel: "సర్వుల సర్వకర్మలలో పూజ్యురాలికి, స్కందకాంతకు, దేవతలను రక్షించుదానికి — షష్ఠీదేవికి నమో నమః." },
    { s: 1, n: "7",
      deva: "शुद्धसत्त्वस्वरूपायै वन्दितायै नृणां सदा ।\nहिंसाक्रोधवर्जितायै षष्ठीदेव्यै नमो नमः ॥",
      iast: "śuddha-sattva-svarūpāyai vanditāyai nṛṇāṁ sadā ।\nhiṁsā-krodha-varjitāyai ṣaṣṭhī-devyai namo namaḥ ॥",
      en: "To her whose nature is pure sattva, whom mankind salutes for ever, in whom is no violence and no anger — to Ṣaṣṭhī Devī, homage upon homage.",
      tel: "శుద్ధసత్త్వస్వరూపిణికి, నరులచే సదా వందితకు, హింసాక్రోధరహితకు — షష్ఠీదేవికి నమో నమః." },
    { s: 1, n: "8",
      deva: "धनं देहि प्रियां देहि पुत्रं देहि सुरेश्वरि ।\nमानं देहि जयं देहि द्विषो जहि महेश्वरि ॥",
      iast: "dhanaṁ dehi priyāṁ dehi putraṁ dehi sureśvari ।\nmānaṁ dehi jayaṁ dehi dviṣo jahi maheśvari ॥",
      en: "Give wealth, give a beloved, give a son, O queen of the gods; give honour, give victory, and strike down those who hate us, O great Goddess.",
      tel: "ధనమునిమ్ము, ప్రియను ఇమ్ము, పుత్రుని ఇమ్ము, ఓ సురేశ్వరీ; మానము నిమ్ము, జయము నిమ్ము, శత్రువులను హరింపుము, ఓ మహేశ్వరీ." },
    { s: 1, n: "9",
      deva: "धर्मं देहि यशो देहि षष्ठीदेवि नमो नमः ।\nदेहि भूमिं प्रजां देहि विद्यां देहि सुपूजिते ।\nकल्याणं च जयं देहि षष्ठीदेव्यै नमो नमः ॥",
      iast: "dharmaṁ dehi yaśo dehi ṣaṣṭhī-devi namo namaḥ ।\ndehi bhūmiṁ prajāṁ dehi vidyāṁ dehi supūjite ।\nkalyāṇaṁ ca jayaṁ dehi ṣaṣṭhī-devyai namo namaḥ ॥",
      en: "Give dharma, give renown — Ṣaṣṭhī Devī, homage to you; give land, give progeny, give learning, O greatly worshipped one; give welfare and victory — to Ṣaṣṭhī Devī, homage upon homage.",
      tel: "ధర్మము నిమ్ము, యశస్సు నిమ్ము — షష్ఠీదేవీ, నమో నమః; భూమిని, సంతానమును, విద్యను ఇమ్ము, ఓ సుపూజితా; కల్యాణమును జయమును ఇమ్ము — షష్ఠీదేవికి నమో నమః." },
    { s: 2, n: "10",
      deva: "इति देवीं च संस्तुत्य लभेत्पुत्रं प्रियव्रतम् ।\nयशस्विनं च राजेन्द्रं षष्ठीदेवीप्रसादतः ॥",
      iast: "iti devīṁ ca saṁstutya labhet putraṁ priyavratam ।\nyaśasvinaṁ ca rājendraṁ ṣaṣṭhī-devī-prasādataḥ ॥",
      en: "Praising the Goddess thus, one obtains — as king Priyavrata did — a son devoted to his vows, renowned, princely, by the grace of Ṣaṣṭhī Devī.",
      tel: "ఈ విధముగా దేవిని స్తుతించి, ప్రియవ్రతునివలె — వ్రతనిష్ఠుడు, యశస్వి, రాజేంద్రుడైన పుత్రుని షష్ఠీదేవి ప్రసాదముచే పొందును." },
    { s: 2, n: "11",
      deva: "षष्ठीस्तोत्रमिदं ब्रह्मान् यः शृणोति तु वत्सरम् ।\nअपुत्रो लभते पुत्रं वरं सुचिरजीवनम् ॥",
      iast: "ṣaṣṭhī-stotram idaṁ brahmān yaḥ śṛṇoti tu vatsaram ।\naputro labhate putraṁ varaṁ sucira-jīvanam ॥",
      en: "O Brahman — whoever hears this Ṣaṣṭhī-stotra for a year: the sonless gains an excellent, long-lived son.",
      tel: "ఓ బ్రహ్మజ్ఞా — ఈ షష్ఠీస్తోత్రమును ఒక సంవత్సరము వినువాడు: పుత్రహీనుడు శ్రేష్ఠుడైన, దీర్ఘాయుష్మంతుడైన పుత్రుని పొందును." },
    { s: 2, n: "12",
      deva: "वर्षमेकं च या भक्त्या संस्तुत्येदं शृणोति च ।\nसर्वपापाद्विनिर्मुक्ता महावन्ध्या प्रसूयते ॥",
      iast: "varṣam ekaṁ ca yā bhaktyā saṁstutyedaṁ śṛṇoti ca ।\nsarva-pāpād vinirmuktā mahā-vandhyā prasūyate ॥",
      en: "And the woman who recites and hears it with devotion for one year — released from every sin, even one long deemed barren gives birth.",
      tel: "ఏ స్త్రీ ఒక సంవత్సరము భక్తితో దీనిని స్తుతించి వినునో — సర్వపాపవిముక్తయై, మహావంధ్య అయినను ప్రసవించును." },
    { s: 2, n: "13",
      deva: "वीरं पुत्रं च गुणिनं विद्यावन्तं यशस्विनम् ।\nसुचिरायुष्यवन्तं च सूते देवीप्रसादतः ॥",
      iast: "vīraṁ putraṁ ca guṇinaṁ vidyāvantaṁ yaśasvinam ।\nsucirāyuṣyavantaṁ ca sūte devī-prasādataḥ ॥",
      en: "By the Goddess's grace she bears a son heroic, virtuous, learned, renowned and long of life.",
      tel: "దేవి ప్రసాదముచే — వీరుడు, గుణవంతుడు, విద్యావంతుడు, యశస్వి, దీర్ఘాయుష్మంతుడైన పుత్రుని కనును." },
    { s: 2, n: "14",
      deva: "काकवन्ध्या च या नारी मृतवत्सा च या भवेत् ।\nवर्षं श्रुत्वा लभेत्पुत्रं षष्ठीदेवीप्रसादतः ॥",
      iast: "kāka-vandhyā ca yā nārī mṛta-vatsā ca yā bhavet ।\nvarṣaṁ śrutvā labhet putraṁ ṣaṣṭhī-devī-prasādataḥ ॥",
      en: "The woman who has borne but one child, and she whose children have died — hearing it for a year, she gains a son by the grace of Ṣaṣṭhī Devī.",
      tel: "ఒకే బిడ్డతో ఆగిన కాకవంధ్య, బిడ్డలు మృతులైన మృతవత్స — సంవత్సరము విని, షష్ఠీదేవి ప్రసాదముచే పుత్రుని పొందుదురు." },
    { s: 2, n: "15",
      deva: "रोगयुक्ते च बाले च पितामाता शृणोति चेत् ।\nमासेन मुच्यते रोगान् षष्ठीदेवीप्रसादतः ॥",
      iast: "roga-yukte ca bāle ca pitā-mātā śṛṇoti cet ।\nmāsena mucyate rogān ṣaṣṭhī-devī-prasādataḥ ॥",
      en: "And when a child lies ill — if father and mother hear this hymn, within a month the child is freed of its disease, by the grace of Ṣaṣṭhī Devī.",
      tel: "బిడ్డ రోగపీడితుడైనప్పుడు తల్లిదండ్రులు దీనిని విన్నచో — నెలలోపల ఆ బిడ్డ రోగవిముక్తుడగును, షష్ఠీదేవి ప్రసాదముచే." },
    { s: 2, n: "16",
      deva: "जय देवि जगन्मातः जगदानन्दकारिणि ।\nप्रसीद मम कल्याणि नमस्ते षष्ठीदेवते ॥",
      iast: "jaya devi jagan-mātaḥ jagad-ānanda-kāriṇi ।\nprasīda mama kalyāṇi namas te ṣaṣṭhī-devate ॥",
      en: "Victory, O Goddess, mother of the world, maker of the world's joy! Be gracious to me, O auspicious one — homage to you, divine Ṣaṣṭhī.",
      tel: "జయము, ఓ దేవీ, జగన్మాతా, జగదానందకారిణీ! నాయందు ప్రసన్నురాలవు కమ్ము, ఓ కల్యాణీ — నీకు నమస్కారము, ఓ షష్ఠీదేవతా." },
  ],
},

{
  deities: ["subrahmanya"],
  title: "Skanda Stotram (Mahābhārate)",
  blurb: "Mārkaṇḍeya answers Yudhiṣṭhira in the forest — first the divine names of Kārtikeya, then a praise that widens until Skanda is the year, the directions, and the worlds.",
  colophon: { deva: "इति श्रीमन्महाभारते अरण्यपर्वणि त्रयस्त्रिंशदधिकद्विशततमोऽध्याये स्कन्दस्तोत्रम् ॥", iast: "iti śrīman-mahābhārate araṇya-parvaṇi trayastriṁśad-adhika-dviśatatamo'dhyāye skanda-stotram ॥" },
  sections: [{ tel: "దివ్యనామాలు", roman: "The Divine Names" }, { tel: "స్తుతి", roman: "The Praise" }, { tel: "ఫలశ్రుతి", roman: "The Fruit of Recitation" }],
  verses: [
    { s: 0, n: "1",
      deva: "मार्कण्डेय उवाच ।\nआग्नेयश्चैव स्कन्दश्च दीप्तकीर्तिरनामयः ।\nमयूरकेतुर्धर्मात्मा भूतेशो महिषार्दनः ॥",
      iast: "mārkaṇḍeya uvāca ।\nāgneyaś caiva skandaś ca dīpta-kīrtir anāmayaḥ ।\nmayūra-ketur dharmātmā bhūteśo mahiṣārdanaḥ ॥",
      en: "Mārkaṇḍeya said: Son of Agni; Skanda; he of blazing fame; the ever-hale; peacock-bannered; the dharma-souled; lord of beings; crusher of Mahiṣa.",
      tel: "మార్కండేయుడు పలికెను — ఆగ్నేయుడు; స్కందుడు; దీప్తకీర్తి; అనామయుడు; మయూరకేతువు; ధర్మాత్ముడు; భూతేశుడు; మహిషార్దనుడు." },
    { s: 0, n: "2",
      deva: "कामजित्कामदः कान्तः सत्यवाग्भुवनेश्वरः ।\nशिशुः शीघ्रः शुचिश्चण्डो दीप्तवर्णः शुभाननः ॥",
      iast: "kāma-jit kāma-daḥ kāntaḥ satya-vāg bhuvaneśvaraḥ ।\nśiśuḥ śīghraḥ śuciś caṇḍo dīpta-varṇaḥ śubhānanaḥ ॥",
      en: "Conqueror of desire, yet giver of desires; the beautiful; true of speech; lord of the worlds; the child; the swift; the pure; the fierce; bright-hued; fair-faced.",
      tel: "కామజిత్తు; కామదుడు; కాంతుడు; సత్యవాక్కు; భువనేశ్వరుడు; శిశువు; శీఘ్రుడు; శుచి; చండుడు; దీప్తవర్ణుడు; శుభాననుడు." },
    { s: 0, n: "3",
      deva: "अमोघस्त्वनघो रौद्रः प्रियश्चन्द्राननस्तथा ।\nदीप्तशक्तिः प्रशान्तात्मा भद्रकृत्कुक्कुटध्वजः ॥",
      iast: "amoghas tv anagho raudraḥ priyaś candrānanas tathā ।\ndīpta-śaktiḥ praśāntātmā bhadra-kṛt kukkuṭa-dhvajaḥ ॥",
      en: "The unfailing; the sinless; the Rudra-fierce; the dear one; moon-faced; bearer of the blazing spear; serene of soul; worker of good; rooster-bannered.",
      tel: "అమోఘుడు; అనఘుడు; రౌద్రుడు; ప్రియుడు; చంద్రాననుడు; దీప్తశక్తి; ప్రశాంతాత్ముడు; భద్రకృత్తు; కుక్కుటధ్వజుడు." },
    { s: 0, n: "4",
      deva: "षष्ठीप्रियश्च धर्मात्मा पवित्रो मातृवत्सलः ।\nकन्याभर्ता विभक्तश्च स्वाहेयो रेवतीसुतः ॥",
      iast: "ṣaṣṭhī-priyaś ca dharmātmā pavitro mātṛ-vatsalaḥ ।\nkanyā-bhartā vibhaktaś ca svāheyo revatī-sutaḥ ॥",
      en: "Beloved of Ṣaṣṭhī; righteous-souled; the purifier; tender to the Mothers; husband of the divine maiden; the many-parted; son of Svāhā; child of Revatī.",
      tel: "షష్ఠీప్రియుడు; ధర్మాత్ముడు; పవిత్రుడు; మాతృవత్సలుడు; కన్యాభర్త; విభక్తుడు; స్వాహేయుడు; రేవతీసుతుడు." },
    { s: 0, n: "5",
      deva: "प्रभुर्नेता विशाखश्च नैगमेयः सुदुश्चरः ।\nसुव्रतो ललितश्चैव बालक्रीडनकप्रियः ॥",
      iast: "prabhur netā viśākhaś ca naigameyaḥ suduścaraḥ ।\nsuvrato lalitaś caiva bāla-krīḍanaka-priyaḥ ॥",
      en: "The master; the leader; Viśākha; Naigameya; he whose way is hard to follow; true to vows; the graceful; fond of children's play.",
      tel: "ప్రభువు; నేత; విశాఖుడు; నైగమేయుడు; సుదుశ్చరుడు; సువ్రతుడు; లలితుడు; బాలక్రీడనకప్రియుడు." },
    { s: 0, n: "6",
      deva: "खचारी ब्रह्मचारी च शूरः शरवणोद्भवः ।\nविश्वामित्रप्रियश्चैव देवसेनाप्रियस्तथा ।\nवासुदेवप्रियश्चैव प्रियः प्रियकृदेव तु ॥",
      iast: "kha-cārī brahmacārī ca śūraḥ śaravaṇodbhavaḥ ।\nviśvāmitra-priyaś caiva devasenā-priyas tathā ।\nvāsudeva-priyaś caiva priyaḥ priya-kṛd eva tu ॥",
      en: "Walker of the sky; the celibate; the hero; born of the reed-thicket; dear to Viśvāmitra, dear to Devasenā, dear to Vāsudeva — the beloved, and the doer of what is dear.",
      tel: "ఖచారి; బ్రహ్మచారి; శూరుడు; శరవణోద్భవుడు; విశ్వామిత్రప్రియుడు; దేవసేనాప్రియుడు; వాసుదేవప్రియుడు; ప్రియుడు; ప్రియకృత్తు." },
    { s: 0, n: "7",
      deva: "नामान्येतानि दिव्यानि कार्तिकेयस्य यः पठेत् ।\nस्वर्गं कीर्तिं धनं चैव स लभेन्नात्र संशयः ॥",
      iast: "nāmāny etāni divyāni kārtikeyasya yaḥ paṭhet ।\nsvargaṁ kīrtiṁ dhanaṁ caiva sa labhen nātra saṁśayaḥ ॥",
      en: "Whoever recites these divine names of Kārtikeya gains heaven, fame and wealth — of this there is no doubt.",
      tel: "కార్తికేయుని ఈ దివ్యనామములను పఠించువాడు స్వర్గమును, కీర్తిని, ధనమును పొందును — ఇందు సంశయము లేదు." },
    { s: 1, n: "8",
      deva: "स्तोष्यामि देवैर्ऋषिभिश्च जुष्टं\nशक्त्या गुहं नामभिरप्रमेयम् ।\nषडाननं शक्तिधरं सुवीरं\nनिबोध चैतानि कुरुप्रवीर ॥",
      iast: "stoṣyāmi devair ṛṣibhiś ca juṣṭaṁ\nśaktyā guhaṁ nāmabhir aprameyam ।\nṣaḍānanaṁ śakti-dharaṁ suvīraṁ\nnibodha caitāni kuru-pravīra ॥",
      en: "\"Now I shall praise, as far as my power reaches, Guha whom gods and seers attend — the immeasurable one, six-faced, spear-bearing, truly heroic. Hear these names, hero of the Kurus.\"",
      tel: "\"దేవతలు ఋషులు సేవించు గుహుని — అప్రమేయుని, షడాననుని, శక్తిధరుని, సువీరుని — నా శక్తికొలది నామములతో స్తుతించెదను. ఓ కురుప్రవీరా, వినుము.\"" },
    { s: 1, n: "9",
      deva: "ब्रह्मण्यो वै ब्रह्मजो ब्रह्मविच्च\nब्रह्मेशयो ब्रह्मवतां वरिष्ठः ।\nब्रह्मप्रियो ब्राह्मणसर्वमन्त्री त्वं\nब्रह्मणां ब्राह्मणानां च नेता ॥",
      iast: "brahmaṇyo vai brahmajo brahma-vic ca\nbrahmeśayo brahmavatāṁ variṣṭhaḥ ।\nbrahma-priyo brāhmaṇa-sarva-mantrī tvaṁ\nbrahmaṇāṁ brāhmaṇānāṁ ca netā ॥",
      en: "Devoted to Brahman, born of Brahman, knower of Brahman; resting in Brahman, first among the knowers of Brahman; lover of Brahman, counsellor of all the brāhmaṇas — you are the leader of prayers and of those who pray.",
      tel: "బ్రహ్మణ్యుడవు, బ్రహ్మజుడవు, బ్రహ్మవేత్తవు; బ్రహ్మమునందు శయనించువాడవు, బ్రహ్మవేత్తలలో వరిష్ఠుడవు; బ్రహ్మప్రియుడవు, బ్రాహ్మణులకు సర్వమంత్రివి — వేదములకు, బ్రాహ్మణులకు నేతవు నీవే." },
    { s: 1, n: "10",
      deva: "स्वाहा स्वधा त्वं परमं पवित्रं\nमन्त्रस्तुतस्त्वं प्रथितः षडर्चिः ।\nसंवत्सरस्त्वमृतवश्च षड्वै\nमासार्धमासाश्च दिनं दिशश्च ॥",
      iast: "svāhā svadhā tvaṁ paramaṁ pavitraṁ\nmantra-stutas tvaṁ prathitaḥ ṣaḍ-arciḥ ।\nsaṁvatsaras tvam ṛtavaś ca ṣaḍ vai\nmāsārdha-māsāś ca dinaṁ diśaś ca ॥",
      en: "You are svāhā and svadhā, the supreme purity; hymned by the mantras, famed as the six-flamed fire; you are the year, the six seasons, the months and fortnights, the day, and the directions themselves.",
      tel: "స్వాహా నీవే, స్వధా నీవే, పరమ పవిత్రము నీవే; మంత్రస్తుతుడవు, షడర్చి యని ప్రసిద్ధుడవు; సంవత్సరము నీవే, ఆరు ఋతువులు, మాసార్ధమాసములు, దినము, దిక్కులు — అన్నియు నీవే." },
    { s: 1, n: "11",
      deva: "त्वं पुष्कराक्षस्त्वरविन्दवक्त्रः\nसहस्रचक्षोऽसि सहस्रबाहुः ।\nत्वं लोकपालः परमं हविश्च\nत्वं भावनः सर्वसुरासुराणाम् ॥",
      iast: "tvaṁ puṣkarākṣas tv aravinda-vaktraḥ\nsahasra-cakṣo'si sahasra-bāhuḥ ।\ntvaṁ loka-pālaḥ paramaṁ haviś ca\ntvaṁ bhāvanaḥ sarva-surāsurāṇām ॥",
      en: "Lotus-eyed, lotus-faced; thousand-eyed and thousand-armed; guardian of the worlds and the supreme oblation itself; you are the origin of all the gods and the asuras.",
      tel: "పుష్కరాక్షుడవు, అరవిందవక్త్రుడవు; సహస్రచక్షువు, సహస్రబాహుడవు; లోకపాలుడవు, పరమ హవిస్సు నీవే; సర్వ సురాసురులకు భావనుడవు — ఉత్పత్తిస్థానము నీవే." },
    { s: 1, n: "12",
      deva: "त्वमेव सेनाधिपतिः प्रचण्डः\nप्रभुर्विभुश्चाप्यथ शक्रजेता ।\nसहस्रभूस्त्वं धरणी त्वमेव\nसहस्रतुष्टिश्च सहस्रभुक्च ॥",
      iast: "tvam eva senādhipatiḥ pracaṇḍaḥ\nprabhur vibhuś cāpy atha śakra-jetā ।\nsahasra-bhūs tvaṁ dharaṇī tvam eva\nsahasra-tuṣṭiś ca sahasra-bhuk ca ॥",
      en: "You alone are the fierce commander of the hosts, master, all-pervading, victor even over Indra's foes; thousand-fold in being, you are the earth itself, thousand-fold in contentment, thousand-fold the enjoyer.",
      tel: "ప్రచండుడైన సేనాధిపతివి నీవే; ప్రభుడవు, విభుడవు, శక్రజేతవు; సహస్రరూపుడవు, ధరణివి నీవే; సహస్రతుష్టివి, సహస్రభుక్కువు." },
    { s: 1, n: "13",
      deva: "सहस्रशीर्षस्त्वमनन्तरूपः\nसहस्रपात्त्वं दशशक्तिधारी ।\nगङ्गासुतस्त्वं स्वमतेन देव\nस्वाहामहीकृत्तिकानां तथैव ॥",
      iast: "sahasra-śīrṣas tvam ananta-rūpaḥ\nsahasra-pāt tvaṁ daśa-śakti-dhārī ।\ngaṅgā-sutas tvaṁ sva-matena deva\nsvāhā-mahī-kṛttikānāṁ tathaiva ॥",
      en: "Thousand-headed, of endless form, thousand-footed, wielder of the tenfold power; by each one's own reckoning, O god, you are son of Gaṅgā, of Svāhā, of the Earth, of the Kṛttikās alike.",
      tel: "సహస్రశీర్షుడవు, అనంతరూపుడవు, సహస్రపాదుడవు, దశశక్తిధారివి; ఓ దేవా — ఎవరి మతమున వారికి గంగాసుతుడవు, స్వాహాసుతుడవు, భూసుతుడవు, కృత్తికాసుతుడవు నీవే." },
    { s: 1, n: "14",
      deva: "त्वं क्रीडसे षण्मुख कुक्कुटेन\nयथेष्टनानाविधकामरूपी ।\nदीक्षाऽसि सोमो मरुतः सदैव\nधर्मोऽसि वायुरचलेन्द्र इन्द्रः ॥",
      iast: "tvaṁ krīḍase ṣaṇmukha kukkuṭena\nyatheṣṭa-nānā-vidha-kāma-rūpī ।\ndīkṣā'si somo marutaḥ sadaiva\ndharmo'si vāyur acalendra indraḥ ॥",
      en: "You play, six-faced one, with your rooster, taking whatever forms you please; you are the rite's consecration, Soma, the Maruts for ever; you are Dharma, the Wind, the king of mountains, Indra.",
      tel: "ఓ షణ్ముఖా, ఇష్టము వచ్చిన నానా రూపములు దాల్చుచు కుక్కుటముతో క్రీడించుచున్నావు; దీక్షవు నీవే, సోముడవు, మరుత్తులవు; ధర్ముడవు, వాయువువు, పర్వతరాజువు, ఇంద్రుడవు నీవే." },
    { s: 1, n: "15",
      deva: "सनातनानामपि शाश्वतस्त्वं\nप्रभुः प्रभूणामपि चोग्रधन्वा ।\nऋतस्य कर्ता दितिजान्तकस्त्वं\nजेता रिपूणां प्रवरः सुराणाम् ॥",
      iast: "sanātanānām api śāśvatas tvaṁ\nprabhuḥ prabhūṇām api cogra-dhanvā ।\nṛtasya kartā ditijāntakas tvaṁ\njetā ripūṇāṁ pravaraḥ surāṇām ॥",
      en: "More lasting than the everlasting ones, lord over lords, bearer of the terrible bow; maker of the cosmic order, ender of Diti's sons, conqueror of foes, foremost of the gods.",
      tel: "సనాతనులకును శాశ్వతుడవు; ప్రభువులకును ప్రభుడవు, ఉగ్రధన్వుడవు; ఋతమునకు కర్తవు, దితిజాంతకుడవు; శత్రుజేతవు, సురలలో ప్రవరుడవు." },
    { s: 1, n: "16",
      deva: "सूक्ष्मं तपस्तत्परमं त्वमेव\nपरावरज्ञोऽसि परावरस्त्वम् ।\nधर्मस्य कामस्य परस्य चैव\nत्वत्तेजसा कृत्स्नमिदं महात्मन् ॥",
      iast: "sūkṣmaṁ tapas tat paramaṁ tvam eva\nparāvara-jño'si parāvaras tvam ।\ndharmasya kāmasya parasya caiva\ntvat-tejasā kṛtsnam idaṁ mahātman ॥",
      en: "You are that subtlest, highest tapas; knower of the high and the low, and yourself both; of dharma, of desire, and of what lies beyond — by your fire, great-souled one, this whole world is filled.",
      tel: "సూక్ష్మము, పరమము అయిన తపస్సు నీవే; పరావరజ్ఞుడవు, పరావరుడవు నీవే; ధర్మము, కామము, పరతత్త్వము — ఓ మహాత్మా, నీ తేజస్సుచే ఈ సమస్తము నిండియున్నది." },
    { s: 1, n: "17",
      deva: "व्याप्तं जगत्सर्वसुरप्रवीर\nशक्त्या मया संस्तुत लोकनाथ ।\nनमोऽस्तु ते द्वादशनेत्रबाहो\nअतः परं वेद्मि गतिं न तेऽहम् ॥",
      iast: "vyāptaṁ jagat sarva-sura-pravīra\nśaktyā mayā saṁstuta loka-nātha ।\nnamo'stu te dvādaśa-netra-bāho\nataḥ paraṁ vedmi gatiṁ na te'ham ॥",
      en: "The world is pervaded by you, first hero of all the gods. I have praised you as far as my strength allows, lord of the worlds. Homage to you of the twelve eyes and twelve arms — beyond this I cannot follow where you go.",
      tel: "ఓ సర్వసురప్రవీరా, జగత్తు నీచే వ్యాపింపబడియున్నది; ఓ లోకనాథా, నా శక్తికొలది నిన్ను స్తుతించితిని. ద్వాదశనేత్రబాహుడా, నీకు నమస్కారము — ఇంతకుమించి నీ గతిని నేనెరుగను." },
    { s: 2, n: "18",
      deva: "स्कन्दस्य य इदं विप्रः पठेज्जन्म समाहितः ।\nश्रावयेद्ब्राह्मणेभ्यो यः शृणुयाद्वा द्विजेरितम् ॥",
      iast: "skandasya ya idaṁ vipraḥ paṭhej janma samāhitaḥ ।\nśrāvayed brāhmaṇebhyo yaḥ śṛṇuyād vā dvijeritam ॥",
      en: "The learned one who with collected mind recites this birth-story of Skanda, who causes brāhmaṇas to hear it, or hears it told by the twice-born —",
      tel: "ఏ విప్రుడు ఏకాగ్రచిత్తుడై ఈ స్కందజన్మవృత్తాంతమును పఠించునో, బ్రాహ్మణులకు వినిపించునో, ద్విజులు చెప్పగా వినునో —" },
    { s: 2, n: "19",
      deva: "धनमायुर्यशो दीप्तं पुत्रान् शत्रुजयं तथा ।\nस पुष्टितुष्टी सम्प्राप्य स्कन्दसालोक्यमाप्नुयात् ॥",
      iast: "dhanam āyur yaśo dīptaṁ putrān śatru-jayaṁ tathā ।\nsa puṣṭi-tuṣṭī samprāpya skanda-sālokyam āpnuyāt ॥",
      en: "— gains wealth, long life, blazing fame, sons and victory over enemies; and having won fullness and contentment, he attains the world of Skanda.",
      tel: "— ధనమును, ఆయువును, దీప్తమైన యశస్సును, పుత్రులను, శత్రుజయమును పొంది; పుష్టిని తుష్టిని పొంది, స్కందసాలోక్యమును పొందును." },
  ],
}];
