/* ============================================================
   STUTI — Śiva full texts, part 1
   Liṅgāṣṭakam · Rudrāṣṭakam · Nirvāṇa Ṣaṭkam · Śiva Mānasa Pūjā
   · Toṭakāṣṭakam
   Devanāgarī is the source of truth; Telugu and other scripts are
   derived at read time by stuti-translit.js. `tel` carries the
   Telugu meaning (అర్థం), not the mūla.
   Titles must match STOTRA_INDEX exactly — that is how each text
   binds to its catalogue entry.
   ============================================================ */
export const extra = [{
  deities: ["shiva"],
  title: "Liṅgāṣṭakam",
  blurb: "Eight verses that do one thing eight times — name the liṅga, and bow to it. Recited walking the shrine.",
  sections: [{ tel: "స్తోత్రం", roman: "The Eight Verses" }, { tel: "ఫలశ్రుతి", roman: "The Fruit of Recitation" }],
  verses: [
    { s: 0, n: "1",
      deva: "ब्रह्ममुरारिसुरार्चितलिङ्गं\nनिर्मलभासितशोभितलिङ्गम् ।\nजन्मजदुःखविनाशकलिङ्गं\nतत्प्रणमामि सदाशिवलिङ्गम् ॥",
      iast: "brahma-murāri-surārcita-liṅgaṁ\nnirmala-bhāsita-śobhita-liṅgam ।\njanmaja-duḥkha-vināśaka-liṅgaṁ\ntat-praṇamāmi sadāśiva-liṅgam ॥",
      en: "The liṅga worshipped by Brahmā, by Viṣṇu the foe of Mura, and by the gods; the liṅga shining with a spotless light; the liṅga that destroys the sorrow born of birth — to that liṅga of Sadāśiva I bow.",
      tel: "బ్రహ్మచేత, మురారి అయిన విష్ణువుచేత, దేవతలచేత అర్చించబడిన లింగము; నిర్మలమైన కాంతితో ప్రకాశించే లింగము; జన్మవలన కలిగే దుఃఖమును నశింపజేసే లింగము — ఆ సదాశివ లింగమునకు నమస్కరించుచున్నాను." },
    { s: 0, n: "2",
      deva: "देवमुनिप्रवरार्चितलिङ्गं\nकामदहं करुणाकरलिङ्गम् ।\nरावणदर्पविनाशनलिङ्गं\nतत्प्रणमामि सदाशिवलिङ्गम् ॥",
      iast: "deva-muni-pravarārcita-liṅgaṁ\nkāma-dahaṁ karuṇākara-liṅgam ।\nrāvaṇa-darpa-vināśana-liṅgaṁ\ntat-praṇamāmi sadāśiva-liṅgam ॥",
      en: "The liṅga worshipped by the gods and the foremost of sages; the liṅga that burned Kāma, the very mine of compassion; the liṅga that broke the pride of Rāvaṇa — to that liṅga of Sadāśiva I bow.",
      tel: "దేవతలచేత, మునిశ్రేష్ఠులచేత అర్చించబడిన లింగము; మన్మథుని దహించినది, కరుణకు నిధియైన లింగము; రావణుని గర్వమును అణచిన లింగము — ఆ సదాశివ లింగమునకు నమస్కరించుచున్నాను." },
    { s: 0, n: "3",
      deva: "सर्वसुगन्धिसुलेपितलिङ्गं\nबुद्धिविवर्धनकारणलिङ्गम् ।\nसिद्धसुरासुरवन्दितलिङ्गं\nतत्प्रणमामि सदाशिवलिङ्गम् ॥",
      iast: "sarva-sugandhi-sulepita-liṅgaṁ\nbuddhi-vivardhana-kāraṇa-liṅgam ।\nsiddha-surāsura-vandita-liṅgaṁ\ntat-praṇamāmi sadāśiva-liṅgam ॥",
      en: "The liṅga anointed with every fragrance; the liṅga that is the cause of the growth of understanding; the liṅga saluted by siddhas, gods and asuras alike — to that liṅga of Sadāśiva I bow.",
      tel: "సర్వ సుగంధములతో లేపనము చేయబడిన లింగము; బుద్ధి వికాసమునకు కారణమైన లింగము; సిద్ధులచేత, దేవతలచేత, అసురులచేత వందించబడిన లింగము — ఆ సదాశివ లింగమునకు నమస్కరించుచున్నాను." },
    { s: 0, n: "4",
      deva: "कनकमहामणिभूषितलिङ्गं\nफणिपतिवेष्टितशोभितलिङ्गम् ।\nदक्षसुयज्ञविनाशनलिङ्गं\nतत्प्रणमामि सदाशिवलिङ्गम् ॥",
      iast: "kanaka-mahāmaṇi-bhūṣita-liṅgaṁ\nphaṇipati-veṣṭita-śobhita-liṅgam ।\ndakṣa-suyajña-vināśana-liṅgaṁ\ntat-praṇamāmi sadāśiva-liṅgam ॥",
      en: "The liṅga adorned with gold and great gems; the liṅga made beautiful by the lord of serpents coiled about it; the liṅga that undid Dakṣa's grand sacrifice — to that liṅga of Sadāśiva I bow.",
      tel: "బంగారముతో, మహామణులతో అలంకరించబడిన లింగము; సర్పరాజు చుట్టుకొని ఉండగా శోభించే లింగము; దక్షుని యజ్ఞమును నాశనము చేసిన లింగము — ఆ సదాశివ లింగమునకు నమస్కరించుచున్నాను." },
    { s: 0, n: "5",
      deva: "कुङ्कुमचन्दनलेपितलिङ्गं\nपङ्कजहारसुशोभितलिङ्गम् ।\nसञ्चितपापविनाशनलिङ्गं\nतत्प्रणमामि सदाशिवलिङ्गम् ॥",
      iast: "kuṅkuma-candana-lepita-liṅgaṁ\npaṅkaja-hāra-suśobhita-liṅgam ।\nsañcita-pāpa-vināśana-liṅgaṁ\ntat-praṇamāmi sadāśiva-liṅgam ॥",
      en: "The liṅga smeared with kumkuma and sandal; the liṅga graced with a garland of lotuses; the liṅga that destroys the sin heaped up over lifetimes — to that liṅga of Sadāśiva I bow.",
      tel: "కుంకుమతో, చందనముతో లేపనము చేయబడిన లింగము; పద్మముల హారముతో శోభించే లింగము; సంచిత పాపమును నశింపజేసే లింగము — ఆ సదాశివ లింగమునకు నమస్కరించుచున్నాను." },
    { s: 0, n: "6",
      deva: "देवगणार्चितसेवितलिङ्गं\nभावैर्भक्तिभिरेव च लिङ्गम् ।\nदिनकरकोटिप्रभाकरलिङ्गं\nतत्प्रणमामि सदाशिवलिङ्गम् ॥",
      iast: "deva-gaṇārcita-sevita-liṅgaṁ\nbhāvair-bhaktibhir-eva ca liṅgam ।\ndinakara-koṭi-prabhākara-liṅgaṁ\ntat-praṇamāmi sadāśiva-liṅgam ॥",
      en: "The liṅga worshipped and served by the hosts of gods; the liṅga reached by feeling and devotion alone; the liṅga blazing like ten million suns — to that liṅga of Sadāśiva I bow.",
      tel: "దేవగణములచేత అర్చించబడి సేవించబడిన లింగము; భావముచేత, భక్తిచేత మాత్రమే చేరదగిన లింగము; కోటి సూర్యుల కాంతితో వెలిగే లింగము — ఆ సదాశివ లింగమునకు నమస్కరించుచున్నాను." },
    { s: 0, n: "7",
      deva: "अष्टदलोपरिवेष्टितलिङ्गं\nसर्वसमुद्भवकारणलिङ्गम् ।\nअष्टदरिद्रविनाशितलिङ्गं\nतत्प्रणमामि सदाशिवलिङ्गम् ॥",
      iast: "aṣṭadalopari-veṣṭita-liṅgaṁ\nsarva-samudbhava-kāraṇa-liṅgam ।\naṣṭa-daridra-vināśita-liṅgaṁ\ntat-praṇamāmi sadāśiva-liṅgam ॥",
      en: "The liṅga set within the eight-petalled lotus; the liṅga that is the cause of all that comes to be; the liṅga that destroys the eightfold poverty — to that liṅga of Sadāśiva I bow.",
      tel: "అష్టదళ పద్మము మధ్య ఉంచబడిన లింగము; సర్వ సృష్టికి కారణమైన లింగము; ఎనిమిది విధములైన దారిద్ర్యమును నశింపజేసే లింగము — ఆ సదాశివ లింగమునకు నమస్కరించుచున్నాను." },
    { s: 0, n: "8",
      deva: "सुरगुरुसुरवरपूजितलिङ्गं\nसुरवनपुष्पसदार्चितलिङ्गम् ।\nपरात्परं परमात्मकलिङ्गं\nतत्प्रणमामि सदाशिवलिङ्गम् ॥",
      iast: "suraguru-suravara-pūjita-liṅgaṁ\nsuravana-puṣpa-sadārcita-liṅgam ।\nparātparaṁ paramātmaka-liṅgaṁ\ntat-praṇamāmi sadāśiva-liṅgam ॥",
      en: "The liṅga worshipped by the teacher of the gods and by the best of the gods; the liṅga ever adored with flowers from the celestial grove; the liṅga higher than the highest, whose nature is the supreme Self — to that liṅga of Sadāśiva I bow.",
      tel: "దేవగురువుచేత, దేవశ్రేష్ఠులచేత పూజించబడిన లింగము; దేవవన పుష్పములతో సదా అర్చించబడిన లింగము; పరాత్పరమైనది, పరమాత్మ స్వరూపమైన లింగము — ఆ సదాశివ లింగమునకు నమస్కరించుచున్నాను." },
    { s: 1, n: null,
      deva: "लिङ्गाष्टकमिदं पुण्यं यः पठेच्छिवसन्निधौ ।\nशिवलोकमवाप्नोति शिवेन सह मोदते ॥",
      iast: "liṅgāṣṭakam-idaṁ puṇyaṁ yaḥ paṭhec-chiva-sannidhau ।\nśivalokam-avāpnoti śivena saha modate ॥",
      en: "Whoever recites this holy Liṅgāṣṭaka in the presence of Śiva attains the world of Śiva and rejoices there in his company.",
      tel: "ఈ పుణ్యప్రదమైన లింగాష్టకమును శివసన్నిధిలో ఎవరు పఠించెదరో, వారు శివలోకమును పొంది, శివునితో కూడి ఆనందించెదరు." },
  ],
},

{
  deities: ["shiva"],
  title: "Rudrāṣṭakam",
  blurb: "Tulsīdās to Rudra, from the Uttarakāṇḍa — seven verses of praise, and an eighth that admits the singer knows neither yoga nor japa nor pūjā.",
  sections: [{ tel: "స్తోత్రం", roman: "The Eight Verses" }, { tel: "ఫలశ్రుతి", roman: "The Fruit of Recitation" }],
  verses: [
    { s: 0, n: "1",
      deva: "नमामीशमीशान निर्वाणरूपं\nविभुं व्यापकं ब्रह्मवेदस्वरूपम् ।\nनिजं निर्गुणं निर्विकल्पं निरीहं\nचिदाकाशमाकाशवासं भजेऽहम् ॥",
      iast: "namāmīśam-īśāna nirvāṇa-rūpaṁ\nvibhuṁ vyāpakaṁ brahma-veda-svarūpam ।\nnijaṁ nirguṇaṁ nirvikalpaṁ nirīhaṁ\ncidākāśam-ākāśa-vāsaṁ bhaje'ham ॥",
      en: "I bow to the Lord Īśāna, whose form is liberation itself, the all-pervading one whose nature is Brahman and the Vedas. Self-abiding, without attributes, without division, without desire — I worship him, the sky of consciousness whose dwelling is space.",
      tel: "నిర్వాణ స్వరూపుడైన ఈశానుని నమస్కరించుచున్నాను; సర్వవ్యాపి, బ్రహ్మ-వేద స్వరూపుడు. తనయందు తానే ఉన్నవాడు, నిర్గుణుడు, నిర్వికల్పుడు, కోరికలు లేనివాడు — చిదాకాశ స్వరూపుడై ఆకాశమునే నివాసముగా కలవానిని భజించుచున్నాను." },
    { s: 0, n: "2",
      deva: "निराकारमोंकारमूलं तुरीयं\nगिरा ज्ञान गोतीतमीशं गिरीशम् ।\nकरालं महाकाल कालं कृपालं\nगुणागार संसारपारं नतोऽहम् ॥",
      iast: "nirākāram-oṁkāra-mūlaṁ turīyaṁ\ngirā jñāna gotītam-īśaṁ girīśam ।\nkarālaṁ mahākāla kālaṁ kṛpālaṁ\nguṇāgāra saṁsāra-pāraṁ nato'ham ॥",
      en: "Formless, the root of Oṁ, the fourth state; beyond speech, beyond knowing, beyond the senses — the Lord of the mountain. Terrible, the death of Death himself, yet full of grace; the treasury of all virtue, the far shore of the world — to him I bow.",
      tel: "నిరాకారుడు, ఓంకారమునకు మూలము, తురీయ స్వరూపుడు; వాక్కునకు, జ్ఞానమునకు, ఇంద్రియములకు అతీతుడైన గిరీశుడు. భయంకరుడు, మహాకాలునికే కాలమైనవాడు, అయినను కృపాళుడు; గుణములకు నిలయము, సంసారమునకు అవతలి తీరము — అట్టివానికి నమస్కరించుచున్నాను." },
    { s: 0, n: "3",
      deva: "तुषाराद्रिसंकाशगौरं गभीरं\nमनोभूतकोटिप्रभा श्री शरीरम् ।\nस्फुरन्मौलिकल्लोलिनी चारुगङ्गा\nलसद्भालबालेन्दु कण्ठे भुजङ्गा ॥",
      iast: "tuṣārādri-saṁkāśa-gauraṁ gabhīraṁ\nmanobhūta-koṭi-prabhā śrī śarīram ।\nsphuran-mauli-kallolinī cāru-gaṅgā\nlasad-bhāla-bālendu kaṇṭhe bhujaṅgā ॥",
      en: "White as the snow-mountain and unfathomable; his radiant body brighter than ten million gods of love. On his flashing crown the lovely, rippling Gaṅgā; on his brow the crescent moon; at his throat the serpent.",
      tel: "మంచు కొండవలె తెల్లనివాడు, గంభీరుడు; కోటి మన్మథుల కాంతిని మించిన శ్రీశరీరము కలవాడు. మెరిసే జటాజూటమునందు అలలతో ప్రవహించే సుందర గంగ; నుదుటిపై బాలచంద్రుడు; కంఠమునందు సర్పము." },
    { s: 0, n: "4",
      deva: "चलत्कुण्डलं भ्रू सुनेत्रं विशालं\nप्रसन्नाननं नीलकण्ठं दयालम् ।\nमृगाधीशचर्माम्बरं मुण्डमालं\nप्रियं शंकरं सर्वनाथं भजामि ॥",
      iast: "calat-kuṇḍalaṁ bhrū sunetraṁ viśālaṁ\nprasannānanaṁ nīlakaṇṭhaṁ dayālam ।\nmṛgādhīśa-carmāmbaraṁ muṇḍa-mālaṁ\npriyaṁ śaṅkaraṁ sarva-nāthaṁ bhajāmi ॥",
      en: "His earrings swaying, his brows fine, his eyes wide; his face serene, his throat dark blue, his heart merciful. Clad in the tiger's skin, garlanded with skulls — I worship Śaṅkara the beloved, the Lord of all.",
      tel: "కదలాడే కుండలములు, అందమైన కనుబొమలు, విశాలమైన నేత్రములు; ప్రసన్నమైన ముఖము, నీలకంఠము, దయాశీలము. పులిచర్మము వస్త్రముగా, ముండమాల ధరించినవాడు — ప్రియుడైన శంకరుని, సర్వనాథుని భజించుచున్నాను." },
    { s: 0, n: "5",
      deva: "प्रचण्डं प्रकृष्टं प्रगल्भं परेशं\nअखण्डमजं भानुकोटिप्रकाशम् ।\nत्रयःशूलनिर्मूलनं शूलपाणिं\nभजेऽहं भवानीपतिं भावगम्यम् ॥",
      iast: "pracaṇḍaṁ prakṛṣṭaṁ pragalbhaṁ pareśaṁ\nakhaṇḍam-ajaṁ bhānu-koṭi-prakāśam ।\ntrayaḥ-śūla-nirmūlanaṁ śūla-pāṇiṁ\nbhaje'haṁ bhavānī-patiṁ bhāva-gamyam ॥",
      en: "Fierce, exalted, unshakable, the supreme Lord; undivided, unborn, shining like ten million suns. He who uproots the three sufferings, the trident in his hand — I worship the husband of Bhavānī, reached only by feeling.",
      tel: "ప్రచండుడు, ఉత్కృష్టుడు, ధైర్యశాలి, పరమేశ్వరుడు; అఖండుడు, అజుడు, కోటి సూర్యుల కాంతి కలవాడు. మూడు విధముల తాపములను వేరుతో పెకలించువాడు, శూలపాణి — భావముచేత మాత్రమే చేరదగిన భవానీపతిని భజించుచున్నాను." },
    { s: 0, n: "6",
      deva: "कलातीत कल्याण कल्पान्तकारी\nसदा सज्जनानन्ददाता पुरारी ।\nचिदानन्दसंदोह मोहापहारी\nप्रसीद प्रसीद प्रभो मन्मथारी ॥",
      iast: "kalātīta kalyāṇa kalpānta-kārī\nsadā sajjanānanda-dātā purārī ।\ncidānanda-sandoha mohāpahārī\nprasīda prasīda prabho manmathārī ॥",
      en: "Beyond all measure of time, auspicious, the one who brings the aeon to its close; ever the giver of joy to the good, the destroyer of the Three Cities. Mass of consciousness and bliss, thief of delusion — be gracious, be gracious, O Lord, foe of Manmatha.",
      tel: "కాలమునకు అతీతుడు, కల్యాణస్వరూపుడు, కల్పాంతమును కలిగించువాడు; సజ్జనులకు సదా ఆనందమునిచ్చువాడు, త్రిపురారి. చిదానంద సముదాయము, మోహమును హరించువాడు — ప్రసన్నుడవు కమ్ము, ప్రసన్నుడవు కమ్ము, ఓ ప్రభూ, మన్మథారీ." },
    { s: 0, n: "7",
      deva: "न यावदुमानाथपादारविन्दं\nभजन्तीह लोके परे वा नराणाम् ।\nन तावत्सुखं शान्ति सन्तापनाशं\nप्रसीद प्रभो सर्वभूताधिवासम् ॥",
      iast: "na yāvad-umānātha-pādāravindaṁ\nbhajantīha loke pare vā narāṇām ।\nna tāvat-sukhaṁ śānti santāpa-nāśaṁ\nprasīda prabho sarva-bhūtādhivāsam ॥",
      en: "So long as men do not worship the lotus feet of Umā's lord, there is for them neither happiness nor peace nor an end of grief, in this world or the next. Be gracious, O Lord who dwells in every being.",
      tel: "ఉమానాథుని పాదపద్మములను ఎంతవరకు మనుష్యులు భజించరో, అంతవరకు ఈ లోకమునందైనను పరలోకమునందైనను వారికి సుఖము లేదు, శాంతి లేదు, తాపము తీరదు. ప్రసన్నుడవు కమ్ము ప్రభూ — సర్వభూతములలో నివసించువాడా." },
    { s: 0, n: "8",
      deva: "न जानामि योगं जपं नैव पूजां\nनतोऽहं सदा सर्वदा शम्भु तुभ्यम् ।\nजराजन्मदुःखौघतातप्यमानं\nप्रभो पाहि आपन्नमामीश शम्भो ॥",
      iast: "na jānāmi yogaṁ japaṁ naiva pūjāṁ\nnato'haṁ sadā sarvadā śambhu tubhyam ।\njarā-janma-duḥkhaugha-tātapyamānaṁ\nprabho pāhi āpannam-āmīśa śambho ॥",
      en: "I know no yoga, no japa, no rite of worship; always and in every way, Śambhu, I only bow to you. Scorched by the flood of sorrows that are age and birth — protect me, O Lord Śambhu, protect one who has come to grief.",
      tel: "నాకు యోగము తెలియదు, జపము తెలియదు, పూజయు తెలియదు; శంభూ, సదా సర్వదా నీకు నమస్కరించుచున్నాను మాత్రమే. ముసలితనము, జన్మము అను దుఃఖప్రవాహముచే తపించుచున్న — ఆపన్నుడనైన నన్ను రక్షింపుము, ఈశ శంభో." },
    { s: 1, n: null,
      deva: "रुद्राष्टकमिदं प्रोक्तं विप्रेण हरतोषये ।\nये पठन्ति नरा भक्त्या तेषां शम्भुः प्रसीदति ॥",
      iast: "rudrāṣṭakam-idaṁ proktaṁ vipreṇa hara-toṣaye ।\nye paṭhanti narā bhaktyā teṣāṁ śambhuḥ prasīdati ॥",
      en: "This Rudrāṣṭaka was spoken by the brāhmaṇa for the pleasure of Hara. Śambhu is gracious to those who recite it with devotion.",
      tel: "హరుని సంతోషము కొరకు విప్రునిచే చెప్పబడిన ఈ రుద్రాష్టకమును ఎవరు భక్తితో పఠించెదరో, వారియెడ శంభుడు ప్రసన్నుడగును." },
  ],
},

{
  deities: ["shiva"],
  title: "Nirvāṇa Ṣaṭkam",
  blurb: "Six verses of subtraction — not mind, not breath, not merit, not death — each ending in what is left over: I am Śiva.",
  sections: [{ tel: "స్తోత్రం", roman: "The Six Verses" }],
  verses: [
    { s: 0, n: "1",
      deva: "मनोबुद्ध्यहंकारचित्तानि नाहं\nन च श्रोत्रजिह्वे न च घ्राणनेत्रे ।\nन च व्योम भूमिर्न तेजो न वायुः\nचिदानन्दरूपः शिवोऽहम् शिवोऽहम् ॥",
      iast: "mano-buddhy-ahaṅkāra-cittāni nāhaṁ\nna ca śrotra-jihve na ca ghrāṇa-netre ।\nna ca vyoma bhūmir-na tejo na vāyuḥ\ncidānanda-rūpaḥ śivo'ham śivo'ham ॥",
      en: "I am not mind, intellect, ego or memory; not ear or tongue, not nose or eye; not space, not earth, not fire, not wind. I am consciousness and bliss — I am Śiva, I am Śiva.",
      tel: "నేను మనస్సు కాను, బుద్ధి కాను, అహంకారము కాను, చిత్తము కాను; చెవి కాను, నాలుక కాను, ముక్కు కాను, కన్ను కాను; ఆకాశము కాను, భూమి కాను, తేజస్సు కాను, వాయువు కాను. చిదానంద స్వరూపుడను — నేను శివుడను, నేను శివుడను." },
    { s: 0, n: "2",
      deva: "न च प्राणसंज्ञो न वै पञ्चवायुः\nन वा सप्तधातुर्न वा पञ्चकोशः ।\nन वाक्पाणिपादं न चोपस्थपायु\nचिदानन्दरूपः शिवोऽहम् शिवोऽहम् ॥",
      iast: "na ca prāṇa-saṁjño na vai pañca-vāyuḥ\nna vā sapta-dhātur-na vā pañca-kośaḥ ।\nna vāk-pāṇi-pādaṁ na copastha-pāyu\ncidānanda-rūpaḥ śivo'ham śivo'ham ॥",
      en: "I am not what is called the vital breath, nor the five airs; not the seven bodily elements, nor the five sheaths; not speech, hand, foot, nor the organs of generation and excretion. I am consciousness and bliss — I am Śiva, I am Śiva.",
      tel: "నేను ప్రాణము కాను, పంచవాయువులు కాను; సప్తధాతువులు కాను, పంచకోశములు కాను; వాక్కు, చేయి, పాదము కాను, ఉపస్థ-పాయువులు కాను. చిదానంద స్వరూపుడను — నేను శివుడను, నేను శివుడను." },
    { s: 0, n: "3",
      deva: "न मे द्वेषरागौ न मे लोभमोहौ\nमदो नैव मे नैव मात्सर्यभावः ।\nन धर्मो न चार्थो न कामो न मोक्षः\nचिदानन्दरूपः शिवोऽहम् शिवोऽहम् ॥",
      iast: "na me dveṣa-rāgau na me lobha-mohau\nmado naiva me naiva mātsarya-bhāvaḥ ।\nna dharmo na cārtho na kāmo na mokṣaḥ\ncidānanda-rūpaḥ śivo'ham śivo'ham ॥",
      en: "I have no hatred or attachment, no greed or delusion; no pride, and no envy either. I am neither dharma nor wealth, neither desire nor liberation. I am consciousness and bliss — I am Śiva, I am Śiva.",
      tel: "నాకు ద్వేషము లేదు, రాగము లేదు; లోభము లేదు, మోహము లేదు; మదము లేదు, మాత్సర్యము లేదు. ధర్మము కాను, అర్థము కాను, కామము కాను, మోక్షము కాను. చిదానంద స్వరూపుడను — నేను శివుడను, నేను శివుడను." },
    { s: 0, n: "4",
      deva: "न पुण्यं न पापं न सौख्यं न दुःखं\nन मन्त्रो न तीर्थं न वेदा न यज्ञाः ।\nअहं भोजनं नैव भोज्यं न भोक्ता\nचिदानन्दरूपः शिवोऽहम् शिवोऽहम् ॥",
      iast: "na puṇyaṁ na pāpaṁ na saukhyaṁ na duḥkhaṁ\nna mantro na tīrthaṁ na vedā na yajñāḥ ।\nahaṁ bhojanaṁ naiva bhojyaṁ na bhoktā\ncidānanda-rūpaḥ śivo'ham śivo'ham ॥",
      en: "Not merit, not sin; not pleasure, not pain; not mantra, not holy water, not the Vedas, not sacrifices. I am not the eating, nor the food, nor the eater. I am consciousness and bliss — I am Śiva, I am Śiva.",
      tel: "పుణ్యము కాను, పాపము కాను; సుఖము కాను, దుఃఖము కాను; మంత్రము కాను, తీర్థము కాను, వేదములు కాను, యజ్ఞములు కాను. భోజనము కాను, భోజ్యము కాను, భోక్తను కాను. చిదానంద స్వరూపుడను — నేను శివుడను, నేను శివుడను." },
    { s: 0, n: "5",
      deva: "न मे मृत्युशंका न मे जातिभेदः\nपिता नैव मे नैव माता न जन्म ।\nन बन्धुर्न मित्रं गुरुर्नैव शिष्यः\nचिदानन्दरूपः शिवोऽहम् शिवोऽहम् ॥",
      iast: "na me mṛtyu-śaṅkā na me jāti-bhedaḥ\npitā naiva me naiva mātā na janma ।\nna bandhur-na mitraṁ gurur-naiva śiṣyaḥ\ncidānanda-rūpaḥ śivo'ham śivo'ham ॥",
      en: "I have no fear of death, no distinction of birth; no father, no mother, no being born. No kinsman, no friend, no teacher and no disciple. I am consciousness and bliss — I am Śiva, I am Śiva.",
      tel: "నాకు మృత్యుభయము లేదు, జాతిభేదము లేదు; తండ్రి లేడు, తల్లి లేదు, జన్మము లేదు. బంధువు లేడు, మిత్రుడు లేడు, గురువు లేడు, శిష్యుడు లేడు. చిదానంద స్వరూపుడను — నేను శివుడను, నేను శివుడను." },
    { s: 0, n: "6",
      deva: "अहं निर्विकल्पो निराकाररूपो\nविभुत्वाच्च सर्वत्र सर्वेन्द्रियाणाम् ।\nन चासङ्गतं नैव मुक्तिर्न मेयः\nचिदानन्दरूपः शिवोऽहम् शिवोऽहम् ॥",
      iast: "ahaṁ nirvikalpo nirākāra-rūpo\nvibhutvāc-ca sarvatra sarvendriyāṇām ।\nna cāsaṅgataṁ naiva muktir-na meyaḥ\ncidānanda-rūpaḥ śivo'ham śivo'ham ॥",
      en: "I am without division, without form; being all-pervading, I am everywhere, in all the senses. Neither bound nor released, and never an object to be measured. I am consciousness and bliss — I am Śiva, I am Śiva.",
      tel: "నేను నిర్వికల్పుడను, నిరాకార స్వరూపుడను; సర్వవ్యాపకత్వము వలన సర్వేంద్రియములలో, సర్వత్ర ఉన్నవాడను. బంధమును లేదు, ముక్తియు లేదు, ప్రమాణములకు అందువాడను కాను. చిదానంద స్వరూపుడను — నేను శివుడను, నేను శివుడను." },
  ],
},

{
  deities: ["shiva"],
  title: "Śiva Mānasa Pūjā",
  blurb: "A pūjā done entirely in the mind — throne, bath, food, music, all offered in thought; and the fifth verse asks pardon for every act of the body that was not.",
  sections: [{ tel: "మానస పూజ", roman: "The Worship in the Mind" }, { tel: "క్షమాపణ", roman: "The Asking of Pardon" }],
  verses: [
    { s: 0, n: "1",
      deva: "रत्नैः कल्पितमासनं हिमजलैः स्नानं च दिव्याम्बरं\nनानारत्नविभूषितं मृगमदामोदाङ्कितं चन्दनम् ।\nजातीचम्पकबिल्वपत्ररचितं पुष्पं च धूपं तथा\nदीपं देव दयानिधे पशुपते हृत्कल्पितं गृह्यताम् ॥",
      iast: "ratnaiḥ kalpitam-āsanaṁ hima-jalaiḥ snānaṁ ca divyāmbaraṁ\nnānā-ratna-vibhūṣitaṁ mṛgamadāmodāṅkitaṁ candanam ।\njātī-campaka-bilva-patra-racitaṁ puṣpaṁ ca dhūpaṁ tathā\ndīpaṁ deva dayā-nidhe paśupate hṛt-kalpitaṁ gṛhyatām ॥",
      en: "A throne fashioned of jewels, a bath in snow-cold water, heavenly garments, ornaments of many gems, sandal paste scented with musk; flowers of jasmine, campaka and bilva leaves, incense and the lamp — O God, ocean of mercy, Lord of creatures, accept this worship built in the heart.",
      tel: "రత్నములతో కల్పించిన ఆసనము, హిమజలములతో స్నానము, దివ్య వస్త్రములు, నానా రత్నాభరణములు, కస్తూరి పరిమళముతో కూడిన చందనము; జాజి, సంపెంగ, బిల్వపత్రములతో కూర్చిన పుష్పములు, ధూపము, దీపము — ఓ దయానిధీ, పశుపతీ, హృదయమునందు కల్పించిన ఈ పూజను స్వీకరింపుము." },
    { s: 0, n: "2",
      deva: "सौवर्णे नवरत्नखण्डरचिते पात्रे घृतं पायसं\nभक्ष्यं पञ्चविधं पयोदधियुतं रम्भाफलं पानकम् ।\nशाकानामयुतं जलं रुचिकरं कर्पूरखण्डोज्ज्वलं\nताम्बूलं मनसा मया विरचितं भक्त्या प्रभो स्वीकुरु ॥",
      iast: "sauvarṇe nava-ratna-khaṇḍa-racite pātre ghṛtaṁ pāyasaṁ\nbhakṣyaṁ pañca-vidhaṁ payo-dadhi-yutaṁ rambhā-phalaṁ pānakam ।\nśākānām-ayutaṁ jalaṁ rucikaraṁ karpūra-khaṇḍojjvalaṁ\ntāmbūlaṁ manasā mayā viracitaṁ bhaktyā prabho svīkuru ॥",
      en: "In a golden vessel set with the nine gems: ghee and pāyasa, five kinds of food, milk and curds, plantains and sweet drink, greens beyond counting, water made pleasant, camphor burning bright, and betel — all this I have made with my mind, in devotion. Accept it, Lord.",
      tel: "నవరత్నములు పొదిగిన బంగారు పాత్రలో నెయ్యి, పాయసము, ఐదు విధముల భక్ష్యములు, పాలు, పెరుగు, అరటిపండ్లు, పానకము; లెక్కకు మించిన శాకములు, రుచికరమైన జలము, ప్రకాశించే కర్పూరము, తాంబూలము — ఇవి అన్నియు నేను మనస్సుతో భక్తితో కూర్చినవి. ప్రభూ, స్వీకరింపుము." },
    { s: 0, n: "3",
      deva: "छत्रं चामरयोर्युगं व्यजनकं चादर्शकं निर्मलं\nवीणाभेरिमृदङ्गकाहलकला गीतं च नृत्यं तथा ।\nसाष्टाङ्गं प्रणतिः स्तुतिर्बहुविधा ह्येतत्समस्तं मया\nसङ्कल्पेन समर्पितं तव विभो पूजां गृहाण प्रभो ॥",
      iast: "chatraṁ cāmarayor-yugaṁ vyajanakaṁ cādarśakaṁ nirmalaṁ\nvīṇā-bheri-mṛdaṅga-kāhala-kalā gītaṁ ca nṛtyaṁ tathā ।\nsāṣṭāṅgaṁ praṇatiḥ stutir-bahu-vidhā hy-etat-samastaṁ mayā\nsaṅkalpena samarpitaṁ tava vibho pūjāṁ gṛhāṇa prabho ॥",
      en: "A parasol, a pair of yak-tail whisks, a fan, a spotless mirror; the arts of vīṇā, drum, mṛdaṅga and horn, with song and dance; prostration on all eight limbs and praise of many kinds — all of it I offer you by intention alone. Accept this worship, O Lord.",
      tel: "ఛత్రము, రెండు చామరములు, వ్యజనము, నిర్మలమైన అద్దము; వీణ, భేరి, మృదంగ, కాహళ కళలు, గీతము, నృత్యము; సాష్టాంగ ప్రణామము, బహువిధ స్తుతి — ఇవి అన్నియు సంకల్పముచేతనే నీకు సమర్పించుచున్నాను. ప్రభూ, ఈ పూజను గ్రహింపుము." },
    { s: 0, n: "4",
      deva: "आत्मा त्वं गिरिजा मतिः सहचराः प्राणाः शरीरं गृहं\nपूजा ते विषयोपभोगरचना निद्रा समाधिस्थितिः ।\nसञ्चारः पदयोः प्रदक्षिणविधिः स्तोत्राणि सर्वा गिरो\nयद्यत्कर्म करोमि तत्तदखिलं शम्भो तवाराधनम् ॥",
      iast: "ātmā tvaṁ girijā matiḥ sahacarāḥ prāṇāḥ śarīraṁ gṛhaṁ\npūjā te viṣayopabhoga-racanā nidrā samādhi-sthitiḥ ।\nsañcāraḥ padayoḥ pradakṣiṇa-vidhiḥ stotrāṇi sarvā giro\nyad-yat-karma karomi tat-tad-akhilaṁ śambho tavārādhanam ॥",
      en: "You are my self; Girijā is my understanding; my breaths are your attendants, my body your house. My enjoyment of the senses is worship of you, my sleep is absorption; my walking is circumambulation, all my speech is hymn — whatever act I do, Śambhu, all of it is worship of you.",
      tel: "నీవే నా ఆత్మవు; గిరిజ నా బుద్ధి; ప్రాణములు నీ పరివారము; శరీరము నీ గృహము. విషయోపభోగము నీకు పూజ; నిద్ర సమాధి స్థితి; నా నడక ప్రదక్షిణము; నా మాటలన్నియు స్తోత్రములు — నేను చేయు ప్రతి కర్మయు, శంభో, నీ ఆరాధనమే." },
    { s: 1, n: "5",
      deva: "करचरणकृतं वाक्कायजं कर्मजं वा\nश्रवणनयनजं वा मानसं वापराधम् ।\nविहितमविहितं वा सर्वमेतत्क्षमस्व\nजय जय करुणाब्धे श्रीमहादेव शम्भो ॥",
      iast: "kara-caraṇa-kṛtaṁ vāk-kāya-jaṁ karma-jaṁ vā\nśravaṇa-nayana-jaṁ vā mānasaṁ vāparādham ।\nvihitam-avihitaṁ vā sarvam-etat-kṣamasva\njaya jaya karuṇābdhe śrī-mahādeva śambho ॥",
      en: "Whatever wrong I have done with hand or foot, by speech or body or deed, by ear or eye or in the mind; whether prescribed or forbidden — forgive it all. Victory, victory to you, ocean of compassion, Śrī Mahādeva, Śambhu.",
      tel: "చేతులతో, పాదములతో చేసిన; వాక్కు, శరీరము, కర్మల వలన కలిగిన; చెవులు, కన్నుల వలన లేదా మనస్సు వలన కలిగిన అపరాధమును; విహితమైనను, అవిహితమైనను — ఇదంతయు క్షమింపుము. జయము జయము, కరుణాసముద్రుడా, శ్రీ మహాదేవా, శంభో." },
  ],
},

{
  deities: ["shiva", "guru"],
  title: "Toṭakāṣṭakam",
  blurb: "Toṭakācārya to his teacher, in the metre that gave him his name — every verse ends by asking Śaṅkara himself to be the refuge.",
  sections: [{ tel: "స్తోత్రం", roman: "The Eight Verses" }],
  verses: [
    { s: 0, n: "1",
      deva: "विदिताखिलशास्त्रसुधाजलधे\nमहितोपनिषत्कथितार्थनिधे ।\nहृदये कलये विमलं चरणं\nभव शंकर देशिक मे शरणम् ॥",
      iast: "viditākhila-śāstra-sudhā-jaladhe\nmahitopaniṣat-kathitārtha-nidhe ।\nhṛdaye kalaye vimalaṁ caraṇaṁ\nbhava śaṅkara deśika me śaraṇam ॥",
      en: "O ocean of the nectar of all the śāstras, known to you entire; O treasury of the meaning declared by the honoured Upaniṣads — in my heart I hold your spotless feet. Śaṅkara, my teacher, be my refuge.",
      tel: "సమస్త శాస్త్రములనెడి అమృత సముద్రమును ఎఱిగినవాడా; పూజ్యములైన ఉపనిషత్తులు చెప్పిన అర్థమునకు నిధియైనవాడా — నీ నిర్మల చరణములను హృదయమునందు ధ్యానించుచున్నాను. శంకర దేశికా, నాకు శరణమవుము." },
    { s: 0, n: "2",
      deva: "करुणावरुणालय पालय मां\nभवसागरदुःखविदूनहृदम् ।\nरचयाखिलदर्शनतत्त्वविदं\nभव शंकर देशिक मे शरणम् ॥",
      iast: "karuṇā-varuṇālaya pālaya māṁ\nbhava-sāgara-duḥkha-vidūna-hṛdam ।\nracayākhila-darśana-tattva-vidaṁ\nbhava śaṅkara deśika me śaraṇam ॥",
      en: "O sea of compassion, protect me — my heart worn thin by the sorrow of the ocean of birth. Make me one who knows the truth of every school of thought. Śaṅkara, my teacher, be my refuge.",
      tel: "కరుణా సముద్రుడా, భవసాగర దుఃఖముచే క్షీణించిన హృదయము గల నన్ను రక్షింపుము. సమస్త దర్శనముల తత్త్వమును ఎఱిగినవానిగా నన్ను చేయుము. శంకర దేశికా, నాకు శరణమవుము." },
    { s: 0, n: "3",
      deva: "भवता जनता सुहिता भविता\nनिजबोधविचारणचारुमते ।\nकलयेश्वरजीवविवेकविदं\nभव शंकर देशिक मे शरणम् ॥",
      iast: "bhavatā janatā suhitā bhavitā\nnija-bodha-vicāraṇa-cāru-mate ।\nkalayeśvara-jīva-viveka-vidaṁ\nbhava śaṅkara deśika me śaraṇam ॥",
      en: "By you the people will be made happy, O you whose mind is lovely with enquiry into your own realisation. Grant me the discernment that knows the Lord and the soul. Śaṅkara, my teacher, be my refuge.",
      tel: "ఆత్మబోధ విచారణచేత సుందరమైన బుద్ధి గలవాడా — నీవలన లోకము సుఖమును పొందును. ఈశ్వరుడు, జీవుడు అను వివేకమును నాకు కలిగింపుము. శంకర దేశికా, నాకు శరణమవుము." },
    { s: 0, n: "4",
      deva: "भव एव भवानिति मे नितरां\nसमजायत चेतसि कौतुकिता ।\nमम वारय मोहमहाजलधिं\nभव शंकर देशिक मे शरणम् ॥",
      iast: "bhava eva bhavān-iti me nitarāṁ\nsamajāyata cetasi kautukitā ।\nmama vāraya moha-mahā-jaladhiṁ\nbhava śaṅkara deśika me śaraṇam ॥",
      en: "That you are Śiva himself — this certainty has risen in my mind and filled it with wonder. Hold back for me the great ocean of delusion. Śaṅkara, my teacher, be my refuge.",
      tel: "నీవే సాక్షాత్తు శివుడవను నిశ్చయము నా మనస్సునందు కలిగి, గొప్ప ఆనందాశ్చర్యమును కలిగించినది. నా మోహమను మహాసముద్రమును అడ్డగింపుము. శంకర దేశికా, నాకు శరణమవుము." },
    { s: 0, n: "5",
      deva: "सुकृतेऽधिकृते बहुधा भवतो\nभविता समदर्शनलालसता ।\nअतिदीनमिमं परिपालय मां\nभव शंकर देशिक मे शरणम् ॥",
      iast: "sukṛte'dhikṛte bahudhā bhavato\nbhavitā sama-darśana-lālasatā ।\nati-dīnam-imaṁ paripālaya māṁ\nbhava śaṅkara deśika me śaraṇam ॥",
      en: "Only when much merit has been gathered does the longing arise to see you as you are. Guard me, wretched as I am. Śaṅkara, my teacher, be my refuge.",
      tel: "ఎంతో పుణ్యము సమకూరినప్పుడే నీ సమదర్శనమును పొందవలెననే ఆకాంక్ష కలుగును. అతిదీనుడనైన నన్ను పరిపాలింపుము. శంకర దేశికా, నాకు శరణమవుము." },
    { s: 0, n: "6",
      deva: "जगतीमवितुं कलिताकृतयो\nविचरन्ति महामहसश्छलतः ।\nअहिमांशुरिवात्र विभासि गुरो\nभव शंकर देशिक मे शरणम् ॥",
      iast: "jagatīm-avituṁ kalitākṛtayo\nvicaranti mahā-mahasaś-chalataḥ ।\nahimāṁśur-ivātra vibhāsi guro\nbhava śaṅkara deśika me śaraṇam ॥",
      en: "To protect the world, great lights take on forms and walk among us in disguise. Among them, O Guru, you shine like the sun. Śaṅkara, my teacher, be my refuge.",
      tel: "లోకమును రక్షించుటకు మహాతేజస్సులు రూపములను ధరించి, మారువేషములతో సంచరించుచుండును. వారిలో, ఓ గురువరా, నీవు సూర్యునివలె ప్రకాశించుచున్నావు. శంకర దేశికా, నాకు శరణమవుము." },
    { s: 0, n: "7",
      deva: "गुरुपुङ्गव पुङ्गवकेतन ते\nसमतामयतां नहि कोऽपि सुधीः ।\nशरणागतवत्सल तत्त्वनिधे\nभव शंकर देशिक मे शरणम् ॥",
      iast: "guru-puṅgava puṅgava-ketana te\nsamatām-ayatāṁ nahi ko'pi sudhīḥ ।\nśaraṇāgata-vatsala tattva-nidhe\nbhava śaṅkara deśika me śaraṇam ॥",
      en: "O bull among teachers, you whose banner bears the bull — no wise man anywhere is your equal. Tender to those who take refuge, treasury of truth: Śaṅkara, my teacher, be my refuge.",
      tel: "గురుశ్రేష్ఠుడా, వృషభధ్వజా — విద్వాంసులలో నీతో సమానుడు ఎవడును లేడు. శరణాగతవత్సలా, తత్త్వనిధీ — శంకర దేశికా, నాకు శరణమవుము." },
    { s: 0, n: "8",
      deva: "विदिता न मया विशदैककला\nन च किंचन काञ्चनमस्ति गुरो ।\nद्रुतमेव विधेहि कृपां सहजां\nभव शंकर देशिक मे शरणम् ॥",
      iast: "viditā na mayā viśadaika-kalā\nna ca kiñcana kāñcanam-asti guro ।\ndrutam-eva vidhehi kṛpāṁ sahajāṁ\nbhava śaṅkara deśika me śaraṇam ॥",
      en: "Not one art have I mastered clearly, and I have no gold at all to give, O Guru. Show me quickly that grace which is natural to you. Śaṅkara, my teacher, be my refuge.",
      tel: "ఓ గురువరా — నేను ఒక్క కళనైనను స్పష్టముగా నేర్వలేదు; ఇవ్వదగిన కాంచనమును నా వద్ద లేదు. నీ సహజమైన కృపను శీఘ్రముగా చూపుము. శంకర దేశికా, నాకు శరణమవుము." },
  ],
},];
