/* ============================================================
   STUTI — Devī full texts, part 2
   Kanakadhārā Stotram · Mahālakṣmī Aṣṭakam
   Devanāgarī is the source of truth; other scripts are derived at
   read time. Each verse ships with all four glosses from the start:
   `en` · `tel` (అర్థం) · `hi` (अर्थ). No fallback to English.
   ============================================================ */
export const extra = [{
  deities: ["devi"],
  title: "Kanakadhārā Stotram",
  blurb: "The boy Śaṅkara, given a single gooseberry by a woman with nothing else in the house, sang this — and gold is said to have fallen in her courtyard. Almost every verse is really about one thing: Lakṣmī's sidelong glance, and where it happens to land.",
  sections: [
    { tel: "కటాక్షము", roman: "The Glance", hi: "कटाक्ष" },
    { tel: "నమోఽస్తు", roman: "Salutations", hi: "नमोऽस्तु" },
    { tel: "ప్రార్థన", roman: "The Prayer", hi: "प्रार्थना" },
    { tel: "ఫలశ్రుతి", roman: "The Fruit of Recitation", hi: "फलश्रुति" },
  ],
  verses: [
    { s: 0, n: "1",
      deva: "अङ्गं हरेः पुलकभूषणमाश्रयन्ती\nभृङ्गाङ्गनेव मुकुलाभरणं तमालम् ।\nअङ्गीकृताखिलविभूतिरपाङ्गलीला\nमाङ्गल्यदास्तु मम मङ्गलदेवतायाः ॥",
      iast: "aṅgaṁ hareḥ pulaka-bhūṣaṇam-āśrayantī\nbhṛṅgāṅganeva mukulābharaṇaṁ tamālam ।\naṅgīkṛtākhila-vibhūtir-apāṅga-līlā\nmāṅgalya-dāstu mama maṅgala-devatāyāḥ ॥",
      en: "As a bee settles on the tamāla tree adorned with buds, so her glance rests on Hari's body, which wears its thrill as ornament. May the sidelong play of the goddess of good fortune — the play that has taken all splendour into itself — give me what is auspicious.",
      tel: "మొగ్గలతో అలంకరించబడిన తమాలవృక్షమును ఆడుతుమ్మెద ఆశ్రయించునట్లు, పులకాంకురములే భూషణమైన హరి శరీరమును ఆమె చూపు ఆశ్రయించుచున్నది. సమస్త వైభవమును తనయందు స్వీకరించిన ఆ మంగళదేవత అపాంగలీల నాకు మంగళమును ఇచ్చునుగాక.",
      hi: "जैसे भ्रमरी कलियों से सजे तमाल वृक्ष का आश्रय लेती है, वैसे ही उनकी दृष्टि हरि के उस शरीर पर टिकी है जिसका भूषण ही रोमाञ्च है। समस्त विभूति को अपने में समाये हुए उस मङ्गलदेवता की अपाङ्गलीला मुझे माङ्गल्य दे।" },
    { s: 0, n: "2",
      deva: "मुग्धा मुहुर्विदधती वदने मुरारेः\nप्रेमत्रपाप्रणिहितानि गतागतानि ।\nमाला दृशोर्मधुकरीव महोत्पले या\nसा मे श्रियं दिशतु सागरसम्भवायाः ॥",
      iast: "mugdhā muhur-vidadhatī vadane murāreḥ\nprema-trapā-praṇihitāni gatāgatāni ।\nmālā dṛśor-madhu-karīva mahotpale yā\nsā me śriyaṁ diśatu sāgara-sambhavāyāḥ ॥",
      en: "Innocent, again and again her eyes go to Murāri's face and come back, sent out by love and drawn back by modesty — a garland of glances, like a bee at a great blue lotus. May that garland of the ocean-born one grant me prosperity.",
      tel: "ముగ్ధురాలైన ఆమె చూపులు, ప్రేమచే పంపబడి, సిగ్గుచే మరల్చబడి, మురారి ముఖమువైపు మరలమరల పోయి వచ్చుచున్నవి — పెద్ద నల్లకలువపై ఆడుతుమ్మెదవలె సాగు ఆ చూపుల మాల. సాగరసంభవయైన ఆ తల్లి చూపుల మాల నాకు శ్రీని ఇచ్చునుగాక.",
      hi: "मुग्धा उनकी दृष्टि प्रेम से भेजी और लज्जा से लौटाई जाकर मुरारि के मुख की ओर बार-बार आती-जाती है — महानीलकमल पर मँडराती मधुकरी के समान वह दृष्टियों की माला। सागर से उत्पन्न उस देवी की वह माला मुझे श्री दे।" },
    { s: 0, n: "3",
      deva: "विश्वामरेन्द्रपदविभ्रमदानदक्षम्\nआनन्दहेतुरधिकं मुरविद्विषोऽपि ।\nईषन्निषीदतु मयि क्षणमीक्षणार्धम्\nइन्दीवरोदरसहोदरमिन्दिरायाः ॥",
      iast: "viśvāmarendra-pada-vibhrama-dāna-dakṣam\nānanda-hetur-adhikaṁ mura-vidviṣo'pi ।\nīṣan-niṣīdatu mayi kṣaṇam-īkṣaṇārdham\nindīvarodara-sahodaram-indirāyāḥ ॥",
      en: "It is able to hand out the splendour of Indra's own station in the universe; it is the greater cause of joy even to the enemy of Mura. Let half a glance of Indirā — sister to the heart of a blue lotus — rest on me a little, for one moment.",
      tel: "విశ్వమునందు ఇంద్రపదవి యొక్క వైభవమునే ఇవ్వగల సమర్థమైనది; మురాసురుని శత్రువైన శ్రీహరికే అధికమైన ఆనందహేతువైనది. నల్లకలువ లోపలి భాగమునకు సహోదరమైన ఇందిర యొక్క అర్ధేక్షణము ఒక్క క్షణము నాపై కొంచెము నిలువనీ.",
      hi: "जो विश्व में इन्द्रपद का वैभव भी दे सकने में समर्थ है; जो मुरारि के लिए भी अधिक आनन्द का कारण है — नीलकमल के भीतरी भाग की सहोदरी, इन्दिरा का वह आधा ईक्षण एक क्षण मुझ पर तनिक ठहरे।" },
    { s: 0, n: "4",
      deva: "आमीलिताक्षमधिगम्य मुदा मुकुन्दम्\nआनन्दकन्दमनिमेषमनङ्गतन्त्रम् ।\nआकेकरस्थितकनीनिकपक्ष्मनेत्रं\nभूत्यै भवेन्मम भुजङ्गशयाङ्गनायाः ॥",
      iast: "āmīlitākṣam-adhigamya mudā mukundam\nānanda-kandam-animeṣam-anaṅga-tantram ।\nākekara-sthita-kanīnika-pakṣma-netraṁ\nbhūtyai bhaven-mama bhujaṅga-śayāṅganāyāḥ ॥",
      en: "Reaching Mukunda with delight — the root of bliss, his eyes half closed, unblinking, held by love — her eye stands with its pupil drawn to the corner beneath the lashes. May the eye of the consort of him who sleeps on the serpent bring me abundance.",
      tel: "ఆనందకందుడు, అరమోడ్పు కన్నులవాడు, రెప్పవాల్చనివాడు, అనంగుని వశమైనవాడు — అట్టి ముకుందుని ఆమె ముదముతో చేరగా, ఆమె కనుపాప రెప్పల క్రింద ప్రక్కకు ఒరిగి నిలిచినది. శేషశయనుని ఇల్లాలైన ఆ తల్లి నేత్రము నాకు సంపదను కూర్చునుగాక.",
      hi: "आनन्द के कन्द, अधमुँदी आँखों वाले, अनिमेष, अनङ्ग के वश हुए मुकुन्द तक मुदित होकर पहुँचकर, उनकी पुतली पलकों के नीचे कोर पर ठहर गई। शेषशायी की उस अङ्गना का वह नेत्र मुझे भूति दे।" },
    { s: 0, n: "5",
      deva: "बाह्वन्तरे मुरजितः श्रितकौस्तुभे या\nहारावलीव हरिनीलमयी विभाति ।\nकामप्रदा भगवतोऽपि कटाक्षमाला\nकल्याणमावहतु मे कमलालयायाः ॥",
      iast: "bāhv-antare mura-jitaḥ śrita-kaustubhe yā\nhārāvalīva hari-nīlamayī vibhāti ।\nkāma-pradā bhagavato'pi kaṭākṣa-mālā\nkalyāṇam-āvahatu me kamalālayāyāḥ ॥",
      en: "On the breast of Mura's conqueror, where the Kaustubha rests, it shines like a necklace strung of sapphires; that garland of glances grants his wish even to the Lord himself. May the glance-garland of her whose home is the lotus bring me well-being.",
      tel: "కౌస్తుభమణి నిలిచిన మురారి వక్షస్థలమునందు అది ఇంద్రనీలముల హారమువలె ప్రకాశించుచున్నది; ఆ కటాక్షమాల భగవంతునికే కోరిక తీర్చునది. కమలాలయ యొక్క ఆ కటాక్షమాల నాకు కల్యాణమును కూర్చునుగాక.",
      hi: "कौस्तुभ धारण किये मुरजित् के वक्ष पर वह इन्द्रनीलमणियों के हार-सी शोभती है; वह कटाक्षमाला भगवान् की भी कामना पूर्ण करती है। कमलालया की वह कटाक्षमाला मुझे कल्याण दे।" },
    { s: 0, n: "6",
      deva: "कालाम्बुदालिललितोरसि कैटभारेः\nधाराधरे स्फुरति या तटिदङ्गनेव ।\nमातुस्समस्तजगतां महनीयमूर्तिः\nभद्राणि मे दिशतु भार्गवनन्दनायाः ॥",
      iast: "kālāmbudāli-lalitorasi kaiṭabhāreḥ\ndhārādhare sphurati yā taṭid-aṅganeva ।\nmātus-samasta-jagatāṁ mahanīya-mūrtiḥ\nbhadrāṇi me diśatu bhārgava-nandanāyāḥ ॥",
      en: "On the breast of Kaiṭabha's foe, lovely as a bank of dark rain-clouds, she flashes like lightning across the cloud that carries the rain. May that honoured form — the mother of all the worlds, the daughter of Bhṛgu — grant me every good.",
      tel: "నల్లని మేఘపంక్తివలె లలితమైన కైటభారి వక్షస్థలమునందు, వర్షమును మోయు మేఘమునందు మెరుపువలె ఆమె మెరయుచున్నది. సమస్త జగత్తులకు తల్లియైన, భార్గవనందనయైన ఆ మహనీయమూర్తి నాకు భద్రములను ఇచ్చునుగాక.",
      hi: "कृष्ण मेघपङ्क्ति के समान ललित कैटभारि के वक्ष पर, धाराधर मेघ में विद्युत् की भाँति वह चमकती है। समस्त जगतों की माता, भार्गवनन्दिनी की वह महनीय मूर्ति मुझे भद्र दे।" },
    { s: 0, n: "7",
      deva: "प्राप्तं पदं प्रथमतः खलु यत्प्रभावात्\nमाङ्गल्यभाजि मधुमाथिनि मन्मथेन ।\nमय्यापतेत्तदिह मन्थरमीक्षणार्धं\nमन्दालसं च मकरालयकन्यकायाः ॥",
      iast: "prāptaṁ padaṁ prathamataḥ khalu yat-prabhāvāt\nmāṅgalya-bhāji madhu-māthini manmathena ।\nmayyāpatet-tad-iha mantharam-īkṣaṇārdhaṁ\nmandālasaṁ ca makarālaya-kanyakāyāḥ ॥",
      en: "By the power of that glance Manmatha first won his place with the auspicious slayer of Madhu. Let that same half-glance of the ocean's daughter — slow, unhurried and languid — fall here upon me.",
      tel: "ఆ చూపు ప్రభావముననే మన్మథుడు మంగళస్వరూపుడైన మధుమథనునియందు మొదట తన స్థానమును పొందెను. మకరాలయకన్యక యొక్క ఆ మందమైన, ఆలసమైన అర్ధేక్షణము ఇచట నాపై పడునుగాక.",
      hi: "उस दृष्टि के प्रभाव से ही मन्मथ ने माङ्गल्यरूप मधुमथन के पास पहले स्थान पाया। समुद्रकन्या का वही मन्थर, मन्द और आलस-भरा आधा ईक्षण यहाँ मुझ पर पड़े।" },
    { s: 0, n: "8",
      deva: "दद्याद्दयानुपवनो द्रविणाम्बुधाराम्\nअस्मिन्नकिञ्चनविहङ्गशिशौ विषण्णे ।\nदुष्कर्मघर्ममपनीय चिराय दूरं\nनारायणप्रणयिनीनयनाम्बुवाहः ॥",
      iast: "dadyād-dayānupavano draviṇāmbu-dhārām\nasminn-akiñcana-vihaṅga-śiśau viṣaṇṇe ।\nduṣkarma-gharmam-apanīya cirāya dūraṁ\nnārāyaṇa-praṇayinī-nayanāmbu-vāhaḥ ॥",
      en: "May the rain-cloud that is the eye of Nārāyaṇa's beloved, driven by the wind of compassion, pour a stream of wealth-water on this dejected fledgling who has nothing — and carry the heat of my bad deeds far off, for good.",
      tel: "కరుణ యను గాలిచే నడపబడిన నారాయణ ప్రియురాలి నేత్రమేఘము, ఏమియు లేని ఈ దీనమైన పక్షిపిల్లపై ధనజలధారను కురియునుగాక — దుష్కర్మముల వేడిమిని చిరకాలము దూరముగా తొలగించునుగాక.",
      hi: "करुणा की पवन से चली नारायण-प्रणयिनी के नेत्र का वह मेघ, इस अकिञ्चन, विषण्ण पक्षिशिशु पर धनजल की धारा बरसाये — और दुष्कर्म की तपन को चिरकाल के लिए दूर कर दे।" },
    { s: 0, n: "9",
      deva: "इष्टाविशिष्टमतयोऽपि यया दयार्द्र\nदृष्ट्या त्रिविष्टपपदं सुलभं लभन्ते ।\nदृष्टिः प्रहृष्टकमलोदरदीप्तिरिष्टां\nपुष्टिं कृषीष्ट मम पुष्करविष्टरायाः ॥",
      iast: "iṣṭāviśiṣṭa-matayo'pi yayā dayārdra\ndṛṣṭyā triviṣṭapa-padaṁ sulabhaṁ labhante ।\ndṛṣṭiḥ prahṛṣṭa-kamalodara-dīptir-iṣṭāṁ\npuṣṭiṁ kṛṣīṣṭa mama puṣkara-viṣṭarāyāḥ ॥",
      en: "By that compassion-moist look, even those of no distinguished merit come easily to heaven's station. May the look of her who is seated on the lotus — bright as the heart of a lotus in full delight — draw to me the nourishment I long for.",
      tel: "కరుణతో తడిసిన ఆ చూపుచేతనే విశిష్టమైన బుద్ధి లేనివారును స్వర్గపదవిని సులభముగా పొందుచున్నారు. వికసించిన కమలము లోపలి కాంతివలె ప్రకాశించు పుష్కరవిష్టర యొక్క ఆ దృష్టి నాకు కోరిన పుష్టిని కూర్చునుగాక.",
      hi: "करुणा से आर्द्र उस दृष्टि से विशिष्ट बुद्धि रहित जन भी स्वर्गपद सुलभता से पा लेते हैं। पूर्ण प्रफुल्ल कमल के भीतरी भाग-सी दीप्त, कमलासना की वह दृष्टि मुझे इष्ट पुष्टि दे।" },
    { s: 1, n: "10",
      deva: "गीर्देवतेति गरुडध्वजसुन्दरीति\nशाकम्भरीति शशिशेखरवल्लभेति ।\nसृष्टिस्थितिप्रलयकेलिषु संस्थितायै\nतस्यै नमस्त्रिभुवनैकगुरोस्तरुण्यै ॥",
      iast: "gīr-devateti garuḍa-dhvaja-sundarīti\nśākambharīti śaśi-śekhara-vallabheti ।\nsṛṣṭi-sthiti-pralaya-keliṣu saṁsthitāyai\ntasyai namas-tri-bhuvanaika-guros-taruṇyai ॥",
      en: "As the goddess of speech, as the beauty of him whose banner is Garuḍa, as Śākambharī, as the beloved of the moon-crested one — she stands within the play of making, holding and dissolving. Salutation to her, the young consort of the one teacher of the three worlds.",
      tel: "వాగ్దేవతయని, గరుడధ్వజుని సుందరియని, శాకంభరియని, చంద్రశేఖరుని వల్లభయని — సృష్టి, స్థితి, ప్రళయ లీలలయందు నిలిచియున్న ఆమెకు — ముల్లోకములకు ఏకగురువైనవాని తరుణికి — నమస్కారము.",
      hi: "वाग्देवता कहकर, गरुडध्वज की सुन्दरी कहकर, शाकम्भरी कहकर, चन्द्रशेखर की वल्लभा कहकर — सृष्टि, स्थिति और प्रलय की लीलाओं में स्थित उस देवी को, त्रिभुवन के एक गुरु की तरुणी को नमस्कार।" },
    { s: 1, n: "11",
      deva: "श्रुत्यै नमोऽस्तु शुभकर्मफलप्रसूत्यै\nरत्यै नमोऽस्तु रमणीयगुणार्णवायै ।\nशक्त्यै नमोऽस्तु शतपत्रनिकेतनायै\nपुष्ट्यै नमोऽस्तु पुरुषोत्तमवल्लभायै ॥",
      iast: "śrutyai namo'stu śubha-karma-phala-prasūtyai\nratyai namo'stu ramaṇīya-guṇārṇavāyai ।\nśaktyai namo'stu śata-patra-niketanāyai\npuṣṭyai namo'stu puruṣottama-vallabhāyai ॥",
      en: "Salutation to her as revelation, who brings forth the fruit of good deeds; salutation to her as delight, an ocean of lovely qualities; salutation to her as power, whose house is the hundred-petalled lotus; salutation to her as nourishment, the beloved of the highest person.",
      tel: "శుభకర్మల ఫలమును ప్రసవించు శ్రుతిస్వరూపిణికి నమస్కారము; రమణీయ గుణములకు సముద్రమైన రతిస్వరూపిణికి నమస్కారము; శతపత్ర కమలము నివాసమైన శక్తిస్వరూపిణికి నమస్కారము; పురుషోత్తముని వల్లభయైన పుష్టిస్వరూపిణికి నమస్కారము.",
      hi: "शुभ कर्मों का फल प्रसव करने वाली श्रुतिरूपा को नमस्कार; रमणीय गुणों के सागर, रतिरूपा को नमस्कार; शतपत्र कमल जिसका निकेतन है, उस शक्तिरूपा को नमस्कार; पुरुषोत्तम की वल्लभा, पुष्टिरूपा को नमस्कार।" },
    { s: 1, n: "12",
      deva: "नमोऽस्तु नालीकनिभाननायै\nनमोऽस्तु दुग्धोदधिजन्मभूत्यै ।\nनमोऽस्तु सोमामृतसोदरायै\nनमोऽस्तु नारायणवल्लभायै ॥",
      iast: "namo'stu nālīka-nibhānanāyai\nnamo'stu dugdhodadhi-janma-bhūtyai ।\nnamo'stu somāmṛta-sodarāyai\nnamo'stu nārāyaṇa-vallabhāyai ॥",
      en: "Salutation to her whose face is like a lotus; salutation to her whose birth and abundance came from the ocean of milk; salutation to her, sister of the moon and of the nectar; salutation to her, the beloved of Nārāyaṇa.",
      tel: "కమలమువంటి ముఖము గలదానికి నమస్కారము; పాలసముద్రమునుండి జన్మించిన సంపత్స్వరూపిణికి నమస్కారము; చంద్రునికిని అమృతమునకును సహోదరియైనదానికి నమస్కారము; నారాయణ వల్లభకు నమస్కారము.",
      hi: "कमल-सदृश मुख वाली को नमस्कार; क्षीरसागर से जन्मी उस विभूति को नमस्कार; चन्द्र और अमृत की सहोदरी को नमस्कार; नारायण की वल्लभा को नमस्कार।" },
    { s: 1, n: "13",
      deva: "नमोऽस्तु हेमाम्बुजपीठिकायै\nनमोऽस्तु भूमण्डलनायिकायै ।\nनमोऽस्तु देवादिदयापरायै\nनमोऽस्तु शार्ङ्गायुधवल्लभायै ॥",
      iast: "namo'stu hemāmbuja-pīṭhikāyai\nnamo'stu bhū-maṇḍala-nāyikāyai ।\nnamo'stu devādi-dayā-parāyai\nnamo'stu śārṅgāyudha-vallabhāyai ॥",
      en: "Salutation to her whose seat is the golden lotus; salutation to her, mistress of the circle of the earth; salutation to her who is intent on compassion for the gods and all others; salutation to her, the beloved of him who bears the Śārṅga bow.",
      tel: "బంగరు కమలము ఆసనమైనదానికి నమస్కారము; భూమండలమునకు నాయికయైనదానికి నమస్కారము; దేవతలు మొదలుకొని అందరిపై దయయందు నిమగ్నమైనదానికి నమస్కారము; శార్ఙ్గధనుర్ధారి వల్లభకు నమస్కారము.",
      hi: "स्वर्णकमल जिसकी पीठिका है, उसे नमस्कार; भूमण्डल की नायिका को नमस्कार; देवों आदि पर दया में तत्पर रहने वाली को नमस्कार; शार्ङ्गधनुर्धारी की वल्लभा को नमस्कार।" },
    { s: 1, n: "14",
      deva: "नमोऽस्तु देव्यै भृगुनन्दनायै\nनमोऽस्तु विष्णोरुरसि स्थितायै ।\nनमोऽस्तु लक्ष्म्यै कमलालयायै\nनमोऽस्तु दामोदरवल्लभायै ॥",
      iast: "namo'stu devyai bhṛgu-nandanāyai\nnamo'stu viṣṇor-urasi sthitāyai ।\nnamo'stu lakṣmyai kamalālayāyai\nnamo'stu dāmodara-vallabhāyai ॥",
      en: "Salutation to the goddess, the daughter of Bhṛgu; salutation to her who abides on Viṣṇu's breast; salutation to Lakṣmī, whose home is the lotus; salutation to her, the beloved of Dāmodara.",
      tel: "భృగునందనయైన దేవికి నమస్కారము; విష్ణువక్షస్థలమునందు నిలిచియున్నదానికి నమస్కారము; కమలము నివాసమైన లక్ష్మికి నమస్కారము; దామోదర వల్లభకు నమస్కారము.",
      hi: "भृगुनन्दिनी देवी को नमस्कार; विष्णु के वक्ष पर स्थित को नमस्कार; कमल जिसका आलय है, उस लक्ष्मी को नमस्कार; दामोदर की वल्लभा को नमस्कार।" },
    { s: 1, n: "15",
      deva: "नमोऽस्तु कान्त्यै कमलेक्षणायै\nनमोऽस्तु भूत्यै भुवनप्रसूत्यै ।\nनमोऽस्तु देवादिभिरर्चितायै\nनमोऽस्तु नन्दात्मजवल्लभायै ॥",
      iast: "namo'stu kāntyai kamalekṣaṇāyai\nnamo'stu bhūtyai bhuvana-prasūtyai ।\nnamo'stu devādibhir-arcitāyai\nnamo'stu nandātmaja-vallabhāyai ॥",
      en: "Salutation to her as radiance, the lotus-eyed; salutation to her as abundance, who brings forth the worlds; salutation to her who is worshipped by the gods and all others; salutation to her, the beloved of Nanda's son.",
      tel: "కమలనేత్రయైన కాంతిస్వరూపిణికి నమస్కారము; భువనములను ప్రసవించు భూతిస్వరూపిణికి నమస్కారము; దేవతలు మొదలుకొని అందరిచే పూజింపబడుదానికి నమస్కారము; నందకుమారుని వల్లభకు నమస్కారము.",
      hi: "कमलनयना कान्तिरूपा को नमस्कार; भुवनों को प्रसव करने वाली भूतिरूपा को नमस्कार; देवों आदि से अर्चित को नमस्कार; नन्दात्मज की वल्लभा को नमस्कार।" },
    { s: 2, n: "16",
      deva: "सम्पत्कराणि सकलेन्द्रियनन्दनानि\nसाम्राज्यदानविभवानि सरोरुहाक्षि ।\nत्वद्वन्दनानि दुरिताहरणोद्यतानि\nमामेव मातरनिशं कलयन्तु मान्ये ॥",
      iast: "sampat-karāṇi sakalendriya-nandanāni\nsāmrājya-dāna-vibhavāni saroruhākṣi ।\ntvad-vandanāni duritāharaṇodyatāni\nmām-eva mātar-aniśaṁ kalayantu mānye ॥",
      en: "Lotus-eyed one, honoured Mother: acts of salutation to you bring wealth, gladden every sense, have the power to bestow empires, and stand ready to carry away sin. Let them take hold of me, and of no one else, unceasingly.",
      tel: "ఓ సరోరుహాక్షీ, ఓ మాన్యమైన తల్లీ — నీ వందనములు సంపదను కూర్చునవి, సకల ఇంద్రియములకు ఆనందము కలిగించునవి, సామ్రాజ్యములను ఇచ్చు వైభవము గలవి, పాపమును తొలగించుటకు సిద్ధమైనవి. అవి నన్నే నిరంతరము ఆవరించునుగాక.",
      hi: "हे सरोरुहाक्षि, हे मान्य माता — तेरे वन्दन सम्पत्ति देते हैं, समस्त इन्द्रियों को आनन्दित करते हैं, साम्राज्य देने का विभव रखते हैं और पाप हरने को उद्यत हैं। वे मुझे ही निरन्तर आवृत करें।" },
    { s: 2, n: "17",
      deva: "यत्कटाक्षसमुपासनाविधिः\nसेवकस्य सकलार्थसम्पदः ।\nसन्तनोति वचनाङ्गमानसैः\nत्वां मुरारिहृदयेश्वरीं भजे ॥",
      iast: "yat-kaṭākṣa-samupāsanā-vidhiḥ\nsevakasya sakalārtha-sampadaḥ ।\nsantanoti vacanāṅga-mānasaiḥ\ntvāṁ murāri-hṛdayeśvarīṁ bhaje ॥",
      en: "The rite of worshipping that glance spreads out for the servant every object of desire and all wealth. With word, body and mind I worship you, mistress of Murāri's heart.",
      tel: "ఏ కటాక్షమును ఉపాసించు విధి సేవకునికి సకల అర్థములను, సంపదలను విస్తరించునో — ఆ నిన్ను, మురారి హృదయేశ్వరిని, వాక్కుతో, శరీరముతో, మనసుతో సేవించుచున్నాను.",
      hi: "जिस कटाक्ष की उपासना-विधि सेवक के लिए समस्त अर्थ और सम्पत्ति फैला देती है — उस तुझे, मुरारि की हृदयेश्वरी को, वचन, शरीर और मन से भजता हूँ।" },
    { s: 2, n: "18",
      deva: "सरसिजनिलये सरोजहस्ते\nधवलतमांशुकगन्धमाल्यशोभे ।\nभगवति हरिवल्लभे मनोज्ञे\nत्रिभुवनभूतिकरि प्रसीद मह्यम् ॥",
      iast: "sarasija-nilaye saroja-haste\ndhavala-tamāṁśuka-gandha-mālya-śobhe ।\nbhagavati hari-vallabhe manojñe\ntri-bhuvana-bhūti-kari prasīda mahyam ॥",
      en: "Dweller in the lotus, lotus in hand, resplendent in whitest silk with fragrance and garlands; Bhagavatī, beloved of Hari, delight of the mind, maker of the wealth of the three worlds — be gracious to me.",
      tel: "కమలమునందు నివసించుదానా, చేతిలో కమలము ధరించుదానా, అతి తెల్లని వస్త్రముతో, గంధముతో, మాలలతో శోభించుదానా; ఓ భగవతీ, హరివల్లభా, మనోజ్ఞా, ముల్లోకముల సంపదను కూర్చుదానా — నాయందు ప్రసన్నురాలవు కమ్ము.",
      hi: "कमल में निवास करने वाली, हाथ में कमल धारण करने वाली, अतिश्वेत वस्त्र, गन्ध और माल्य से शोभित; हे भगवती, हरिवल्लभे, मनोज्ञे, त्रिभुवन की भूति करने वाली — मुझ पर प्रसन्न हो।" },
    { s: 2, n: "19",
      deva: "दिग्घस्तिभिः कनककुम्भमुखावसृष्ट\nस्वर्वाहिनीविमलचारुजलप्लुताङ्गीम् ।\nप्रातर्नमामि जगतां जननीमशेष\nलोकाधिनाथगृहिणीममृताब्धिपुत्रीम् ॥",
      iast: "dig-ghastibhiḥ kanaka-kumbha-mukhāvasṛṣṭa\nsvar-vāhinī-vimala-cāru-jala-plutāṅgīm ।\nprātar-namāmi jagatāṁ jananīm-aśeṣa\nlokādhinātha-gṛhiṇīm-amṛtābdhi-putrīm ॥",
      en: "Her limbs bathed by the clear, lovely water of the heavenly river, poured from golden vessels held in the trunks of the elephants of the quarters — at daybreak I bow to the mother of the worlds, the wife of the lord of all realms, the daughter of the ocean of nectar.",
      tel: "దిగ్గజములు తమ తొండములతో ఎత్తిన బంగరు కుంభముల ముఖమునుండి కురిసిన ఆకాశగంగ నిర్మలమైన సుందర జలముచే తడిసిన శరీరము గలదానిని — జగత్తులకు తల్లిని, సమస్త లోకాధినాథుని ఇల్లాలిని, అమృతసముద్రపుత్రికను — ప్రాతఃకాలమున నమస్కరించుచున్నాను.",
      hi: "दिग्गजों के द्वारा उठाये स्वर्णकुम्भों के मुख से गिरे आकाशगङ्गा के निर्मल सुन्दर जल से जिसके अङ्ग सिञ्चित हैं — जगतों की जननी, समस्त लोकाधिनाथ की गृहिणी, अमृतसागर की पुत्री को — प्रातःकाल मैं नमन करता हूँ।" },
    { s: 2, n: "20",
      deva: "कमले कमलाक्षवल्लभे त्वं\nकरुणापूरतरङ्गितैरपाङ्गैः ।\nअवलोकय मामकिञ्चनानां\nप्रथमं पात्रमकृत्रिमं दयायाः ॥",
      iast: "kamale kamalākṣa-vallabhe tvaṁ\nkaruṇā-pūra-taraṅgitair-apāṅgaiḥ ।\navalokaya mām-akiñcanānāṁ\nprathamaṁ pātram-akṛtrimaṁ dayāyāḥ ॥",
      en: "Kamalā, beloved of the lotus-eyed one — look upon me with sidelong glances rippling with a flood of compassion. Of all who have nothing, I am the first, and no false claimant to your pity.",
      tel: "ఓ కమలా, కమలాక్షుని వల్లభా — కరుణాప్రవాహముతో తరంగించు నీ అపాంగములతో నన్ను చూడుము. ఏమియు లేనివారిలో నేనే మొదటివాడను, నీ దయకు కృత్రిమము కాని పాత్రుడను.",
      hi: "हे कमले, कमलाक्ष की वल्लभे — करुणा के पूर से तरङ्गित अपाङ्गों से मुझे देख। अकिञ्चनों में मैं प्रथम हूँ, और तेरी दया का अकृत्रिम पात्र हूँ।" },
    { s: 3, n: "21",
      deva: "स्तुवन्ति ये स्तुतिभिरमूभिरन्वहं\nत्रयीमयीं त्रिभुवनमातरं रमाम् ।\nगुणाधिका गुरुतरभाग्यभागिनो\nभवन्ति ते बुधभाविताशयाः ॥",
      iast: "stuvanti ye stutibhir-amūbhir-anvahaṁ\ntrayī-mayīṁ tri-bhuvana-mātaraṁ ramām ।\nguṇādhikā gurutara-bhāgya-bhāgino\nbhavanti te budha-bhāvitāśayāḥ ॥",
      en: "Those who praise Ramā day after day with these verses — she who is the three Vedas, the mother of the three worlds — grow rich in virtue, come to share a weightier fortune, and their minds are held in regard by the wise.",
      tel: "మూడు వేదముల స్వరూపిణి, ముల్లోకములకు తల్లియైన రమను ఈ స్తుతులతో ప్రతిదినము స్తుతించువారు — గుణములలో అధికులై, గురుతరమైన భాగ్యమునకు భాగస్వాములై, పండితులచే గౌరవింపబడు మనసు గలవారగుదురు.",
      hi: "जो त्रयीस्वरूपा, त्रिभुवन की माता रमा की इन स्तुतियों से प्रतिदिन स्तुति करते हैं — वे गुणों में अधिक होते हैं, गुरुतर भाग्य के भागी बनते हैं, और उनका आशय बुधजनों से आदृत होता है।" },
  ],
},

{
  deities: ["devi"],
  title: "Mahālakṣmī Aṣṭakam",
  blurb: "Indra's hymn from the Padma Purāṇa — eight short verses, each ending in the same four syllables, so it learns itself by the third reading.",
  sections: [
    { tel: "అష్టకం", roman: "The Eight Verses", hi: "अष्टकम्" },
    { tel: "ఫలశ్రుతి", roman: "The Fruit of Recitation", hi: "फलश्रुति" },
  ],
  verses: [
    { s: 0, n: "1",
      deva: "नमस्तेऽस्तु महामाये श्रीपीठे सुरपूजिते ।\nशङ्खचक्रगदाहस्ते महालक्ष्मि नमोऽस्तु ते ॥",
      iast: "namaste'stu mahāmāye śrī-pīṭhe sura-pūjite ।\nśaṅkha-cakra-gadā-haste mahālakṣmi namo'stu te ॥",
      en: "Salutation to you, great Māyā, seated on the seat of splendour, worshipped by the gods; conch, discus and mace in your hands — Mahālakṣmī, salutation to you.",
      tel: "ఓ మహామాయా, శ్రీపీఠమునందు కూర్చున్నదానా, దేవతలచే పూజింపబడుదానా — నీకు నమస్కారము; శంఖము, చక్రము, గద చేతులలో ధరించినదానా — మహాలక్ష్మీ, నీకు నమస్కారము.",
      hi: "हे महामाये, श्रीपीठ पर विराजमान, सुरों से पूजिते — तुझे नमस्कार; शङ्ख, चक्र और गदा हाथों में धारण करने वाली — महालक्ष्मी, तुझे नमस्कार।" },
    { s: 0, n: "2",
      deva: "नमस्ते गरुडारूढे कोलासुरभयङ्करि ।\nसर्वपापहरे देवि महालक्ष्मि नमोऽस्तु ते ॥",
      iast: "namaste garuḍārūḍhe kolāsura-bhayaṅkari ।\nsarva-pāpa-hare devi mahālakṣmi namo'stu te ॥",
      en: "Salutation to you, mounted on Garuḍa, terror of the demon Kola; goddess who takes away every sin — Mahālakṣmī, salutation to you.",
      tel: "గరుడారూఢయైనదానా, కోలాసురునికి భయము కలిగించుదానా — నీకు నమస్కారము; సర్వపాపములను హరించు దేవీ — మహాలక్ష్మీ, నీకు నమస్కారము.",
      hi: "गरुड पर आरूढ़, कोलासुर के लिए भयङ्करी — तुझे नमस्कार; समस्त पाप हरने वाली देवी — महालक्ष्मी, तुझे नमस्कार।" },
    { s: 0, n: "3",
      deva: "सर्वज्ञे सर्ववरदे सर्वदुष्टभयङ्करि ।\nसर्वदुःखहरे देवि महालक्ष्मि नमोऽस्तु ते ॥",
      iast: "sarvajñe sarva-varade sarva-duṣṭa-bhayaṅkari ।\nsarva-duḥkha-hare devi mahālakṣmi namo'stu te ॥",
      en: "Knower of all, giver of every boon, terror of all the wicked; goddess who takes away every sorrow — Mahālakṣmī, salutation to you.",
      tel: "సర్వమును ఎరిగినదానా, సర్వవరములనిచ్చుదానా, దుష్టులందరికి భయము కలిగించుదానా; సర్వదుఃఖములను హరించు దేవీ — మహాలక్ష్మీ, నీకు నమస్కారము.",
      hi: "सर्वज्ञे, सब वर देने वाली, समस्त दुष्टों के लिए भयङ्करी; सब दुःख हरने वाली देवी — महालक्ष्मी, तुझे नमस्कार।" },
    { s: 0, n: "4",
      deva: "सिद्धिबुद्धिप्रदे देवि भुक्तिमुक्तिप्रदायिनि ।\nमन्त्रमूर्ते सदा देवि महालक्ष्मि नमोऽस्तु ते ॥",
      iast: "siddhi-buddhi-prade devi bhukti-mukti-pradāyini ।\nmantra-mūrte sadā devi mahālakṣmi namo'stu te ॥",
      en: "Goddess who gives attainment and understanding, who grants both enjoyment and release; goddess whose form is the mantra itself, always — Mahālakṣmī, salutation to you.",
      tel: "సిద్ధిని, బుద్ధిని ఇచ్చు దేవీ, భుక్తిని ముక్తిని ప్రసాదించుదానా; సదా మంత్రస్వరూపిణియైన దేవీ — మహాలక్ష్మీ, నీకు నమస్కారము.",
      hi: "सिद्धि और बुद्धि देने वाली देवी, भुक्ति और मुक्ति प्रदान करने वाली; सदा मन्त्रमूर्ति देवी — महालक्ष्मी, तुझे नमस्कार।" },
    { s: 0, n: "5",
      deva: "आद्यन्तरहिते देवि आद्यशक्ति महेश्वरि ।\nयोगजे योगसम्भूते महालक्ष्मि नमोऽस्तु ते ॥",
      iast: "ādy-antara-hite devi ādya-śakti maheśvari ।\nyogaje yoga-sambhūte mahālakṣmi namo'stu te ॥",
      en: "Goddess without beginning or end, primordial power, great sovereign; born of yoga, arisen from yoga — Mahālakṣmī, salutation to you.",
      tel: "ఆదియు అంతమును లేని దేవీ, ఆద్యశక్తీ, మహేశ్వరీ; యోగమునుండి పుట్టినదానా, యోగమునుండి ఉద్భవించినదానా — మహాలక్ష్మీ, నీకు నమస్కారము.",
      hi: "आदि और अन्त से रहित देवी, आद्याशक्ति, महेश्वरी; योग से जन्मी, योग से उद्भूत — महालक्ष्मी, तुझे नमस्कार।" },
    { s: 0, n: "6",
      deva: "स्थूलसूक्ष्ममहारौद्रे महाशक्ति महोदरे ।\nमहापापहरे देवि महालक्ष्मि नमोऽस्तु ते ॥",
      iast: "sthūla-sūkṣma-mahā-raudre mahā-śakti mahodare ।\nmahā-pāpa-hare devi mahālakṣmi namo'stu te ॥",
      en: "You who are the gross and the subtle and the greatly terrible; great power, great in your depths; goddess who takes away great sin — Mahālakṣmī, salutation to you.",
      tel: "స్థూలరూపమును, సూక్ష్మరూపమును, మహారౌద్రరూపమును అయినదానా; మహాశక్తీ, మహోదరీ; మహాపాపములను హరించు దేవీ — మహాలక్ష్మీ, నీకు నమస్కారము.",
      hi: "स्थूल, सूक्ष्म और महारौद्र रूप वाली; महाशक्ति, महोदरी; महापाप हरने वाली देवी — महालक्ष्मी, तुझे नमस्कार।" },
    { s: 0, n: "7",
      deva: "पद्मासनस्थिते देवि परब्रह्मस्वरूपिणि ।\nपरमेशि जगन्मातर्महालक्ष्मि नमोऽस्तु ते ॥",
      iast: "padmāsana-sthite devi para-brahma-svarūpiṇi ।\nparameśi jagan-mātar-mahālakṣmi namo'stu te ॥",
      en: "Goddess seated on the lotus, whose own form is the supreme brahman; highest sovereign, mother of the world — Mahālakṣmī, salutation to you.",
      tel: "పద్మాసనమునందు నిలిచియున్న దేవీ, పరబ్రహ్మస్వరూపిణీ; పరమేశ్వరీ, జగన్మాతా — మహాలక్ష్మీ, నీకు నమస్కారము.",
      hi: "पद्मासन पर स्थित देवी, परब्रह्मस्वरूपिणी; परमेशी, जगन्माता — महालक्ष्मी, तुझे नमस्कार।" },
    { s: 0, n: "8",
      deva: "श्वेताम्बरधरे देवि नानालङ्कारभूषिते ।\nजगत्स्थिते जगन्मातर्महालक्ष्मि नमोऽस्तु ते ॥",
      iast: "śvetāmbara-dhare devi nānālaṅkāra-bhūṣite ।\njagat-sthite jagan-mātar-mahālakṣmi namo'stu te ॥",
      en: "Goddess clothed in white, adorned with many ornaments; you who abide within the world and are its mother — Mahālakṣmī, salutation to you.",
      tel: "తెల్లని వస్త్రములు ధరించిన దేవీ, నానావిధ అలంకారములతో అలంకరించబడినదానా; జగత్తునందు నిలిచియున్నదానా, జగన్మాతా — మహాలక్ష్మీ, నీకు నమస్కారము.",
      hi: "श्वेत वस्त्र धारण करने वाली देवी, नाना अलङ्कारों से भूषिते; जगत् में स्थित, जगन्माता — महालक्ष्मी, तुझे नमस्कार।" },
    { s: 1, n: "9",
      deva: "महालक्ष्म्यष्टकं स्तोत्रं यः पठेद्भक्तिमान्नरः ।\nसर्वसिद्धिमवाप्नोति राज्यं प्राप्नोति सर्वदा ॥",
      iast: "mahālakṣmy-aṣṭakaṁ stotraṁ yaḥ paṭhed-bhaktimān naraḥ ।\nsarva-siddhim-avāpnoti rājyaṁ prāpnoti sarvadā ॥",
      en: "Whoever recites this hymn of eight verses to Mahālakṣmī with devotion attains every accomplishment, and comes always into dominion.",
      tel: "ఈ మహాలక్ష్మ్యష్టక స్తోత్రమును భక్తితో పఠించు మనుజుడు సర్వసిద్ధిని పొందును, ఎల్లప్పుడును రాజ్యమును పొందును.",
      hi: "जो मनुष्य भक्तिपूर्वक इस महालक्ष्म्यष्टक स्तोत्र का पाठ करता है, वह सर्वसिद्धि पाता है और सदा राज्य प्राप्त करता है।" },
    { s: 1, n: "10",
      deva: "एककाले पठेन्नित्यं महापापविनाशनम् ।\nद्विकालं यः पठेन्नित्यं धनधान्यसमन्वितः ॥",
      iast: "eka-kāle paṭhen-nityaṁ mahā-pāpa-vināśanam ।\ndvi-kālaṁ yaḥ paṭhen-nityaṁ dhana-dhānya-samanvitaḥ ॥",
      en: "Recited once a day, it destroys great sin; whoever recites it twice a day, every day, comes to have wealth and grain.",
      tel: "దినమునకు ఒకసారి పఠించినచో మహాపాపములు నశించును; ప్రతిదినము రెండుసారులు పఠించువాడు ధనధాన్యములతో కూడినవాడగును.",
      hi: "प्रतिदिन एक बार पाठ करने से महापाप नष्ट होते हैं; जो नित्य दो बार पाठ करता है, वह धन-धान्य से सम्पन्न होता है।" },
    { s: 1, n: "11",
      deva: "त्रिकालं यः पठेन्नित्यं महाशत्रुविनाशनम् ।\nमहालक्ष्मीर्भवेन्नित्यं प्रसन्ना वरदा शुभा ॥",
      iast: "tri-kālaṁ yaḥ paṭhen-nityaṁ mahā-śatru-vināśanam ।\nmahālakṣmīr-bhaven-nityaṁ prasannā varadā śubhā ॥",
      en: "For whoever recites it three times a day, great enemies are destroyed; and Mahālakṣmī, auspicious and giving boons, is always pleased with him.",
      tel: "ప్రతిదినము మూడుసారులు పఠించువానికి మహాశత్రువులు నశింతురు; శుభస్వరూపిణి, వరదాయిని అయిన మహాలక్ష్మి సదా ప్రసన్నురాలగును.",
      hi: "जो नित्य तीन बार पाठ करता है, उसके महाशत्रु नष्ट होते हैं; और वरदायिनी, शुभा महालक्ष्मी सदा उस पर प्रसन्न रहती हैं।" },
  ],
},];
