/* ============================================================
   STUTI — Hanumān full texts, part 1
   Saṅkaṭamocana Hanumān Aṣṭakam · Śrī Hanumat Pañcaratnam
   ------------------------------------------------------------
   The A\u1e63\u1e6dakam is Tulsīdās's Awadhī, keyed to the standard printed
   reading — not normalised toward Sanskrit spelling, which is the
   mistake the Cālīsā carried for a while: बाल, भयो, तिहारो, अँधियारो
   stay as they are written and as they are sung. Its `hi` is a
   modern Hindi rendering, since the mūla is already Devanāgarī but
   not Hindi. The Pañcaratnam is Śaṅkara's Sanskrit.
   Each verse ships with all four glosses: `en` · `tel` · `hi`.
   ============================================================ */
export const extra = [{
  deities: ["hanuman"],
  title: "Saṅkaṭamocana Hanumān Aṣṭakam",
  blurb: "Eight troubles from the Rāmāyaṇa, each one ended by Hanumān, and after each the same question put to the world: who does not know your name — the undoer of trouble?",
  sections: [
    { tel: "అష్టకం", roman: "The Eight Verses", hi: "अष्टक" },
    { tel: "దోహా", roman: "The Closing Dohā", hi: "दोहा" },
  ],
  verses: [
    { s: 0, n: "1",
      deva: "बाल समय रवि भक्षि लियो तब, तीनहुँ लोक भयो अँधियारो ।\nताहि सों त्रास भयो जग को, यह संकट काहु सों जात न टारो ।\nको नहिं जानत है जग में कपि, संकटमोचन नाम तिहारो ॥",
      iast: "bāla samaya ravi bhakṣi liyo taba, tīnahu loka bhayo aṁdhiyāro ।\ntāhi soṁ trāsa bhayo jaga ko, yaha saṅkaṭa kāhu soṁ jāta na ṭāro ।\nko nahiṁ jānata hai jaga meṁ kapi, saṅkaṭa-mocana nāma tihāro ॥",
      en: "As a child you swallowed the sun, and all three worlds went dark. The world was terrified, and that trouble could be removed by no one. Who in this world does not know, monkey-lord, that your name is the Undoer of Trouble?",
      tel: "బాల్యమునందు నీవు సూర్యుని మింగివేసితివి, మూడు లోకములు అంధకారమయ్యెను. జగత్తు భయపడినది, ఆ సంకటమును ఎవరును తొలగింపలేకపోయిరి. ఓ కపివరా, జగత్తులో ఎవరు ఎరుగరు — నీ పేరు సంకటమోచనమని?",
      hi: "बाल्यकाल में तुमने सूर्य को निगल लिया, और तीनों लोक अन्धकार में डूब गये। संसार भयभीत हुआ, और वह सङ्कट कोई भी दूर न कर सका। हे कपि, जगत् में कौन नहीं जानता कि तुम्हारा नाम सङ्कटमोचन है?" },
    { s: 0, n: "2",
      deva: "बालि की त्रास कपीस बसैं गिरि, जात महाप्रभु पंथ निहारो ।\nचौंकि महामुनि साप दियो तब, चाहिय कौन बिचार बिचारो ।\nको नहिं जानत है जग में कपि, संकटमोचन नाम तिहारो ॥",
      iast: "bāli kī trāsa kapīsa basaiṁ giri, jāta mahāprabhu paṁtha nihāro ।\ncauṁki mahāmuni sāpa diyo taba, cāhiya kauna bicāra bicāro ।\nko nahiṁ jānata hai jaga meṁ kapi, saṅkaṭa-mocana nāma tihāro ॥",
      en: "In fear of Bāli, the monkey king lived on the mountain and watched the road for the great Lord to come. A great sage, startled, had laid a curse — what counsel was there left to consider? Who in this world does not know, monkey-lord, that your name is the Undoer of Trouble?",
      tel: "బాలి భయముచే కపిరాజు పర్వతమున నివసించి, మహాప్రభువు వచ్చు దారిని కనిపెట్టుకొనియుండెను. ఉలికిపడిన మహాముని శాపమిచ్చెను — అప్పుడు ఏ ఆలోచన చేయవలెను? ఓ కపివరా, జగత్తులో ఎవరు ఎరుగరు — నీ పేరు సంకటమోచనమని?",
      hi: "बालि के भय से कपिराज पर्वत पर रहते और महाप्रभु के आने का मार्ग देखते रहे। चौंककर महामुनि ने शाप दे दिया — तब कौन सा विचार किया जाये? हे कपि, जगत् में कौन नहीं जानता कि तुम्हारा नाम सङ्कटमोचन है?" },
    { s: 0, n: "3",
      deva: "अंगद के सँग लेन गये सिय, खोज कपीस यह बैन उचारो ।\nजीवत ना बचिहौ हम सो जु, बिना सुधि लाइ इहाँ पगु धारो ।\nको नहिं जानत है जग में कपि, संकटमोचन नाम तिहारो ॥",
      iast: "aṁgada ke saṁga lena gaye siya, khoja kapīsa yaha baina ucāro ।\njīvata nā bacihau hama so ju, binā sudhi lāi ihāṁ pagu dhāro ।\nko nahiṁ jānata hai jaga meṁ kapi, saṅkaṭa-mocana nāma tihāro ॥",
      en: "You went with Aṅgada to search out Sītā, and the monkey king had spoken these words: none of you will come back alive if you set foot here again without news of her. Who in this world does not know, monkey-lord, that your name is the Undoer of Trouble?",
      tel: "అంగదునితో కలిసి సీతను వెదకుటకు వెళ్ళితివి; కపిరాజు ఈ మాట పలికియుండెను — ఆమె జాడ తెలియకుండ ఇచటికి అడుగుపెట్టినచో మీలో ఎవరును ప్రాణములతో మిగలరు. ఓ కపివరా, జగత్తులో ఎవరు ఎరుగరు — నీ పేరు సంకటమోచనమని?",
      hi: "अङ्गद के साथ तुम सीता की खोज में गये, और कपिराज ने यह वचन कहा था — उनकी सुधि लाये बिना यहाँ पग रखोगे तो जीवित न बचोगे। हे कपि, जगत् में कौन नहीं जानता कि तुम्हारा नाम सङ्कटमोचन है?" },
    { s: 0, n: "4",
      deva: "रावन त्रास दई सिय को सब, राक्षसि सों कहि सोक निवारो ।\nताहि समय हनुमान महाप्रभु, जाय महा रजनीचर मारो ।\nको नहिं जानत है जग में कपि, संकटमोचन नाम तिहारो ॥",
      iast: "rāvana trāsa daī siya ko saba, rākṣasi soṁ kahi soka nivāro ।\ntāhi samaya hanumāna mahāprabhu, jāya mahā rajanīcara māro ।\nko nahiṁ jānata hai jaga meṁ kapi, saṅkaṭa-mocana nāma tihāro ॥",
      en: "Rāvaṇa terrified Sītā in every way; you spoke to the demon women and took her grief away. At that hour, Hanumān, great lord, you went and struck down the mighty night-walkers. Who in this world does not know, monkey-lord, that your name is the Undoer of Trouble?",
      tel: "రావణుడు సీతను అన్నివిధములుగా భయపెట్టెను; నీవు రాక్షస స్త్రీలతో పలికి ఆమె శోకమును తొలగించితివి. ఆ సమయమున, ఓ హనుమాన్ మహాప్రభూ, వెళ్ళి మహా రాక్షసులను సంహరించితివి. ఓ కపివరా, జగత్తులో ఎవరు ఎరుగరు — నీ పేరు సంకటమోచనమని?",
      hi: "रावण ने सीता को सब प्रकार से भय दिया; तुमने राक्षसियों से कहकर उनका शोक दूर किया। उस समय, हे हनुमान् महाप्रभु, जाकर महा निशाचरों को मारा। हे कपि, जगत् में कौन नहीं जानता कि तुम्हारा नाम सङ्कटमोचन है?" },
    { s: 0, n: "5",
      deva: "बान लग्यो उर लछिमन के तब, प्राण तजे सुत रावन मारो ।\nलै गृह बैद्य सुषेन समेत, तबै गिरि द्रोण सु बीर उपारो ।\nको नहिं जानत है जग में कपि, संकटमोचन नाम तिहारो ॥",
      iast: "bāna lagyo ura lachimana ke taba, prāṇa taje suta rāvana māro ।\nlai gṛha baidya suṣena sameta, tabai giri droṇa su bīra upāro ।\nko nahiṁ jānata hai jaga meṁ kapi, saṅkaṭa-mocana nāma tihāro ॥",
      en: "When the arrow struck Lakṣmaṇa's chest and Rāvaṇa's son took his life away, you brought the physician Suṣeṇa, house and all, and then, hero, tore up the Droṇa mountain itself. Who in this world does not know, monkey-lord, that your name is the Undoer of Trouble?",
      tel: "లక్ష్మణుని వక్షమునకు బాణము తగిలి, రావణుని కుమారుడు అతని ప్రాణము తీసినపుడు — నీవు వైద్యుడైన సుషేణుని ఇంటితో సహా తీసుకొనివచ్చితివి, పిమ్మట ఓ వీరా, ద్రోణపర్వతమునే పెకలించితివి. ఓ కపివరా, జగత్తులో ఎవరు ఎరుగరు — నీ పేరు సంకటమోచనమని?",
      hi: "जब लक्ष्मण के हृदय में बाण लगा और रावण के पुत्र ने उनके प्राण हर लिये — तुम वैद्य सुषेण को घर सहित ले आये, और तब, हे वीर, द्रोण पर्वत को ही उखाड़ लिया। हे कपि, जगत् में कौन नहीं जानता कि तुम्हारा नाम सङ्कटमोचन है?" },
    { s: 0, n: "6",
      deva: "रावन जुद्ध अजान कियो तब, नाग कि फाँस सबै सिर डारो ।\nश्रीरघुनाथ समेत सबै दल, मोह भयो यह संकट भारो ।\nको नहिं जानत है जग में कपि, संकटमोचन नाम तिहारो ॥",
      iast: "rāvana juddha ajāna kiyo taba, nāga ki phāṁsa sabai sira ḍāro ।\nśrī-raghunātha sameta sabai dala, moha bhayo yaha saṅkaṭa bhāro ।\nko nahiṁ jānata hai jaga meṁ kapi, saṅkaṭa-mocana nāma tihāro ॥",
      en: "When Rāvaṇa fought by stealth and cast the serpent-noose over every head, the whole army together with Rāma himself fell senseless — a heavy trouble, that. Who in this world does not know, monkey-lord, that your name is the Undoer of Trouble?",
      tel: "రావణుడు మాయాయుద్ధము చేసి నాగపాశమును అందరి తలలపై వేసినపుడు, శ్రీరఘునాథునితో సహా సమస్త సేన మూర్ఛిల్లినది — అది భారమైన సంకటము. ఓ కపివరా, జగత్తులో ఎవరు ఎరుగరు — నీ పేరు సంకటమోచనమని?",
      hi: "जब रावण ने छल-युद्ध किया और नागपाश सबके सिर पर डाल दिया, तब श्रीरघुनाथ सहित सारी सेना मोहित हो गयी — यह भारी सङ्कट था। हे कपि, जगत् में कौन नहीं जानता कि तुम्हारा नाम सङ्कटमोचन है?" },
    { s: 0, n: "7",
      deva: "बंधु समेत जबै अहिरावन, लै रघुनाथ पताल सिधारो ।\nदेबिहिं पूजि भली बिधि सों बलि, देउ सबै मिलि मंत्र बिचारो ।\nको नहिं जानत है जग में कपि, संकटमोचन नाम तिहारो ॥",
      iast: "baṁdhu sameta jabai ahirāvana, lai raghunātha patāla sidhāro ।\ndebihiṁ pūji bhalī bidhi soṁ bali, deu sabai mili maṁtra bicāro ।\nko nahiṁ jānata hai jaga meṁ kapi, saṅkaṭa-mocana nāma tihāro ॥",
      en: "When Ahirāvaṇa carried Rāma and his brother away to the underworld, and after worshipping the goddess by full rite meant to offer them up, the gods took counsel together over it. Who in this world does not know, monkey-lord, that your name is the Undoer of Trouble?",
      tel: "అహిరావణుడు సోదరునితో సహా రఘునాథుని పాతాళమునకు తీసుకొనిపోయి, దేవిని విధిపూర్వకముగా పూజించి బలి ఇవ్వబోయినపుడు — దేవతలందరు కలిసి ఆలోచన చేసిరి. ఓ కపివరా, జగత్తులో ఎవరు ఎరుగరు — నీ పేరు సంకటమోచనమని?",
      hi: "जब अहिरावण भाई सहित रघुनाथ को पाताल ले गया, और देवी की विधिपूर्वक पूजा कर बलि देने को हुआ — तब सब देवों ने मिलकर मन्त्र विचारा। हे कपि, जगत् में कौन नहीं जानता कि तुम्हारा नाम सङ्कटमोचन है?" },
    { s: 0, n: "8",
      deva: "काज किये बड़ देवन के तुम, बीर महाप्रभु देखि बिचारो ।\nकौन सो संकट मोर गरीब को, जो तुमसों नहिं जात है टारो ।\nको नहिं जानत है जग में कपि, संकटमोचन नाम तिहारो ॥",
      iast: "kāja kiye baṛa devana ke tuma, bīra mahāprabhu dekhi bicāro ।\nkauna so saṅkaṭa mora garība ko, jo tumasoṁ nahiṁ jāta hai ṭāro ।\nko nahiṁ jānata hai jaga meṁ kapi, saṅkaṭa-mocana nāma tihāro ॥",
      en: "You have done great work for the gods; consider it, hero, great lord. What trouble of mine — a poor man's — could there be that you cannot remove? Who in this world does not know, monkey-lord, that your name is the Undoer of Trouble?",
      tel: "దేవతలకు నీవు గొప్ప కార్యములు చేసితివి; ఓ వీరా, మహాప్రభూ, చూచి ఆలోచింపుము. బీదవాడనైన నా సంకటము ఏది ఉన్నది — నీచే తొలగింపబడనిది? ఓ కపివరా, జగత్తులో ఎవరు ఎరుగరు — నీ పేరు సంకటమోచనమని?",
      hi: "तुमने देवों के बड़े काज किये; हे वीर महाप्रभु, देखकर विचार करो। मुझ गरीब का कौन सा सङ्कट है जो तुमसे टल न सके? हे कपि, जगत् में कौन नहीं जानता कि तुम्हारा नाम सङ्कटमोचन है?" },
    { s: 1, n: null,
      deva: "लाल देह लाली लसे, अरु धरि लाल लंगूर ।\nबज्र देह दानव दलन, जय जय जय कपि सूर ॥",
      iast: "lāla deha lālī lase, aru dhari lāla laṁgūra ।\nbajra deha dānava dalana, jaya jaya jaya kapi sūra ॥",
      en: "Red of body, glowing red, and bearing a red tail; body hard as the thunderbolt, crusher of demons — hail, hail, hail, valiant monkey!",
      tel: "ఎరుపు దేహము, ఎరుపు కాంతితో ప్రకాశించునది, ఎరుపు తోకను ధరించినది; వజ్రమువంటి దేహము, దానవులను దలించునది — జయము జయము జయము, శూరుడైన కపీ!",
      hi: "लाल देह, लाली से दीप्त, और लाल लङ्गूर धारण किये; वज्र-सी देह, दानवों का दलन करने वाले — जय जय जय, हे शूर कपि!" },
  ],
},

{
  deities: ["hanuman"],
  title: "Śrī Hanumat Pañcaratnam",
  blurb: "Five dense Sanskrit verses of Śaṅkara's — every one a single long compound describing the son of the wind, and every one ending in the act of seeing him.",
  sections: [
    { tel: "పంచరత్నం", roman: "The Five Jewels", hi: "पञ्चरत्नम्" },
    { tel: "ఫలశ్రుతి", roman: "The Fruit of Recitation", hi: "फलश्रुति" },
  ],
  verses: [
    { s: 0, n: "1",
      deva: "वीताखिलविषयेच्छं जातानन्दाश्रुपुलकमत्यच्छम् ।\nसीतापतिदूताद्यं वातात्मजमद्य भावये हृद्यम् ॥",
      iast: "vītākhila-viṣayecchaṁ jātānandāśru-pulakam-atyaccham ।\nsītā-pati-dūtādyaṁ vātātmajam-adya bhāvaye hṛdyam ॥",
      en: "Every desire for the objects of sense gone from him; tears of joy risen, his body thrilled, utterly clear; foremost among the messengers of Sītā's lord — today I contemplate the son of the wind, the delight of the heart.",
      tel: "సమస్త విషయవాంఛలు తొలగినవాడు; ఆనందబాష్పములు, పులకాంకురములు కలిగినవాడు, మిక్కిలి నిర్మలుడు; సీతాపతి దూతలలో అగ్రగణ్యుడు — హృదయమునకు ప్రియమైన ఆ వాయుపుత్రుని నేడు భావించుచున్నాను.",
      hi: "समस्त विषयों की इच्छा से रहित; आनन्द के अश्रु और पुलक से युक्त, अत्यन्त निर्मल; सीतापति के दूतों में अग्रगण्य — हृदय को प्रिय उस वातात्मज का आज मैं भावन करता हूँ।" },
    { s: 0, n: "2",
      deva: "तरुणारुणमुखकमलं करुणारसपूरपूरितापाङ्गम् ।\nसञ्जीवनमाशासे मञ्जुलमहिमानमञ्जनाभाग्यम् ॥",
      iast: "taruṇāruṇa-mukha-kamalaṁ karuṇā-rasa-pūra-pūritāpāṅgam ।\nsañjīvanam-āśāse mañjula-mahimānam-añjanā-bhāgyam ॥",
      en: "His lotus face the red of a young dawn, the corners of his eyes brimming with a flood of compassion; his greatness gentle, and he the good fortune of Añjanā — on him, the restorer of life, I set my hope.",
      tel: "బాల సూర్యునివలె అరుణమైన ముఖకమలము గలవాడు, కరుణారసప్రవాహముతో నిండిన కడకన్నులు గలవాడు; మనోహరమైన మహిమ గలవాడు, అంజన యొక్క భాగ్యమైనవాడు — ప్రాణమును తిరిగి ఇచ్చు ఆ స్వామిపైనే ఆశ నిలుపుచున్నాను.",
      hi: "तरुण अरुण-सा मुखकमल, करुणा-रस के पूर से भरे अपाङ्ग; मञ्जुल महिमा वाले, अञ्जना का भाग्य — उस सञ्जीवन पर मैं आशा रखता हूँ।" },
    { s: 0, n: "3",
      deva: "शम्बरवैरिशरातिगमम्बुजदलविपुललोचनोदारम् ।\nकम्बुगलमनिलदिष्टम् बिम्बज्वलितोष्ठमेकमवलम्बे ॥",
      iast: "śambara-vairi-śarātigam-ambuja-dala-vipula-locanodāram ।\nkambu-galam-anila-diṣṭam bimba-jvalitoṣṭham-ekam-avalambe ॥",
      en: "Beyond the reach of the arrows of Kāma, enemy of Śambara; noble, his eyes wide as lotus petals; his throat like a conch, appointed by the wind, his lip glowing like the bimba fruit — on him alone I lean.",
      tel: "శంబరాసురుని శత్రువైన మన్మథుని బాణములకు అందనివాడు; కమలదళములవలె విశాలమైన నేత్రములు గలవాడు, ఉదారుడు; శంఖమువంటి కంఠము గలవాడు, వాయువుచే నియోగింపబడినవాడు, దొండపండువలె ప్రకాశించు పెదవి గలవాడు — ఆ ఒక్కనినే ఆశ్రయించుచున్నాను.",
      hi: "शम्बर के शत्रु कामदेव के बाणों से अतीत; कमलदल-से विशाल नेत्रों वाले, उदार; शङ्ख-सा कण्ठ, वायु से नियुक्त, बिम्ब-सा दीप्त ओष्ठ — उस एक का ही मैं अवलम्ब लेता हूँ।" },
    { s: 0, n: "4",
      deva: "दूरीकृतसीतार्तिः प्रकटीकृतरामवैभवस्फूर्तिः ।\nदारितदशमुखकीर्तिः पुरतो मम भातु हनुमतो मूर्तिः ॥",
      iast: "dūrī-kṛta-sītārtiḥ prakaṭī-kṛta-rāma-vaibhava-sphūrtiḥ ।\ndārita-daśa-mukha-kīrtiḥ purato mama bhātu hanumato mūrtiḥ ॥",
      en: "He put Sītā's anguish far away; he made the splendour of Rāma break into view; he tore the ten-faced one's fame to pieces — may the form of Hanumān shine before me.",
      tel: "సీత దుఃఖమును దూరము చేసినవాడు; రామవైభవమును ప్రకటించినవాడు; పదిముఖముల వాని కీర్తిని చీల్చివేసినవాడు — ఆ హనుమంతుని మూర్తి నా ఎదుట ప్రకాశించునుగాక.",
      hi: "सीता की आर्ति को दूर किया; राम के वैभव की स्फूर्ति प्रकट की; दशमुख की कीर्ति को विदीर्ण किया — हनुमान् की वह मूर्ति मेरे सामने भासित हो।" },
    { s: 0, n: "5",
      deva: "वानरनिकराध्यक्षं दानवकुलकुमुदरविकरसदृक्षम् ।\nदीनजनावनदीक्षं पवनतपःपाकपुञ्जमद्राक्षम् ॥",
      iast: "vānara-nikarādhyakṣaṁ dānava-kula-kumuda-ravi-kara-sadṛkṣam ।\ndīna-janāvana-dīkṣaṁ pavana-tapaḥ-pāka-puñjam-adrākṣam ॥",
      en: "Overseer of the host of monkeys; to the demon race what the sun's rays are to the night lotus; consecrated to the protecting of the helpless — I have seen him, the whole ripened fruit of the wind's austerity.",
      tel: "వానరసమూహమునకు అధ్యక్షుడు; దానవకులమునకు కలువలకు సూర్యకిరణములవంటివాడు; దీనజనులను రక్షించుటకే దీక్ష వహించినవాడు — వాయుదేవుని తపఃఫలము మూర్తీభవించిన ఆ స్వామిని దర్శించితిని.",
      hi: "वानर-निकर के अध्यक्ष; दानव-कुल के लिए कुमुद के प्रति सूर्य-किरण के समान; दीनजनों की रक्षा में दीक्षित — पवन के तप के पाक-पुञ्ज उन्हें मैंने देखा।" },
    { s: 1, n: "6",
      deva: "एतत्पवनसुतस्य स्तोत्रं यः पठति पञ्चरत्नाख्यम् ।\nचिरमिह निखिलान् भोगान् भुक्त्वा श्रीरामभक्तिभाग् भवति ॥",
      iast: "etat-pavana-sutasya stotraṁ yaḥ paṭhati pañca-ratnākhyam ।\nciram-iha nikhilān bhogān bhuktvā śrī-rāma-bhakti-bhāg bhavati ॥",
      en: "Whoever recites this hymn to the son of the wind, called the Five Jewels, enjoys here for long every good thing, and comes to have a share in devotion to Rāma.",
      tel: "పంచరత్నమను పేరుగల ఈ పవనసుత స్తోత్రమును పఠించువాడు — ఇచట చిరకాలము సమస్త భోగములను అనుభవించి, శ్రీరామభక్తికి భాగస్వామి యగును.",
      hi: "जो पञ्चरत्न नामक इस पवनसुत स्तोत्र का पाठ करता है, वह यहाँ चिरकाल तक समस्त भोग भोगकर श्रीराम की भक्ति का भागी होता है।" },
  ],
},];
