/* ============================================================
   STUTI — Subrahmaṇya full texts (desktop batch, files 23/24/25)
   Skanda Daṇḍakam · Śaravaṇabhava Devaseneśa Ṣaṭkam · Svāminātha Pañcakam
   Converted verbatim from the user's sourced dossier files —
   Devanāgarī is the source of truth; verses carry en/tel/hi glosses
   inline. Titles must match STOTRA_INDEX exactly.
   ============================================================ */
export const extra = [{
  deities: ["subrahmanya"],
  title: "Skanda Daṇḍakam",
  blurb: "One continuous, breathless chain of vocatives — the daṇḍaka metre carrying Skanda's whole iconography without a single full stop.",
  colophon: { deva: "इति श्री स्कन्द दण्डकम् ।", iast: "iti śrī skanda daṇḍakam |" },
  sections: [{ tel: "దండకం", roman: "The Daṇḍakam" }, { tel: "ముగింపు శ్లోకం", roman: "The Concluding Verse" }],
  verses: [
    { s: 0, n: null,
      deva: "अयि जय जयाम्भोजिनीजानिडिम्भोदयोद्यत् कुसुम्भोल्लसत्फुल्ल दम्भोपमर्दप्रवीण प्रभाधोरणीपूरिताशावकाश,\nवरानन्दसान्द्रप्रकाश,\nसहैवोत्तरङ्गीभवत्सौहृदावेशमीशान पञ्चाननी पार्वतीवक्त्रसञ्चुम्ब्यमानाननाम्भोजषट्क,\nद्विषत्कायरक्तौघरज्यत्पृषत्क,\nस्वकीय प्रभु द्वादशात्म द्रढीयस्तमप्रेम धामायित द्वादशाम्भोज वृन्दिष्ठ बंहिष्ठ सौन्दर्य धुर्येक्षण,\nसाधुसंरक्षण,\nनिजचरण वन्दनासक्त सद्वृन्द भूयस्तरानन्द दायिस्फुरन्मन्दहासद्युतिस्यन्द दूरीकृतामन्दकुन्द प्रसूनप्रभा कन्दलीसुन्दरत्वाभिमान,\nसमस्तामरस्तोम संस्तूयमान,\nजगत्याहितात्याहितादित्यपत्याहित प्रौढ वक्षःस्थलोद्गच्छदास्रच्छटा धूमल च्छाय शक्तिस्फुरत्पाणि पाथोरुह,\nभक्तमन्दार पृथ्वीरुह,\nविहितपरिरम्भ वल्लीवपुर्वल्लरी मेलनोल्लासितोरस्तट श्रीनिरस्ता चिरज्योतिराश्लिष्ट सन्ध्याम्बुदानोपमाडम्बर,\nतप्तजाम्बूनद भ्राजमानाम्बर,\nपिञ्छभार प्रभामण्डली पिण्डिताखण्डलेष्वासनाखण्डरोचिः शिखण्डिप्रकाण्डोपरिद्योतमान,\nपदश्रीहृत श्रीगृहव्रातमान,\nप्रथितहरिगीतालयालङ्कृते, कार्तिकेयार्तबन्धो, दयापूरसिन्धो,\nनमस्ते समस्तेश मां पाहि पाहि प्रसीद प्रसीद ॥",
      iast: "ayi jaya jayāmbhojinījāniḍimbhodayodyat kusumbhollasatphulla dambhopamardapravīṇa prabhādhoraṇīpūritāśāvakāśa,\nvarānandasāndraprakāśa,\nsahaivottaraṅgībhavatsauhṛdāveśamīśāna pañcānanī pārvatīvaktrasañcumbyamānānanāmbhojaṣaṭka,\ndviṣatkāyaraktaugharajyatpṛṣatka,\nsvakīya prabhu dvādaśātma draḍhīyastamaprema dhāmāyita dvādaśāmbhoja vṛndiṣṭha baṁhiṣṭha saundarya dhuryekṣaṇa,\nsādhusaṁrakṣaṇa,\nnijacaraṇa vandanāsakta sadvṛnda bhūyastarānanda dāyisphuranmandahāsadyutisyanda dūrīkṛtāmandakunda prasūnaprabhā kandalīsundaratvābhimāna,\nsamastāmarastoma saṁstūyamāna,\njagatyāhitātyāhitādityapatyāhita prauḍha vakṣaḥsthalodgacchadāsracchaṭā dhūmala cchāya śaktisphuratpāṇi pāthoruha,\nbhaktamandāra pṛthvīruha,\nvihitaparirambha vallīvapurvallarī melanollāsitorastaṭa śrīnirastā cirajyotirāśliṣṭa sandhyāmbudānopamāḍambara,\ntaptajāmbūnada bhrājamānāmbara,\npiñchabhāra prabhāmaṇḍalī piṇḍitākhaṇḍaleṣvāsanākhaṇḍarociḥ śikhaṇḍiprakāṇḍoparidyotamāna,\npadaśrīhṛta śrīgṛhavrātamāna,\nprathitaharigītālayālaṅkṛte, kārtikeyārtabandho, dayāpūrasindho,\nnamaste samasteśa māṁ pāhi pāhi prasīda prasīda ||",
      en: "Hail, victory, victory! You fill every quarter of space with an unbroken array of splendor that outshines the pride of freshly blossomed lotuses, and your own radiance is deep and joy-drenched; your six lotus faces are kissed, in a welling rush of tenderness, by the mouth of Pārvatī, consort of the five-faced Śiva, and your arrows run red with torrents of enemy blood; your twelve lotus eyes, loveliest among their own throng, are the very seat of the deepest love for your own lord, and you are the protector of the virtuous; your softly gleaming, gentle smile pours out ever-greater bliss upon the good multitude that clings to worshipping your feet, a radiance that has stripped the jasmine-spray of its pride in its own beauty, and the whole host of immortals sings your praise; you are the one refuge against the extreme calamity that beset the world, your broad chest sending up a trail of blood-dark, smoke-hued splendor as the śakti-spear gleams in your lotus hand, and you are a wish-granting tree sprung up on earth for your devotees; embracing the vine-soft body of Vallī has made your chest so glorious that it outshines the pomp of a twilight cloud clasping an unfading flash of lightning, and you are clothed in garments that blaze like molten gold; you shine gloriously astride your splendid peacock, the massed radiance of whose plume gathers up the unbroken luster of Indra's bow, and the glory of your very feet has stolen away the pride of Lakṣmī's own abode; you adorn the renowned shrine of Harigītāpuram — Harippad — O Kārtikeya, kinsman of the afflicted, ocean brimming with compassion: salutations to you, lord of all; protect me, protect me; be gracious, be gracious.",
      tel: "జయము, జయము! వికసించిన పద్మముల గర్వమును అణచు తేజోధారతో సమస్త దిక్కులను నింపినవాడా, గాఢమైన ఆనందకాంతిగలవాడా; ఈశానుని అర్ధాంగియైన పార్వతీదేవి పెల్లుబికే వాత్సల్యంతో నీ ఆరు పద్మముఖములను ముద్దాడగా, శత్రువుల రక్తప్రవాహముతో ఎర్రబారిన బాణములు కలవాడా; నీ పండ్రెండు పద్మనేత్రములు తమ సమూహంలోనే అత్యంత సుందరమైనవి, నీ ప్రభువుపై గాఢమైన ప్రేమకు నిలయమైనవి, సజ్జనులను రక్షించువాడా; నీ పాదములను కొలుచు సజ్జనసమూహమునకు నానాటికీ మిక్కుటమగు ఆనందమిచ్చు మందహాసకాంతి మల్లెపూల సౌందర్యగర్వమును సైతం తొలగించినది, దేవతాసమూహమంతటిచే స్తుతింపబడువాడా; లోకమునకు వాటిల్లిన మహావిపత్తుకు ఏకైక శరణమైనవాడా, రక్తవర్ణపు పొగవంటి కాంతిపొర వ్యాపించిన విశాల వక్షస్థలముపై శక్త్యాయుధమును పద్మహస్తమున ధరించువాడా, భక్తులకు భూమిపై మొలచిన కల్పవృక్షమువంటివాడా; వల్లీదేవి లతవంటి దేహమును కౌగిలించుకొనుటచే మెరుపును పొదివిపట్టిన సంధ్యాకాలమేఘపు వైభవమునే మించిన కాంతిగల విశాలవక్షస్థలము కలవాడా, కరిగిన బంగారము వంటి తళతళలాడు వస్త్రములు ధరించువాడా; ఇంద్రధనుస్సు యొక్క అనన్యమైన కాంతినంతటినీ తనలో కూర్చుకున్న నెమలిపింఛపు ప్రభామండలముతో శోభిల్లు నెమలిపైనధిష్ఠించి ప్రకాశించువాడా, నీ పాదముల శోభ లక్ష్మీదేవి నివాసముయొక్క గౌరవమునే అపహరించినది; ప్రసిద్ధమైన హరిగీతాపురము (హరిప్పాడు) ఆలయమును అలంకరించువాడా, కార్తికేయా, ఆర్తబాంధవా, దయాసముద్రమా — సర్వేశ్వరా, నీకు నమస్కారము; నన్ను రక్షింపుము, రక్షింపుము; ప్రసన్నుడవు కమ్ము, ప్రసన్నుడవు కమ్ము.",
      hi: "जय हो, जय हो! हे स्वामी, खिले हुए कमलों के गर्व को कुचलने वाली तेजोमाला से समस्त दिशाओं को भरने वाले, गहन आनन्दमय कान्ति वाले; ईशान (शिव) की अर्धांगिनी पार्वती जिनके छह कमल-मुखों को उमड़ते हुए स्नेह से चूमती हैं, शत्रुओं के रक्त-प्रवाह से रँगे हुए बाण धारण करने वाले; जिनके बारह कमल-नेत्र अपने ही समूह में सर्वाधिक सुंदर हैं और अपने प्रभु के प्रति गहनतम प्रेम के निवास हैं, सज्जनों की रक्षा करने वाले; जिनकी मंद मुस्कान की कांति अपने चरणों की वंदना में लगे सज्जन-समूह को उत्तरोत्तर आनन्द प्रदान करती है और जिसने मालती-पुष्पों के सौन्दर्य-गर्व को भी दूर कर दिया है, समस्त देवगण द्वारा स्तुत, संसार पर आए महाविपत्ति के एकमात्र आश्रय, जिनके विशाल वक्षस्थल से धूम्र-वर्ण रक्त-कान्ति की रेखा उठती है और जो कमल-हस्त में शक्ति-अस्त्र धारण करते हैं, भक्तों के लिए धरती पर उगे कल्पवृक्ष के समान; वल्ली के लता-सुकुमार शरीर के आलिंगन से जिनका वक्षस्थल संध्याकालीन बिजली समेटे मेघ के वैभव को भी मात करता है, तपे हुए स्वर्ण के समान चमकते वस्त्र धारण करने वाले; इन्द्रधनुष की अखण्ड कान्ति को समेटे हुए मयूर-पिच्छ की प्रभा-मण्डली से सुशोभित, अपने भव्य मयूर पर आरूढ़ होकर प्रकाशमान, जिनके चरणों की शोभा ने लक्ष्मी के निवास-स्थान के गौरव को भी हर लिया है; प्रसिद्ध हरिगीतापुरम् (हरिप्पाड) मंदिर को सुशोभित करने वाले, हे कार्तिकेय, पीड़ितों के बन्धु, करुणा-सिन्धु — हे सर्वेश्वर, आपको नमस्कार; मेरी रक्षा करें, रक्षा करें; प्रसन्न हों, प्रसन्न हों।" },
    { s: 1, n: null,
      deva: "कारुण्याम्बुनिधे समस्तसुमनः सन्तापदानोद्यतस्फायद्दर्पभरासुरप्रभुसमूलोन्मूलनैकायन ।\nबिभ्राणः क्षितिभृद्विभेदनचणां शक्तिं त्वमाग्नेय मां\nपाहि श्रीहरिगीतपत्तनपते देहि श्रियं मे जवात् ॥",
      iast: "kāruṇyāmbunidhe samastasumanaḥ santāpadānodyatasphāyaddarpabharāsuraprabhusamūlonmūlanaikāyana |\nbibhrāṇaḥ kṣitibhṛdvibhedanacaṇāṁ śaktiṁ tvamāgneya māṁ\npāhi śrīharigītapattanapate dehi śriyaṁ me javāt ||",
      en: "O ocean of compassion, you are the sole means of uprooting, root and branch, the demon-lord whose swelling burden of pride was bent on tormenting all the celestials; bearing the śakti-spear that is potent to cleave mountains, O son of Agni, protect me; O lord of the city of Harigītapattana, grant me prosperity swiftly.",
      tel: "కరుణాసముద్రుడా, సమస్త దేవతలను బాధించుటకు పూనుకున్న, గర్వముతో ఉప్పొంగిన అసురప్రభువును సమూలముగా పెకలించివేయుటకు నీవే ఏకైక ఉపాయమువు; పర్వతములను చీల్చగల శక్త్యాయుధమును ధరించు అగ్నికుమారా, నన్ను రక్షింపుము; శ్రీ హరిగీతపట్టణమునకు (హరిప్పాడు) ప్రభువా, నాకు శీఘ్రమే సంపదను ప్రసాదింపుము.",
      hi: "हे करुणा के सागर, समस्त देवताओं को संताप देने पर तुले हुए, गर्व से फूले हुए असुर-प्रभु को समूल उखाड़ फेंकने का आप ही एकमात्र उपाय हैं; पर्वतों को विदीर्ण करने में समर्थ शक्ति-अस्त्र धारण करने वाले, हे अग्निपुत्र, मेरी रक्षा करें; श्री हरिगीतपत्तन (हरिप्पाड) के स्वामी, मुझे शीघ्र ही श्री (सम्पदा) प्रदान करें।" },
  ],
},

{
  deities: ["subrahmanya"],
  title: "Śaravaṇabhava Devaseneśa Ṣaṭkam",
  blurb: "Six verses that reach Skanda through Devasenā rather than Vaḷḷī — weapon, mount, lineage — by the Śṛṅgeri Jagadguru Śivābhinava Nṛsiṁha Bhāratī.",
  colophon: { deva: "इति शृङ्गेरिजगद्गुरु श्रीसच्चिदानन्दशिवाभिनवनृसिंहभारती स्वामिभिः विरचितं श्री शरवणभव देवसेनेश षट्कम् ।", iast: "iti śṛṅgerijagadguru śrīsaccidānandaśivābhinavanṛsiṁhabhāratī svāmibhiḥ viracitaṁ śrī śaravaṇabhava devasenesha ṣaṭkam |" },
  verses: [
    { s: 0, n: "1",
      deva: "करतलराजच्छक्ते स्वरदपराभूतकुन्दसुमगर्व ।\nसुरवरनिषेविताङ्घ्रे शरवणभव पाहि देवसेनेश ॥",
      iast: "karatalarājacchakte svaradaparābhūtakundasumagarva |\nsuravaraniṣevitāṅghre śaravaṇabhava pāhi devasenesha ||",
      en: "O you whose śakti-spear gleams shining in your very palm, who have humbled the pride of jasmine (kunda) buds with the brilliance of your row of teeth (svarada), whose lotus-feet are attended by the finest of the gods — O Śaravaṇabhava, lord of Devasenā, protect me.",
      tel: "అరచేతిలో ప్రకాశించే శక్త్యాయుధం ధరించినవాడా, తన పలువరుస కాంతితో మల్లెమొగ్గల గర్వాన్ని అణచినవాడా, శ్రేష్ఠులైన దేవతలచే సేవింపబడే పాదపద్మాలు కలవాడా — ఓ శరవణభవా, దేవసేనానాథా, నన్ను రక్షించు.",
      hi: "जिनकी हथेली में शक्ति-आयुध देदीप्यमान है, जिन्होंने अपनी दंतपंक्ति (स्वरद) की कांति से मल्लिका-कलियों के गर्व को कुचल दिया है, जिनके चरण-कमलों की सेवा श्रेष्ठ देवता करते हैं — हे शरवणभव, देवसेना के स्वामी, मेरी रक्षा करें।" },
    { s: 0, n: "2",
      deva: "तटिदाभदेहकान्ते कटिविलसत्पीतवर्णकौशेय ।\nपाटितशूरासुर भो शरवणभव पाहि देवसेनेश ॥",
      iast: "taṭidābhadehakānte kaṭivilasatpītavarṇakauśeya |\npāṭitaśūrāsura bho śaravaṇabhava pāhi devasenesha ||",
      en: "O you whose bodily luster is like lightning (taṭit), who wear a shining yellow-hued silk (kauśeya) cloth about your waist, who rent asunder the demon Śūra (Śūrapadmāsura) — O Śaravaṇabhava, lord of Devasenā, protect me.",
      tel: "మెరుపుతీగ వంటి దేహకాంతి కలవాడా, నడుముపై ప్రకాశించే పచ్చని పట్టువస్త్రం ధరించినవాడా, శూరాసురుని సంహరించినవాడా — ఓ శరవణభవా, దేవసేనానాథా, నన్ను రక్షించు.",
      hi: "जिनकी देहकांति बिजली (तटित्) के समान है, जो कमर पर देदीप्यमान पीत रेशमी (कौशेय) वस्त्र धारण करते हैं, जिन्होंने शूरासुर का विदारण किया — हे शरवणभव, देवसेना के स्वामी, मेरी रक्षा करें।" },
    { s: 0, n: "3",
      deva: "नीलग्रीवतनूद्भव बालदिनेशानकोटिनिभदेह ।\nकालप्रतिभटमोदद शरवणभव पाहि देवसेनेश ॥",
      iast: "nīlagrīvatanūdbhava bāladineśānakoṭinibhadeha |\nkālapratibhaṭamodada śaravaṇabhava pāhi devasenesha ||",
      en: "O you born from the body of blue-throated Śiva (Nīlagrīva), whose form resembles a myriad (koṭi) newly-risen suns, who are the delight of him who is the conquering rival of Kāla (Yama) — that is, of your father Śiva himself — O Śaravaṇabhava, lord of Devasenā, protect me.",
      tel: "నీలకంఠుడైన శివుని శరీరం నుండి ఆవిర్భవించినవాడా, కోటి బాలభానుల తేజస్సు గల దేహం కలవాడా, కాలుని జయించిన తండ్రి శివునికి ఆనందం కలిగించువాడా — ఓ శరవణభవా, దేవసేనానాథా, నన్ను రక్షించు.",
      hi: "नीलकंठ शिव के शरीर से प्रकट हुए, करोड़ों उदीयमान सूर्यों के समान तेजस्वी देह वाले, काल (यम) को जीतने वाले पिता शिव को आनंदित करने वाले — हे शरवणभव, देवसेना के स्वामी, मेरी रक्षा करें।" },
    { s: 0, n: "4",
      deva: "पदजितपङ्कज पङ्कजभवपङ्कजनेत्रमुख्यसुरवन्द्य ।\nपदवीं प्रापय महतीं शरवणभव पाहि देवसेनेश ॥",
      iast: "padajitapaṅkaja paṅkajabhavapaṅkajanetramukhyasuravandya |\npadavīṁ prāpaya mahatīṁ śaravaṇabhava pāhi devasenesha ||",
      en: "O you whose feet have outdone the lotus (paṅkaja) itself, worshipped by the foremost gods headed by lotus-born Brahmā (Paṅkajabhava) and lotus-eyed Viṣṇu (Paṅkajanetra) — grant me that exalted state (mahatī padavī, i.e., liberation). O Śaravaṇabhava, lord of Devasenā, protect me.",
      tel: "పద్మాన్ని సైతం మించిన పాదములు కలవాడా, పద్మసంభవుడైన బ్రహ్మ, పద్మనేత్రుడైన విష్ణువు మొదలైన ముఖ్య దేవతలచే నమస్కరింపబడువాడా — నాకు ఉత్తమమైన పదవిని ప్రసాదించు. ఓ శరవణభవా, దేవసేనానాథా, నన్ను రక్షించు.",
      hi: "जिनके चरण कमल को भी मात देते हैं, जो कमलजन्मा ब्रह्मा और कमलनयन विष्णु आदि प्रमुख देवताओं द्वारा वंदित हैं — मुझे वह महती पदवी (मोक्ष) प्रदान करें। हे शरवणभव, देवसेना के स्वामी, मेरी रक्षा करें।" },
    { s: 0, n: "5",
      deva: "तारकदैत्यनिवारक तारापतिगर्वहारिषड्वक्त्र ।\nतारक भवाम्बुराशेः शरवणभव पाहि देवसेनेश ॥",
      iast: "tārakadaityanivāraka tārāpatigarvahāriṣaḍvaktra |\ntāraka bhavāmburāśeḥ śaravaṇabhava pāhi devasenesha ||",
      en: "O queller of the demon Tāraka, six-faced one (ṣaḍvaktra) whose splendor humbles the pride of the moon (tārāpati, \"lord of the stars\"), O deliverer (tāraka) across the ocean of worldly existence (bhava) — O Śaravaṇabhava, lord of Devasenā, protect me. The verse turns on a deliberate pun: tāraka names the slain demon in the first line, then, in the second, means \"one who ferries across,\" from the same root (√tṝ, to cross).",
      tel: "తారకాసురుడనే రాక్షసుని అణచినవాడా, చంద్రుని గర్వాన్ని హరించిన ఆరుముఖముల వాడా, సంసారసాగరాన్ని దాటించు నావ వంటివాడా — ఓ శరవణభవా, దేవసేనానాథా, నన్ను రక్షించు. ఇక్కడ \"తారక\" అనే పదం మొదట రాక్షసుని పేరుగానూ, మలుపున \"దాటించువాడు\" అనే అర్థంలోనూ శ్లేషగా ప్రయోగించబడింది.",
      hi: "तारकासुर राक्षस का दमन करने वाले, चंद्रमा के गर्व को हरने वाले षड्मुख, संसार-सागर से पार उतारने वाले — हे शरवणभव, देवसेना के स्वामी, मेरी रक्षा करें। यहाँ \"तारक\" शब्द पहले राक्षस के नाम के रूप में और फिर \"पार उतारने वाला\" के अर्थ में, एक ही धातु (√तृ) से, श्लेष के रूप में प्रयुक्त हुआ है।" },
    { s: 0, n: "6",
      deva: "पर्वतसुतामनोऽम्बुजसद्यःसञ्जातवासरेशतते ।\nसर्वश्रुतिगीतविभो शरवणभव पाहि देवसेनेश ॥",
      iast: "parvatasutāmano'mbujasadyaḥsañjātavāsareśatate |\nsarvaśrutigītavibho śaravaṇabhava pāhi devasenesha ||",
      en: "O you who, like a sudden host (tati) of suns (vāsareśa, \"lords of the day\"), instantly bring the lotus that is the mind of the mountain's daughter, Pārvatī, into bloom — that is, who fill your mother's heart with joy — O lord glorified by all the Vedas (śruti), O Śaravaṇabhava, lord of Devasenā, protect me.",
      tel: "పర్వతపుత్రిక పార్వతి మనసు అనే పద్మాన్ని ఒక్కసారిగా వికసింపజేసే సూర్యసమూహం వంటివాడా — అనగా తల్లి హృదయాన్ని ఆనందభరితం చేయువాడా — సకల వేదాలచే కీర్తింపబడు ప్రభూ, ఓ శరవణభవా, దేవసేనానాథా, నన్ను రక్షించు.",
      hi: "पर्वतपुत्री पार्वती के मन-रूपी कमल को क्षण भर में खिला देने वाले सूर्यसमूह के समान — अर्थात् माता के हृदय को आनंदित करने वाले — समस्त वेदों द्वारा गाए जाने वाले प्रभु, हे शरवणभव, देवसेना के स्वामी, मेरी रक्षा करें।" },
  ],
},

{
  deities: ["subrahmanya"],
  title: "Svāminātha Pañcakam",
  blurb: "Svāminātha of Swamimalai — the child who taught his own father the meaning of Om, laughing in Śambhu's ear. By Anantarāma Dīkṣita.",
  sections: [{ tel: "మంగళాచరణం", roman: "Maṅgalācaraṇam" }, { tel: "పంచకం", roman: "The Five Verses" }, { tel: "ఫలశ్రుతి", roman: "The Fruit of Recitation" }],
  verses: [
    { s: 0, n: null,
      deva: "हे स्वामिनाथार्तबन्धो ।\nभस्मलिप्ताङ्ग गाङ्गेय कारुण्यसिन्धो ॥",
      iast: "he svāmināthārtabandho |\nbhasmaliptāṅga gāṅgeya kāruṇyasindho ||",
      en: "O Svāminātha, kinsman of the afflicted, your limbs smeared with sacred ash, Gāṅgeya (son of the Gaṅgā), ocean of compassion!",
      tel: "ఓ స్వామినాథా, ఆర్తులకు బంధువా, భస్మలేపిత శరీరుడా, గాంగేయా (గంగాపుత్రుడా), కారుణ్యసముద్రుడా!",
      hi: "हे स्वामिनाथ, आर्तों के बंधु, भस्म से लिप्त अंगों वाले, गाङ्गेय (गंगापुत्र), करुणा के सागर!" },
    { s: 1, n: "1",
      deva: "रुद्राक्षधारिन्नमस्ते\nरौद्ररोगं हर त्वं पुरारेर्गुरोर्मे ।\nराकेन्दुवक्त्रं भवन्तं\nमाररूपं कुमारं भजे कामपूरम् ॥",
      iast: "rudrākṣadhārinnamaste\nraudrarogaṁ hara tvaṁ purārergurorme |\nrākenduvaktraṁ bhavantaṁ\nmārarūpaṁ kumāraṁ bhaje kāmapūram ||",
      en: "Homage to you, wearer of rudrākṣa beads, guru even to Purāri (Śiva) himself — destroy my terrible affliction. I worship Kumāra, moon-faced, handsome as Māra (the god of love), the fulfiller of desire (kāmapūra).",
      tel: "రుద్రాక్షధారీ, నీకు నమస్కారం; పురారి (శివుడు)కి కూడా గురువైన నీవు నా భయంకర రోగాన్ని పోగొట్టుము. చంద్రబింబం వంటి ముఖము గల, మారుని వలె సుందరుడైన, కోరికలను తీర్చే కుమారుని (కామపూరుని) నేను భజిస్తున్నాను.",
      hi: "हे रुद्राक्षधारी, तुम्हें नमस्कार; पुरारि (शिव) के भी गुरु तुम मेरे भयंकर रोग को दूर करो। चंद्रमुख, मार (कामदेव) के समान सुंदर, कामनाओं को पूर्ण करने वाले (कामपूर) कुमार का मैं भजन करता हूँ।" },
    { s: 1, n: "2",
      deva: "मां पाहि रोगादघोरात्\nमङ्गलापाङ्गपातेन भङ्गात्स्वराणाम् ।\nकालाच्च दुष्पाककूलात्\nकालकालस्यसूनुं भजे क्रान्तसानुम् ॥",
      iast: "māṁ pāhi rogādaghorāt\nmaṅgalāpāṅgapātena bhaṅgātsvarāṇām |\nkālācca duṣpākakūlāt\nkālakālasyasūnuṁ bhaje krāntasānum ||",
      en: "Protect me from terrible disease by the fall of your auspicious sidelong glance, from loss of voice, and from death and the brink of evil result (duṣpāka, misfortune). I worship the son of Kālakāla (Śiva, \"death of Death\"), who is throned upon the mountain ridge (krāntasānu).",
      tel: "శుభకరమైన నీ కటాక్షవీక్షణం వల్ల నన్ను భయంకర రోగం నుండి, స్వరభంగం నుండి, మృత్యువు నుండి, దుష్పాకం (దుష్ఫలితం) అనే గట్టు నుండి రక్షించుము. కొండ శిఖరాన్ని అధిరోహించిన (క్రాంతసానుడైన) కాలకాలుని (శివుని) కుమారుని నేను భజిస్తున్నాను.",
      hi: "अपने मंगलमय कटाक्ष से मुझे भयंकर रोग से, स्वर-भंग से, मृत्यु से और दुष्पाक (अशुभ फल) के तट से रक्षा करो। पर्वत-शिखर पर आरूढ़ (क्रांतसानु) कालकाल (शिव) के पुत्र का मैं भजन करता हूँ।" },
    { s: 1, n: "3",
      deva: "ब्रह्मादयो यस्य शिष्याः\nब्रह्मपुत्रा गिरौ यस्य सोपानभूताः ।\nसैन्यं सुराश्चापि सर्वे\nसामवेदादिगेयं भजे कार्तिकेयम् ॥",
      iast: "brahmādayo yasya śiṣyāḥ\nbrahmaputrā girau yasya sopānabhūtāḥ |\nsainyaṁ surāścāpi sarve\nsāmavedādigeyaṁ bhaje kārtikeyam ||",
      en: "Brahmā and the other gods are his disciples; the sons of Brahmā (the sages) have themselves become the steps of his hill; all the gods together are his army. I worship Kārtikeya, sung of by the Sāmaveda and the other Vedas.",
      tel: "బ్రహ్మాదులు ఎవని శిష్యులో, ఎవని కొండకు బ్రహ్మపుత్రులు (ఋషులు) మెట్లుగా మారారో, దేవతలందరూ ఎవని సైన్యమో, సామవేదాది వేదాలచే స్తుతింపబడే ఆ కార్తికేయుని నేను భజిస్తున్నాను.",
      hi: "ब्रह्मादि जिसके शिष्य हैं, जिसके पर्वत की सीढ़ियाँ स्वयं ब्रह्मपुत्र (ऋषिगण) बन गए हैं, समस्त देवता जिसकी सेना हैं, सामवेद आदि वेदों द्वारा गाए जाने वाले उस कार्तिकेय का मैं भजन करता हूँ।" },
    { s: 1, n: "4",
      deva: "काषाय संवीत गात्रं\nकामरोगादि संहारि भिक्षान्न पात्रम् ।\nकारुण्य सम्पूर्ण नेत्रं\nशक्तिहस्तं पवित्रं भजे शम्भुपुत्रम् ॥",
      iast: "kāṣāya saṁvīta gātraṁ\nkāmarogādi saṁhāri bhikṣānna pātram |\nkāruṇya sampūrṇa netraṁ\nśaktihastaṁ pavitraṁ bhaje śambhuputram ||",
      en: "I worship the son of Śambhu (Śiva) — his body wrapped in the ochre robe (kāṣāya) of a renunciate, destroyer of desire, disease and the like, holding the mendicant's alms-bowl, his eyes full of compassion, the śakti-spear in hand, the pure one.",
      tel: "కాషాయ వస్త్రధారియై, కామరోగాదులను నశింపజేసేవాడై, భిక్షాపాత్రను ధరించినవాడై, కారుణ్యంతో నిండిన కన్నులు గలవాడై, శక్త్యాయుధాన్ని చేత ధరించిన పవిత్రుడైన శంభుపుత్రుని నేను భజిస్తున్నాను.",
      hi: "काषाय वस्त्र धारण किए, काम-रोग आदि का नाश करने वाले, भिक्षा-पात्र लिए, करुणा से परिपूर्ण नेत्रों वाले, हाथ में शक्ति-आयुध धारण किए पवित्र शंभुपुत्र का मैं भजन करता हूँ।" },
    { s: 1, n: "5",
      deva: "श्रीस्वामि शैले वसन्तं\nसाधुसङ्घस्य रोगान् सदा संहरन्तम् ।\nओङ्कारतत्त्वं वदन्तं\nशम्भुकर्णे हसन्तं भजेऽहं शिशुं तम् ॥",
      iast: "śrīsvāmi śaile vasantaṁ\nsādhusaṅghasya rogān sadā saṁharantam |\noṅkāratattvaṁ vadantaṁ\nśambhukarṇe hasantaṁ bhaje'haṁ śiśuṁ tam ||",
      en: "I worship that child who dwells on the holy Svāmi hill, ever destroying the diseases of the community of holy ones, declaring the truth of Auṁkāra (the syllable Om), laughing as he does so in Śambhu's (Śiva's) ear.",
      tel: "పవిత్రమైన స్వామిమలై కొండపై నివసిస్తూ, సాధుసంఘం రోగాలను ఎల్లప్పుడూ పోగొడుతూ, ఓంకార తత్త్వాన్ని బోధిస్తూ, శంభుని (శివుని) చెవిలో నవ్వుతూ చెప్పే ఆ శిశువును నేను భజిస్తున్నాను.",
      hi: "पवित्र स्वामिमलई पर्वत पर निवास करते हुए, साधुसंघ के रोगों को सदा नष्ट करते हुए, ओंकार के तत्त्व को कहते हुए और शंभु (शिव) के कान में हँसते हुए बताने वाले उस शिशु का मैं भजन करता हूँ।" },
    { s: 2, n: "6",
      deva: "स्तोत्रं कृतं चित्रचित्रं\nदीक्षितानन्तरामेण सर्वार्थसिद्ध्यै ।\nभक्त्या पठेद्यः प्रभाते\nदेवदेवप्रसादात् लभेताष्टसिद्धिम् ॥",
      iast: "stotraṁ kṛtaṁ citracitraṁ\ndīkṣitānantarāmeṇa sarvārthasiddhyai |\nbhaktyā paṭhedyaḥ prabhāte\ndevadevaprasādāt labhetāṣṭasiddhim ||",
      en: "This wondrous hymn (citracitra) was composed by Dīkṣita Anantarāma for the accomplishment of every aim; whoever recites it with devotion at dawn shall obtain the eight siddhis (supernatural powers) by the grace of the god of gods.",
      tel: "ఈ అద్భుతమైన స్తోత్రాన్ని దీక్షితుడైన అనంతరాముడు సర్వార్థసిద్ధి కోసం రచించాడు; దీనిని ప్రభాతకాలంలో భక్తితో పఠించేవారు దేవదేవుని అనుగ్రహం వలన అష్టసిద్ధులను పొందుతారు.",
      hi: "यह अद्भुत स्तोत्र दीक्षित अनंतराम द्वारा सर्वार्थसिद्धि के लिए रचा गया; जो प्रातःकाल भक्तिपूर्वक इसका पाठ करता है, वह देवदेव की कृपा से अष्ट सिद्धियाँ प्राप्त करता है।\n\n---\nRecension note: This item was not found in the earlier-scanned portion of sanskritdocuments.org's doc_subrahmanya catalog (which covered entries through \"subrahmaṇyāṣṭakaṁ 2\"), but it does appear further down that same catalog page — under the alternate title \"svAminAthaShaTkam\" (Svāminātha Ṣaṭkam) rather than \"Pañcakam.\" Its text (svAminAthaShaTkam.itx, attributed to Anantarāma Dīkṣita, transliterated/proofread by Malathi Ravi Kuduvaa, last updated 23 Jan 2021) is word-for-word identical to vignanam.org's and stotranidhi.com's \"Svāminātha Pañcakam,\" so all three sources fully agree and this is a full, not reduced, cross-check. The only divergence across the three is how the six numbered units are counted: vignanam.org and stotranidhi.com (followed here) leave the opening couplet unnumbered and number the five core verses 1–5 plus a closing verse 6, while sanskritdocuments.org numbers the opening couplet itself as \"1\" and shifts the remainder to 2–6, leaving the phala-śruti unnumbered — hence \"Pañcakam\" (five) versus \"Ṣaṭkam\" (six) as titles for what is, textually, one and the same six-unit composition. No other variant readings were found among the three sources; hariome.com's Telugu-language page for this title (consulted only as a title check, not fetched for full text since the three sources above already gave complete agreement) confirms the same title is current in Telugu-tradition usage." },
  ],
},];
