/* ============================================================
   STUTI — Viṣṇu full texts, part 2
   Daśāvatāra Stotram · Bālamukundāṣṭakam
   Devanāgarī is the source of truth; other scripts are derived at
   read time. Each verse ships with all four glosses from the start:
   `en` · `tel` (అర్థం) · `hi` (अर्थ). No fallback to English.
   ============================================================ */
export const extra = [{
  deities: ["vishnu"],
  title: "Daśāvatāra Stotram",
  blurb: "Jayadeva's ten descents, one verse each, every one closing on the same shout — jaya jagadīśa hare. The tenth is still to come, which is why the hymn ends looking forward.",
  sections: [
    { tel: "దశావతారములు", roman: "The Ten Descents", hi: "दशावतार" },
    { tel: "ఫలశ్రుతి", roman: "The Fruit of Recitation", hi: "फलश्रुति" },
  ],
  verses: [
    { s: 0, n: "1",
      deva: "प्रलयपयोधिजले धृतवानसि वेदं\nविहितवहित्रचरित्रमखेदम् ।\nकेशव धृतमीनशरीर जय जगदीश हरे ॥",
      iast: "pralaya-payodhi-jale dhṛtavān-asi vedaṁ\nvihita-vahitra-caritram-akhedam ।\nkeśava dhṛta-mīna-śarīra jaya jagadīśa hare ॥",
      en: "In the waters of the ocean at the world's dissolution you held up the Veda, playing the part of a boat, and never wearied. Keśava, who took the body of a fish — hail, lord of the world, Hari!",
      tel: "ప్రళయసముద్ర జలములలో నీవు వేదమును ధరించితివి — నావ పాత్రను నిర్వహించి, అలసట లేకుండ. ఓ కేశవా, మీనశరీరమును ధరించినవాడా — జయము, జగదీశా, హరీ!",
      hi: "प्रलय के समुद्र के जल में तुमने वेद को धारण किया — नौका का चरित्र निभाते हुए, बिना खेद। हे केशव, मीन शरीर धारण करने वाले — जय हो, जगदीश हरे!" },
    { s: 0, n: "2",
      deva: "क्षितिरतिविपुलतरे तिष्ठति तव पृष्ठे\nधरणिधरणकिणचक्रगरिष्ठे ।\nकेशव धृतकच्छपरूप जय जगदीश हरे ॥",
      iast: "kṣitir-ati-vipulatare tiṣṭhati tava pṛṣṭhe\ndharaṇi-dharaṇa-kiṇa-cakra-gariṣṭhe ।\nkeśava dhṛta-kacchapa-rūpa jaya jagadīśa hare ॥",
      en: "The earth rests on your vast back, made the more venerable by the ring of callus that bearing the earth has left on it. Keśava, who took the form of a tortoise — hail, lord of the world, Hari!",
      tel: "మిక్కిలి విశాలమైన నీ వెన్నుపై భూమి నిలిచియున్నది — భూమిని మోసిన కారణమున ఏర్పడిన కాయ యొక్క వలయముచే ఆ వెన్ను మరింత గౌరవనీయమైనది. ఓ కేశవా, కచ్ఛపరూపమును ధరించినవాడా — జయము, జగదీశా, హరీ!",
      hi: "अति विपुल तेरी पीठ पर पृथ्वी स्थित है — धरणी को धारण करने से पड़े किण-चक्र से वह पीठ और गरिष्ठ हो गई। हे केशव, कच्छप रूप धारण करने वाले — जय हो, जगदीश हरे!" },
    { s: 0, n: "3",
      deva: "वसति दशनशिखरे धरणी तव लग्ना\nशशिनि कलङ्ककलेव निमग्ना ।\nकेशव धृतसूकररूप जय जगदीश हरे ॥",
      iast: "vasati daśana-śikhare dharaṇī tava lagnā\nśaśini kalaṅka-kaleva nimagnā ।\nkeśava dhṛta-sūkara-rūpa jaya jagadīśa hare ॥",
      en: "The earth clings to the tip of your tusk and rests there, sunk into it like the mark of the stain on the moon. Keśava, who took the form of a boar — hail, lord of the world, Hari!",
      tel: "నీ దంతపు కొనకు అంటుకొని భూమి నిలిచియున్నది — చంద్రునియందు కళంకపు గుర్తువలె అందు మునిగియున్నది. ఓ కేశవా, సూకరరూపమును ధరించినవాడా — జయము, జగదీశా, హరీ!",
      hi: "तेरे दन्त के शिखर पर लगी हुई धरणी वहीं बसती है — चन्द्र में कलङ्क की रेखा के समान उसमें निमग्न। हे केशव, सूकर रूप धारण करने वाले — जय हो, जगदीश हरे!" },
    { s: 0, n: "4",
      deva: "तव करकमलवरे नखमद्भुतशृङ्गं\nदलितहिरण्यकशिपुतनुभृङ्गम् ।\nकेशव धृतनरहरिरूप जय जगदीश हरे ॥",
      iast: "tava kara-kamala-vare nakham-adbhuta-śṛṅgaṁ\ndalita-hiraṇyakaśipu-tanu-bhṛṅgam ।\nkeśava dhṛta-narahari-rūpa jaya jagadīśa hare ॥",
      en: "On your fine lotus hand the nail was a wondrous peak, and it tore open the bee that was Hiraṇyakaśipu's body. Keśava, who took the form of the man-lion — hail, lord of the world, Hari!",
      tel: "నీ శ్రేష్ఠమైన కరకమలమునందలి నఖము అద్భుతమైన శిఖరమై, హిరణ్యకశిపుని దేహమను తుమ్మెదను చీల్చివేసినది. ఓ కేశవా, నరహరిరూపమును ధరించినవాడా — జయము, జగదీశా, హరీ!",
      hi: "तेरे श्रेष्ठ करकमल का नख अद्भुत शृङ्ग बना, और उसने हिरण्यकशिपु के शरीर-रूपी भृङ्ग को विदीर्ण कर दिया। हे केशव, नरहरि रूप धारण करने वाले — जय हो, जगदीश हरे!" },
    { s: 0, n: "5",
      deva: "छलयसि विक्रमणे बलिमद्भुतवामन\nपदनखनीरजनितजनपावन ।\nकेशव धृतवामनरूप जय जगदीश हरे ॥",
      iast: "chalayasi vikramaṇe balim-adbhuta-vāmana\npada-nakha-nīra-janita-jana-pāvana ।\nkeśava dhṛta-vāmana-rūpa jaya jagadīśa hare ॥",
      en: "Wondrous dwarf, with a stride you outwitted Bali; and the water born at the nail of your foot makes people pure. Keśava, who took the form of the dwarf — hail, lord of the world, Hari!",
      tel: "ఓ అద్భుతమైన వామనా, అడుగు వేయుటలోనే బలిని మోసగించితివి; నీ పాదనఖమునుండి పుట్టిన జలము జనులను పావనము చేయుచున్నది. ఓ కేశవా, వామనరూపమును ధరించినవాడా — జయము, జగదీశా, హరీ!",
      hi: "हे अद्भुत वामन, विक्रम करते ही तुमने बलि को छल लिया; और तेरे पदनख से जनित जल जनों को पावन करता है। हे केशव, वामन रूप धारण करने वाले — जय हो, जगदीश हरे!" },
    { s: 0, n: "6",
      deva: "क्षत्रियरुधिरमये जगदपगतपापं\nस्नपयसि पयसि शमितभवतापम् ।\nकेशव धृतभृगुपतिरूप जय जगदीश हरे ॥",
      iast: "kṣatriya-rudhira-maye jagad-apagata-pāpaṁ\nsnapayasi payasi śamita-bhava-tāpam ।\nkeśava dhṛta-bhṛgupati-rūpa jaya jagadīśa hare ॥",
      en: "In water made of warriors' blood you bathed the world, and its sin was gone and the fever of becoming stilled. Keśava, who took the form of Bhṛgu's lord — hail, lord of the world, Hari!",
      tel: "క్షత్రియుల రక్తముతో నిండిన జలములలో నీవు జగత్తును స్నానము చేయించితివి; పాపము తొలగినది, సంసారతాపము శమించినది. ఓ కేశవా, భృగుపతిరూపమును ధరించినవాడా — జయము, జగదీశా, హరీ!",
      hi: "क्षत्रियों के रुधिर से भरे जल में तुमने जगत् को स्नान कराया; पाप दूर हुआ और भव का ताप शान्त हुआ। हे केशव, भृगुपति रूप धारण करने वाले — जय हो, जगदीश हरे!" },
    { s: 0, n: "7",
      deva: "वितरसि दिक्षु रणे दिक्पतिकमनीयं\nदशमुखमौलिबलिं रमणीयम् ।\nकेशव धृतरघुपतिरूप जय जगदीश हरे ॥",
      iast: "vitarasi dikṣu raṇe dik-pati-kamanīyaṁ\ndaśa-mukha-mauli-baliṁ ramaṇīyam ।\nkeśava dhṛta-raghupati-rūpa jaya jagadīśa hare ॥",
      en: "In battle you dealt out to every quarter the lovely offering of the ten-faced one's heads — an oblation the guardians of the quarters had longed for. Keśava, who took the form of Raghu's lord — hail, lord of the world, Hari!",
      tel: "రణమునందు నీవు దిక్కులన్నిటికి పదిముఖముల వాని శిరములను రమణీయమైన బలిగా పంచిపెట్టితివి — దిక్పాలకులు కాంక్షించిన ఆ ఆహుతిని. ఓ కేశవా, రఘుపతిరూపమును ధరించినవాడా — జయము, జగదీశా, హరీ!",
      hi: "रण में तुमने दिशाओं को दशमुख के मुकुटों की रमणीय बलि बाँट दी — वह आहुति जो दिक्पतियों को कमनीय थी। हे केशव, रघुपति रूप धारण करने वाले — जय हो, जगदीश हरे!" },
    { s: 0, n: "8",
      deva: "वहसि वपुषि विशदे वसनं जलदाभं\nहलहतिभीतिमिलितयमुनाभम् ।\nकेशव धृतहलधररूप जय जगदीश हरे ॥",
      iast: "vahasi vapuṣi viśade vasanaṁ jaladābhaṁ\nhala-hati-bhīti-milita-yamunābham ।\nkeśava dhṛta-haladhara-rūpa jaya jagadīśa hare ॥",
      en: "On your bright body you wear a garment dark as a rain-cloud — dark as the Yamunā, gathered close for fear of the stroke of your plough. Keśava, who took the form of the plough-bearer — hail, lord of the world, Hari!",
      tel: "ప్రకాశమైన నీ దేహముపై మేఘమువంటి నల్లని వస్త్రమును ధరించుచున్నావు — నాగలి దెబ్బకు భయపడి ఒక్కటిగా చేరిన యమునవలె నల్లనైనది. ఓ కేశవా, హలధరరూపమును ధరించినవాడా — జయము, జగదీశా, హరీ!",
      hi: "अपने विशद शरीर पर तुम जलद-सा वसन धारण करते हो — हल के प्रहार के भय से सिमट आई यमुना-सा श्याम। हे केशव, हलधर रूप धारण करने वाले — जय हो, जगदीश हरे!" },
    { s: 0, n: "9",
      deva: "निन्दसि यज्ञविधेरहह श्रुतिजातं\nसदयहृदयदर्शितपशुघातम् ।\nकेशव धृतबुद्धशरीर जय जगदीश हरे ॥",
      iast: "nindasi yajña-vidher-ahaha śruti-jātaṁ\nsadaya-hṛdaya-darśita-paśu-ghātam ।\nkeśava dhṛta-buddha-śarīra jaya jagadīśa hare ॥",
      en: "Ah — you censure the whole body of scripture about the rite of sacrifice, showing with a compassionate heart the killing of animals in it. Keśava, who took the body of the Buddha — hail, lord of the world, Hari!",
      tel: "ఆహా — యజ్ఞవిధిని గూర్చిన శ్రుతిసమూహమును నీవు నిందించుచున్నావు; దయగల హృదయముతో అందున్న పశుహింసను చూపుచున్నావు. ఓ కేశవా, బుద్ధశరీరమును ధరించినవాడా — జయము, జగదీశా, హరీ!",
      hi: "अहह — यज्ञविधि से सम्बद्ध श्रुतिसमूह की तुम निन्दा करते हो, सदय हृदय से उसमें दिखाई देने वाले पशुघात को दर्शाते हुए। हे केशव, बुद्ध शरीर धारण करने वाले — जय हो, जगदीश हरे!" },
    { s: 0, n: "10",
      deva: "म्लेच्छनिवहनिधने कलयसि करवालं\nधूमकेतुमिव किमपि करालम् ।\nकेशव धृतकल्किशरीर जय जगदीश हरे ॥",
      iast: "mlecchha-nivaha-nidhane kalayasi kara-vālaṁ\ndhūma-ketum-iva kim-api karālam ।\nkeśava dhṛta-kalki-śarīra jaya jagadīśa hare ॥",
      en: "To make an end of the barbarian hordes you wield a sword — dreadful past saying, like a comet in the sky. Keśava, who takes the body of Kalki — hail, lord of the world, Hari!",
      tel: "మ్లేచ్ఛ సమూహములను నశింపజేయుటకు నీవు కరవాలమును ధరించుచున్నావు — తోకచుక్కవలె చెప్పనలవికాని భయంకరమైనది. ఓ కేశవా, కల్కిశరీరమును ధరించువాడా — జయము, జగదీశా, హరీ!",
      hi: "म्लेच्छ समूहों के निधन के लिए तुम करवाल धारण करते हो — धूमकेतु-सा, कहने में न आने वाला कराल। हे केशव, कल्कि शरीर धारण करने वाले — जय हो, जगदीश हरे!" },
    { s: 1, n: "11",
      deva: "श्रीजयदेवकवेरिदमुदितमुदारं\nशृणु सुखदं शुभदं भवसारम् ।\nकेशव धृतदशविधरूप जय जगदीश हरे ॥",
      iast: "śrī-jayadeva-kaver-idam-uditam-udāraṁ\nśṛṇu sukhadaṁ śubhadaṁ bhava-sāram ।\nkeśava dhṛta-daśa-vidha-rūpa jaya jagadīśa hare ॥",
      en: "Hear this generous song uttered by the poet Jayadeva — giver of ease, giver of good, the very pith of existence. Keśava, who took the ten forms — hail, lord of the world, Hari!",
      tel: "శ్రీజయదేవ కవి పలికిన ఈ ఉదారమైన గీతమును వినుము — సుఖమునిచ్చునది, శుభమునిచ్చునది, భవసారమైనది. ఓ కేశవా, పదివిధములైన రూపములను ధరించినవాడా — జయము, జగదీశా, హరీ!",
      hi: "श्रीजयदेव कवि के कहे इस उदार गीत को सुनो — सुखद, शुभद, भव का सार। हे केशव, दशविध रूप धारण करने वाले — जय हो, जगदीश हरे!" },
  ],
},

{
  deities: ["vishnu"],
  title: "Bālamukundāṣṭakam",
  blurb: "Eight verses on the child: a foot in the mouth, butter eaten and sleep feigned, a dance on the serpent's hood. Each one ends the same way — him I call to mind.",
  sections: [{ tel: "అష్టకం", roman: "The Eight Verses", hi: "अष्टकम्" }],
  verses: [
    { s: 0, n: "1",
      deva: "करारविन्देन पदारविन्दं मुखारविन्दे विनिवेशयन्तम् ।\nवटस्य पत्रस्य पुटे शयानं बालं मुकुन्दं मनसा स्मरामि ॥",
      iast: "karāravindena padāravindaṁ mukhāravinde viniveśayantam ।\nvaṭasya patrasya puṭe śayānaṁ bālaṁ mukundaṁ manasā smarāmi ॥",
      en: "With his lotus hand setting his lotus foot into his lotus mouth, lying in the cup of a banyan leaf — the child Mukunda I call to mind.",
      tel: "కరకమలముతో పాదకమలమును ముఖకమలమునందు పెట్టుకొనుచు, మఱ్ఱి ఆకు దొప్పలో పరుండియున్న — ఆ బాలముకుందుని మనసుతో స్మరించుచున్నాను.",
      hi: "करकमल से पादकमल को मुखकमल में रखते हुए, वट के पत्ते के दोने में शयन करते — उस बाल मुकुन्द का मैं मन से स्मरण करता हूँ।" },
    { s: 0, n: "2",
      deva: "संहृत्य लोकान् वटपत्रमध्ये शयानमाद्यन्तविहीनरूपम् ।\nसर्वेश्वरं सर्वहितावतारं बालं मुकुन्दं मनसा स्मरामि ॥",
      iast: "saṁhṛtya lokān vaṭa-patra-madhye śayānam-ādyanta-vihīna-rūpam ।\nsarveśvaraṁ sarva-hitāvatāraṁ bālaṁ mukundaṁ manasā smarāmi ॥",
      en: "Having gathered the worlds back into himself, lying on a banyan leaf, his form without beginning or end; lord of all, whose descent is for the good of all — the child Mukunda I call to mind.",
      tel: "లోకములను తనలో ఉపసంహరించుకొని, మఱ్ఱి ఆకుపై పరుండి, ఆది అంతము లేని రూపము గలవాడు; సర్వేశ్వరుడు, సర్వహితము కోసమే అవతరించినవాడు — ఆ బాలముకుందుని మనసుతో స్మరించుచున్నాను.",
      hi: "लोकों को समेटकर वटपत्र पर शयन करते, आदि-अन्त से रहित रूप वाले; सर्वेश्वर, सर्वहित के लिए अवतरित — उस बाल मुकुन्द का मैं मन से स्मरण करता हूँ।" },
    { s: 0, n: "3",
      deva: "इन्दीवरश्यामलकोमलाङ्गं इन्द्रादिदेवार्चितपादपद्मम् ।\nसन्तानकल्पद्रुममाश्रितानां बालं मुकुन्दं मनसा स्मरामि ॥",
      iast: "indīvara-śyāmala-komalāṅgaṁ indrādi-devārcita-pāda-padmam ।\nsantāna-kalpa-drumam-āśritānāṁ bālaṁ mukundaṁ manasā smarāmi ॥",
      en: "His soft limbs dark as a blue lotus, his lotus feet worshipped by Indra and the gods; the wish-granting tree for those who take shelter with him — the child Mukunda I call to mind.",
      tel: "నల్లకలువవలె శ్యామలమైన కోమల అంగములు గలవాడు, ఇంద్రుడు మొదలైన దేవతలచే పూజింపబడిన పాదపద్మములు గలవాడు; ఆశ్రయించిన వారికి కల్పవృక్షమైనవాడు — ఆ బాలముకుందుని మనసుతో స్మరించుచున్నాను.",
      hi: "इन्दीवर-सा श्यामल कोमल अङ्ग, इन्द्र आदि देवों से अर्चित पादपद्म; आश्रितों के लिए कल्पवृक्ष — उस बाल मुकुन्द का मैं मन से स्मरण करता हूँ।" },
    { s: 0, n: "4",
      deva: "लम्बालकं लम्बितहारयष्टिं शृङ्गारलीलाङ्कितदन्तपङ्क्तिम् ।\nबिम्बाधरं चारुविशालनेत्रं बालं मुकुन्दं मनसा स्मरामि ॥",
      iast: "lambālakaṁ lambita-hāra-yaṣṭiṁ śṛṅgāra-līlāṅkita-danta-paṅktim ।\nbimbādharaṁ cāru-viśāla-netraṁ bālaṁ mukundaṁ manasā smarāmi ॥",
      en: "His curls hanging loose, a long necklace swinging, his row of teeth marked by the play of love; his lip red as the bimba fruit, his eyes lovely and wide — the child Mukunda I call to mind.",
      tel: "వ్రేలాడు ముంగురులు గలవాడు, వ్రేలాడు హారము గలవాడు, శృంగారలీలచే గుర్తింపబడిన దంతపంక్తి గలవాడు; దొండపండువంటి పెదవి, సుందరమైన విశాలమైన కన్నులు గలవాడు — ఆ బాలముకుందుని మనసుతో స్మరించుచున్నాను.",
      hi: "लटकते अलक, झूलती हारयष्टि, शृङ्गार की लीला से अङ्कित दन्तपङ्क्ति; बिम्ब-सा अधर, चारु विशाल नेत्र — उस बाल मुकुन्द का मैं मन से स्मरण करता हूँ।" },
    { s: 0, n: "5",
      deva: "शिक्ये निधायाद्यपयोदधीनि बहिर्गतायां व्रजनायिकायाम् ।\nभुक्त्वा यथेष्टं कपटेन सुप्तं बालं मुकुन्दं मनसा स्मरामि ॥",
      iast: "śikye nidhāyādya-payo-dadhīni bahir-gatāyāṁ vraja-nāyikāyām ।\nbhuktvā yatheṣṭaṁ kapaṭena suptaṁ bālaṁ mukundaṁ manasā smarāmi ॥",
      en: "The mistress of Vraja had hung the day's milk and curds in the sling and gone out; he ate his fill and then lay there pretending to sleep — the child Mukunda I call to mind.",
      tel: "వ్రజనాయకి ఆ రోజు పాలను, పెరుగును ఉట్టిలో పెట్టి బయటికి వెళ్ళగా, ఇష్టము వచ్చినట్లు తిని, కపటముతో నిద్రించుచున్నట్లు పరుండిన — ఆ బాలముకుందుని మనసుతో స్మరించుచున్నాను.",
      hi: "व्रज की नायिका ने उस दिन का दूध और दही सींके में रखकर बाहर गयी, और उसने यथेष्ट खाकर कपट से सोने का बहाना किया — उस बाल मुकुन्द का मैं मन से स्मरण करता हूँ।" },
    { s: 0, n: "6",
      deva: "कलिन्दजान्तस्थितकालियस्य फणाग्ररङ्गे नटनप्रियन्तम् ।\nतत्पुच्छहस्तं च प्रदीपयन्तं बालं मुकुन्दं मनसा स्मरामि ॥",
      iast: "kalinda-jāntas-thita-kāliyasya phaṇāgra-raṅge naṭana-priyantam ।\ntat-puccha-hastaṁ ca pradīpayantaṁ bālaṁ mukundaṁ manasā smarāmi ॥",
      en: "On the stage of the hood-tips of Kāliya, who lay within the Yamunā, he loved to dance — holding that tail in his hand and making it blaze. The child Mukunda I call to mind.",
      tel: "యమునలో ఉన్న కాళియుని పడగల కొనలే రంగస్థలముగా నర్తించుట ఇష్టపడినవాడు — దాని తోకను చేతబట్టి ప్రకాశింపజేసినవాడు. ఆ బాలముకుందుని మనసుతో స్మరించుచున్నాను.",
      hi: "यमुना में स्थित कालिय के फणाग्रों के रङ्गमञ्च पर नृत्य करना जिसे प्रिय था — उसकी पूँछ हाथ में लेकर प्रदीप्त करते हुए। उस बाल मुकुन्द का मैं मन से स्मरण करता हूँ।" },
    { s: 0, n: "7",
      deva: "उलूखले बद्धमुदारशौर्यं उत्तुङ्गयुग्मार्जुनभङ्गलीलम् ।\nउत्फुल्लपद्मायतचारुनेत्रं बालं मुकुन्दं मनसा स्मरामि ॥",
      iast: "ulūkhale baddham-udāra-śauryaṁ uttuṅga-yugmārjuna-bhaṅga-līlam ।\nutphulla-padmāyata-cāru-netraṁ bālaṁ mukundaṁ manasā smarāmi ॥",
      en: "Tied to the mortar, his valour undiminished, whose play was the breaking of the two tall arjuna trees; his lovely eyes long as an open lotus — the child Mukunda I call to mind.",
      tel: "రోలుకు కట్టబడినవాడు, ఉదారమైన శౌర్యము గలవాడు, ఎత్తైన రెండు మద్ది చెట్లను విరుచుట లీలగా గలవాడు; వికసించిన కమలమువలె నిడుపైన సుందర నేత్రములు గలవాడు — ఆ బాలముకుందుని మనసుతో స్మరించుచున్నాను.",
      hi: "ऊखल में बँधे हुए, उदार शौर्य वाले, दो ऊँचे अर्जुन वृक्षों को भङ्ग करना जिसकी लीला थी; खिले कमल-से लम्बे चारु नेत्र वाले — उस बाल मुकुन्द का मैं मन से स्मरण करता हूँ।" },
    { s: 0, n: "8",
      deva: "आलोक्य मातुर्मुखमादरेण स्तन्यं पिबन्तं सरसीरुहाक्षम् ।\nसच्चिन्मयं देवमनन्तरूपं बालं मुकुन्दं मनसा स्मरामि ॥",
      iast: "ālokya mātur-mukham-ādareṇa stanyaṁ pibantaṁ sarasīruhākṣam ।\nsac-cin-mayaṁ devam-ananta-rūpaṁ bālaṁ mukundaṁ manasā smarāmi ॥",
      en: "Looking up at his mother's face with love as he drinks at her breast, his eyes lotuses; the god who is being and awareness, whose forms are endless — the child Mukunda I call to mind.",
      tel: "ఆదరముతో తల్లి ముఖమును చూచుచు స్తన్యమును త్రాగుచున్నవాడు, కమలనేత్రుడు; సచ్చిన్మయుడైన దేవుడు, అనంతరూపుడు — ఆ బాలముకుందుని మనసుతో స్మరించుచున్నాను.",
      hi: "आदर से माता का मुख देखते हुए स्तन्य पीते, सरसीरुह-से नेत्र वाले; सच्चिन्मय देव, अनन्तरूप — उस बाल मुकुन्द का मैं मन से स्मरण करता हूँ।" },
  ],
},];
