/* ============================================================
   STUTI — Śiva full texts, part 3
   Mahāmṛtyuñjaya Stotram · Candraśekharāṣṭakam
   · Umā Maheśvara Stotram
   Devanāgarī is the source of truth; other scripts are derived at
   read time. `tel` carries the Telugu meaning (అర్థం).
   ============================================================ */
export const extra = [{
  deities: ["shiva"],
  title: "Mahāmṛtyuñjaya Stotram",
  blurb: "Mārkaṇḍeya's hymn, said at the hour his life was due to end — nine names and one question repeated: what then can death do to us?",
  sections: [{ tel: "మృత్యుంజయ మంత్రం", roman: "The Mṛtyuñjaya Mantra" }, { tel: "స్తోత్రం", roman: "The Hymn" }, { tel: "ఫలశ్రుతి", roman: "The Fruit of Recitation" }],
  verses: [
    { s: 0, n: null,
      deva: "ॐ त्र्यम्बकं यजामहे सुगन्धिं पुष्टिवर्धनम् ।\nउर्वारुकमिव बन्धनान्मृत्योर्मुक्षीय मामृतात् ॥",
      iast: "oṁ tryambakaṁ yajāmahe sugandhiṁ puṣṭi-vardhanam ।\nurvārukam-iva bandhanān-mṛtyor-mukṣīya māmṛtāt ॥",
      en: "We worship the three-eyed one, fragrant, who increases well-being. As the cucumber is freed from its stalk, may I be freed from death — but not from immortality.",
      tel: "సుగంధుడు, పుష్టిని వృద్ధిచేయువాడు అయిన త్ర్యంబకుని ఆరాధించుచున్నాము. దోసపండు తీగనుండి విడివడినట్లు, నేను మృత్యువునుండి విడుదల పొందుదునుగాక — అమృతత్వమునుండి కాదు." },
    { s: 1, n: "1",
      deva: "रुद्रं पशुपतिं स्थाणुं नीलकण्ठमुमापतिम् ।\nनमामि शिरसा देवं किं नो मृत्युः करिष्यति ॥",
      iast: "rudraṁ paśupatiṁ sthāṇuṁ nīlakaṇṭham-umāpatim ।\nnamāmi śirasā devaṁ kiṁ no mṛtyuḥ kariṣyati ॥",
      en: "Rudra, lord of creatures, the unmoving pillar, the blue-throated, husband of Umā — I bow my head to that god. What then can death do to us?",
      tel: "రుద్రుడు, పశుపతి, స్థాణువు, నీలకంఠుడు, ఉమాపతి అయిన ఆ దేవునికి శిరస్సు వంచి నమస్కరించుచున్నాను. మృత్యువు మనలను ఏమి చేయగలదు?" },
    { s: 1, n: "2",
      deva: "कालकण्ठं कलामूर्तिं कालाग्निं कालनाशनम् ।\nनमामि शिरसा देवं किं नो मृत्युः करिष्यति ॥",
      iast: "kāla-kaṇṭhaṁ kalā-mūrtiṁ kālāgniṁ kāla-nāśanam ।\nnamāmi śirasā devaṁ kiṁ no mṛtyuḥ kariṣyati ॥",
      en: "The dark-throated, embodied in all the arts, the fire of time, the destroyer of time — I bow my head to that god. What then can death do to us?",
      tel: "కాలకంఠుడు, కళాస్వరూపుడు, కాలాగ్ని, కాలమునే నశింపజేయువాడు అయిన ఆ దేవునికి శిరస్సు వంచి నమస్కరించుచున్నాను. మృత్యువు మనలను ఏమి చేయగలదు?" },
    { s: 1, n: "3",
      deva: "नीलकण्ठं विरूपाक्षं निर्मलं निरुपद्रवम् ।\nनमामि शिरसा देवं किं नो मृत्युः करिष्यति ॥",
      iast: "nīlakaṇṭhaṁ virūpākṣaṁ nirmalaṁ nirupadravam ।\nnamāmi śirasā devaṁ kiṁ no mṛtyuḥ kariṣyati ॥",
      en: "The blue-throated, the odd-eyed, spotless and untroubled — I bow my head to that god. What then can death do to us?",
      tel: "నీలకంఠుడు, విరూపాక్షుడు, నిర్మలుడు, ఉపద్రవరహితుడు అయిన ఆ దేవునికి శిరస్సు వంచి నమస్కరించుచున్నాను. మృత్యువు మనలను ఏమి చేయగలదు?" },
    { s: 1, n: "4",
      deva: "वामदेवं महादेवं लोकनाथं जगद्गुरुम् ।\nनमामि शिरसा देवं किं नो मृत्युः करिष्यति ॥",
      iast: "vāmadevaṁ mahādevaṁ lokanāthaṁ jagad-gurum ।\nnamāmi śirasā devaṁ kiṁ no mṛtyuḥ kariṣyati ॥",
      en: "Vāmadeva, the great god, lord of the worlds, teacher of all that is — I bow my head to that god. What then can death do to us?",
      tel: "వామదేవుడు, మహాదేవుడు, లోకనాథుడు, జగద్గురువు అయిన ఆ దేవునికి శిరస్సు వంచి నమస్కరించుచున్నాను. మృత్యువు మనలను ఏమి చేయగలదు?" },
    { s: 1, n: "5",
      deva: "देवदेवं जगन्नाथं देवेशं वृषभध्वजम् ।\nनमामि शिरसा देवं किं नो मृत्युः करिष्यति ॥",
      iast: "deva-devaṁ jagan-nāthaṁ deveśaṁ vṛṣabha-dhvajam ।\nnamāmi śirasā devaṁ kiṁ no mṛtyuḥ kariṣyati ॥",
      en: "God of gods, lord of the world, ruler of the gods, whose banner bears the bull — I bow my head to that god. What then can death do to us?",
      tel: "దేవదేవుడు, జగన్నాథుడు, దేవేశుడు, వృషభధ్వజుడు అయిన ఆ దేవునికి శిరస్సు వంచి నమస్కరించుచున్నాను. మృత్యువు మనలను ఏమి చేయగలదు?" },
    { s: 1, n: "6",
      deva: "गङ्गाधरं महादेवं सर्वाभरणभूषितम् ।\nनमामि शिरसा देवं किं नो मृत्युः करिष्यति ॥",
      iast: "gaṅgādharaṁ mahādevaṁ sarvābharaṇa-bhūṣitam ।\nnamāmi śirasā devaṁ kiṁ no mṛtyuḥ kariṣyati ॥",
      en: "Bearer of the Gaṅgā, the great god, adorned with every ornament — I bow my head to that god. What then can death do to us?",
      tel: "గంగాధరుడు, మహాదేవుడు, సర్వాభరణ భూషితుడు అయిన ఆ దేవునికి శిరస్సు వంచి నమస్కరించుచున్నాను. మృత్యువు మనలను ఏమి చేయగలదు?" },
    { s: 1, n: "7",
      deva: "अनाथः परमानन्दं कैवल्यपदगामिनम् ।\nनमामि शिरसा देवं किं नो मृत्युः करिष्यति ॥",
      iast: "anāthaḥ paramānandaṁ kaivalya-pada-gāminam ।\nnamāmi śirasā devaṁ kiṁ no mṛtyuḥ kariṣyati ॥",
      en: "I who have no protector bow my head to the god who is supreme bliss, who leads to the state of aloneness. What then can death do to us?",
      tel: "అనాథుడనైన నేను — పరమానంద స్వరూపుడు, కైవల్యపదమునకు చేర్చువాడు అయిన ఆ దేవునికి శిరస్సు వంచి నమస్కరించుచున్నాను. మృత్యువు మనలను ఏమి చేయగలదు?" },
    { s: 1, n: "8",
      deva: "स्वर्गापवर्गदातारं सृष्टिस्थित्यन्तकारिणम् ।\nनमामि शिरसा देवं किं नो मृत्युः करिष्यति ॥",
      iast: "svargāpavarga-dātāraṁ sṛṣṭi-sthity-anta-kāriṇam ।\nnamāmi śirasā devaṁ kiṁ no mṛtyuḥ kariṣyati ॥",
      en: "Giver of heaven and of release, who makes creation, sustenance and the end — I bow my head to that god. What then can death do to us?",
      tel: "స్వర్గమును, మోక్షమును ఇచ్చువాడు; సృష్టి, స్థితి, లయములను చేయువాడు అయిన ఆ దేవునికి శిరస్సు వంచి నమస్కరించుచున్నాను. మృత్యువు మనలను ఏమి చేయగలదు?" },
    { s: 1, n: "9",
      deva: "उत्पत्तिस्थितिसंहारकर्तारमीश्वरं गुरुम् ।\nनमामि शिरसा देवं किं नो मृत्युः करिष्यति ॥",
      iast: "utpatti-sthiti-saṁhāra-kartāram-īśvaraṁ gurum ।\nnamāmi śirasā devaṁ kiṁ no mṛtyuḥ kariṣyati ॥",
      en: "Maker of arising, of standing and of dissolution, the Lord, the teacher — I bow my head to that god. What then can death do to us?",
      tel: "ఉత్పత్తి, స్థితి, సంహారములను చేయువాడు, ఈశ్వరుడు, గురువు అయిన ఆ దేవునికి శిరస్సు వంచి నమస్కరించుచున్నాను. మృత్యువు మనలను ఏమి చేయగలదు?" },
    { s: 2, n: "10",
      deva: "मार्कण्डेयकृतं स्तोत्रं यः पठेच्छिवसन्निधौ ।\nतस्य मृत्युभयं नास्ति नाग्निचौरभयं क्वचित् ॥",
      iast: "mārkaṇḍeya-kṛtaṁ stotraṁ yaḥ paṭhec-chiva-sannidhau ।\ntasya mṛtyu-bhayaṁ nāsti nāgni-caura-bhayaṁ kvacit ॥",
      en: "Whoever recites this hymn made by Mārkaṇḍeya in the presence of Śiva has no fear of death, and nowhere any fear of fire or of thieves.",
      tel: "మార్కండేయుడు రచించిన ఈ స్తోత్రమును శివసన్నిధిలో ఎవరు పఠించెదరో, వారికి మృత్యుభయము లేదు; అగ్ని, చోరుల భయము ఎచటను లేదు." },
    { s: 2, n: "11",
      deva: "शतावर्तं प्रकर्तव्यं सङ्कटे कष्टनाशनम् ।\nशुचिर्भूत्वा पठेत् स्तोत्रं सर्वसिद्धिप्रदायकम् ॥",
      iast: "śatāvartaṁ prakartavyaṁ saṅkaṭe kaṣṭa-nāśanam ।\nśucir-bhūtvā paṭhet stotraṁ sarva-siddhi-pradāyakam ॥",
      en: "In times of danger it should be done a hundred times over, for it destroys distress; purified first, one should recite this hymn, which grants every attainment.",
      tel: "సంకటకాలమునందు దీనిని నూరుసార్లు ఆవృత్తి చేయవలెను — అది కష్టములను నశింపజేయును; శుచియై, సర్వసిద్ధులనిచ్చే ఈ స్తోత్రమును పఠించవలెను." },
  ],
},

{
  deities: ["shiva"],
  title: "Candraśekharāṣṭakam",
  blurb: "Mārkaṇḍeya again, and the same defiance in a different metre — eight verses that each end by asking what Yama could possibly do.",
  sections: [{ tel: "ఆవాహనం", roman: "The Invocation" }, { tel: "స్తోత్రం", roman: "The Eight Verses" }, { tel: "ఫలశ్రుతి", roman: "The Fruit of Recitation" }],
  verses: [
    { s: 0, n: null,
      deva: "चन्द्रशेखर चन्द्रशेखर चन्द्रशेखर पाहि माम् ।\nचन्द्रशेखर चन्द्रशेखर चन्द्रशेखर रक्ष माम् ॥",
      iast: "candraśekhara candraśekhara candraśekhara pāhi mām ।\ncandraśekhara candraśekhara candraśekhara rakṣa mām ॥",
      en: "Moon-crested one, moon-crested one, moon-crested one — guard me. Moon-crested one, moon-crested one, moon-crested one — protect me.",
      tel: "చంద్రశేఖరా, చంద్రశేఖరా, చంద్రశేఖరా — నన్ను కాపాడుము. చంద్రశేఖరా, చంద్రశేఖరా, చంద్రశేఖరా — నన్ను రక్షింపుము." },
    { s: 1, n: "1",
      deva: "रत्नसानुशरासनं रजताद्रिशृङ्गनिकेतनं\nशिञ्जिनीकृतपन्नगेश्वरमच्युतानलसायकम् ।\nक्षिप्रदग्धपुरत्रयं त्रिदशालयैरभिवन्दितं\nचन्द्रशेखरमाश्रये मम किं करिष्यति वै यमः ॥",
      iast: "ratna-sānu-śarāsanaṁ rajatādri-śṛṅga-niketanaṁ\nśiñjinī-kṛta-pannageśvaram-acyutānala-sāyakam ।\nkṣipra-dagdha-pura-trayaṁ tridaśālayair-abhivanditaṁ\ncandraśekharam-āśraye mama kiṁ kariṣyati vai yamaḥ ॥",
      en: "His bow the jewelled mountain, his home the silver peak; the serpent king his bowstring, Viṣṇu his arrow and fire its point; who burned the Three Cities in an instant, and whom the dwellers of heaven salute — in the moon-crested one I take refuge. What indeed can Yama do to me?",
      tel: "రత్నపర్వతమే విల్లుగా, వెండికొండ శిఖరమే నివాసముగా కలవాడు; సర్పరాజునే వింటినారిగా, విష్ణువునే బాణముగా, అగ్నినేములుకుగా చేసినవాడు; క్షణములో త్రిపురములను దహించినవాడు, దేవతలచే వందించబడినవాడు — ఆ చంద్రశేఖరుని ఆశ్రయించుచున్నాను. యముడు నన్నేమి చేయగలడు?" },
    { s: 1, n: "2",
      deva: "पञ्चपादपपुष्पगन्धपदाम्बुजद्वयशोभितं\nभाललोचनजातपावकदग्धमन्मथविग्रहम् ।\nभस्मदिग्धकलेवरं भवनाशनं भवमव्ययं\nचन्द्रशेखरमाश्रये मम किं करिष्यति वै यमः ॥",
      iast: "pañca-pādapa-puṣpa-gandha-padāmbuja-dvaya-śobhitaṁ\nbhāla-locana-jāta-pāvaka-dagdha-manmatha-vigraham ।\nbhasma-digdha-kalevaraṁ bhava-nāśanaṁ bhavam-avyayaṁ\ncandraśekharam-āśraye mama kiṁ kariṣyati vai yamaḥ ॥",
      en: "His two lotus feet fragrant with the flowers of the five celestial trees; the fire born of his brow-eye burned the body of Kāma; his own body smeared with ash — the ender of worldly existence, existence itself, imperishable — in the moon-crested one I take refuge. What indeed can Yama do to me?",
      tel: "పంచ కల్పవృక్షముల పుష్పముల సుగంధముతో శోభించే పాదపద్మములు కలవాడు; ఫాలనేత్రమునుండి పుట్టిన అగ్నిచే మన్మథుని దేహమును దహించినవాడు; భస్మము పూసిన శరీరము కలవాడు, భవమును నశింపజేయువాడు, భవస్వరూపుడు, అవ్యయుడు — ఆ చంద్రశేఖరుని ఆశ్రయించుచున్నాను. యముడు నన్నేమి చేయగలడు?" },
    { s: 1, n: "3",
      deva: "मत्तवारणमुख्यचर्मकृतोत्तरीयमनोहरं\nपङ्कजासनपद्मलोचनपूजिताङ्घ्रिसरोरुहम् ।\nदेवसिन्धुतरङ्गसीकरसिक्तशुभ्रजटाधरं\nचन्द्रशेखरमाश्रये मम किं करिष्यति वै यमः ॥",
      iast: "matta-vāraṇa-mukhya-carma-kṛtottarīya-manoharaṁ\npaṅkajāsana-padma-locana-pūjitāṅghri-saroruham ।\ndeva-sindhu-taraṅga-sīkara-sikta-śubhra-jaṭādharaṁ\ncandraśekharam-āśraye mama kiṁ kariṣyati vai yamaḥ ॥",
      en: "Beautiful in an upper garment made of the hide of the great rutting elephant; his lotus feet worshipped by the lotus-seated Brahmā and the lotus-eyed Viṣṇu; wearing white matted locks wet with the spray of the celestial river's waves — in the moon-crested one I take refuge. What indeed can Yama do to me?",
      tel: "మదపుటేనుగు చర్మమును ఉత్తరీయముగా చేసుకొని మనోహరముగా ఉన్నవాడు; పద్మాసనుడైన బ్రహ్మ, పద్మలోచనుడైన విష్ణువు పూజించే పాదపద్మములు కలవాడు; దేవగంగ తరంగముల తుంపరలతో తడిసిన తెల్లని జటలు ధరించినవాడు — ఆ చంద్రశేఖరుని ఆశ్రయించుచున్నాను. యముడు నన్నేమి చేయగలడు?" },
    { s: 1, n: "4",
      deva: "कुण्डलीकृतकुण्डलेश्वरकुण्डलं वृषवाहनं\nनारदादिमुनीश्वरस्तुतवैभवं भुवनेश्वरम् ।\nअन्धकान्तकमाश्रितामरपादपं शमनान्तकं\nचन्द्रशेखरमाश्रये मम किं करिष्यति वै यमः ॥",
      iast: "kuṇḍalī-kṛta-kuṇḍaleśvara-kuṇḍalaṁ vṛṣa-vāhanaṁ\nnāradādi-munīśvara-stuta-vaibhavaṁ bhuvaneśvaram ।\nandhakāntakam-āśritāmara-pādapaṁ śamanāntakaṁ\ncandraśekharam-āśraye mama kiṁ kariṣyati vai yamaḥ ॥",
      en: "Whose earrings are the coiled king of serpents; borne by the bull; whose glory Nārada and the lords of sages praise; ruler of the worlds; slayer of Andhaka, a wish-granting tree to those who take shelter, the ender of the Restrainer — in the moon-crested one I take refuge. What indeed can Yama do to me?",
      tel: "చుట్టచుట్టుకొన్న సర్పరాజునే కుండలములుగా ధరించినవాడు, వృషభవాహనుడు; నారదాది మునీశ్వరులు స్తుతించే వైభవము కలవాడు, భువనేశ్వరుడు; అంధకాసురుని అంతమొందించినవాడు, ఆశ్రితులకు కల్పవృక్షము, యమునకే అంతకుడు — ఆ చంద్రశేఖరుని ఆశ్రయించుచున్నాను. యముడు నన్నేమి చేయగలడు?" },
    { s: 1, n: "5",
      deva: "यक्षराजसखं भगाक्षहरं भुजङ्गविभूषणं\nशैलराजसुतापरिष्कृतचारुवामकलेवरम् ।\nक्ष्वेडनीलगलं परश्वधधारिणं मृगधारिणं\nचन्द्रशेखरमाश्रये मम किं करिष्यति वै यमः ॥",
      iast: "yakṣa-rāja-sakhaṁ bhagākṣa-haraṁ bhujaṅga-vibhūṣaṇaṁ\nśaila-rāja-sutā-pariṣkṛta-cāru-vāma-kalevaram ।\nkṣveḍa-nīla-galaṁ paraśvadha-dhāriṇaṁ mṛga-dhāriṇaṁ\ncandraśekharam-āśraye mama kiṁ kariṣyati vai yamaḥ ॥",
      en: "Friend of the lord of yakṣas; who took the eye of Bhaga; adorned with serpents; the lovely left half of his body graced by the mountain king's daughter; his throat blue with poison, holding the axe and the deer — in the moon-crested one I take refuge. What indeed can Yama do to me?",
      tel: "యక్షరాజునకు మిత్రుడు, భగుని కన్నును హరించినవాడు, సర్పములే ఆభరణములుగా కలవాడు; పర్వతరాజ పుత్రికచే అలంకరించబడిన సుందర వామభాగము కలవాడు; విషముచే నల్లనైన కంఠము కలవాడు, పరశువును, మృగమును ధరించినవాడు — ఆ చంద్రశేఖరుని ఆశ్రయించుచున్నాను. యముడు నన్నేమి చేయగలడు?" },
    { s: 1, n: "6",
      deva: "भेषजं भवरोगिणामखिलापदामपहारिणं\nदक्षयज्ञविनाशिनं त्रिगुणात्मकं त्रिविलोचनम् ।\nभुक्तिमुक्तिफलप्रदं सकलाघसङ्घनिबर्हणं\nचन्द्रशेखरमाश्रये मम किं करिष्यति वै यमः ॥",
      iast: "bheṣajaṁ bhava-rogiṇām-akhilāpadām-apahāriṇaṁ\ndakṣa-yajña-vināśinaṁ tri-guṇātmakaṁ tri-vilocanam ।\nbhukti-mukti-phala-pradaṁ sakalāgha-saṅgha-nibarhaṇaṁ\ncandraśekharam-āśraye mama kiṁ kariṣyati vai yamaḥ ॥",
      en: "The medicine for those sick with worldly existence, the remover of every calamity; destroyer of Dakṣa's sacrifice, whose nature is the three guṇas, the three-eyed; giver of both enjoyment and release, who annihilates the whole mass of sin — in the moon-crested one I take refuge. What indeed can Yama do to me?",
      tel: "భవరోగులకు ఔషధము, సమస్త ఆపదలను తొలగించువాడు; దక్షయజ్ఞమును ధ్వంసము చేసినవాడు, త్రిగుణాత్మకుడు, త్రినేత్రుడు; భుక్తిని, ముక్తిని ఫలముగా ఇచ్చువాడు, సకల పాపరాశిని నశింపజేయువాడు — ఆ చంద్రశేఖరుని ఆశ్రయించుచున్నాను. యముడు నన్నేమి చేయగలడు?" },
    { s: 1, n: "7",
      deva: "भक्तवत्सलमर्चितं निधिमक्षयं हरिदम्बरं\nसर्वभूतपतिं परात्परमप्रमेयमनुत्तमम् ।\nसोमवारिनभोहुताशनसोमपानिलखाकृतिं\nचन्द्रशेखरमाश्रये मम किं करिष्यति वै यमः ॥",
      iast: "bhakta-vatsalam-arcitaṁ nidhim-akṣayaṁ haridambaraṁ\nsarva-bhūta-patiṁ parātparam-aprameyam-anuttamam ।\nsoma-vāri-nabho-hutāśana-soma-pānila-khākṛtiṁ\ncandraśekharam-āśraye mama kiṁ kariṣyati vai yamaḥ ॥",
      en: "Tender to devotees, worshipped, an inexhaustible treasure, clad in the quarters of the sky; lord of all beings, higher than the highest, immeasurable, unsurpassed; whose form is the moon and the waters, the sky, fire, the sacrificer, wind and space — in the moon-crested one I take refuge. What indeed can Yama do to me?",
      tel: "భక్తవత్సలుడు, అర్చించబడువాడు, అక్షయమైన నిధి, దిక్కులే వస్త్రముగా కలవాడు; సర్వభూతపతి, పరాత్పరుడు, అప్రమేయుడు, అనుత్తముడు; చంద్రుడు, జలము, ఆకాశము, అగ్ని, సోమపానము చేయువాడు, వాయువు, ఖము — ఇవి అన్నియు తన ఆకృతిగా కలవాడు — ఆ చంద్రశేఖరుని ఆశ్రయించుచున్నాను. యముడు నన్నేమి చేయగలడు?" },
    { s: 1, n: "8",
      deva: "विश्वसृष्टिविधायिनं पुनरेव पालनतत्परं\nसंहरन्तमपि प्रपञ्चमशेषलोकनिवासिनम् ।\nक्रीडयन्तमहर्निशं गणनाथयूथसमन्वितं\nचन्द्रशेखरमाश्रये मम किं करिष्यति वै यमः ॥",
      iast: "viśva-sṛṣṭi-vidhāyinaṁ punar-eva pālana-tatparaṁ\nsaṁharantam-api prapañcam-aśeṣa-loka-nivāsinam ।\nkrīḍayantam-ahar-niśaṁ gaṇa-nātha-yūtha-samanvitaṁ\ncandraśekharam-āśraye mama kiṁ kariṣyati vai yamaḥ ॥",
      en: "Who ordains the making of the universe, and again is intent on preserving it, and withdraws the whole spread of it too; who dwells in every world and plays day and night surrounded by the troops of his gaṇa lords — in the moon-crested one I take refuge. What indeed can Yama do to me?",
      tel: "విశ్వసృష్టిని విధించువాడు, మరల దానిని పాలించుటయందు నిమగ్నుడు, ప్రపంచమును సంహరించువాడు కూడ; సమస్త లోకములలో నివసించువాడు, గణనాథ సమూహములతో కూడి రేయింబవళ్ళు క్రీడించువాడు — ఆ చంద్రశేఖరుని ఆశ్రయించుచున్నాను. యముడు నన్నేమి చేయగలడు?" },
    { s: 2, n: null,
      deva: "मृत्युभीतमृकण्डुसूनुकृतस्तवं शिवसन्निधौ\nयत्र कुत्र च यः पठेन्न हि तस्य मृत्युभयं भवेत् ।\nपूर्णमायुररोगतामखिलार्थसम्पदमादरात्\nचन्द्रशेखर एव तस्य ददाति मुक्तिमयत्नतः ॥",
      iast: "mṛtyu-bhīta-mṛkaṇḍu-sūnu-kṛta-stavaṁ śiva-sannidhau\nyatra kutra ca yaḥ paṭhen-na hi tasya mṛtyu-bhayaṁ bhavet ।\npūrṇam-āyur-arogatām-akhilārtha-sampadam-ādarāt\ncandraśekhara eva tasya dadāti muktim-ayatnataḥ ॥",
      en: "Whoever recites this hymn — made by Mṛkaṇḍu's son in fear of death — in Śiva's presence, or anywhere at all, will have no fear of death. Candraśekhara himself gives him, and gladly, a full span of life, freedom from illness, every kind of wealth, and liberation without effort.",
      tel: "మృత్యుభయముతో మృకండు కుమారుడు రచించిన ఈ స్తవమును శివసన్నిధిలో గాని, ఎచ్చటనైనను గాని ఎవరు పఠించెదరో, వారికి మృత్యుభయము ఉండదు. పూర్ణాయువును, ఆరోగ్యమును, సమస్త అర్థసంపదలను ఆదరముతో ఇచ్చి, చంద్రశేఖరుడే వారికి ప్రయత్నము లేకుండ ముక్తిని ప్రసాదించును." },
  ],
},

{
  deities: ["shiva"],
  title: "Umā Maheśvara Stotram",
  blurb: "Twelve verses that never address one without the other — every salutation is dual, to Śaṅkara and Pārvatī together.",
  sections: [{ tel: "స్తోత్రం", roman: "The Twelve Verses" }, { tel: "ఫలశ్రుతి", roman: "The Fruit of Recitation" }],
  verses: [
    { s: 0, n: "1",
      deva: "नमः शिवाभ्यां नवयौवनाभ्यां\nपरस्पराश्लिष्टवपुर्धराभ्याम् ।\nनगेन्द्रकन्यावृषकेतनाभ्यां\nनमो नमः शङ्करपार्वतीभ्याम् ॥",
      iast: "namaḥ śivābhyāṁ nava-yauvanābhyāṁ\nparasparāśliṣṭa-vapur-dharābhyām ।\nnagendra-kanyā-vṛṣa-ketanābhyāṁ\nnamo namaḥ śaṅkara-pārvatībhyām ॥",
      en: "Salutations to the two who are auspicious, ever in fresh youth, whose bodies are held in each other's embrace; to the daughter of the mountain king and to him whose banner bears the bull — salutations again and again to Śaṅkara and Pārvatī.",
      tel: "మంగళస్వరూపులు, నవయౌవనులు, పరస్పరము ఆలింగనము చేసుకొనిన శరీరములు కలవారు; పర్వతరాజ పుత్రిక, వృషభధ్వజుడు — ఆ శంకర పార్వతులకు నమస్కారము, మరల మరల నమస్కారము." },
    { s: 0, n: "2",
      deva: "नमः शिवाभ्यां सरसोत्सवाभ्यां\nनमस्कृताभीष्टवरप्रदाभ्याम् ।\nनारायणेनार्चितपादुकाभ्यां\nनमो नमः शङ्करपार्वतीभ्याम् ॥",
      iast: "namaḥ śivābhyāṁ sarasotsavābhyāṁ\nnamaskṛtābhīṣṭa-vara-pradābhyām ।\nnārāyaṇenārcita-pādukābhyāṁ\nnamo namaḥ śaṅkara-pārvatībhyām ॥",
      en: "Salutations to the two who are auspicious, full of delight, who grant the boon desired by those who bow to them, whose sandals Nārāyaṇa himself worships — salutations again and again to Śaṅkara and Pārvatī.",
      tel: "మంగళస్వరూపులు, ఆనందోత్సవముతో ఉన్నవారు, నమస్కరించినవారికి కోరిన వరములనిచ్చువారు, నారాయణునిచే అర్చించబడిన పాదుకలు కలవారు — ఆ శంకర పార్వతులకు నమస్కారము, మరల మరల నమస్కారము." },
    { s: 0, n: "3",
      deva: "नमः शिवाभ्यां वृषवाहनाभ्यां\nविरिञ्चिविष्ण्विन्द्रसुपूजिताभ्याम् ।\nविभूतिपाटीरविलेपनाभ्यां\nनमो नमः शङ्करपार्वतीभ्याम् ॥",
      iast: "namaḥ śivābhyāṁ vṛṣa-vāhanābhyāṁ\nviriñci-viṣṇv-indra-supūjitābhyām ।\nvibhūti-pāṭīra-vilepanābhyāṁ\nnamo namaḥ śaṅkara-pārvatībhyām ॥",
      en: "Salutations to the two who are auspicious, borne by the bull, well worshipped by Brahmā, Viṣṇu and Indra, anointed with sacred ash and sandal — salutations again and again to Śaṅkara and Pārvatī.",
      tel: "మంగళస్వరూపులు, వృషభవాహనులు, బ్రహ్మ-విష్ణు-ఇంద్రులచే చక్కగా పూజించబడినవారు, విభూతి-చందనములతో లేపనము చేసుకొన్నవారు — ఆ శంకర పార్వతులకు నమస్కారము, మరల మరల నమస్కారము." },
    { s: 0, n: "4",
      deva: "नमः शिवाभ्यां जगदीश्वराभ्यां\nजगत्पतिभ्यां जयविग्रहाभ्याम् ।\nजम्भारिमुख्यैरभिवन्दिताभ्यां\nनमो नमः शङ्करपार्वतीभ्याम् ॥",
      iast: "namaḥ śivābhyāṁ jagad-īśvarābhyāṁ\njagat-patibhyāṁ jaya-vigrahābhyām ।\njambhāri-mukhyair-abhivanditābhyāṁ\nnamo namaḥ śaṅkara-pārvatībhyām ॥",
      en: "Salutations to the two who are auspicious, sovereigns of the world, its lord and lady, whose very forms are victory, saluted by Indra and the foremost of the gods — salutations again and again to Śaṅkara and Pārvatī.",
      tel: "మంగళస్వరూపులు, జగదీశ్వరులు, జగత్పతులు, జయస్వరూప విగ్రహములు కలవారు, ఇంద్రాది ప్రముఖులచే అభివందించబడినవారు — ఆ శంకర పార్వతులకు నమస్కారము, మరల మరల నమస్కారము." },
    { s: 0, n: "5",
      deva: "नमः शिवाभ्यां परमौषधाभ्यां\nपञ्चाक्षरीपञ्जररञ्जिताभ्याम् ।\nप्रपञ्चसृष्टिस्थितिसंहृताभ्यां\nनमो नमः शङ्करपार्वतीभ्याम् ॥",
      iast: "namaḥ śivābhyāṁ paramauṣadhābhyāṁ\npañcākṣarī-pañjara-rañjitābhyām ।\nprapañca-sṛṣṭi-sthiti-saṁhṛtābhyāṁ\nnamo namaḥ śaṅkara-pārvatībhyām ॥",
      en: "Salutations to the two who are auspicious, the supreme medicine, delighting within the cage of the five-syllabled mantra, who make, hold and withdraw the whole spread of the world — salutations again and again to Śaṅkara and Pārvatī.",
      tel: "మంగళస్వరూపులు, పరమౌషధము వంటివారు, పంచాక్షరీ మంత్రమనే పంజరమునందు రంజిల్లువారు, ప్రపంచ సృష్టి-స్థితి-సంహారములను చేయువారు — ఆ శంకర పార్వతులకు నమస్కారము, మరల మరల నమస్కారము." },
    { s: 0, n: "6",
      deva: "नमः शिवाभ्यामतिसुन्दराभ्याम्\nअत्यन्तमासक्तहृदम्बुजाभ्याम् ।\nअशेषलोकैकहितङ्कराभ्यां\nनमो नमः शङ्करपार्वतीभ्याम् ॥",
      iast: "namaḥ śivābhyām-ati-sundarābhyām\natyantam-āsakta-hṛd-ambujābhyām ।\naśeṣa-lokaika-hitaṅkarābhyāṁ\nnamo namaḥ śaṅkara-pārvatībhyām ॥",
      en: "Salutations to the two who are auspicious, exceedingly beautiful, their lotus hearts wholly given to one another, the sole benefactors of all the worlds — salutations again and again to Śaṅkara and Pārvatī.",
      tel: "మంగళస్వరూపులు, అతిసుందరులు, ఒకరియందు ఒకరు పూర్ణముగా అనురక్తమైన హృదయపద్మములు కలవారు, సమస్త లోకములకు ఏకైక హితకారులు — ఆ శంకర పార్వతులకు నమస్కారము, మరల మరల నమస్కారము." },
    { s: 0, n: "7",
      deva: "नमः शिवाभ्यां कलिनाशनाभ्यां\nकङ्कालकल्याणवपुर्धराभ्याम् ।\nकैलासशैलस्थितदेवताभ्यां\nनमो नमः शङ्करपार्वतीभ्याम् ॥",
      iast: "namaḥ śivābhyāṁ kali-nāśanābhyāṁ\nkaṅkāla-kalyāṇa-vapur-dharābhyām ।\nkailāsa-śaila-sthita-devatābhyāṁ\nnamo namaḥ śaṅkara-pārvatībhyām ॥",
      en: "Salutations to the two who are auspicious, destroyers of the age of strife, bearing forms both gaunt with bone and radiant with beauty, the deities who abide on Mount Kailāsa — salutations again and again to Śaṅkara and Pārvatī.",
      tel: "మంగళస్వరూపులు, కలిదోషమును నశింపజేయువారు, కంకాళరూపమును, కల్యాణమూర్తిని ధరించినవారు, కైలాస పర్వతమునందు నివసించే దేవతలు — ఆ శంకర పార్వతులకు నమస్కారము, మరల మరల నమస్కారము." },
    { s: 0, n: "8",
      deva: "नमः शिवाभ्यामशुभापहाभ्याम्\nअशेषलोकैकविशेषिताभ्याम् ।\nअकुण्ठिताभ्यां स्मृतिसम्भृताभ्यां\nनमो नमः शङ्करपार्वतीभ्याम् ॥",
      iast: "namaḥ śivābhyām-aśubhāpahābhyām\naśeṣa-lokaika-viśeṣitābhyām ।\nakuṇṭhitābhyāṁ smṛti-sambhṛtābhyāṁ\nnamo namaḥ śaṅkara-pārvatībhyām ॥",
      en: "Salutations to the two who are auspicious, who take away all that is inauspicious, distinguished above every world, undulled and unhindered, held fast in remembrance — salutations again and again to Śaṅkara and Pārvatī.",
      tel: "మంగళస్వరూపులు, అశుభములను తొలగించువారు, సమస్త లోకములలో విశిష్టులు, ఎన్నడును కుంఠితము కానివారు, స్మృతియందు నిలిచియుండువారు — ఆ శంకర పార్వతులకు నమస్కారము, మరల మరల నమస్కారము." },
    { s: 0, n: "9",
      deva: "नमः शिवाभ्यां रथवाहनाभ्यां\nरवीन्दुवैश्वानरलोचनाभ्याम् ।\nराकाशशाङ्काभमुखाम्बुजाभ्यां\nनमो नमः शङ्करपार्वतीभ्याम् ॥",
      iast: "namaḥ śivābhyāṁ ratha-vāhanābhyāṁ\nravīndu-vaiśvānara-locanābhyām ।\nrākā-śaśāṅkābha-mukhāmbujābhyāṁ\nnamo namaḥ śaṅkara-pārvatībhyām ॥",
      en: "Salutations to the two who are auspicious, who ride the chariot, whose eyes are the sun, the moon and fire, whose lotus faces shine like the full moon — salutations again and again to Śaṅkara and Pārvatī.",
      tel: "మంగళస్వరూపులు, రథవాహనులు, సూర్య-చంద్ర-అగ్నులే నేత్రములుగా కలవారు, పున్నమి చంద్రుని వంటి ముఖపద్మములు కలవారు — ఆ శంకర పార్వతులకు నమస్కారము, మరల మరల నమస్కారము." },
    { s: 0, n: "10",
      deva: "नमः शिवाभ्यां जटिलन्धराभ्यां\nजरामृतिभ्यां च विवर्जिताभ्याम् ।\nजनार्दनाब्जोद्भवपूजिताभ्यां\nनमो नमः शङ्करपार्वतीभ्याम् ॥",
      iast: "namaḥ śivābhyāṁ jaṭilan-dharābhyāṁ\njarā-mṛtibhyāṁ ca vivarjitābhyām ।\njanārdanābjodbhava-pūjitābhyāṁ\nnamo namaḥ śaṅkara-pārvatībhyām ॥",
      en: "Salutations to the two who are auspicious, wearing matted locks, untouched by age and by death, worshipped by Viṣṇu and by the lotus-born Brahmā — salutations again and again to Śaṅkara and Pārvatī.",
      tel: "మంగళస్వరూపులు, జటాజూటమును ధరించినవారు, ముసలితనము-మరణము లేనివారు, జనార్దనునిచేత, పద్మసంభవుడైన బ్రహ్మచేత పూజించబడినవారు — ఆ శంకర పార్వతులకు నమస్కారము, మరల మరల నమస్కారము." },
    { s: 0, n: "11",
      deva: "नमः शिवाभ्यां विषमेक्षणाभ्यां\nबिल्वच्छदामल्लिकदामभृद्भ्याम् ।\nशोभावतीशान्तवतीश्वराभ्यां\nनमो नमः शङ्करपार्वतीभ्याम् ॥",
      iast: "namaḥ śivābhyāṁ viṣamekṣaṇābhyāṁ\nbilva-cchadā-mallika-dāma-bhṛdbhyām ।\nśobhāvatī-śāntavatīśvarābhyāṁ\nnamo namaḥ śaṅkara-pārvatībhyām ॥",
      en: "Salutations to the two who are auspicious, of uneven eyes, wearing garlands of bilva leaves and jasmine, lord and lady of splendour and of peace — salutations again and again to Śaṅkara and Pārvatī.",
      tel: "మంగళస్వరూపులు, బేసి కన్నులు కలవారు, బిల్వదళముల మాలను, మల్లెల మాలను ధరించినవారు, శోభకు-శాంతికి అధిపతులు — ఆ శంకర పార్వతులకు నమస్కారము, మరల మరల నమస్కారము." },
    { s: 0, n: "12",
      deva: "नमः शिवाभ्यां पशुपालकाभ्यां\nजगत्रयीरक्षणबद्धहृद्भ्याम् ।\nसमस्तदेवासुरपूजिताभ्यां\nनमो नमः शङ्करपार्वतीभ्याम् ॥",
      iast: "namaḥ śivābhyāṁ paśu-pālakābhyāṁ\njagat-trayī-rakṣaṇa-baddha-hṛdbhyām ।\nsamasta-devāsura-pūjitābhyāṁ\nnamo namaḥ śaṅkara-pārvatībhyām ॥",
      en: "Salutations to the two who are auspicious, herders of all creatures, their hearts bound to the protection of the three worlds, worshipped by all the gods and the asuras — salutations again and again to Śaṅkara and Pārvatī.",
      tel: "మంగళస్వరూపులు, పశువులను (జీవులను) పాలించువారు, ముల్లోకముల రక్షణయందు బంధించబడిన హృదయములు కలవారు, సమస్త దేవతలచేత, అసురులచేత పూజించబడినవారు — ఆ శంకర పార్వతులకు నమస్కారము, మరల మరల నమస్కారము." },
    { s: 1, n: null,
      deva: "स्तोत्रं त्रिसन्ध्यं शिवपार्वतीभ्यां\nभक्त्या पठेद् द्वादशकं नरो यः ।\nस सर्वसौभाग्यफलानि भुङ्क्ते\nशतायुरान्ते शिवलोकमेति ॥",
      iast: "stotraṁ tri-sandhyaṁ śiva-pārvatībhyāṁ\nbhaktyā paṭhed dvādaśakaṁ naro yaḥ ।\nsa sarva-saubhāgya-phalāni bhuṅkte\nśatāyur-ante śivalokam-eti ॥",
      en: "Whoever recites these twelve verses to Śiva and Pārvatī with devotion at the three junctures of the day enjoys every fruit of good fortune, lives a hundred years, and at the end goes to the world of Śiva.",
      tel: "శివపార్వతులకు అర్పితమైన ఈ ద్వాదశ శ్లోకముల స్తోత్రమును త్రిసంధ్యలయందు భక్తితో ఎవరు పఠించెదరో, వారు సమస్త సౌభాగ్య ఫలములను అనుభవించి, నూరేండ్లు జీవించి, అంతమున శివలోకమును చేరుదురు." },
  ],
},];
