/* ============================================================
   STUTI — Pitṛ Tarpaṇa Vidhiḥ
   The recitation scroll for the tarpaṇam, keyed from the Telugu
   paddhati sheet of Rajasekharuni Vijay Śarma and kept whole: one
   household's prayoga, given as an example of a procedure and not
   as a ruling on one. The rite's card (STUTI_TARPANA) carries the
   same material as guidance; this file is the text to read FROM
   while the water is being offered, so the order is the order of
   performance and nothing is abridged.
   Two blanks run through the tarpaṇa section: the first takes the
   gotra, the second the name. The ending śarmaṇaṁ is the brāhmaṇa
   form — varmaṇaṁ, guptaṁ and dāsaṁ stand in their place for the
   other varṇas, as the section's own note says.
   ============================================================ */
(window.STUTI_TEXTS_EXTRA = window.STUTI_TEXTS_EXTRA || []).push(

{
  deities: ["pitr"],
  occasions: "tarpana",
  title: "Pitṛ Tarpaṇa Vidhiḥ",
  blurb: "A rite, not a hymn. It is meant to be read from while it is performed. First ācamanam and the preliminaries. Then the saṅkalpa that the day calls for. Then the sacred thread is turned to the right shoulder. Water is then offered to thirty-three: father and mother, their parents and grandparents, wife, son, daughter, brother, sister, teacher, and others. Each receives three double-handfuls of sesame water, poured over the base of the right thumb.",
  about: "Transcribed in full from the Telugu Pitṛ Tarpaṇam sheet of Rajasekharuni Vijay Śarma. Tarpaṇa procedure differs by śākhā and by family. The order of the recipients, the tīrtha, the position of the yajñopavītam, the number of añjalis, and the use of sesame on a given weekday are all settled by one's own prayoga. This is one household's paddhati, kept whole. It may be followed as it stands, or compared with your own. Where your elders differ, they decide.",
  sections: [
    { roman: "Ācamanam & the preliminaries", tel: "ఆచమనం, పూర్వాంగం" },
    { roman: "Saṅkalpam — one for each occasion", tel: "సంకల్పం — సందర్భాన్ని బట్టి" },
    { roman: "Prācīnāvīti & āvāhanam", tel: "ప్రాచీనావీతి, ఆవాహనం" },
    { roman: "Tarpaṇam — the thirty-three", tel: "తర్పణం — ముప్పై మూడు" },
    { roman: "Samāpanam", tel: "సమాపనం" }
  ],
  verses: [
    { s: 0, n: "1",
      deva: "ॐ केशवाय स्वाहा ।\nॐ नारायणाय स्वाहा ।\nॐ माधवाय स्वाहा ॥",
      iast: "oṁ keśavāya svāhā |\noṁ nārāyaṇāya svāhā |\noṁ mādhavāya svāhā ||",
      en: "Three sips of water, one at each name.",
      tel: "మూడు నామాలతో మూడుసార్లు జలపానం చేయాలి." },
    { s: 0, n: "2",
      deva: "ॐ गोविन्दाय नमः । विष्णवे नमः । मधुसूदनाय नमः । त्रिविक्रमाय नमः ।\nवामनाय नमः । श्रीधराय नमः । हृषीकेशाय नमः । पद्मनाभाय नमः ।\nदामोदराय नमः । सङ्कर्षणाय नमः । वासुदेवाय नमः । प्रद्युम्नाय नमः ॥",
      iast: "oṁ govindāya namaḥ | viṣṇave namaḥ | madhusūdanāya namaḥ | trivikramāya namaḥ |\nvāmanāya namaḥ | śrīdharāya namaḥ | hṛṣīkeśāya namaḥ | padmanābhāya namaḥ |\ndāmodarāya namaḥ | saṅkarṣaṇāya namaḥ | vāsudevāya namaḥ | pradyumnāya namaḥ ||",
      en: "Say the names in order, with the hand at the appointed places.",
      tel: "నామాలను చెబుతూ, నియమిత స్థానాలలో హస్తాన్ని ఉంచాలి." },
    { s: 0, n: "3",
      deva: "अनिरुद्धाय नमः । पुरुषोत्तमाय नमः । अधोक्षजाय नमः । नारसिंहाय नमः ।\nअच्युताय नमः । जनार्दनाय नमः । उपेन्द्राय नमः । हरये नमः ।\nश्रीकृष्णाय नमः ॥",
      iast: "aniruddhāya namaḥ | puruṣottamāya namaḥ | adhokṣajāya namaḥ | nārasiṁhāya namaḥ |\nacyutāya namaḥ | janārdanāya namaḥ | upendrāya namaḥ | haraye namaḥ |\nśrīkṛṣṇāya namaḥ ||",
      en: "The twenty-four names are complete.",
      tel: "ఇరవై నాలుగు నామాలు పూర్తి అయినవి." },
    { s: 0, n: "4",
      deva: "ॐ पवित्रे वन्तः परिवाजपत्नी आ वामगन्म सुमतिं ततो न ।\nआ वां सीदन्तु द्रविणस्य भूरे तत्र मा शक्ती ॥",
      iast: "oṁ pavitre vantaḥ parivājapatnī ā vāmaganma sumatiṁ tato na |\nā vāṁ sīdantu draviṇasya bhūre tatra mā śaktī ||",
      en: "Wear the darbha pavitram on the ring finger. Those who have received the mantra recite it. The rest wear it silently. Then do ācamana once again.",
      tel: "ఉంగరపు వేలికి దర్భ పవిత్రమును ధరించాలి. మంత్రం వచ్చినవారు దీనిని చదవాలి. మిగిలినవారు మౌనంగా ధరించాలి. తరువాత మరల ఆచమనం చేయాలి." },
    { s: 0, n: "5",
      deva: "उत्तिष्ठन्तु भूत पिशाचाः ये ते भूमि भारकाः ।\nयेतेषामविरोधेन ब्रह्म कर्म समारभे ॥",
      iast: "uttiṣṭhantu bhūta piśācāḥ ye te bhūmi bhārakāḥ |\nyeteṣāmavirodhena brahma karma samārabhe ||",
      en: "Let the spirits and piśācas that burden the earth rise and go. Unopposed by them, I begin this brahma-karma. Sprinkle water behind you as it is said.",
      tel: "భూమికి భారమైన భూతపిశాచాలు లేచి వెళ్ళుగాక. వారి విరోధం లేకుండా ఈ బ్రహ్మకర్మను ఆరంభిస్తున్నాను. ఇది చెబుతూ అక్షతలతో కూడిన నీటిని వెనుకకు చల్లాలి." },
    { s: 0, n: "6",
      deva: "ॐ भूः । ॐ भुवः । ॐ सुवः । ॐ महः । ॐ जनः । ॐ तपः । ॐ सत्यम् ।\nॐ तत्सवितुर्वरेण्यं भर्गो देवस्य धीमहि धियो यो नः प्रचोदयात् ।\nॐ आपोज्योतीरसोऽमृतं ब्रह्म भूर्भुवस्सुवरोम् ॥",
      iast: "oṁ bhūḥ | oṁ bhuvaḥ | oṁ suvaḥ | oṁ mahaḥ | oṁ janaḥ | oṁ tapaḥ | oṁ satyam |\noṁ tatsaviturvareṇyaṁ bhargo devasya dhīmahi dhiyo yo naḥ pracodayāt |\noṁ āpojyotīraso'mṛtaṁ brahma bhūrbhuvassuvarom ||",
      en: "Prāṇāyāma. Recite it within, not aloud.",
      tel: "ప్రాణాయామం. మనసులో జపించాలి, పైకి కాదు." },

    { s: 1, n: "7",
      deva: "मम उपात्त समस्त दुरितक्षयद्वारा श्री परमेश्वर प्रीत्यर्थं\nशुभे शोभने मुहूर्ते … संवत्सरे … अयने … ऋतौ … मासे … पक्षे … तिथौ …\n… गोत्रः … शर्मा अहं ॥",
      iast: "mama upātta samasta duritakṣayadvārā śrī parameśvara prītyarthaṁ\nśubhe śobhane muhūrte … saṁvatsare … ayane … ṛtau … māse … pakṣe … tithau …\n… gotraḥ … śarmā ahaṁ ||",
      en: "This is the frame of every saṅkalpa. It states the place and the hour, then your own gotra and name. Then add the one that the day calls for, from the six below.",
      tel: "ఇది ప్రతి సంకల్పపు చట్రం. దేశకాలాలను, తరువాత మీ గోత్రనామాలను చెప్పాలి. తరువాత ఆ రోజుకి తగినదానిని కింది ఆరింటి నుండి చేర్చాలి." },
    { s: 1, n: "8",
      deva: "अस्मत् पितॄणां अक्षय पुण्यलोकावाप्त्यर्थं नित्यश्राद्ध प्रतिनिधि सद्यः\nनित्य पितृ तर्पणं करिष्ये ॥",
      iast: "asmat pitṝṇāṁ akṣaya puṇyalokāvāptyarthaṁ nitya-śrāddha pratinidhi sadyaḥ\nnitya pitṛ tarpaṇaṁ kariṣye ||",
      en: "For the daily tarpaṇam.",
      tel: "నిత్య తర్పణానికి." },
    { s: 1, n: "9",
      deva: "अस्मत् पितॄणां अक्षय पुण्यलोका वाप्त्यर्थं दर्श श्राद्ध प्रतिनिधि सद्यः\nतिल तर्पणं करिष्ये ॥",
      iast: "asmat pitṝṇāṁ akṣaya puṇyalokā vāptyarthaṁ darśa śrāddha pratinidhi sadyaḥ\ntila tarpaṇaṁ kariṣye ||",
      en: "On the amāvāsyā.",
      tel: "అమావాస్య నాడు." },
    { s: 1, n: "10",
      deva: "राहुग्रस्त सोमोपराग समये (केतुग्रस्त सूर्योपराग समये)\nअस्मत् पितॄणां अक्षय पुण्यलोका वाप्त्यर्थं ग्रहण श्राद्ध प्रतिनिधि सद्यः\nतिल तर्पणं करिष्ये ॥",
      iast: "rāhugrasta somoparāga samaye (ketugrasta sūryoparāga samaye)\nasmat pitṝṇāṁ akṣaya puṇyalokā vāptyarthaṁ grahaṇa śrāddha pratinidhi sadyaḥ\ntila tarpaṇaṁ kariṣye ||",
      en: "At an eclipse. The first phrase is for a lunar eclipse, the phrase in brackets for a solar one.",
      tel: "గ్రహణ సమయములో. మొదటి పదం చంద్రగ్రహణానికి, కుండలీకరణములోనిది సూర్యగ్రహణానికి." },
    { s: 1, n: "11",
      deva: "मकर सङ्क्रमण प्रयुक्त उत्तरायण महापर्व पुण्यकाले\n(कर्काटक सङ्क्रमण प्रयुक्त दक्षिणायन महापर्व पुण्यकाले)\nअस्मत् पितॄणां अक्षय पुण्यलोका वाप्त्यर्थं सङ्क्रमण श्राद्ध प्रतिनिधि सद्यः\nतिल तर्पणं करिष्ये ॥",
      iast: "makara saṅkramaṇa prayukta uttarāyaṇa mahāparva puṇyakāle\n(karkāṭaka saṅkramaṇa prayukta dakṣiṇāyana mahāparva puṇyakāle)\nasmat pitṝṇāṁ akṣaya puṇyalokā vāptyarthaṁ saṅkramaṇa śrāddha pratinidhi sadyaḥ\ntila tarpaṇaṁ kariṣye ||",
      en: "At a saṅkramaṇa. Name the ingress that has occurred.",
      tel: "సంక్రమణములకు. జరిగిన సంక్రమణాన్ని పేర్కొనాలి." },
    { s: 1, n: "12",
      deva: "पितॄणां मातामहादीनां सर्वेषां कारुण्यानाञ्च अक्षय पुण्यलोका वाप्त्यर्थं\nकन्यागते सवितरि आपाद्यादि पञ्चमासपक्षे कर्तव्य सकृन्महालयाख्यान्न\nश्राद्ध प्रतिनिधि सद्यः तिल तर्पणं करिष्ये ॥",
      iast: "pitṝṇāṁ mātāmahādīnāṁ sarveṣāṁ kāruṇyānāñca akṣaya puṇyalokā vāptyarthaṁ\nkanyāgate savitari āpādyādi pañcamāsapakṣe kartavya sakṛn-mahālayākhyānna\nśrāddha pratinidhi sadyaḥ tila tarpaṇaṁ kariṣye ||",
      en: "In the mahālaya pakṣa.",
      tel: "మహాలయ పక్షములో." },
    { s: 1, n: "13",
      deva: "पितॄणां मातामहादीनां सर्वेषां कारुण्यानाञ्च अक्षय पुण्यलोका वाप्त्यर्थं\nकन्यागते देवगुरौ सार्ध त्रिकोटि तीर्थ सहित कृष्णवेणी पुष्कर प्रयुक्त\nतीर्थाभ्यां श्राद्ध प्रतिनिधि सद्यः तिल तर्पणं करिष्ये ॥",
      iast: "pitṝṇāṁ mātāmahādīnāṁ sarveṣāṁ kāruṇyānāñca akṣaya puṇyalokā vāptyarthaṁ\nkanyāgate devagurau sārdha trikoṭi tīrtha sahita kṛṣṇaveṇī puṣkara prayukta\ntīrthābhyāṁ śrāddha pratinidhi sadyaḥ tila tarpaṇaṁ kariṣye ||",
      en: "At a puṣkaram. Name the river whose puṣkaram is running.",
      tel: "పుష్కర సమయములలో. పుష్కరం జరుగుతున్న నదిని పేర్కొనాలి." },

    { s: 2, n: "14",
      deva: "प्राचीनावीति ॥",
      iast: "prācīnāvīti ||",
      en: "Move the yajñopavītam from the left shoulder to the right. Spread three darbhas with their points to the east. Spread two more across them, pointing south. The pitṛ-devatās are invoked upon these. Face south, with the left knee on the ground.",
      tel: "యజ్ఞోపవీతమును ఎడమ నుండి కుడి భుజము పైకి మార్చుకోవాలి. తూర్పు కొసలుగా మూడు దర్భలు పరచాలి. వాటిపై దక్షిణ కొసలుగా రెండు కూర్చులు పరచాలి. వాటిపై పితృదేవతలను ఆవాహన చేయాలి. దక్షిణముఖముగా కూర్చుని, ఎడమ మోకాలు నేలపై ఉంచాలి." },
    { s: 2, n: "15",
      deva: "ॐ आगच्छन्तु मे पितर इमं गृह्णन्तु जलाञ्जलिम् ॥",
      iast: "oṁ āgacchantu me pitara imaṁ gṛhṇantu jalāñjalim ||",
      en: "Let my forefathers come, and receive this handful of water. Place sesame as it is said.",
      tel: "నా పితరులు రావలెను, ఈ జలాంజలిని స్వీకరించవలెను. చెబుతూ తిలలు వేయాలి." },

    { s: 3, n: "16",
      deva: "अस्मत् पितरं … गोत्रं … शर्मणं वसुरूपं स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat pitaraṁ … gotraṁ … śarmaṇaṁ vasurūpaṁ svadhā namas tarpayāmi ||3||",
      en: "My father, of such a gotra, of such a name, in the form of a Vasu.",
      tel: "నా తండ్రి — వసురూపుడు." },
    { s: 3, n: "17",
      deva: "अस्मत् पितामहं … गोत्रं … शर्मणं रुद्ररूपं स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat pitāmahaṁ … gotraṁ … śarmaṇaṁ rudrarūpaṁ svadhā namas tarpayāmi ||3||",
      en: "My father's father, in the form of a Rudra.",
      tel: "తాత — రుద్రరూపుడు." },
    { s: 3, n: "18",
      deva: "अस्मत् प्रपितामहं … गोत्रं … शर्मणं आदित्यरूपं स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat prapitāmahaṁ … gotraṁ … śarmaṇaṁ ādityarūpaṁ svadhā namas tarpayāmi ||3||",
      en: "My great-grandfather, in the form of an Āditya.",
      tel: "ముత్తాత — ఆదిత్యరూపుడు." },
    { s: 3, n: "19",
      deva: "अस्मत् मातरं … गोत्रां … पदां वसुरूपां स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat mātaraṁ … gotrāṁ … padāṁ vasurūpāṁ svadhā namas tarpayāmi ||3||",
      en: "My mother, in the form of a Vasu.",
      tel: "తల్లి — వసురూప." },
    { s: 3, n: "20",
      deva: "अस्मत् पितामहीं … गोत्रां … पदां रुद्ररूपां स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat pitāmahīṁ … gotrāṁ … padāṁ rudrarūpāṁ svadhā namas tarpayāmi ||3||",
      en: "My father's mother, in the form of a Rudra.",
      tel: "నాయనమ్మ — రుద్రరూప." },
    { s: 3, n: "21",
      deva: "अस्मत् प्रपितामहीं … गोत्रां … पदां आदित्यरूपां स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat prapitāmahīṁ … gotrāṁ … padāṁ ādityarūpāṁ svadhā namas tarpayāmi ||3||",
      en: "My father's grandmother, in the form of an Āditya.",
      tel: "ముత్తమ్మ — ఆదిత్యరూప." },
    { s: 3, n: "22",
      deva: "अस्मत् सपत्न मातरं … गोत्रां … पदां वसुरूपां स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat sapatna mātaraṁ … gotrāṁ … padāṁ vasurūpāṁ svadhā namas tarpayāmi ||3||",
      en: "My step-mother, in the form of a Vasu.",
      tel: "సవతి తల్లి — వసురూప." },
    { s: 3, n: "23",
      deva: "अस्मत् मातामहं … गोत्रं … शर्मणं वसुरूपं स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat mātāmahaṁ … gotraṁ … śarmaṇaṁ vasurūpaṁ svadhā namas tarpayāmi ||3||",
      en: "My mother's father, in the form of a Vasu.",
      tel: "తల్లి తండ్రి — వసురూపుడు." },
    { s: 3, n: "24",
      deva: "अस्मत् मातुः पितामहं … गोत्रं … शर्मणं रुद्ररूपं स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat mātuḥ pitāmahaṁ … gotraṁ … śarmaṇaṁ rudrarūpaṁ svadhā namas tarpayāmi ||3||",
      en: "My mother's grandfather, in the form of a Rudra.",
      tel: "తల్లి తాత — రుద్రరూపుడు." },
    { s: 3, n: "25",
      deva: "अस्मत् मातुः प्रपितामहं … गोत्रं … शर्मणं आदित्यरूपं स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat mātuḥ prapitāmahaṁ … gotraṁ … śarmaṇaṁ ādityarūpaṁ svadhā namas tarpayāmi ||3||",
      en: "My mother's great-grandfather, in the form of an Āditya.",
      tel: "తల్లి ముత్తాత — ఆదిత్యరూపుడు." },
    { s: 3, n: "26",
      deva: "अस्मत् मातामहीं … गोत्रां … पदां वसुरूपां स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat mātāmahīṁ … gotrāṁ … padāṁ vasurūpāṁ svadhā namas tarpayāmi ||3||",
      en: "My mother's mother, in the form of a Vasu.",
      tel: "అమ్మమ్మ — వసురూప." },
    { s: 3, n: "27",
      deva: "अस्मत् मातुः पितामहीं … गोत्रां … पदां रुद्ररूपां स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat mātuḥ pitāmahīṁ … gotrāṁ … padāṁ rudrarūpāṁ svadhā namas tarpayāmi ||3||",
      en: "My mother's grandmother, in the form of a Rudra.",
      tel: "తల్లికి నానమ్మ — రుద్రరూప." },
    { s: 3, n: "28",
      deva: "अस्मत् मातुः प्रपितामहीं … गोत्रां … पदां आदित्यरूपां स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat mātuḥ prapitāmahīṁ … gotrāṁ … padāṁ ādityarūpāṁ svadhā namas tarpayāmi ||3||",
      en: "My mother's great-grandmother, in the form of an Āditya.",
      tel: "తల్లికి ముత్తమ్మ — ఆదిత్యరూప." },
    { s: 3, n: "29",
      deva: "अस्मत् आत्मपत्नीं … गोत्रां … पदां वसुरूपां स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat ātmapatnīṁ … gotrāṁ … padāṁ vasurūpāṁ svadhā namas tarpayāmi ||3||",
      en: "My own wife, in the form of a Vasu.",
      tel: "తన భార్య — వసురూప." },
    { s: 3, n: "30",
      deva: "अस्मत् सुतं … गोत्रं … शर्मणं वसुरूपं स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat sutaṁ … gotraṁ … śarmaṇaṁ vasurūpaṁ svadhā namas tarpayāmi ||3||",
      en: "My son, in the form of a Vasu.",
      tel: "కుమారుడు — వసురూపుడు." },
    { s: 3, n: "31",
      deva: "अस्मत् ज्येष्ठ (कनिष्ठ) भ्रातरं … गोत्रं … शर्मणं वसुरूपं सपत्नीकं\nस्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat jyeṣṭha (kaniṣṭha) bhrātaraṁ … gotraṁ … śarmaṇaṁ vasurūpaṁ sapatnīkaṁ\nsvadhā namas tarpayāmi ||3||",
      en: "My elder or younger brother. If his wife too is gone, sapatnīkaṁ is added.",
      tel: "అన్న లేదా తమ్ముడు. భార్య కూడా లేనట్లయితే సపత్నీకం అని చేర్చాలి." },
    { s: 3, n: "32",
      deva: "अस्मत् ज्येष्ठ (कनिष्ठ) पितृव्यं … गोत्रं … शर्मणं वसुरूपं सपत्नीकं\nस्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat jyeṣṭha (kaniṣṭha) pitṛvyaṁ … gotraṁ … śarmaṇaṁ vasurūpaṁ sapatnīkaṁ\nsvadhā namas tarpayāmi ||3||",
      en: "My father's elder or younger brother.",
      tel: "తండ్రి సోదరులు: పెదనాన్న, బాబాయి." },
    { s: 3, n: "33",
      deva: "अस्मत् मातुलं … गोत्रं … शर्मणं वसुरूपं सपत्नीकं स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat mātulaṁ … gotraṁ … śarmaṇaṁ vasurūpaṁ sapatnīkaṁ svadhā namas tarpayāmi ||3||",
      en: "My mother's brother.",
      tel: "మేనమామ." },
    { s: 3, n: "34",
      deva: "अस्मत् दुहितरं … गोत्रां … पदां वसुरूपां स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat duhitaraṁ … gotrāṁ … padāṁ vasurūpāṁ svadhā namas tarpayāmi ||3||",
      en: "My daughter.",
      tel: "కుమార్తె." },
    { s: 3, n: "35",
      deva: "अस्मत् भगिनीं … गोत्रां … पदां वसुरूपां स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat bhaginīṁ … gotrāṁ … padāṁ vasurūpāṁ svadhā namas tarpayāmi ||3||",
      en: "My sister.",
      tel: "తోబుట్టువు." },
    { s: 3, n: "36",
      deva: "अस्मत् दौहित्रं … गोत्रं … शर्मणं वसुरूपं सपत्नीकं स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat dauhitraṁ … gotraṁ … śarmaṇaṁ vasurūpaṁ sapatnīkaṁ svadhā namas tarpayāmi ||3||",
      en: "My daughter's son.",
      tel: "కూతురి కొడుకు." },
    { s: 3, n: "37",
      deva: "अस्मत् भागिनेयकं … गोत्रं … शर्मणं वसुरूपं सपत्नीकं स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat bhāgineyakaṁ … gotraṁ … śarmaṇaṁ vasurūpaṁ sapatnīkaṁ svadhā namas tarpayāmi ||3||",
      en: "My sister's son.",
      tel: "మేనల్లుడు." },
    { s: 3, n: "38",
      deva: "अस्मत् पितृभगिनीं … गोत्रां … पदां वसुरूपां सभर्तृकं स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat pitṛbhaginīṁ … gotrāṁ … padāṁ vasurūpāṁ sabhartṛkaṁ svadhā namas tarpayāmi ||3||",
      en: "My father's sister. If her husband too is gone, sabhartṛkaṁ is added.",
      tel: "మేనత్త. భర్త కూడా లేనట్లయితే సభర్తృకం అని చేర్చాలి." },
    { s: 3, n: "39",
      deva: "अस्मत् मातृभगिनीं … गोत्रां … पदां वसुरूपां सभर्तृकं स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat mātṛbhaginīṁ … gotrāṁ … padāṁ vasurūpāṁ sabhartṛkaṁ svadhā namas tarpayāmi ||3||",
      en: "My mother's sister.",
      tel: "తల్లి తోబుట్టువు: పిన్ని, పెద్దమ్మ." },
    { s: 3, n: "40",
      deva: "अस्मत् जामातरं … गोत्रं … शर्मणं वसुरूपं स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat jāmātaraṁ … gotraṁ … śarmaṇaṁ vasurūpaṁ svadhā namas tarpayāmi ||3||",
      en: "My son-in-law.",
      tel: "అల్లుడు." },
    { s: 3, n: "41",
      deva: "अस्मत् भावुकं … गोत्रं … शर्मणं वसुरूपं स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat bhāvukaṁ … gotraṁ … śarmaṇaṁ vasurūpaṁ svadhā namas tarpayāmi ||3||",
      en: "My sister's husband.",
      tel: "బావగారు." },
    { s: 3, n: "42",
      deva: "अस्मत् स्नुषां … गोत्रां … पदां वसुरूपां स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat snuṣāṁ … gotrāṁ … padāṁ vasurūpāṁ svadhā namas tarpayāmi ||3||",
      en: "My daughter-in-law.",
      tel: "కోడలు." },
    { s: 3, n: "43",
      deva: "अस्मत् श्वशुरं … गोत्रं … शर्मणं वसुरूपं स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat śvaśuraṁ … gotraṁ … śarmaṇaṁ vasurūpaṁ svadhā namas tarpayāmi ||3||",
      en: "My wife's father.",
      tel: "భార్య తండ్రి, మామగారు." },
    { s: 3, n: "44",
      deva: "अस्मत् श्वश्रूं … गोत्रां … पदां वसुरूपां स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat śvaśrūṁ … gotrāṁ … padāṁ vasurūpāṁ svadhā namas tarpayāmi ||3||",
      en: "My wife's mother.",
      tel: "భార్య తల్లి, అత్తగారు." },
    { s: 3, n: "45",
      deva: "अस्मत् श्यालकं … गोत्रं … शर्मणं वसुरूपं सपत्नीकं स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat śyālakaṁ … gotraṁ … śarmaṇaṁ vasurūpaṁ sapatnīkaṁ svadhā namas tarpayāmi ||3||",
      en: "My wife's brother.",
      tel: "భార్య సోదరుడు, బావమరిది." },
    { s: 3, n: "46",
      deva: "अस्मत् स्वामिनं … गोत्रं … शर्मणं वसुरूपं सपत्नीकं स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat svāminaṁ … gotraṁ … śarmaṇaṁ vasurūpaṁ sapatnīkaṁ svadhā namas tarpayāmi ||3||",
      en: "The one I served.",
      tel: "ప్రభువు, నేను సేవించినవారు." },
    { s: 3, n: "47",
      deva: "अस्मत् गुरुं … गोत्रं … शर्मणं वसुरूपं सपत्नीकं स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat guruṁ … gotraṁ … śarmaṇaṁ vasurūpaṁ sapatnīkaṁ svadhā namas tarpayāmi ||3||",
      en: "My teacher.",
      tel: "గురువు." },
    { s: 3, n: "48",
      deva: "अस्मत् ऋक्तिनं … गोत्रं … शर्मणं वसुरूपं सपत्नीकं स्वधा नमस्तर्पयामि ॥३॥",
      iast: "asmat ṛktinaṁ … gotraṁ … śarmaṇaṁ vasurūpaṁ sapatnīkaṁ svadhā namas tarpayāmi ||3||",
      en: "The one who gave me wealth. Only those who have died are named. Śarmaṇaṁ is the brāhmaṇa ending. Varmaṇaṁ, guptaṁ and dāsaṁ stand in its place for the others.",
      tel: "ధనమిచ్చినవారు. మరణించినవారి పేర్లే చదవాలి. బ్రాహ్మణులైతే శర్మణం అనాలి. రాజులైతే వర్మణం, వైశ్యులైతే గుప్తం, ఇతరులు దాసం అని మార్చాలి." },

    { s: 4, n: "49",
      deva: "ये के चास्मत् कुले जाताः अपुत्रा गोत्रिणो मृताः ।\nते गृह्णन्तु मयादत्तं वस्त्र निष्पीडनोदकम् ॥",
      iast: "ye ke cāsmat kule jātāḥ aputrā gotriṇo mṛtāḥ |\nte gṛhṇantu mayādattaṁ vastra niṣpīḍanodakam ||",
      en: "Whoever was born in this line and died without a son, of this gotra, let them receive the water I give, wrung from the cloth. Twist the pavitram into a nīvīti. Dip its knot in water. Wring it out over the ground as this is read.",
      tel: "ఈ కులములో పుట్టి, పుత్రులు లేక మరణించిన ఈ గోత్రీయులందరూ నేనిచ్చే వస్త్రనిష్పీడనోదకమును స్వీకరించుగాక. పవిత్రమును నివీతిగా పేనుకోవాలి. ముడిని నీటిలో ముంచాలి. ఇది చదువుతూ నేలపై పిండాలి." },
    { s: 4, n: "50",
      deva: "सव्यम् ॥ श्रीराम राम राम ॥",
      iast: "savyam || śrīrāma rāma rāma ||",
      en: "Return the yajñopavītam to the left shoulder. Touch the knot of the pavitram to the eyes and untwist it. Do ācamana. Set the darbha aside in a clean place.",
      tel: "యజ్ఞోపవీతమును ఎడమ భుజము పైకి మార్చుకోవాలి. పవిత్రపు ముడిని కళ్ళకద్దుకుని సవ్యము చేసుకోవాలి. ఆచమనం చేయాలి. దర్భను శుభ్రమైన చోట ఉంచాలి." }
  ]
}

);
