/* ============================================================
   STUTI — Viṣṇu full texts, part 1
   Bhagavad Gītā (Dhyānam) · Achyutāṣṭakam
   Devanāgarī is the source of truth; other scripts are derived at
   read time. Each verse ships with all four glosses from the start:
   `en` · `tel` (అర్థం) · `hi` (अर्थ). No fallback to English.
   ============================================================ */
export const extra = [{
  deities: ["vishnu"],
  title: "Bhagavad Gītā (Dhyānam)",
  blurb: "The nine verses said before opening the Gītā — to the book, to Vyāsa who wrote it, to Kṛṣṇa who spoke it, and to the river of the war it was spoken in the middle of.",
  sections: [
    { tel: "ధ్యానం", roman: "The Invocation", hi: "ध्यानम्" },
    { tel: "వందనం", roman: "The Salutation", hi: "वन्दनम्" },
  ],
  verses: [
    { s: 0, n: "1",
      deva: "ॐ पार्थाय प्रतिबोधितां भगवता नारायणेन स्वयं\nव्यासेन ग्रथितां पुराणमुनिना मध्ये महाभारतम् ।\nअद्वैतामृतवर्षिणीं भगवतीमष्टादशाध्यायिनीं\nअम्ब त्वामनुसन्दधामि भगवद्गीते भवद्वेषिणीम् ॥",
      iast: "oṁ pārthāya pratibodhitāṁ bhagavatā nārāyaṇena svayaṁ\nvyāsena grathitāṁ purāṇa-muninā madhye mahābhāratam ।\nadvaitāmṛta-varṣiṇīṁ bhagavatīm-aṣṭādaśādhyāyinīṁ\namba tvām-anusandadhāmi bhagavad-gīte bhava-dveṣiṇīm ॥",
      en: "Om. Taught to Arjuna by the Lord Nārāyaṇa himself, set down by the ancient sage Vyāsa in the middle of the Mahābhārata; raining the nectar of non-duality, holy, of eighteen chapters — Mother Bhagavad Gītā, undoer of becoming, on you I fix my mind.",
      tel: "ఓం. భగవానుడైన నారాయణుడే స్వయముగా అర్జునునికి బోధించినది, పురాణమునియైన వ్యాసుడు మహాభారతము మధ్యలో గ్రంథించినది; అద్వైతామృతమును కురియునది, భగవతి, పదునెనిమిది అధ్యాయములు గలది — ఓ తల్లీ భగవద్గీతా, సంసారమును నశింపజేయుదానా, నిన్నే మనసునందు నిలుపుకొందును.",
      hi: "ॐ। भगवान् नारायण ने स्वयं अर्जुन को जिसका बोध कराया, पुराणमुनि व्यास ने महाभारत के मध्य में जिसे ग्रथित किया; अद्वैत के अमृत की वर्षा करने वाली, भगवती, अठारह अध्यायों वाली — हे अम्ब भगवद्गीते, भव का नाश करने वाली, तुझ में मैं मन लगाता हूँ।" },
    { s: 0, n: "2",
      deva: "नमोऽस्तु ते व्यास विशालबुद्धे फुल्लारविन्दायतपत्रनेत्र ।\nयेन त्वया भारततैलपूर्णः प्रज्वालितो ज्ञानमयः प्रदीपः ॥",
      iast: "namo'stu te vyāsa viśāla-buddhe phullāravindāyata-patra-netra ।\nyena tvayā bhārata-taila-pūrṇaḥ prajvālito jñānamayaḥ pradīpaḥ ॥",
      en: "Salutation to you, Vyāsa of vast understanding, whose eyes are the long petals of an open lotus — you by whom the lamp of knowledge was lit, filled with the oil of the Bhārata.",
      tel: "ఓ విశాలబుద్ధి గల వ్యాసా, వికసించిన కమలదళములవంటి నిడుపైన కన్నులు గలవాడా, నీకు నమస్కారము — భారతమను తైలముతో నిండిన జ్ఞానదీపమును వెలిగించినది నీవే.",
      hi: "हे विशालबुद्धि व्यास, खिले कमल के लम्बे पत्रों-से नेत्र वाले, तुझे नमस्कार — जिसने भारत के तेल से भरा ज्ञानमय प्रदीप प्रज्वलित किया।" },
    { s: 0, n: "3",
      deva: "प्रपन्नपारिजाताय तोत्रवेत्रैकपाणये ।\nज्ञानमुद्राय कृष्णाय गीतामृतदुहे नमः ॥",
      iast: "prapanna-pārijātāya totra-vetraika-pāṇaye ।\njñāna-mudrāya kṛṣṇāya gītāmṛta-duhe namaḥ ॥",
      en: "To the wish-tree of those who take refuge, who holds the goad and the reins in one hand; to Kṛṣṇa, whose hand is the sign of knowledge, who milked out the nectar of the Gītā — salutation.",
      tel: "శరణాగతులకు పారిజాతమైనవానికి, ఒక చేతిలో ములుకోలను, పరిచేతిని ధరించినవానికి; జ్ఞానముద్ర గలవానికి, గీతామృతమును పిదికినవానికి — ఆ కృష్ణునికి నమస్కారము.",
      hi: "शरणागतों के लिए पारिजात, एक हाथ में तोत्र और वेत्र धारण करने वाले; ज्ञानमुद्रा वाले, गीता के अमृत का दोहन करने वाले — उन कृष्ण को नमस्कार।" },
    { s: 0, n: "4",
      deva: "सर्वोपनिषदो गावो दोग्धा गोपालनन्दनः ।\nपार्थो वत्सः सुधीर्भोक्ता दुग्धं गीतामृतं महत् ॥",
      iast: "sarvopaniṣado gāvo dogdhā gopāla-nandanaḥ ।\npārtho vatsaḥ sudhīr-bhoktā dugdhaṁ gītāmṛtaṁ mahat ॥",
      en: "All the Upaniṣads are the cows; the cowherd's son is the milker; Arjuna is the calf; the clear-minded are those who drink; and the milk is the great nectar of the Gītā.",
      tel: "సమస్త ఉపనిషత్తులు గోవులు; గోపాలనందనుడు పిదుకువాడు; అర్జునుడు దూడ; సుబుద్ధులు త్రాగువారు; పాలు గీతామృతమను మహత్తరమైనది.",
      hi: "समस्त उपनिषद् गौएँ हैं; गोपालनन्दन दोहने वाला; अर्जुन बछड़ा; सुधीजन पीने वाले; और दूध है गीता का महान् अमृत।" },
    { s: 0, n: "5",
      deva: "वसुदेवसुतं देवं कंसचाणूरमर्दनम् ।\nदेवकीपरमानन्दं कृष्णं वन्दे जगद्गुरुम् ॥",
      iast: "vasudeva-sutaṁ devaṁ kaṁsa-cāṇūra-mardanam ।\ndevakī-paramānandaṁ kṛṣṇaṁ vande jagad-gurum ॥",
      en: "The son of Vasudeva, the god, crusher of Kaṁsa and Cāṇūra, the highest joy of Devakī — Kṛṣṇa, teacher of all that is, I salute.",
      tel: "వసుదేవుని కుమారుడు, దేవుడు, కంస చాణూరులను మర్దించినవాడు, దేవకికి పరమానందమైనవాడు — జగద్గురువైన కృష్ణునికి నమస్కరించుచున్నాను.",
      hi: "वसुदेव के पुत्र, देव, कंस और चाणूर का मर्दन करने वाले, देवकी के परमानन्द — जगद्गुरु कृष्ण को मैं वन्दन करता हूँ।" },
    { s: 0, n: "6",
      deva: "भीष्मद्रोणतटा जयद्रथजला गान्धारनीलोत्पला\nशल्यग्राहवती कृपेण वहनी कर्णेन वेलाकुला ।\nअश्वत्थामविकर्णघोरमकरा दुर्योधनावर्तिनी\nसोत्तीर्णा खलु पाण्डवैः रणनदी कैवर्तकः केशवः ॥",
      iast: "bhīṣma-droṇa-taṭā jayadratha-jalā gāndhāra-nīlotpalā\nśalya-grāhavatī kṛpeṇa vahanī karṇena velākulā ।\naśvatthāma-vikarṇa-ghora-makarā duryodhanāvartinī\nsottīrṇā khalu pāṇḍavaiḥ raṇa-nadī kaivartakaḥ keśavaḥ ॥",
      en: "Bhīṣma and Droṇa were its banks, Jayadratha its water, Śakuni its blue lotuses; Śalya was the crocodile in it, Kṛpa its current, Karṇa its restless tide; Aśvatthāmā and Vikarṇa its dreadful sea-monsters, Duryodhana its whirlpool — and the Pāṇḍavas crossed that river of war, with Keśava for their ferryman.",
      tel: "భీష్మ ద్రోణులు దరులు, జయద్రథుడు జలము, శకుని నల్లకలువలు; శల్యుడు మొసలి, కృపుడు ప్రవాహము, కర్ణుడు కల్లోలమైన అలలు; అశ్వత్థామ వికర్ణులు భయంకరమైన మకరములు, దుర్యోధనుడు సుడిగుండము — అట్టి రణనదిని పాండవులు దాటిరి; కేశవుడే పడవవాడు.",
      hi: "भीष्म और द्रोण उसके तट, जयद्रथ जल, शकुनि नीलोत्पल; शल्य उसका ग्राह, कृप प्रवाह, कर्ण उद्वेलित लहरें; अश्वत्थामा और विकर्ण घोर मकर, दुर्योधन भँवर — उस रणनदी को पाण्डवों ने पार किया, और केशव ही केवट थे।" },
    { s: 0, n: "7",
      deva: "पाराशर्यवचःसरोजममलं गीतार्थगन्धोत्कटं\nनानाख्यानककेसरं हरिकथासम्बोधनाबोधितम् ।\nलोके सज्जनषट्पदैरहरहः पेपीयमानं मुदा\nभूयाद्भारतपङ्कजं कलिमलप्रध्वंसि नः श्रेयसे ॥",
      iast: "pārāśarya-vacaḥ-sarojam-amalaṁ gītārtha-gandhotkaṭaṁ\nnānākhyānaka-kesaraṁ hari-kathā-sambodhanābodhitam ।\nloke sajjana-ṣaṭpadair-ahar-ahaḥ pepīyamānaṁ mudā\nbhūyād-bhārata-paṅkajaṁ kali-mala-pradhvaṁsi naḥ śreyase ॥",
      en: "The spotless lotus of the son of Parāśara's speech, pungent with the scent of the Gītā's meaning; its filaments the many tales, opened by the awakening that is the story of Hari; drunk day after day with delight by the bees who are the good — may that Bhārata-lotus, destroyer of the filth of the Kali age, be for our good.",
      tel: "పరాశరపుత్రుని వాక్కు అను నిర్మలమైన కమలము, గీతార్థమను తీవ్రమైన సువాసన గలది; నానా ఆఖ్యానములే కేసరములు, హరికథ యను మేల్కొలుపుచే వికసించినది; సజ్జనులను తుమ్మెదలు ప్రతిదినము ముదముతో త్రాగుచున్నవి — కలిమలమును నశింపజేయు ఆ భారతకమలము మా శ్రేయమునకు అగునుగాక.",
      hi: "पराशरपुत्र के वचन का निर्मल कमल, गीता के अर्थ की तीव्र गन्ध से भरा; नाना आख्यान उसके केसर, हरिकथा के सम्बोधन से विकसित; लोक में सज्जन-भ्रमरों द्वारा प्रतिदिन मुदित होकर पिया जाता — कलिमल का ध्वंस करने वाला वह भारत-पङ्कज हमारे श्रेय के लिए हो।" },
    { s: 1, n: "8",
      deva: "मूकं करोति वाचालं पङ्गुं लङ्घयते गिरिम् ।\nयत्कृपा तमहं वन्दे परमानन्दमाधवम् ॥",
      iast: "mūkaṁ karoti vācālaṁ paṅguṁ laṅghayate girim ।\nyat-kṛpā tam-ahaṁ vande paramānanda-mādhavam ॥",
      en: "Whose grace makes the mute eloquent and carries the lame over a mountain — him I salute, Mādhava, who is the highest joy.",
      tel: "ఎవరి కృప మూగవానిని వాక్పటువును చేయునో, కుంటివానిని పర్వతమును దాటించునో — ఆ పరమానందస్వరూపుడైన మాధవునికి నమస్కరించుచున్నాను.",
      hi: "जिसकी कृपा मूक को वाचाल बना देती है और पङ्गु को पर्वत लङ्घा देती है — उस परमानन्दस्वरूप माधव को मैं वन्दन करता हूँ।" },
    { s: 1, n: "9",
      deva: "यं ब्रह्मा वरुणेन्द्ररुद्रमरुतः स्तुन्वन्ति दिव्यैः स्तवैः\nवेदैः साङ्गपदक्रमोपनिषदैर्गायन्ति यं सामगाः ।\nध्यानावस्थिततद्गतेन मनसा पश्यन्ति यं योगिनो\nयस्यान्तं न विदुः सुरासुरगणा देवाय तस्मै नमः ॥",
      iast: "yaṁ brahmā varuṇendra-rudra-marutaḥ stunvanti divyaiḥ stavaiḥ\nvedaiḥ sāṅga-pada-kramopaniṣadair-gāyanti yaṁ sāmagāḥ ।\ndhyānāvasthita-tad-gatena manasā paśyanti yaṁ yogino\nyasyāntaṁ na vidur-surāsura-gaṇā devāya tasmai namaḥ ॥",
      en: "Whom Brahmā, Varuṇa, Indra, Rudra and the Maruts praise with divine hymns; whom the singers of the Sāman sing with the Vedas, their limbs, the pada and krama recitations and the Upaniṣads; whom the yogins see with a mind settled in meditation and gone wholly to him; whose end neither gods nor demons know — to that god, salutation.",
      tel: "బ్రహ్మ, వరుణుడు, ఇంద్రుడు, రుద్రుడు, మరుత్తులు దివ్యమైన స్తవములతో ఎవరిని స్తుతించుచున్నారో; సామగాయకులు వేదములతో, అంగములతో, పదక్రమములతో, ఉపనిషత్తులతో ఎవరిని గానము చేయుచున్నారో; యోగులు ధ్యానమునందు నిలిచి, తద్గతమైన మనసుతో ఎవరిని దర్శించుచున్నారో; ఎవరి అంతమును సురాసురగణములు ఎరుగరో — ఆ దేవునికి నమస్కారము.",
      hi: "जिसे ब्रह्मा, वरुण, इन्द्र, रुद्र और मरुत् दिव्य स्तवों से स्तुत करते हैं; जिसे सामगायक वेदों, अङ्गों, पद-क्रम और उपनिषदों से गाते हैं; जिसे योगी ध्यान में स्थित, तद्गत मन से देखते हैं; जिसका अन्त सुर-असुर गण नहीं जानते — उस देव को नमस्कार।" },
  ],
},

{
  deities: ["vishnu"],
  title: "Achyutāṣṭakam",
  blurb: "Eight verses that are almost entirely names — Achyuta, Keśava, Rāma, Nārāyaṇa, one after another — as if the whole hymn were a garland being counted off.",
  sections: [
    { tel: "అష్టకం", roman: "The Eight Verses", hi: "अष्टकम्" },
    { tel: "ఫలశ్రుతి", roman: "The Fruit of Recitation", hi: "फलश्रुति" },
  ],
  verses: [
    { s: 0, n: "1",
      deva: "अच्युतं केशवं रामनारायणं कृष्णदामोदरं वासुदेवं हरिम् ।\nश्रीधरं माधवं गोपिकावल्लभं जानकीनायकं रामचन्द्रं भजे ॥",
      iast: "acyutaṁ keśavaṁ rāma-nārāyaṇaṁ kṛṣṇa-dāmodaraṁ vāsudevaṁ harim ।\nśrīdharaṁ mādhavaṁ gopikā-vallabhaṁ jānakī-nāyakaṁ rāma-candraṁ bhaje ॥",
      en: "Achyuta, Keśava, Rāma, Nārāyaṇa, Kṛṣṇa, Dāmodara, Vāsudeva, Hari; Śrīdhara, Mādhava, beloved of the gopīs, lord of Jānakī — Rāmacandra I worship.",
      tel: "అచ్యుతుడు, కేశవుడు, రామనారాయణుడు, కృష్ణదామోదరుడు, వాసుదేవుడు, హరి; శ్రీధరుడు, మాధవుడు, గోపికావల్లభుడు, జానకీనాయకుడు — ఆ రామచంద్రుని భజించుచున్నాను.",
      hi: "अच्युत, केशव, राम-नारायण, कृष्ण-दामोदर, वासुदेव, हरि; श्रीधर, माधव, गोपिकावल्लभ, जानकीनायक — उन रामचन्द्र को मैं भजता हूँ।" },
    { s: 0, n: "2",
      deva: "अच्युतं केशवं सत्यभामाधवं माधवं श्रीधरं राधिकाराधितम् ।\nइन्दिरामन्दिरं चेतसा सुन्दरं देवकीनन्दनं नन्दजं सन्दधे ॥",
      iast: "acyutaṁ keśavaṁ satyabhāmā-dhavaṁ mādhavaṁ śrīdharaṁ rādhikārādhitam ।\nindirā-mandiraṁ cetasā sundaraṁ devakī-nandanaṁ nanda-jaṁ sandadhe ॥",
      en: "Achyuta, Keśava, husband of Satyabhāmā, Mādhava, Śrīdhara, worshipped by Rādhikā; the dwelling of Indirā, beautiful — Devakī's son, Nanda's boy — on him I fix my mind.",
      tel: "అచ్యుతుడు, కేశవుడు, సత్యభామాపతి, మాధవుడు, శ్రీధరుడు, రాధికచే ఆరాధింపబడినవాడు; ఇందిరకు మందిరమైనవాడు, సుందరుడు — దేవకీనందనుడు, నందుని బాలుడు — అతనిని మనసునందు నిలుపుకొందును.",
      hi: "अच्युत, केशव, सत्यभामा के पति, माधव, श्रीधर, राधिका से आराधित; इन्दिरा के मन्दिर, सुन्दर — देवकीनन्दन, नन्द के बालक — उन्हें मैं चित्त में धारण करता हूँ।" },
    { s: 0, n: "3",
      deva: "विष्णवे जिष्णवे शङ्खिने चक्रिणे रुक्मिणीरागिणे जानकीजानये ।\nवल्लवीवल्लभायार्चितायात्मने कंसविध्वंसिने वंशिने ते नमः ॥",
      iast: "viṣṇave jiṣṇave śaṅkhine cakriṇe rukmiṇī-rāgiṇe jānakī-jānaye ।\nvallavī-vallabhāyārcitāyātmane kaṁsa-vidhvaṁsine vaṁśine te namaḥ ॥",
      en: "To Viṣṇu, the victorious, bearer of the conch and the discus, lover of Rukmiṇī, husband of Jānakī; to the beloved of the cowherd women, the worshipped one, the very Self, destroyer of Kaṁsa, holder of the flute — to you, salutation.",
      tel: "విష్ణువుకు, జయశీలునికి, శంఖము చక్రము ధరించినవానికి, రుక్మిణిపై అనురాగము గలవానికి, జానకీపతికి; గోపికల వల్లభునికి, పూజింపబడువానికి, ఆత్మస్వరూపునికి, కంసవిధ్వంసునికి, వేణుధారికి — నీకు నమస్కారము.",
      hi: "विष्णु को, जिष्णु को, शङ्ख और चक्र धारण करने वाले को, रुक्मिणी के अनुरागी को, जानकी के पति को; वल्लवियों के वल्लभ को, अर्चित को, आत्मस्वरूप को, कंस का विध्वंस करने वाले को, वंशीधर को — तुझे नमस्कार।" },
    { s: 0, n: "4",
      deva: "कृष्ण गोविन्द हे राम नारायण श्रीपते वासुदेवाजित श्रीनिधे ।\nअच्युतानन्त हे माधवाधोक्षज द्वारकानायक द्रौपदीरक्षक ॥",
      iast: "kṛṣṇa govinda he rāma nārāyaṇa śrīpate vāsudevājita śrī-nidhe ।\nacyutānanta he mādhavādhokṣaja dvārakā-nāyaka draupadī-rakṣaka ॥",
      en: "Kṛṣṇa, Govinda, O Rāma, Nārāyaṇa, lord of Śrī, Vāsudeva, unconquered, treasury of splendour; Achyuta, Ananta, O Mādhava, Adhokṣaja, lord of Dvārakā, protector of Draupadī.",
      tel: "కృష్ణా, గోవిందా, ఓ రామా, నారాయణా, శ్రీపతీ, వాసుదేవా, అజితా, శ్రీనిధీ; అచ్యుతా, అనంతా, ఓ మాధవా, అధోక్షజా, ద్వారకానాయకా, ద్రౌపదీరక్షకా.",
      hi: "कृष्ण, गोविन्द, हे राम, नारायण, श्रीपते, वासुदेव, अजित, श्रीनिधे; अच्युत, अनन्त, हे माधव, अधोक्षज, द्वारकानायक, द्रौपदी के रक्षक।" },
    { s: 0, n: "5",
      deva: "राक्षसक्षोभितः सीतया शोभितो दण्डकारण्यभूपुण्यताकारणः ।\nलक्ष्मणेनान्वितो वानरैः सेवितोऽगस्त्यसम्पूजितो राघवः पातु माम् ॥",
      iast: "rākṣasa-kṣobhitaḥ sītayā śobhito daṇḍakāraṇya-bhū-puṇyatā-kāraṇaḥ ।\nlakṣmaṇenānvito vānaraiḥ sevito'gastya-sampūjito rāghavaḥ pātu mām ॥",
      en: "Harried by the demons, made lovely by Sītā's presence, the reason the soil of Daṇḍaka forest became holy; accompanied by Lakṣmaṇa, served by the monkeys, worshipped by Agastya — may Rāghava protect me.",
      tel: "రాక్షసులచే క్షోభింపబడినవాడు, సీతతో శోభించినవాడు, దండకారణ్య భూమి పవిత్రమగుటకు కారణమైనవాడు; లక్ష్మణునితో కూడినవాడు, వానరులచే సేవింపబడినవాడు, అగస్త్యునిచే పూజింపబడినవాడు — ఆ రాఘవుడు నన్ను రక్షించునుగాక.",
      hi: "राक्षसों से क्षोभित, सीता से शोभित, दण्डकारण्य की भूमि के पुण्य होने का कारण; लक्ष्मण से युक्त, वानरों से सेवित, अगस्त्य से सम्पूजित — वे राघव मेरी रक्षा करें।" },
    { s: 0, n: "6",
      deva: "धेनुकारिष्टकानिष्टकृद्द्वेषिहा केशिहा कंसहृद्वंशिकावादकः ।\nपूतनाकोपकः सूरजाखेलनो बालगोपालकः पातु मां सर्वदा ॥",
      iast: "dhenukāriṣṭakāniṣṭa-kṛd-dveṣi-hā keśi-hā kaṁsa-hṛd-vaṁśikā-vādakaḥ ।\npūtanā-kopakaḥ sūrajā-khelano bāla-gopālakaḥ pātu māṁ sarvadā ॥",
      en: "Slayer of Dhenuka and Ariṣṭa and of every ill-wisher, killer of Keśī, taker of Kaṁsa's life, player of the flute; the undoing of Pūtanā, who played on the Yamunā's banks — may the boy cowherd protect me always.",
      tel: "ధేనుకుని, అరిష్టుని, కీడు కోరు వారందరిని సంహరించినవాడు, కేశిని చంపినవాడు, కంసుని ప్రాణము తీసినవాడు, వేణువు వాయించువాడు; పూతనకు అంతమైనవాడు, యమునాతీరమున ఆడినవాడు — ఆ బాలగోపాలుడు నన్ను సదా రక్షించునుగాక.",
      hi: "धेनुक और अरिष्ट तथा प्रत्येक द्वेषी का नाश करने वाले, केशी का वध करने वाले, कंस के प्राण हरने वाले, वंशी बजाने वाले; पूतना का अन्त करने वाले, यमुना के तट पर खेलने वाले — वे बालगोपाल मेरी सदा रक्षा करें।" },
    { s: 0, n: "7",
      deva: "विद्युदुद्योतवत्प्रस्फुरद्वाससं प्रावृडम्भोदवत्प्रोल्लसद्विग्रहम् ।\nवन्यया मालया शोभितोरःस्थलं लोहिताङ्घ्रिद्वयं वारिजाक्षं भजे ॥",
      iast: "vidyud-udyotavat-prasphurad-vāsasaṁ prāvṛḍ-ambhodavat-prollasad-vigraham ।\nvanyayā mālayā śobhitoraḥ-sthalaṁ lohitāṅghri-dvayaṁ vārijākṣaṁ bhaje ॥",
      en: "His garment flashing like a stroke of lightning, his form glowing like a rain-cloud of the monsoon; his breast graced with a garland of forest flowers, his two feet reddened — the lotus-eyed one I worship.",
      tel: "మెరుపువలె మెరయు వస్త్రము గలవాడు, వర్షాకాలపు మేఘమువలె ప్రకాశించు దేహము గలవాడు; అడవిపూల మాలతో శోభించు వక్షస్థలము గలవాడు, ఎరుపెక్కిన పాదద్వయము గలవాడు — ఆ కమలనేత్రుని భజించుచున్నాను.",
      hi: "विद्युत् की चमक-सा फुरकता वस्त्र, वर्षा के मेघ-सा प्रकाशमान शरीर; वन्य पुष्पों की माला से शोभित वक्षःस्थल, लोहित चरणयुगल — उन वारिजाक्ष को मैं भजता हूँ।" },
    { s: 0, n: "8",
      deva: "कुञ्चितैः कुन्तलैर्भ्राजमानाननं रत्नमौलिं लसत्कुण्डलं गण्डयोः ।\nहारकेयूरकं कङ्कणप्रोज्ज्वलं किङ्किणीमञ्जुलं श्यामलं तं भजे ॥",
      iast: "kuñcitaiḥ kuntalair-bhrājamānānanaṁ ratna-mauliṁ lasat-kuṇḍalaṁ gaṇḍayoḥ ।\nhāra-keyūrakaṁ kaṅkaṇa-projjvalaṁ kiṅkiṇī-mañjulaṁ śyāmalaṁ taṁ bhaje ॥",
      en: "His face bright within its curling locks, a jewelled crest, earrings glinting at his cheeks; necklace and armlets, bracelets ablaze, sweet with little bells — that dark one I worship.",
      tel: "ఉంగరాల ముంగురులతో ప్రకాశించు ముఖము గలవాడు, రత్నకిరీటము గలవాడు, చెక్కిళ్ళపై మెరయు కుండలములు గలవాడు; హారము, కేయూరములు, ప్రజ్వలించు కంకణములు గలవాడు, గజ్జెలతో మనోహరమైనవాడు — ఆ శ్యామలుని భజించుచున్నాను.",
      hi: "घुँघराले कुन्तलों में दीप्त मुख, रत्नमुकुट, गालों पर चमकते कुण्डल; हार और केयूर, प्रज्वलित कङ्कण, किङ्किणियों से मञ्जुल — उस श्यामल को मैं भजता हूँ।" },
    { s: 1, n: "9",
      deva: "अच्युतस्याष्टकं यः पठेदिष्टदं प्रेमतः प्रत्यहं पूरुषः सस्पृहम् ।\nवृत्ततः सुन्दरं कर्तृविश्वम्भरस्तस्य वश्यो हरिर्जायते सत्वरम् ॥",
      iast: "acyutasyāṣṭakaṁ yaḥ paṭhed-iṣṭadaṁ prematḥ pratyahaṁ pūruṣaḥ sa-spṛham ।\nvṛttataḥ sundaraṁ kartṛ-viśvambharas-tasya vaśyo harir-jāyate satvaram ॥",
      en: "Whoever recites with love and longing, day after day, this wish-granting eight-verse hymn to Achyuta — beautiful in its metre, and made by one whom the sustainer of the world moved — to him Hari quickly becomes bound.",
      tel: "కోరికలను ఇచ్చు ఈ అచ్యుతాష్టకమును ప్రేమతో, ఆసక్తితో ప్రతిదినము పఠించువాడు — ఛందస్సునందు సుందరమైనది, విశ్వంభరుని ప్రేరణతో రచింపబడినది — అట్టివానికి హరి శీఘ్రముగా వశుడగును.",
      hi: "जो पुरुष प्रेम और स्पृहा से प्रतिदिन अच्युत के इस इष्टदायक अष्टक का पाठ करता है — वृत्त में सुन्दर, विश्वम्भर की प्रेरणा से रचित — उसके लिए हरि शीघ्र ही वश्य हो जाते हैं।" },
  ],
},];
