/* ============================================================
   STUTI — Gaṇeśa full texts, part 3
   Vighneśvara Aṣṭottara Śatanāmāvali · Vātāpi Gaṇapatiṁ Bhaje
   · Mahāgaṇapatiṁ Manasā Smarāmi · Mahāgaṇapati Stotram
   · Gaṇapati Tālam
   The nāmāvali follows the Telugu-tradition list (vignanam.org),
   one name to a line, each its own numbered verse.
   The two Dīkṣitar kṛtis are Sanskrit compositions; sections carry
   their musical divisions (pallavi · anupallavi · caraṇam).
   ============================================================ */
export const extra = [{
  deities: ["ganesha"],
  title: "Vighneśvara Aṣṭottara Śatanāmāvali",
  blurb: "The hundred and eight names of the lord of obstacles, each offered with Om and namaḥ.",
  sections: [{ tel: "నామావళి", roman: "The Hundred and Eight Names" }],
  verses: [
    { s: 0, n: "1",
      deva: "ॐ गजाननाय नमः ।",
      iast: "oṁ gajānanāya namaḥ ।",
      en: "The elephant-faced.",
      tel: "గజాననుడు." },
    { s: 0, n: "2",
      deva: "ॐ गणाध्यक्षाय नमः ।",
      iast: "oṁ gaṇādhyakṣāya namaḥ ।",
      en: "Overseer of the gaṇas.",
      tel: "గణముల అధ్యక్షుడు." },
    { s: 0, n: "3",
      deva: "ॐ विघ्नराजाय नमः ।",
      iast: "oṁ vighnarājāya namaḥ ।",
      en: "King of obstacles.",
      tel: "విఘ్నరాజు." },
    { s: 0, n: "4",
      deva: "ॐ विनायकाय नमः ।",
      iast: "oṁ vināyakāya namaḥ ।",
      en: "The leader supreme.",
      tel: "వినాయకుడు." },
    { s: 0, n: "5",
      deva: "ॐ द्वैमातुराय नमः ।",
      iast: "oṁ dvaimāturāya namaḥ ।",
      en: "Son of two mothers.",
      tel: "ఇద్దరు తల్లుల కుమారుడు." },
    { s: 0, n: "6",
      deva: "ॐ द्विमुखाय नमः ।",
      iast: "oṁ dvimukhāya namaḥ ।",
      en: "The two-faced.",
      tel: "ద్విముఖుడు." },
    { s: 0, n: "7",
      deva: "ॐ प्रमुखाय नमः ।",
      iast: "oṁ pramukhāya namaḥ ।",
      en: "The foremost.",
      tel: "ప్రముఖుడు." },
    { s: 0, n: "8",
      deva: "ॐ सुमुखाय नमः ।",
      iast: "oṁ sumukhāya namaḥ ।",
      en: "The fair-faced.",
      tel: "సుముఖుడు." },
    { s: 0, n: "9",
      deva: "ॐ कृतिने नमः ।",
      iast: "oṁ kṛtine namaḥ ।",
      en: "The accomplisher.",
      tel: "కార్యసాధకుడు." },
    { s: 0, n: "10",
      deva: "ॐ सुप्रदीपाय नमः ।",
      iast: "oṁ supradīpāya namaḥ ।",
      en: "Shining brightly.",
      tel: "చక్కగా ప్రకాశించువాడు." },
    { s: 0, n: "11",
      deva: "ॐ सुखनिधये नमः ।",
      iast: "oṁ sukhanidhaye namaḥ ।",
      en: "Treasure-house of happiness.",
      tel: "సుఖములకు నిధి." },
    { s: 0, n: "12",
      deva: "ॐ सुराध्यक्षाय नमः ।",
      iast: "oṁ surādhyakṣāya namaḥ ।",
      en: "Overseer of the gods.",
      tel: "దేవతల అధ్యక్షుడు." },
    { s: 0, n: "13",
      deva: "ॐ सुरारिघ्नाय नमः ।",
      iast: "oṁ surārighnāya namaḥ ।",
      en: "Slayer of the gods' foes.",
      tel: "దేవశత్రువులను సంహరించువాడు." },
    { s: 0, n: "14",
      deva: "ॐ महागणपतये नमः ।",
      iast: "oṁ mahāgaṇapataye namaḥ ।",
      en: "The great lord of the gaṇas.",
      tel: "మహాగణపతి." },
    { s: 0, n: "15",
      deva: "ॐ मान्याय नमः ।",
      iast: "oṁ mānyāya namaḥ ।",
      en: "Worthy of honour.",
      tel: "మాన్యుడు." },
    { s: 0, n: "16",
      deva: "ॐ महाकालाय नमः ।",
      iast: "oṁ mahākālāya namaḥ ।",
      en: "Great Time itself.",
      tel: "మహాకాలుడు." },
    { s: 0, n: "17",
      deva: "ॐ महाबलाय नमः ।",
      iast: "oṁ mahābalāya namaḥ ।",
      en: "Of great strength.",
      tel: "మహాబలుడు." },
    { s: 0, n: "18",
      deva: "ॐ हेरम्बाय नमः ।",
      iast: "oṁ herambāya namaḥ ।",
      en: "Heramba, shelter of the helpless.",
      tel: "హేరంబుడు (దీనుల రక్షకుడు)." },
    { s: 0, n: "19",
      deva: "ॐ लम्बजठराय नमः ।",
      iast: "oṁ lambajaṭharāya namaḥ ।",
      en: "Of pendulous belly.",
      tel: "లంబజఠరుడు." },
    { s: 0, n: "20",
      deva: "ॐ ह्रस्वग्रीवाय नमः ।",
      iast: "oṁ hrasvagrīvāya namaḥ ।",
      en: "Short-necked.",
      tel: "పొట్టి మెడ గలవాడు." },
    { s: 0, n: "21",
      deva: "ॐ महोदराय नमः ।",
      iast: "oṁ mahodarāya namaḥ ।",
      en: "Great-bellied.",
      tel: "మహోదరుడు." },
    { s: 0, n: "22",
      deva: "ॐ मदोत्कटाय नमः ।",
      iast: "oṁ madotkaṭāya namaḥ ।",
      en: "Exultant with ichor.",
      tel: "మదముతో ఉప్పొంగువాడు." },
    { s: 0, n: "23",
      deva: "ॐ महावीराय नमः ।",
      iast: "oṁ mahāvīrāya namaḥ ।",
      en: "The great hero.",
      tel: "మహావీరుడు." },
    { s: 0, n: "24",
      deva: "ॐ मन्त्रिणे नमः ।",
      iast: "oṁ mantriṇe namaḥ ।",
      en: "The counsellor.",
      tel: "మంత్రి (ఆలోచన చెప్పువాడు)." },
    { s: 0, n: "25",
      deva: "ॐ मङ्गलस्वराय नमः ।",
      iast: "oṁ maṅgalasvarāya namaḥ ।",
      en: "Of auspicious voice.",
      tel: "మంగళస్వరుడు." },
    { s: 0, n: "26",
      deva: "ॐ प्रमथाय नमः ।",
      iast: "oṁ pramathāya namaḥ ।",
      en: "Lord of the pramatha hosts.",
      tel: "ప్రమథగణాధిపుడు." },
    { s: 0, n: "27",
      deva: "ॐ प्रथमाय नमः ।",
      iast: "oṁ prathamāya namaḥ ।",
      en: "The first of all.",
      tel: "అందరిలో మొదటివాడు." },
    { s: 0, n: "28",
      deva: "ॐ प्राज्ञाय नमः ।",
      iast: "oṁ prājñāya namaḥ ।",
      en: "The deeply wise.",
      tel: "ప్రాజ్ఞుడు." },
    { s: 0, n: "29",
      deva: "ॐ विघ्नकर्त्रे नमः ।",
      iast: "oṁ vighnakartre namaḥ ।",
      en: "The setter of obstacles.",
      tel: "విఘ్నములను కలిగించువాడు." },
    { s: 0, n: "30",
      deva: "ॐ विघ्नहन्त्रे नमः ।",
      iast: "oṁ vighnahantre namaḥ ।",
      en: "The destroyer of obstacles.",
      tel: "విఘ్నములను హరించువాడు." },
    { s: 0, n: "31",
      deva: "ॐ विश्वनेत्रे नमः ।",
      iast: "oṁ viśvanetre namaḥ ।",
      en: "Eye of the universe.",
      tel: "విశ్వమునకు నేత్రమైనవాడు." },
    { s: 0, n: "32",
      deva: "ॐ विराट्पतये नमः ।",
      iast: "oṁ virāṭpataye namaḥ ।",
      en: "Lord of the cosmic form.",
      tel: "విరాట్పతి." },
    { s: 0, n: "33",
      deva: "ॐ श्रीपतये नमः ।",
      iast: "oṁ śrīpataye namaḥ ।",
      en: "Lord of Śrī.",
      tel: "శ్రీపతి." },
    { s: 0, n: "34",
      deva: "ॐ वाक्पतये नमः ।",
      iast: "oṁ vākpataye namaḥ ।",
      en: "Lord of speech.",
      tel: "వాక్పతి." },
    { s: 0, n: "35",
      deva: "ॐ शृङ्गारिणे नमः ।",
      iast: "oṁ śṛṅgāriṇe namaḥ ।",
      en: "The graceful one.",
      tel: "శృంగారి." },
    { s: 0, n: "36",
      deva: "ॐ आश्रितवत्सलाय नमः ।",
      iast: "oṁ āśritavatsalāya namaḥ ।",
      en: "Tender to those who take refuge.",
      tel: "ఆశ్రితవత్సలుడు." },
    { s: 0, n: "37",
      deva: "ॐ शिवप्रियाय नमः ।",
      iast: "oṁ śivapriyāya namaḥ ।",
      en: "Dear to Śiva.",
      tel: "శివునికి ప్రియమైనవాడు." },
    { s: 0, n: "38",
      deva: "ॐ शीघ्रकारिणे नमः ।",
      iast: "oṁ śīghrakāriṇe namaḥ ।",
      en: "Swift in action.",
      tel: "శీఘ్రముగా చేయువాడు." },
    { s: 0, n: "39",
      deva: "ॐ शाश्वताय नमः ।",
      iast: "oṁ śāśvatāya namaḥ ।",
      en: "The everlasting.",
      tel: "శాశ్వతుడు." },
    { s: 0, n: "40",
      deva: "ॐ बलाय नमः ।",
      iast: "oṁ balāya namaḥ ।",
      en: "Strength itself.",
      tel: "బలస్వరూపుడు." },
    { s: 0, n: "41",
      deva: "ॐ बलोत्थिताय नमः ।",
      iast: "oṁ balotthitāya namaḥ ।",
      en: "Risen up in strength.",
      tel: "బలముతో లేచినవాడు." },
    { s: 0, n: "42",
      deva: "ॐ भवात्मजाय नमः ।",
      iast: "oṁ bhavātmajāya namaḥ ।",
      en: "Son of Bhava.",
      tel: "భవుని (శివుని) కుమారుడు." },
    { s: 0, n: "43",
      deva: "ॐ पुराणपुरुषाय नमः ।",
      iast: "oṁ purāṇapuruṣāya namaḥ ।",
      en: "The ancient person.",
      tel: "పురాణపురుషుడు." },
    { s: 0, n: "44",
      deva: "ॐ पूष्णे नमः ।",
      iast: "oṁ pūṣṇe namaḥ ।",
      en: "The nourisher.",
      tel: "పోషించువాడు." },
    { s: 0, n: "45",
      deva: "ॐ पुष्करोत्क्षिप्तवारिणे नमः ।",
      iast: "oṁ puṣkarotkṣiptavāriṇe namaḥ ।",
      en: "Who tosses up water with the tip of his trunk.",
      tel: "తొండము కొనతో నీటిని పైకి చిమ్మువాడు." },
    { s: 0, n: "46",
      deva: "ॐ अग्रगण्याय नमः ।",
      iast: "oṁ agragaṇyāya namaḥ ।",
      en: "Counted first of all.",
      tel: "అగ్రగణ్యుడు." },
    { s: 0, n: "47",
      deva: "ॐ अग्रपूज्याय नमः ।",
      iast: "oṁ agrapūjyāya namaḥ ।",
      en: "First to be worshipped.",
      tel: "అగ్రపూజ్యుడు." },
    { s: 0, n: "48",
      deva: "ॐ अग्रगामिने नमः ।",
      iast: "oṁ agragāmine namaḥ ।",
      en: "Who goes before.",
      tel: "ముందు నడుచువాడు." },
    { s: 0, n: "49",
      deva: "ॐ मन्त्रकृते नमः ।",
      iast: "oṁ mantrakṛte namaḥ ।",
      en: "Maker of mantra.",
      tel: "మంత్రకర్త." },
    { s: 0, n: "50",
      deva: "ॐ चामीकरप्रभाय नमः ।",
      iast: "oṁ cāmīkaraprabhāya namaḥ ।",
      en: "Radiant as gold.",
      tel: "బంగారు కాంతి గలవాడు." },
    { s: 0, n: "51",
      deva: "ॐ सर्वाय नमः ।",
      iast: "oṁ sarvāya namaḥ ।",
      en: "The all.",
      tel: "సర్వస్వరూపుడు." },
    { s: 0, n: "52",
      deva: "ॐ सर्वोपास्याय नमः ।",
      iast: "oṁ sarvopāsyāya namaḥ ।",
      en: "Adored by all.",
      tel: "అందరిచే ఉపాసింపబడువాడు." },
    { s: 0, n: "53",
      deva: "ॐ सर्वकर्त्रे नमः ।",
      iast: "oṁ sarvakartre namaḥ ।",
      en: "Maker of all.",
      tel: "సర్వకర్త." },
    { s: 0, n: "54",
      deva: "ॐ सर्वनेत्रे नमः ।",
      iast: "oṁ sarvanetre namaḥ ।",
      en: "Eye of all.",
      tel: "అందరికి నేత్రమైనవాడు." },
    { s: 0, n: "55",
      deva: "ॐ सर्वसिद्धिप्रदाय नमः ।",
      iast: "oṁ sarvasiddhipradāya namaḥ ।",
      en: "Giver of every attainment.",
      tel: "సర్వసిద్ధులనిచ్చువాడు." },
    { s: 0, n: "56",
      deva: "ॐ सर्वसिद्धये नमः ।",
      iast: "oṁ sarvasiddhaye namaḥ ।",
      en: "Attainment itself.",
      tel: "సర్వసిద్ధి స్వరూపుడు." },
    { s: 0, n: "57",
      deva: "ॐ पञ्चहस्ताय नमः ।",
      iast: "oṁ pañcahastāya namaḥ ।",
      en: "Five-handed.",
      tel: "పంచహస్తుడు." },
    { s: 0, n: "58",
      deva: "ॐ पार्वतीनन्दनाय नमः ।",
      iast: "oṁ pārvatīnandanāya namaḥ ।",
      en: "Pārvatī's delight.",
      tel: "పార్వతీనందనుడు." },
    { s: 0, n: "59",
      deva: "ॐ प्रभवे नमः ।",
      iast: "oṁ prabhave namaḥ ।",
      en: "The mighty source.",
      tel: "ప్రభువు." },
    { s: 0, n: "60",
      deva: "ॐ कुमारगुरवे नमः ।",
      iast: "oṁ kumāragurave namaḥ ।",
      en: "Elder and teacher of Kumāra.",
      tel: "కుమారస్వామికి గురువు (అన్న)." },
    { s: 0, n: "61",
      deva: "ॐ अक्षोभ्याय नमः ।",
      iast: "oṁ akṣobhyāya namaḥ ।",
      en: "The unshakable.",
      tel: "క్షోభింపజేయరానివాడు." },
    { s: 0, n: "62",
      deva: "ॐ कुञ्जरासुरभञ्जनाय नमः ।",
      iast: "oṁ kuñjarāsurabhañjanāya namaḥ ।",
      en: "Breaker of the elephant demon.",
      tel: "కుంజరాసురుని భంజించినవాడు." },
    { s: 0, n: "63",
      deva: "ॐ प्रमोदाय नमः ।",
      iast: "oṁ pramodāya namaḥ ।",
      en: "Gladness itself.",
      tel: "ప్రమోదుడు." },
    { s: 0, n: "64",
      deva: "ॐ मोदकप्रियाय नमः ।",
      iast: "oṁ modakapriyāya namaḥ ।",
      en: "Lover of modakas.",
      tel: "మోదకప్రియుడు." },
    { s: 0, n: "65",
      deva: "ॐ कान्तिमते नमः ।",
      iast: "oṁ kāntimate namaḥ ।",
      en: "Full of lustre.",
      tel: "కాంతిమంతుడు." },
    { s: 0, n: "66",
      deva: "ॐ धृतिमते नमः ।",
      iast: "oṁ dhṛtimate namaḥ ।",
      en: "Full of steadfastness.",
      tel: "ధైర్యవంతుడు." },
    { s: 0, n: "67",
      deva: "ॐ कामिने नमः ।",
      iast: "oṁ kāmine namaḥ ।",
      en: "The loving.",
      tel: "కామి (ప్రేమ స్వరూపుడు)." },
    { s: 0, n: "68",
      deva: "ॐ कपित्थवनप्रियाय नमः ।",
      iast: "oṁ kapitthavanapriyāya namaḥ ।",
      en: "Fond of the wood-apple grove.",
      tel: "కపిత్థవనము ప్రియమైనవాడు." },
    { s: 0, n: "69",
      deva: "ॐ ब्रह्मचारिणे नमः ।",
      iast: "oṁ brahmacāriṇe namaḥ ।",
      en: "The celibate student.",
      tel: "బ్రహ్మచారి." },
    { s: 0, n: "70",
      deva: "ॐ ब्रह्मरूपिणे नमः ।",
      iast: "oṁ brahmarūpiṇe namaḥ ।",
      en: "Of the form of Brahman.",
      tel: "బ్రహ్మరూపి." },
    { s: 0, n: "71",
      deva: "ॐ ब्रह्मविद्यादिदानभुवे नमः ।",
      iast: "oṁ brahmavidyādidānabhuve namaḥ ।",
      en: "Fount of the gift of brahma-knowledge.",
      tel: "బ్రహ్మవిద్యాదానమునకు మూలమైనవాడు." },
    { s: 0, n: "72",
      deva: "ॐ जिष्णवे नमः ।",
      iast: "oṁ jiṣṇave namaḥ ।",
      en: "The ever-victorious.",
      tel: "జయశీలుడు." },
    { s: 0, n: "73",
      deva: "ॐ विष्णुप्रियाय नमः ।",
      iast: "oṁ viṣṇupriyāya namaḥ ।",
      en: "Dear to Viṣṇu.",
      tel: "విష్ణువుకు ప్రియుడు." },
    { s: 0, n: "74",
      deva: "ॐ भक्तजीविताय नमः ।",
      iast: "oṁ bhaktajīvitāya namaḥ ।",
      en: "The very life of his devotees.",
      tel: "భక్తులకు జీవితమైనవాడు." },
    { s: 0, n: "75",
      deva: "ॐ जितमन्मथाय नमः ।",
      iast: "oṁ jitamanmathāya namaḥ ।",
      en: "Conqueror of desire.",
      tel: "మన్మథుని జయించినవాడు." },
    { s: 0, n: "76",
      deva: "ॐ ऐश्वर्यकारणाय नमः ।",
      iast: "oṁ aiśvaryakāraṇāya namaḥ ।",
      en: "Cause of all sovereignty.",
      tel: "ఐశ్వర్యమునకు కారణమైనవాడు." },
    { s: 0, n: "77",
      deva: "ॐ ज्यायसे नमः ।",
      iast: "oṁ jyāyase namaḥ ।",
      en: "The elder.",
      tel: "జ్యేష్ఠుడు." },
    { s: 0, n: "78",
      deva: "ॐ यक्षकिन्नरसेविताय नमः ।",
      iast: "oṁ yakṣakinnarasevitāya namaḥ ।",
      en: "Served by yakṣas and kinnaras.",
      tel: "యక్షకిన్నరులచే సేవింపబడువాడు." },
    { s: 0, n: "79",
      deva: "ॐ गङ्गासुताय नमः ।",
      iast: "oṁ gaṅgāsutāya namaḥ ।",
      en: "Son of Gaṅgā.",
      tel: "గంగాసుతుడు." },
    { s: 0, n: "80",
      deva: "ॐ गणाधीशाय नमः ।",
      iast: "oṁ gaṇādhīśāya namaḥ ।",
      en: "Overlord of the gaṇas.",
      tel: "గణాధీశుడు." },
    { s: 0, n: "81",
      deva: "ॐ गम्भीरनिनदाय नमः ।",
      iast: "oṁ gambhīraninadāya namaḥ ।",
      en: "Of deep thunderous voice.",
      tel: "గంభీరమైన నాదము గలవాడు." },
    { s: 0, n: "82",
      deva: "ॐ वटवे नमः ।",
      iast: "oṁ vaṭave namaḥ ।",
      en: "The eternal youth.",
      tel: "నిత్యవటువు." },
    { s: 0, n: "83",
      deva: "ॐ अभीष्टवरदायिने नमः ।",
      iast: "oṁ abhīṣṭavaradāyine namaḥ ।",
      en: "Granter of longed-for boons.",
      tel: "అభీష్టవరములనిచ్చువాడు." },
    { s: 0, n: "84",
      deva: "ॐ ज्योतिषे नमः ।",
      iast: "oṁ jyotiṣe namaḥ ।",
      en: "The light itself.",
      tel: "జ్యోతిస్వరూపుడు." },
    { s: 0, n: "85",
      deva: "ॐ भक्तनिधये नमः ।",
      iast: "oṁ bhaktanidhaye namaḥ ।",
      en: "Treasure of his devotees.",
      tel: "భక్తులకు నిధి." },
    { s: 0, n: "86",
      deva: "ॐ भावगम्याय नमः ।",
      iast: "oṁ bhāvagamyāya namaḥ ।",
      en: "Reached through feeling alone.",
      tel: "భావముచే మాత్రమే చేరదగినవాడు." },
    { s: 0, n: "87",
      deva: "ॐ मङ्गलप्रदाय नमः ।",
      iast: "oṁ maṅgalapradāya namaḥ ।",
      en: "Giver of auspiciousness.",
      tel: "మంగళప్రదుడు." },
    { s: 0, n: "88",
      deva: "ॐ अव्यक्ताय नमः ।",
      iast: "oṁ avyaktāya namaḥ ।",
      en: "The unmanifest.",
      tel: "అవ్యక్తుడు." },
    { s: 0, n: "89",
      deva: "ॐ अप्राकृतपराक्रमाय नमः ।",
      iast: "oṁ aprākṛtaparākramāya namaḥ ।",
      en: "Of unworldly valour.",
      tel: "లోకాతీత పరాక్రమము గలవాడు." },
    { s: 0, n: "90",
      deva: "ॐ सत्यधर्मिणे नमः ।",
      iast: "oṁ satyadharmiṇe namaḥ ।",
      en: "Whose law is truth.",
      tel: "సత్యధర్ముడు." },
    { s: 0, n: "91",
      deva: "ॐ सखये नमः ।",
      iast: "oṁ sakhaye namaḥ ।",
      en: "The friend.",
      tel: "సఖుడు (మిత్రుడు)." },
    { s: 0, n: "92",
      deva: "ॐ सरसाम्बुनिधये नमः ।",
      iast: "oṁ sarasāmbunidhaye namaḥ ।",
      en: "Ocean of sweet waters.",
      tel: "తీయని జలముల నిధి." },
    { s: 0, n: "93",
      deva: "ॐ महेशाय नमः ।",
      iast: "oṁ maheśāya namaḥ ।",
      en: "The great lord.",
      tel: "మహేశుడు." },
    { s: 0, n: "94",
      deva: "ॐ दिव्याङ्गाय नमः ।",
      iast: "oṁ divyāṅgāya namaḥ ।",
      en: "Of divine body.",
      tel: "దివ్యమైన అంగములు గలవాడు." },
    { s: 0, n: "95",
      deva: "ॐ मणिकिङ्किणीमेखलाय नमः ।",
      iast: "oṁ maṇikiṅkiṇīmekhalāya namaḥ ।",
      en: "Girdled with a belt of gem-bells.",
      tel: "మణికింకిణుల మొలనూలు గలవాడు." },
    { s: 0, n: "96",
      deva: "ॐ समस्तदेवतामूर्तये नमः ।",
      iast: "oṁ samastadevatāmūrtaye namaḥ ।",
      en: "The form of all deities in one.",
      tel: "సమస్త దేవతల మూర్తి." },
    { s: 0, n: "97",
      deva: "ॐ सहिष्णवे नमः ।",
      iast: "oṁ sahiṣṇave namaḥ ।",
      en: "The forbearing.",
      tel: "సహనశీలుడు." },
    { s: 0, n: "98",
      deva: "ॐ सततोत्थिताय नमः ।",
      iast: "oṁ satatotthitāya namaḥ ।",
      en: "Ever risen and ready.",
      tel: "సదా సంసిద్ధుడు." },
    { s: 0, n: "99",
      deva: "ॐ विघातकारिणे नमः ।",
      iast: "oṁ vighātakāriṇe namaḥ ।",
      en: "Who strikes down hindrance.",
      tel: "అడ్డంకులను కూల్చువాడు." },
    { s: 0, n: "100",
      deva: "ॐ विश्वग्दृशे नमः ।",
      iast: "oṁ viśvagdṛśe namaḥ ।",
      en: "Seeing in every direction.",
      tel: "అన్ని దిక్కులలో చూచువాడు." },
    { s: 0, n: "101",
      deva: "ॐ विश्वरक्षाकृते नमः ।",
      iast: "oṁ viśvarakṣākṛte namaḥ ।",
      en: "Guardian of the universe.",
      tel: "విశ్వమును రక్షించువాడు." },
    { s: 0, n: "102",
      deva: "ॐ कल्याणगुरवे नमः ।",
      iast: "oṁ kalyāṇagurave namaḥ ।",
      en: "Teacher of welfare.",
      tel: "కల్యాణగురువు." },
    { s: 0, n: "103",
      deva: "ॐ उन्मत्तवेषाय नमः ।",
      iast: "oṁ unmattaveṣāya namaḥ ।",
      en: "Clad in wild guise.",
      tel: "ఉన్మత్తవేషధారి." },
    { s: 0, n: "104",
      deva: "ॐ अपराजिते नमः ।",
      iast: "oṁ aparājite namaḥ ।",
      en: "The unconquered.",
      tel: "అపరాజితుడు." },
    { s: 0, n: "105",
      deva: "ॐ समस्तजगदाधाराय नमः ।",
      iast: "oṁ samastajagadādhārāya namaḥ ।",
      en: "Support of all the worlds.",
      tel: "సమస్త జగత్తులకు ఆధారము." },
    { s: 0, n: "106",
      deva: "ॐ सर्वैश्वर्यप्रदाय नमः ।",
      iast: "oṁ sarvaiśvaryapradāya namaḥ ।",
      en: "Giver of every lordship.",
      tel: "సర్వైశ్వర్యములనిచ్చువాడు." },
    { s: 0, n: "107",
      deva: "ॐ आक्रान्तचिदचित्प्रभवे नमः ।",
      iast: "oṁ ākrāntacidacitprabhave namaḥ ।",
      en: "Master pervading spirit and matter alike.",
      tel: "చిత్తు అచిత్తులను వ్యాపించిన ప్రభువు." },
    { s: 0, n: "108",
      deva: "ॐ श्रीविघ्नेश्वराय नमः ।",
      iast: "oṁ śrīvighneśvarāya namaḥ ।",
      en: "The blessed lord of obstacles.",
      tel: "శ్రీ విఘ్నేశ్వరుడు." },
  ],
},

{
  deities: ["ganesha"],
  title: "Vātāpi Gaṇapatiṁ Bhaje",
  blurb: "Muttusvāmī Dīkṣitar in rāga Haṁsadhvani — the Gaṇapati of Vātāpi, sung at the head of concerts across the Karnatic world.",
  sections: [{ tel: "పల్లవి", roman: "Pallavi" }, { tel: "అనుపల్లవి", roman: "Anupallavi" }, { tel: "చరణం", roman: "Caraṇam" }],
  verses: [
    { s: 0, n: null,
      deva: "वातापि गणपतिं भजेऽहं\nवारणास्यं वरप्रदं श्री ॥",
      iast: "vātāpi gaṇapatiṁ bhaje'haṁ\nvāraṇāsyaṁ varapradaṁ śrī ॥",
      en: "I worship the Gaṇapati of Vātāpi — the elephant-faced, the giver of boons, the auspicious.",
      tel: "వాతాపి గణపతిని భజించుచున్నాను — వారణాస్యుని (గజముఖుని), వరప్రదుని, శ్రీస్వరూపుని." },
    { s: 1, n: null,
      deva: "भूतादिसंसेवितचरणं\nभूतभौतिकप्रपञ्चभरणम् ।\nवीतरागिणं विनतयोगिनं\nविश्वकारणं विघ्नवारणम् ॥",
      iast: "bhūtādi-saṁsevita-caraṇaṁ\nbhūta-bhautika-prapañca-bharaṇam ।\nvīta-rāgiṇaṁ vinata-yoginaṁ\nviśva-kāraṇaṁ vighna-vāraṇam ॥",
      en: "His feet attended by the bhūtas and all the hosts of beings; bearer of the world of elements and all their compounds; free of passion, bowed to by the yogins; cause of the universe, warder-off of obstacles.",
      tel: "భూతగణాదులచే సేవింపబడు చరణములవాడు; పంచభూత భౌతిక ప్రపంచమును భరించువాడు; రాగరహితుడు, యోగులచే నమస్కరింపబడువాడు; విశ్వకారణుడు, విఘ్నవారణుడు." },
    { s: 2, n: null,
      deva: "पुरा कुम्भसम्भवमुनिवर-\nप्रपूजितं त्रिकोणमध्यगतम् ।\nमुरारिप्रमुखाद्युपासितं\nमूलाधारक्षेत्रस्थितम् ।\nपरादिचत्वारिवागात्मकं\nप्रणवस्वरूपवक्रतुण्डम् ।\nनिरन्तरं निटिलचन्द्रखण्डं\nनिजवामकरविधृतेक्षुदण्डम् ॥",
      iast: "purā kumbha-sambhava-munivara-\nprapūjitaṁ trikoṇa-madhya-gatam ।\nmurāri-pramukhādy-upāsitaṁ\nmūlādhāra-kṣetra-sthitam ।\nparādi-catvāri-vāg-ātmakaṁ\npraṇava-svarūpa-vakratuṇḍam ।\nnirantaraṁ niṭila-candra-khaṇḍaṁ\nnija-vāma-kara-vidhṛtekṣu-daṇḍam ॥",
      en: "Worshipped of old by the great sage born of the jar — Agastya; seated at the centre of the triangle; adored by Murāri and the foremost of gods; abiding in the field of the mūlādhāra; the self of the four levels of speech beginning with parā; the curved-trunked whose form is the praṇava itself; the moon's digit ever on his brow; a stalk of sugarcane held in his left hand.",
      tel: "పూర్వము కుంభసంభవుడైన అగస్త్య మునివరునిచే పూజింపబడినవాడు; త్రికోణ మధ్యమున ఉన్నవాడు; మురారి మొదలగు దేవశ్రేష్ఠులచే ఉపాసింపబడువాడు; మూలాధార క్షేత్రమున నివసించువాడు; పరాది నాలుగు వాక్కుల స్వరూపుడు; ప్రణవస్వరూపుడైన వక్రతుండుడు; నుదుటిపై నిరంతరము చంద్రఖండము గలవాడు; తన ఎడమచేత ఇక్షుదండమును ధరించినవాడు." },
    { s: 2, n: null,
      deva: "कराम्बुजपाशबीजापूरं\nकलुषविदूरं भूताकारम् ।\nहरादिगुरुगुहतोषितबिम्बं\nहंसध्वनिभूषितहेरम्बम् ॥",
      iast: "karāmbuja-pāśa-bījāpūraṁ\nkaluṣa-vidūraṁ bhūtākāram ।\nharādi-guruguha-toṣita-bimbaṁ\nhaṁsadhvani-bhūṣita-herambam ॥",
      en: "Noose and citron in his lotus hands; far from every stain, vast of form; his image the delight of Hara and of Guruguha; Heramba adorned by Haṁsadhvani itself. Guruguha is Dīkṣitar's signature, woven into every kṛti — as is the name of the rāga.",
      tel: "కరకమలములలో పాశము, బీజపూర ఫలము గలవాడు; కల్మషమునకు దూరుడు, మహాకారుడు; హరాదులకు, గురుగుహునికి సంతోషమునిచ్చు స్వరూపము గలవాడు; హంసధ్వని రాగముచే అలంకరింపబడిన హేరంబుడు. గురుగుహ అనునది దీక్షితుల ముద్ర; రాగనామముతో పాటు కృతిలో అల్లబడినది." },
  ],
},

{
  deities: ["ganesha"],
  title: "Mahāgaṇapatiṁ Manasā Smarāmi",
  blurb: "Dīkṣitar in the great Nāṭa rāga — one sweep of pallavi and caraṇam, remembering the great Gaṇapati in the mind.",
  sections: [{ tel: "పల్లవి", roman: "Pallavi" }, { tel: "సమష్టి చరణం", roman: "Samaṣṭi Caraṇam" }],
  verses: [
    { s: 0, n: null,
      deva: "महागणपतिं मनसा स्मरामि\nवसिष्ठवामदेवादिवन्दितम् ॥",
      iast: "mahā-gaṇapatiṁ manasā smarāmi\nvasiṣṭha-vāmadevādi-vanditam ॥",
      en: "I remember the great Gaṇapati in my mind — saluted by Vasiṣṭha, Vāmadeva and the sages.",
      tel: "మహాగణపతిని మనస్సున స్మరించుచున్నాను — వసిష్ఠ వామదేవాది మునులచే వందితుని." },
    { s: 1, n: null,
      deva: "महादेवसुतं गुरुगुहनुतं\nमारकोटिप्रकाशं शान्तम् ।\nमहाकाव्यनाटकादिप्रियं\nमूषिकवाहनं मोदकप्रियम् ॥",
      iast: "mahādeva-sutaṁ guruguha-nutaṁ\nmāra-koṭi-prakāśaṁ śāntam ।\nmahā-kāvya-nāṭakādi-priyaṁ\nmūṣika-vāhanaṁ modaka-priyam ॥",
      en: "Son of Mahādeva, praised by Guruguha; radiant as ten million gods of love, yet serene; fond of the great poems and dramas; mouse-borne, lover of modakas.",
      tel: "మహాదేవుని కుమారుని, గురుగుహునిచే నుతింపబడినవానిని; కోటి మన్మథుల కాంతి గలవానిని, శాంతుని; మహాకావ్య నాటకాదులయందు ప్రీతి గలవానిని; మూషికవాహనుని, మోదకప్రియుని." },
  ],
},

/* Mahāgaṇapati Stotram — Śrī Rāghava Caitanya. Mūla from the
   sanskritdocuments recension (proofread, scan-backed), checked
   against Stotranidhi. Two pāda-breaks in the e-text fall inside a
   word and were re-set where the metre puts them: v2 at yaṁ vidu-
   / -stasmai, v14 at huṁ- / -kārākṣipta. Verses 1–14 are
   śārdūlavikrīḍita, 15 sragdharā, 16 praharṣiṇī. */
{
  deities: ["ganesha"],
  title: "Mahāgaṇapati Stotram",
  blurb: "Rāghava Caitanya hides the mūla-mantra inside the second verse, then walks the whole yantra — the ocean of sugarcane juice, the jewelled island, the six gaṇa-lords in the hexagram, the gods waiting at their four trees.",
  sections: [{ tel: "స్తోత్రం", roman: "Stotram" }, { tel: "ఫలశ్రుతి", roman: "The Fruit of Recitation" }],
  verses: [
    { s: 0, n: "1",
      deva: "योगं योगविदां विधूतविविधव्यासङ्गशुद्धाशय-\nप्रादुर्भूतसुधारसप्रसृमरध्यानास्पदाध्यासिनाम् ।\nआनन्दप्लवमानबोधमधुरामोदच्छटामेदुरं\nतं भूमानमुपास्महे परिणतं दन्तावलास्यात्मना ॥",
      iast: "yogaṁ yogavidāṁ vidhūta-vividha-vyāsaṅga-śuddhāśaya-\nprādurbhūta-sudhārasa-prasṛmara-dhyānāspadādhyāsinām ।\nānanda-plavamāna-bodha-madhurāmoda-cchaṭā-meduraṁ\ntaṁ bhūmānam upāsmahe pariṇataṁ dantāvalāsyātmanā ॥",
      en: "We worship that Plenum — the very yoga of those who know yoga, who dwell in the seat of meditation where, every scattered attachment shaken off and the heart made clear, the nectar has welled up and spread; thick with the sweet burst of fragrance that is awareness afloat in bliss — the Infinite, become embodied with an elephant's face.",
      tel: "నానావిధ ఆసక్తులను వదలి నిర్మలమైన హృదయమున సుధారసము ఉప్పొంగి వ్యాపించగా ధ్యానాస్పదమున నిలిచిన యోగవిదుల యోగస్వరూపుడు; ఆనందమున తేలియాడు బోధ యొక్క మధురామోద ఛటచే దట్టమైనవాడు — గజముఖ రూపమున పరిణమించిన ఆ భూమస్వరూపుని ఉపాసించుచున్నాము." },
    { s: 0, n: "2",
      deva: "तारश्रीपरशक्तिकामवसुधारूपानुगं यं विदु-\nस्तस्मै स्तात्प्रणतिर्गणाधिपतये यो रागिणाभ्यर्थ्यते ।\nआमन्त्र्य प्रथमं वरेति वरदेत्यार्तेन सर्वं जनं\nस्वामिन्मे वशमानयेति सततं स्वाहादिभिः पूजितः ॥",
      iast: "tāra-śrī-para-śakti-kāma-vasudhā-rūpānugaṁ yaṁ vidu-\nstasmai stāt praṇatir gaṇādhipataye yo rāgiṇābhyarthyate ।\nāmantrya prathamaṁ vareti varadety ārtena sarvaṁ janaṁ\nsvāmin me vaśamānayeti satataṁ svāhādibhiḥ pūjitaḥ ॥",
      en: "Salutation be to that lord of the gaṇas whom the knowers know as following the form of tāra, śrī, parāśakti, kāma and vasudhā — Oṁ, Śrīṁ, Hrīṁ, Klīṁ, Glauṁ; who is entreated by the longing; who is worshipped without end with svāhā and the rest, addressed first as vara, then as varada, and then with the ache of the plea — Lord, bring every soul under my sway.",
      tel: "తార (ఓం), శ్రీం, పరాశక్తి (హ్రీం), కామ (క్లీం), వసుధా (గ్లౌం) — ఈ బీజముల రూపమును అనుసరించువాడని తెలిసినవారు ఎవరిని ఎఱుగుదురో; రాగవంతులచే ప్రార్థింపబడువాడో; 'వర' అని, 'వరద' అని మొదట సంబోధించి, 'స్వామీ, సర్వజనమును నాకు వశము చేయుము' అను ఆర్తితో స్వాహాదులచే నిరంతరము పూజింపబడువాడో — ఆ గణాధిపతికి నా ప్రణామము." },
    { s: 0, n: "3",
      deva: "कल्लोलाञ्चलचुम्बिताम्बुदतताविक्षुद्रवाम्भोनिधौ\nद्वीपे रत्नमये सुरद्रुमवनामोदैकमेदस्विनि ।\nमूले कल्पतरोर्महामणिमये पीठेऽक्षराम्भोरुहे\nषट्कोणाकलितत्रिकोणरचनासत्कर्णिकेऽमुं भजे ॥",
      iast: "kallolāñcala-cumbitāmbuda-tatāvikṣu-dravāmbhonidhau\ndvīpe ratnamaye suradruma-vanāmodaika-medasvini ।\nmūle kalpataror mahāmaṇimaye pīṭhe'kṣarāmbhoruhe\nṣaṭkoṇākalita-trikoṇa-racanā-satkarṇike'muṁ bhaje ॥",
      en: "In the ocean of sugarcane juice, whose wave-fringes kiss the reach of the clouds; on the island of gems, rich with the single fragrance of the grove of wish-granting trees; at the root of the kalpa tree, upon a seat of great jewels — the imperishable lotus whose fair pericarp is the triangle drawn within the hexagram — there I worship him.",
      tel: "తరంగముల అంచులు మేఘపంక్తిని ముద్దాడు ఇక్షురస సముద్రమునందు; కల్పవృక్ష వనముల ఏకైక పరిమళముచే పరిపుష్టమైన రత్నద్వీపమునందు; కల్పతరువు మూలమున మహామణిమయ పీఠముపై — షట్కోణమునందు రచింపబడిన త్రికోణమే కర్ణికగా గల అక్షర పద్మమునందు — ఆ స్వామిని భజించుచున్నాను." },
    { s: 0, n: "4",
      deva: "चक्रप्रासरसालकार्मुकगदासद्बीजपूरद्विज-\nव्रीह्यग्रोत्पलपाशपङ्कजकरं शुण्डाग्रजाग्रद्घटम् ।\nआश्लिष्टं प्रियया सरोजकरया रत्नस्फुरद्भूषया\nमाणिक्यप्रतिमं महागणपतिं विश्वेशमाशास्महे ॥",
      iast: "cakra-prāsa-rasāla-kārmuka-gadā-sad-bījapūra-dvija-\nvrīhyagrotpala-pāśa-paṅkaja-karaṁ śuṇḍāgra-jāgrad-ghaṭam ।\nāśliṣṭaṁ priyayā saroja-karayā ratna-sphurad-bhūṣayā\nmāṇikya-pratimaṁ mahāgaṇapatiṁ viśveśam āśāsmahe ॥",
      en: "Discus and dart, mango and bow, mace and fine citron, his own tusk, a sprig of paddy, blue lily, noose and lotus in his hands, a pot alight at the tip of his trunk; embraced by his beloved, a lotus in her hand, her ornaments flashing with gems; ruby-hued — Mahāgaṇapati, lord of all, is what we ask for.",
      tel: "చక్రము, ప్రాసము, రసాలము, ధనుస్సు, గద, శ్రేష్ఠమైన బీజపూరము, దంతము, వరికంకి, ఉత్పలము, పాశము, పంకజము చేతులయందు ధరించినవాడు; తొండము కొనన మెరయు కలశము గలవాడు; పద్మము చేబూని రత్నభూషణములతో మెరయు ప్రియురాలిచే ఆలింగనము చేయబడినవాడు; మాణిక్యము వంటివాడు — విశ్వేశుడైన ఆ మహాగణపతిని ఆశించుచున్నాము." },
    { s: 0, n: "5",
      deva: "दानाम्भःपरिमेदुरप्रसृमरव्यालम्बिरोलम्बभृत्\nसिन्दूरारुणगण्डमण्डलयुगव्याजात्प्रशस्तिद्वयम् ।\nत्रैलोक्येष्टविधानवर्णसुभगं यः पद्मरागोपमं\nधत्ते स श्रियमातनोतु सततं देवो गणानां पतिः ॥",
      iast: "dānāmbhaḥ-parimedura-prasṛmara-vyālambi-rolamba-bhṛt\nsindūrāruṇa-gaṇḍa-maṇḍala-yuga-vyājāt praśasti-dvayam ।\ntrailokyeṣṭa-vidhāna-varṇa-subhagaṁ yaḥ padmarāgopamaṁ\ndhatte sa śriyam ātanotu satataṁ devo gaṇānāṁ patiḥ ॥",
      en: "His two temple-globes, red as vermilion, thick with flowing ichor and hung about with spreading swarms of bees, are as though two panegyrics glowing like ruby, written in letters made lovely by the granting of everything the three worlds desire. May the god who bears them, the lord of the gaṇas, spread prosperity without end.",
      tel: "స్రవించు మదజలముచే దట్టమై, వ్యాపించి వ్రేలాడు తుమ్మెద గుంపులను దాల్చి, సిందూరమువలె అరుణమైన రెండు గండస్థలములు — ముల్లోకముల కోరికలను తీర్చు అక్షరములచే సుభగమై పద్మరాగమువలె వెలుగు రెండు ప్రశస్తులో అన్నట్లున్నవి. వాటిని ధరించిన ఆ గణపతి దేవుడు సతతము శ్రీని విస్తరింపజేయుగాక." },
    { s: 0, n: "6",
      deva: "भ्राम्यन्मन्दरघूर्णनापरवशक्षीराब्धिवीचिच्छटा-\nसच्छायाश्चलचामरव्यतिकरश्रीगर्वसर्वङ्कषाः ।\nदिक्कान्ताघनसारचन्दनरसासाराः श्रयन्तां मनः\nस्वच्छन्दप्रसरप्रलिप्तवियतो हेरम्बदन्तत्विषः ॥",
      iast: "bhrāmyan-mandara-ghūrṇanā-paravaśa-kṣīrābdhi-vīci-cchaṭā-\nsacchāyāś cala-cāmara-vyatikara-śrī-garva-sarvaṅkaṣāḥ ।\ndik-kāntā-ghana-sāra-candana-rasāsārāḥ śrayantāṁ manaḥ\nsvacchanda-prasara-pralipta-viyato heramba-danta-tviṣaḥ ॥",
      en: "Like the spray thrown up by the Milk Ocean helpless under the whirling Mandara; outdoing the proud grace of chowries in motion; a downpour of camphor and sandal paste for the ladies of the quarters; smearing the open sky with their unchecked spread — may the rays of Heramba's tusk take up their dwelling in my mind.",
      tel: "త్రిప్పబడు మందర పర్వతమువలన పరవశమైన క్షీరసాగర తరంగముల తుంపరల వంటివి; కదలు చామరముల శ్రీగర్వమును మించునవి; దిక్కాంతలకు కర్పూర చందన రసముల వర్షము వంటివి; స్వేచ్ఛగా వ్యాపించి ఆకాశమును పూసినవి — హేరంబుని దంతకాంతులు నా మనస్సును ఆశ్రయించుగాక." },
    { s: 0, n: "7",
      deva: "मुक्ताजालकरम्बितप्रविकसन्माणिक्यपुञ्जच्छटा-\nकान्ताः कम्बुकदम्बचुम्बितघनाम्भोजप्रवालोपमाः ।\nज्योत्स्नापूरतरङ्गमन्थरतरत्सन्ध्यावयस्याश्चिरं\nहेरम्बस्य जयन्ति दन्तकिरणाकीर्णाः शरीरत्विषः ॥",
      iast: "muktā-jāla-karambita-pravikasan-māṇikya-puñja-cchaṭā-\nkāntāḥ kambu-kadamba-cumbita-ghanāmbhoja-pravālopamāḥ ।\njyotsnā-pūra-taraṅga-manthara-tarat-sandhyā-vayasyāś ciraṁ\nherambasya jayanti danta-kiraṇākīrṇāḥ śarīra-tviṣaḥ ॥",
      en: "Lovely as the burst of a heap of kindled rubies threaded through with nets of pearl; like coral and dense lotus kissed by a cluster of conches; long companions of the twilight that drifts slow on a tide of moonlight — victorious are the body-rays of Heramba, strewn through with the light of his tusk.",
      tel: "ముత్యాల జాలముతో కలసిన వికసించు మాణిక్య పుంజముల ఛటవలె కాంతిమంతములు; శంఖ సముదాయముచే ముద్దాడబడిన దట్టమైన పద్మముల, పగడముల వంటివి; వెన్నెల ప్రవాహ తరంగములపై మెల్లగా సాగు సంధ్యకు చిరకాల చెలికత్తెలు — దంతకిరణములతో నిండిన హేరంబుని శరీరకాంతులు జయించుచున్నవి." },
    { s: 0, n: "8",
      deva: "शुण्डाग्राकलितेन हेमकलशेनावर्जितेन क्षरन्\nनानारत्नचयेन साधकजनान्सम्भावयन्कोटिशः ।\nदानामोदविनोदलुब्धमधुपप्रोत्सारणाविर्भवत्\nकर्णान्दोलनखेलनो विजयते देवो गणग्रामणीः ॥",
      iast: "śuṇḍāgrākalitena hema-kalaśenāvarjitena kṣaran\nnānā-ratna-cayena sādhaka-janān sambhāvayan koṭiśaḥ ।\ndānāmoda-vinoda-lubdha-madhupa-protsāraṇāvirbhavat\nkarṇāndolana-khelano vijayate devo gaṇa-grāmaṇīḥ ॥",
      en: "Tipping the golden pot he holds at his trunk's tip, he showers heaps of every kind of gem and honours seekers by the million; his ears swinging in play as he waves off the bees greedy for the sport of his fragrant ichor — victorious is the god, foremost of the gaṇas.",
      tel: "తొండము కొనన పట్టుకొనిన బంగారు కలశమును వంచి, నానారత్న రాశులను కురిపించుచు సాధకులను కోటానుకోట్లుగా సత్కరించుచు; మదపరిమళ వినోదమునకు లోభించిన తుమ్మెదలను తోలుటకై కదలు చెవుల ఆట గలవాడు — గణములకు అగ్రణియైన ఆ దేవుడు జయించుచున్నాడు." },
    { s: 0, n: "9",
      deva: "हेरम्बं प्रणमामि यस्य पुरतः शाण्डिल्यमूले श्रिया\nबिभ्रत्याम्बुरुहे समं मधुरिपुस्ते शङ्खचक्रे वहन् ।\nन्यग्रोधस्य तले सहाद्रिसुतया शम्भुस्तथा दक्षिणे\nबिभ्राणः परशुं त्रिशूलमितया पाशाङ्कुशाभ्यां सह ॥",
      iast: "herambaṁ praṇamāmi yasya purataḥ śāṇḍilya-mūle śriyā\nbibhratyāmburuhe samaṁ madhuripus te śaṅkha-cakre vahan ।\nnyagrodhasya tale sahādri-sutayā śambhus tathā dakṣiṇe\nbibhrāṇaḥ paraśuṁ triśūlam itayā pāśāṅkuśābhyāṁ saha ॥",
      en: "I bow to Heramba — before whom, at the foot of the śāṇḍilya tree, stands Madhu's foe bearing conch and discus, with Śrī who holds her lotuses; and to the south, beneath the banyan, Śambhu with the mountain's daughter, he bearing axe and trident, she come with noose and goad.",
      tel: "హేరంబునికి ప్రణమిల్లుచున్నాను — ఎవని ఎదుట శాండిల్య వృక్షమూలమున, పద్మములను ధరించిన శ్రీదేవితో కూడి శంఖచక్రములు దాల్చిన మధురిపువు నిలిచియుండునో; దక్షిణమున న్యగ్రోధ వృక్షము క్రింద, పరశువు త్రిశూలములు ధరించిన శంభుడు పాశాంకుశములు గల అద్రిసుతతో కూడి యుండునో." },
    { s: 0, n: "10",
      deva: "पश्चात्पिप्पलमाश्रितो रतिपतिर्देवस्य रत्योत्पले\nबिभ्रत्या सममैक्षवं धनुरिषून्पौष्पान्वहन्पञ्च च ।\nवामे चक्रगदाधरः स भगवान्क्रोडः प्रियङ्गोस्तले\nहस्तोद्यच्छुकशालिमञ्जरिकया देव्या धरण्या सह ॥",
      iast: "paścāt pippalam āśrito ratipatir devasya ratyotpale\nbibhratyā samam aikṣavaṁ dhanur iṣūn pauṣpān vahan pañca ca ।\nvāme cakra-gadā-dharaḥ sa bhagavān kroḍaḥ priyaṅgos tale\nhastodyac-chuka-śāli-mañjarikayā devyā dharaṇyā saha ॥",
      en: "Behind, resting on the pippala, the lord of Rati with Rati who holds a blue lily — he bearing the sugarcane bow and his five flower-arrows. On the left, beneath the priyaṅgu, the Boar, bearer of discus and mace, with the goddess Earth, a parrot on the sprig of paddy lifted in her hand.",
      tel: "వెనుక పిప్పల వృక్షమును ఆశ్రయించి, ఉత్పలము ధరించిన రతీదేవితో కూడి, ఇక్షు ధనువును ఐదు పుష్పబాణములను దాల్చిన మన్మథుడు. ఎడమవైపు ప్రియంగు చెట్టు క్రింద, చక్రగదాధరుడైన క్రోడస్వామి, చేతిలో ఎత్తిన శాలిమంజరిపై చిలుకతో ఉన్న ధరణీదేవితో కూడి యుండును." },
    { s: 0, n: "11",
      deva: "षट्कोणाश्रिषु षट्सु षड्गजमुखाः पाशाङ्कुशाभीवरान्\nबिभ्राणाः प्रमदासखाः पृथुमहाशोणाश्मपुञ्जत्विषः ।\nआमोदः पुरतः प्रमोदसुमुखौ तं चाभितो दुर्मुखः\nपश्चात्पार्श्वगतोऽस्य विघ्न इति यो यो विघ्नकर्तेति च ॥",
      iast: "ṣaṭkoṇāśriṣu ṣaṭsu ṣaḍ-gaja-mukhāḥ pāśāṅkuśābhī-varān\nbibhrāṇāḥ pramadā-sakhāḥ pṛthu-mahā-śoṇāśma-puñja-tviṣaḥ ।\nāmodaḥ purataḥ pramoda-sumukhau taṁ cābhito durmukhaḥ\npaścāt pārśva-gato'sya vighna iti yo yo vighna-karteti ca ॥",
      en: "At the six angles of the hexagram, six elephant-faced ones with their consorts, bearing noose and goad, the sign of fearlessness and the boon, glowing like a great heap of ruby: Āmoda in front, Pramoda and Sumukha to either side of him, Durmukha behind, and at his flanks the one called Vighna and the one called Vighnakartā.",
      tel: "షట్కోణపు ఆరు కొనలయందు ఆరుగురు గజముఖులు — పాశము, అంకుశము, అభయము, వరము ధరించి, ప్రమదలతో కూడి, పెద్ద మాణిక్య రాశివంటి కాంతి గలవారు: ఎదుట ఆమోదుడు; అతనికి ఇరుప్రక్కల ప్రమోదుడు, సుముఖుడు; వెనుక దుర్ముఖుడు; ప్రక్కలయందు విఘ్నుడు, విఘ్నకర్త అనువారు." },
    { s: 0, n: "12",
      deva: "आमोदादिगणेश्वरप्रियतमास्तत्रैव नित्यं स्थिताः\nकान्ताश्लेषरसज्ञमन्थरदृशः सिद्धिः समृद्धिस्ततः ।\nकान्तिर्या मदनावतीत्यपि तथा कल्पेषु या गीयते\nसाऽन्या याऽपि मदद्रवा तदपरा द्राविण्यमूः पूजिताः ॥",
      iast: "āmodādi-gaṇeśvara-priyatamās tatraiva nityaṁ sthitāḥ\nkāntāśleṣa-rasajña-manthara-dṛśaḥ siddhiḥ samṛddhis tataḥ ।\nkāntir yā madanāvatīty api tathā kalpeṣu yā gīyate\nsā'nyā yā'pi madadravā tad-aparā drāviṇy amūḥ pūjitāḥ ॥",
      en: "The dearest consorts of Āmoda and the other gaṇa-lords stand there always, their glances slow with the savour of a lover's embrace: Siddhi, Samṛddhi, then Kānti, and she whom the kalpas sing as Madanāvatī, and another, Madadravā, and beyond her Drāviṇī — these are the worshipped.",
      tel: "ఆమోదాది గణేశ్వరుల ప్రియతమలు అచ్చటనే నిత్యము నిలిచియుందురు — ప్రియుల ఆలింగన రసమెఱిగిన మందమైన చూపులు గలవారు: సిద్ధి, సమృద్ధి, పిమ్మట కాంతి, కల్పములయందు మదనావతి అని కీర్తింపబడునది, ఇంకొకతె మదద్రవ, ఆ పైన ద్రావిణి — వీరు పూజింపబడుదురు." },
    { s: 0, n: "13",
      deva: "आश्लिष्टौ वसुधेत्यथो वसुमती ताभ्यां सितालोहितौ\nवर्षन्तौ वसुपार्श्वयोर्विलसतस्तौ शङ्खपद्मौ निधी ।\nअङ्गान्यन्वथ मातरश्च परितः शक्रादयोऽब्जाश्रया-\nस्तद्बाह्ये कुलिशादयः परिपतत्कालानलज्योतिषः ॥",
      iast: "āśliṣṭau vasudhety atho vasumatī tābhyāṁ sitālohitau\nvarṣantau vasu pārśvayor vilasatas tau śaṅkha-padmau nidhī ।\naṅgāny anv atha mātaraś ca paritaḥ śakrādayo'bjāśrayā-\nstad-bāhye kuliśādayaḥ paripatat-kālānala-jyotiṣaḥ ॥",
      en: "Embraced by Vasudhā and Vasumatī, the two treasures Śaṅkha and Padma — one white, one red — shine at either side of him, raining wealth. Then the limb-deities and the mothers, and all around them Indra and the rest upon their lotuses; outside these the thunderbolt and the other weapons, blazing like the fire of time as it falls.",
      tel: "వసుధ, వసుమతి అనువారిచే ఆలింగనము చేయబడి, తెలుపు ఎరుపు వన్నెల శంఖ పద్మ నిధులు రెండు ఇరుప్రక్కల ధనమును వర్షించుచు ప్రకాశించును. పిమ్మట అంగదేవతలు, మాతృకలు, చుట్టును పద్మములపై శక్రాదులు; వారికి వెలుపల కులిశాది ఆయుధములు — పడుచున్న కాలాగ్నివంటి తేజస్సు గలవి." },
    { s: 0, n: "14",
      deva: "इत्थं विष्णुशिवादितत्त्वतनवे श्रीवक्रतुण्डाय हुं-\nकाराक्षिप्तसमस्तदैत्यपृतनाव्राताय दीप्तत्विषे ।\nआनन्दैकरसावबोधलहरीविध्वस्तसर्वोर्मये\nसर्वत्र प्रथमानमुग्धमहसे तस्मै परस्मै नमः ॥",
      iast: "itthaṁ viṣṇu-śivādi-tattva-tanave śrī-vakratuṇḍāya huṁ-\nkārākṣipta-samasta-daitya-pṛtanā-vrātāya dīpta-tviṣe ।\nānandaika-rasāvabodha-laharī-vidhvasta-sarvormaye\nsarvatra prathamāna-mugdha-mahase tasmai parasmai namaḥ ॥",
      en: "So then — to Śrī Vakratuṇḍa, whose body is the very principle of Viṣṇu, Śiva and the rest; who scattered every army of the daityas with a single huṁ; of blazing radiance; in whom every wave is stilled by that surge of awareness whose one savour is bliss; whose innocent splendour spreads everywhere — to him, the Supreme, salutation.",
      tel: "ఈ విధముగా — విష్ణు శివాది తత్త్వములే శరీరముగా గలవాడు; హుంకారముచే సమస్త దైత్య సేనా సమూహములను చెదరగొట్టినవాడు; దీప్తకాంతి గలవాడు; ఆనందైక రసమైన అవబోధ లహరిచే సర్వ ఊర్ములను విధ్వంసము చేసినవాడు; సర్వత్ర వ్యాపించు ముగ్ధ తేజస్సు గలవాడు — ఆ శ్రీవక్రతుండునికి, పరమునికి నమస్కారము." },
    { s: 0, n: "15",
      deva: "सेवाहेवाकिदेवासुरनरनिकरस्फारकोटीरकोटि-\nकाटीव्याटीकमानद्युमणिसममणिश्रेणिभावेणिकानाम् ।\nराजन्नीराजनश्रीसखचरणनखद्योतविद्योतमानः\nश्रेयः स्थेयः स देयान्मम विमलदृशो बन्धुरं सिन्धुरास्यः ॥",
      iast: "sevā-hevāki-devāsura-nara-nikara-sphāra-koṭīra-koṭi-\nkāṭī-vyāṭīkamāna-dyumaṇi-sama-maṇi-śreṇi-bhā-veṇikānām ।\nrājan-nīrājana-śrī-sakha-caraṇa-nakha-dyota-vidyotamānaḥ\nśreyaḥ stheyaḥ sa deyān mama vimala-dṛśo bandhuraṁ sindhurāsyaḥ ॥",
      en: "Gods, asuras and men crowd in, eager to serve, and the banked rows of gems in their massed crowns flash like suns braided together — an ārati of light at his feet. Radiant with the glow of those toenails, may the elephant-faced one, who abides, grant me a lasting and shapely good, and the clear sight to know it.",
      tel: "సేవయందు ఉత్సాహము గల దేవ, అసుర, మనుష్య సమూహముల విశాలమైన కిరీటముల కోట్లలో వరుసగా అమరిన రత్నశ్రేణులు సూర్యునివలె ప్రకాశించుచు వేణికవలె ఒప్పగా — ఆ నీరాజన శ్రీచే సేవింపబడిన చరణ నఖముల కాంతిచే విద్యోతమానుడైన సింధురాస్యుడు నాకు నిర్మల దృష్టిని, స్థిరమైన బంధురమైన శ్రేయస్సును ఇచ్చుగాక." },
    { s: 1, n: "16",
      deva: "एतेन प्रकटरहस्यमन्त्रमाला-\nगर्भेण स्फुटतरसंविदा स्तवेन ।\nयः स्तौति प्रचुरतरं महागणेशं\nतस्येयं भवति वशंवदा त्रिलोकी ॥",
      iast: "etena prakaṭa-rahasya-mantra-mālā-\ngarbheṇa sphuṭatara-saṁvidā stavena ।\nyaḥ stauti pracurataraṁ mahāgaṇeśaṁ\ntasyeyaṁ bhavati vaśaṁvadā trilokī ॥",
      en: "Whoever praises the great Gaṇeśa abundantly with this hymn — bright with clear knowing, carrying the secret garland of mantras in its womb, now made plain — for him these three worlds become obedient to his word.",
      tel: "ప్రకటమైన రహస్య మంత్రమాలను గర్భమున దాల్చిన, స్ఫుటమైన సంవిత్తు గల ఈ స్తవముచే మహాగణేశుని ఎవరు ప్రచురముగా స్తుతించునో — అతనికి ఈ మూడు లోకములు వశంవదములగును." },
  ],
},

/* Gaṇapati Tālam — the invocatory piece a dancer opens with, keyed from
   the Telugu recension the rest of this shelf follows. Recensions differ
   widely (the stage carries it by ear, not by manuscript); word division
   and the two soft hyphens the source printed at line-wraps in v9 are
   set as the metre takes them. Verses 1–9 are praise; 10 is jati alone,
   and 11 alternates jati with a pāda of praise. */
{
  deities: ["ganesha"],
  title: "Gaṇapati Tālam",
  blurb: "The invocation danced before anything else is danced — nine verses of praise, then the drum's own syllables, the tāla spoken aloud before the feet take it up.",
  sections: [{ tel: "స్తుతి", roman: "Praise" }, { tel: "జతి", roman: "Jati — the drum-syllables" }],
  verses: [
    { s: 0, n: "1",
      deva: "विकटोत्कटसुन्दरदन्तिमुखं\nभुजगेन्द्रसुसर्पगदाभरणम् ।\nगजनीलगजेन्द्र गणाधिपतिं\nप्रणतोऽस्मि विनायक हस्तिमुखम् ॥",
      iast: "vikaṭotkaṭasundaradantimukhaṁ\nbhujagendrasusarpagadābharaṇam ।\ngajanīlagajendra gaṇādhipatiṁ\npraṇato'smi vināyaka hastimukham ॥",
      en: "Vast, fierce and lovely, the tusked face; the lord of serpents worn as a fine snake, and the mace for ornament; dark as the great elephant, chief of the gaṇas — I bow, Vināyaka, elephant-faced.",
      tel: "వికటము, ఉత్కటము, సుందరమైన దంతిముఖము గలవాడు; భుజగేంద్రుని చక్కని సర్పముగను గదను ఆభరణముగను ధరించినవాడు; గజమువలె నీలవర్ణుడు, గజేంద్రుడు, గణాధిపతి — వినాయకా, హస్తిముఖా, నీకు ప్రణమిల్లుచున్నాను." },
    { s: 0, n: "2",
      deva: "सुर सुर गणपति सुन्दरकेशं\nऋषि ऋषि गणपति यज्ञसमानम् ।\nभव भव गणपति पद्मशरीरं\nजय जय गणपति दिव्यनमस्ते ॥",
      iast: "sura sura gaṇapati sundarakeśaṁ\nṛṣi ṛṣi gaṇapati yajñasamānam ।\nbhava bhava gaṇapati padmaśarīraṁ\njaya jaya gaṇapati divyanamaste ॥",
      en: "Gaṇapati of the gods, fair of hair; Gaṇapati of the ṛṣis, the equal of the sacrifice itself; Gaṇapati of all becoming, whose body is the lotus; hail, hail Gaṇapati — a divine salutation to you. The doubling is the dance's own: each name is said twice before it is answered.",
      tel: "సురలకు సురుడైన గణపతి, సుందరకేశుడు; ఋషులకు ఋషియైన గణపతి, యజ్ఞముతో సమానుడు; భవభవుడైన గణపతి, పద్మశరీరుడు; జయ జయ గణపతీ — నీకు దివ్య నమస్కారము. ఈ ద్విరుక్తి నృత్యమునకు సహజమైనది." },
    { s: 0, n: "3",
      deva: "गजमुखवक्त्रं गिरिजापुत्रं\nगणगुणमित्रं गणपतिमीशप्रियम् ॥",
      iast: "gajamukhavaktraṁ girijāputraṁ\ngaṇaguṇamitraṁ gaṇapatimīśapriyam ॥",
      en: "The elephant-faced, son of Girijā; friend to the gaṇas and to every virtue of theirs — Gaṇapati, dear to Īśa.",
      tel: "గజముఖుడు, గిరిజాపుత్రుడు; గణములకును వారి గుణములకును మిత్రుడు — ఈశునికి ప్రియుడైన గణపతి." },
    { s: 0, n: "4",
      deva: "करधृतपरशुं कङ्कणपाणिं\nकबलितपद्मरुचिम् ।\nसुरपतिवन्द्यं सुन्दरनृत्तं\nसुरचितमणिमकुटम् ॥",
      iast: "karadhṛtaparaśuṁ kaṅkaṇapāṇiṁ\nkabalitapadmarucim ।\nsurapativandyaṁ sundaranṛttaṁ\nsuracitamaṇimakuṭam ॥",
      en: "An axe held in the hand, a bangle at the wrist, the lotus's own lustre swallowed up in him; saluted by the lord of the gods, beautiful in the dance, a jewelled crown finely wrought upon his head.",
      tel: "చేత పరశువును ధరించినవాడు, కంకణము గల చేయి గలవాడు, పద్మకాంతిని గ్రసించినవాడు; సురపతిచే వందితుడు, సుందరమైన నృత్తము గలవాడు, చక్కగా రచింపబడిన మణిమకుటము ధరించినవాడు." },
    { s: 0, n: "5",
      deva: "प्रणमत देवं प्रकटित तालं\nषड्गिरि तालमिदम् ।\nतत्तत् षड्गिरि तालमिदं\nतत्तत् षड्गिरि तालमिदम् ॥",
      iast: "praṇamata devaṁ prakaṭita tālaṁ\nṣaḍgiri tālamidam ।\ntattat ṣaḍgiri tālamidaṁ\ntattat ṣaḍgiri tālamidam ॥",
      en: "Bow to the god — the tāla is struck and shown: this is the ṣaḍgiri tāla; that, and that again, is the ṣaḍgiri tāla.",
      tel: "దేవునికి ప్రణమిల్లుడు — తాళము ప్రకటితమైనది; ఇదియే షడ్గిరి తాళము; తత్తత్ షడ్గిరి తాళమిదే." },
    { s: 0, n: "6",
      deva: "लम्बोदरवर कुञ्जासुरकृत कुङ्कुमवर्णधरम् ।\nश्वेतसशृङ्गं मोदकहस्तं प्रीतिसपनसफलम् ॥",
      iast: "lambodaravara kuñjāsurakṛta kuṅkumavarṇadharam ।\nśvetasaśṛṅgaṁ modakahastaṁ prītisapanasaphalam ॥",
      en: "Great Lambodara, who made an end of the asura, wearing the colour of kuṅkuma; white of tusk, a modaka in his hand, glad of the jackfruit set before him.",
      tel: "లంబోదరవరుడు, అసురుని అంతమొందించినవాడు, కుంకుమవర్ణమును ధరించినవాడు; తెల్లని దంతము గలవాడు, చేత మోదకము గలవాడు, పనసఫలమును ప్రీతితో అందుకొనువాడు." },
    { s: 0, n: "7",
      deva: "नयनत्रयवर नागविभूषित नानागणपतिदं तत्तत्\nनयनत्रयवर नागविभूषित नानागणपतिदं तत्तत्\nनानागणपति तं तत्तत् नानागणपतिदम् ॥",
      iast: "nayanatrayavara nāgavibhūṣita nānāgaṇapatidaṁ tattat\nnayanatrayavara nāgavibhūṣita nānāgaṇapatidaṁ tattat\nnānāgaṇapati taṁ tattat nānāgaṇapatidam ॥",
      en: "Three-eyed and boon-giving, adorned with the serpent — this is Gaṇapati in his many forms; that, and that: the many Gaṇapatis, and this, the many-formed again.",
      tel: "వరమైన మూడు నేత్రములు గలవాడు, నాగముచే విభూషితుడు — ఇది నానారూప గణపతి; తత్తత్ — ఆ నానా గణపతి, ఇదియే నానా గణపతి." },
    { s: 0, n: "8",
      deva: "धवलित जलधरधवलित चन्द्रं\nफणिमणिकिरणविभूषित खड्गम् ।\nतनुतनुविषहर शूलकपालं\nहर हर शिव शिव गणपतिमभयम् ॥",
      iast: "dhavalita jaladharadhavalita candraṁ\nphaṇimaṇikiraṇavibhūṣita khaḍgam ।\ntanutanuviṣahara śūlakapālaṁ\nhara hara śiva śiva gaṇapatimabhayam ॥",
      en: "Whitened — the raincloud whitened, and the moon with it; a sword lit by the rays of the serpent's jewel; slender, slender, bearer of poison away, trident and skull — hara hara, śiva śiva: Gaṇapati, and no fear. The father's emblems are on the son here; the dance makes no distinction between them.",
      tel: "ధవళితుడు — జలధరము ధవళితము, చంద్రుడును; ఫణిమణి కిరణములచే విభూషితమైన ఖడ్గము; తనుతనువైన విషహరుడు, శూలకపాలములు గలవాడు — హర హర శివ శివ, గణపతి అభయము. ఇచట తండ్రి చిహ్నములు కుమారునిపై ఉన్నవి; నృత్యము వారిద్దరిని వేరుచేయదు." },
    { s: 0, n: "9",
      deva: "कटतट विगलितमदजल जलधितगणपतिवाद्यमिदं\nकटतट विगलितमदजल जलधितगणपतिवाद्यमिदं\nतत्तत् गणपतिवाद्यमिदं\nतत्तत् गणपतिवाद्यमिदम् ॥",
      iast: "kaṭataṭa vigalitamadajala jaladhitagaṇapativādyamidaṁ\nkaṭataṭa vigalitamadajala jaladhitagaṇapativādyamidaṁ\ntattat gaṇapativādyamidaṁ\ntattat gaṇapativādyamidam ॥",
      en: "Down the slope of his temples the ichor runs and gathers to a sea — and this is Gaṇapati's music; that, and that: this is Gaṇapati's music.",
      tel: "కటతటముల నుండి జారు మదజలము జలధి యగుచుండగా — ఇదియే గణపతి వాద్యము; తత్తత్ గణపతి వాద్యమిదే." },
    { s: 1, n: "10",
      deva: "तत्तदिं नं तरिकु तरिजणकु कुकु तद्दि\nकुकु तकिट डिण्डिङ्गु डिगुण कुकु तद्दि\nतत्त झं झं तरित\nत झं झं तरित\nतकत झं झं तरित\nत झं झं तरित\nतरिदणत दणजणुत जणुदिमित\nकिटक तरिकिटतों\nतकिट किटक तरिकिटतों\nतकिट किटक तरिकिटतों तां ॥",
      iast: "tattadiṁ naṁ tariku tarijaṇaku kuku taddi\nkuku takiṭa ḍiṇḍiṅgu ḍiguṇa kuku taddi\ntatta jhaṁ jhaṁ tarita\nta jhaṁ jhaṁ tarita\ntakata jhaṁ jhaṁ tarita\nta jhaṁ jhaṁ tarita\ntaridaṇata daṇajaṇuta jaṇudimita\nkiṭaka tarikiṭatoṁ\ntakiṭa kiṭaka tarikiṭatoṁ\ntakiṭa kiṭaka tarikiṭatoṁ tāṁ ॥",
      en: "Jati — the syllables of the drum. They carry no words and are not meant to: this is the tāla said aloud, the mṛdaṅgam's own speech, and the feet answer it.",
      tel: "జతులు — మృదంగపు అక్షరములు. వీటికి పదార్థము లేదు, ఉండనవసరమూ లేదు: ఇది తాళమును నోటితో పలుకుట; పాదములు దానికి బదులిచ్చును." },
    { s: 1, n: "11",
      deva: "तकतकिट तकतकिट तकतकिट तत्तों\nशशिकलित शशिकलित मौलिनं शूलिनम् ।\nतकतकिट तकतकिट तकतकिट तत्तों\nविमलशुभकमलजलपादुकं पाणिनम् ।\nधित्तकिट धित्तकिट धित्तकिट तत्तों\nप्रमथगणगुणकथितशोभनं शोभितम् ।\nधित्तकिट धित्तकिट धित्तकिट तत्तों\nपृथुलभुजसरसिज विषाणकं पोषणम् ।\nतकतकिट तकतकिट तकतकिट तत्तों\nपनसफलकदलिफलमोदनं मोदकम् ।\nधित्तकिट धित्तकिट धित्तकिट तत्तों\nप्रणतगुरु शिवतनय गणपति तालनम् ।\nगणपति तालनं गणपति तालनम् ॥",
      iast: "takatakiṭa takatakiṭa takatakiṭa tattoṁ\nśaśikalita śaśikalita maulinaṁ śūlinam ।\ntakatakiṭa takatakiṭa takatakiṭa tattoṁ\nvimalaśubhakamalajalapādukaṁ pāṇinam ।\ndhittakiṭa dhittakiṭa dhittakiṭa tattoṁ\npramathagaṇaguṇakathitaśobhanaṁ śobhitam ।\ndhittakiṭa dhittakiṭa dhittakiṭa tattoṁ\npṛthulabhujasarasija viṣāṇakaṁ poṣaṇam ।\ntakatakiṭa takatakiṭa takatakiṭa tattoṁ\npanasaphalakadaliphalamodanaṁ modakam ।\ndhittakiṭa dhittakiṭa dhittakiṭa tattoṁ\npraṇataguru śivatanaya gaṇapati tālanam ।\ngaṇapati tālanaṁ gaṇapati tālanam ॥",
      en: "Now a burst of syllables and a line of praise, turn and turn about: the moon's digit set in his crest, the trident-bearer; sandals of clear and blessed lotus-water at his feet; resplendent with the beauty the pramatha hosts recount; broad-armed as lotuses, tusked, the nourisher; jackfruit and plantain, sweet rice and modaka; guru of all who bow, son of Śiva — this is Gaṇapati's tāla, Gaṇapati's tāla.",
      tel: "ఇక జతియు స్తుతిపాదమును మార్చి మార్చి: శిరమున చంద్రకళ గలవాడు, శూలి; నిర్మలమైన శుభకమల జలముల పాదుకలు గలవాడు; ప్రమథగణముల గుణములచే కథింపబడిన శోభతో శోభితుడు; సరసిజముల వంటి విశాలమైన భుజములు, విషాణము గలవాడు, పోషకుడు; పనసఫలము, కదళీఫలము, మోదనము, మోదకము; ప్రణతులకు గురువు, శివతనయుడు — ఇదియే గణపతి తాళము, గణపతి తాళము." },
  ],
}];
