/* ============================================================
   STUTI — the pitṛ texts
   Rucistava · Pitṛ Stotram (Ruci-kṛtam) · Pitṛ Sūktam (Vājasaneyi)
   · Pitṛ Sūktam (Ṛgveda) · Pitṛ Stotram (Brahma-kṛtam)
   Transcribed from the corpus files in stotras/pitr/ — see each
   file's own header for the witnesses collated. The two sūktas
   belong to two different Vedas and are kept apart: neither is a
   variant of the other and neither fills the other's gaps.
   Accent is carried in `deva:` and omitted from `iast:`.
   ============================================================ */
export const extra = [{
  deities: ["pitr"],
  title: "Rucistava",
  blurb: "A hymn sung on the knees before a wall of light. Ruci, an ascetic who had refused to marry, is told by his own dead forefathers that his refusal is dragging them down; he worships them on a river bank, the sky fills with radiance, and he sings — not to his own grandfathers but to the forefathers as a cosmic order, in whom the whole universe is Agni and Soma.",
  about: "Garuḍa Purāṇa, Ācāra-kāṇḍa 89.51–60, after Gītā Press, Antya-karma Śrāddha-prakāśa p. 418. The same volume directs that it be recited, with the Puruṣa Sūkta and the Pitṛ Sūkta, before the brāhmaṇas at the meal of a śrāddha — and forbids these recitations in the preta-śrāddha, the rites before sapiṇḍīkaraṇa, when the dead person has not yet joined the forefathers. It is the second half of one continuous passage: the longer hymn that precedes it is here as Pitṛ Stotram (Ruci-kṛtam), and the tradition catalogues the two separately.",
  sections: [{ roman: "Stotram", tel: "స్తోత్రం" }],
  verses: [
    { s: 0, n: "1",
      deva: "रुचिरुवाच ।\nअर्चितानाममूर्त्तानां पितॄणां दीप्ततेजसाम् ।\nनमस्यामि सदा तेषां ध्यानिनां दिव्यचक्षुषाम् ॥",
      iast: "ruciruvāca |\narcitānāmamūrttānāṁ pitṝṇāṁ dīptatejasām |\nnamasyāmi sadā teṣāṁ dhyānināṁ divyacakṣuṣām ||",
      en: "Ruci said: I bow always to the forefathers — worshipped, formless, of blazing radiance, absorbed in meditation, possessed of divine sight.",
      tel: "రుచి పలికెను: పూజింపబడినవారు, రూపరహితులు, దీప్తమైన తేజస్సు గలవారు, ధ్యానమగ్నులు, దివ్యదృష్టి గలవారు అయిన ఆ పితరులకు నేను సదా నమస్కరిస్తున్నాను.",
      hi: "रुचि बोले — जो पूजित, अमूर्त, अत्यन्त तेजस्वी, ध्यानी और दिव्यदृष्टि-सम्पन्न हैं, उन पितरों को मैं सदा नमस्कार करता हूँ।" },
    { s: 0, n: "2",
      deva: "इन्द्रादीनां च नेतारो दक्षमारीचयोस्तथा ।\nसप्तर्षीणां तथान्येषां तान् नमस्यामि कामदान् ॥",
      iast: "indrādīnāṁ ca netāro dakṣamārīcayostathā |\nsaptarṣīṇāṁ tathānyeṣāṁ tān namasyāmi kāmadān ||",
      en: "They who lead Indra and the other gods, Dakṣa and Mārīca, the seven ṛṣis and others besides — to them, the granters of desires, I bow.",
      tel: "ఇంద్రాది దేవతలకు, దక్షునికి, మారీచునికి, సప్తర్షులకు, ఇతరులకు కూడా నాయకులై కోరికలను తీర్చే ఆ పితరులకు నమస్కరిస్తున్నాను.",
      hi: "जो इन्द्र आदि देवताओं, दक्ष, मारीच, सप्तर्षियों तथा अन्य लोगों के भी नेता हैं, कामनाएँ पूर्ण करने वाले उन पितरों को मैं नमस्कार करता हूँ।" },
    { s: 0, n: "3",
      deva: "मन्वादीनां मुनीन्द्राणां सूर्याचन्द्रमसोस्तथा ।\nतान् नमस्याम्यहं सर्वान् पितॄनप्सूदधावपि ॥",
      iast: "manvādīnāṁ munīndrāṇāṁ sūryācandramasostathā |\ntān namasyāmyahaṁ sarvān pitṝnapsūdadhāvapi ||",
      en: "Those of Manu and the rest, of the lords among sages, of the sun and the moon — all those forefathers I salute, in the waters and in the ocean too.",
      tel: "మను మొదలైనవారికి, మునీంద్రులకు, సూర్యచంద్రులకు నాయకులైన ఆ పితరులందరికీ — జలాలలోను సముద్రంలోను ఉన్నవారికి కూడా — నేను నమస్కరిస్తున్నాను.",
      hi: "जो मनु आदि के, मुनीश्वरों के तथा सूर्य और चन्द्रमा के भी नायक हैं, उन सभी पितरों को मैं जल में और समुद्र में भी नमस्कार करता हूँ।" },
    { s: 0, n: "4",
      deva: "नक्षत्राणां ग्रहाणां च वाय्वग्न्योर्नभसस्तथा ।\nद्यावापृथिव्योश्च तथा नमस्यामि कृताञ्जलिः ॥",
      iast: "nakṣatrāṇāṁ grahāṇāṁ ca vāyvagnyornabhasastathā |\ndyāvāpṛthivyośca tathā namasyāmi kṛtāñjaliḥ ||",
      en: "Those of the stars and the planets, of wind and fire and sky, of heaven and earth — to them I bow with folded hands.",
      tel: "నక్షత్రాలకు, గ్రహాలకు, వాయువుకు, అగ్నికి, ఆకాశానికి, ద్యులోకానికి, భూమికి నాయకులైన వారికి చేతులు జోడించి నమస్కరిస్తున్నాను.",
      hi: "जो नक्षत्रों, ग्रहों, वायु, अग्नि, आकाश तथा द्युलोक और पृथ्वी के भी नेता हैं, उन्हें मैं हाथ जोड़कर प्रणाम करता हूँ।" },
    { s: 0, n: "5",
      deva: "देवर्षीणां जनितॄंश्च सर्वलोकनमस्कृतान् ।\nअक्षय्यस्य सदा दातॄन् नमस्येऽहं कृताञ्जलिः ॥",
      iast: "devarṣīṇāṁ janitṝṁśca sarvalokanamaskṛtān |\nakṣayyasya sadā dātṝn namasye'haṁ kṛtāñjaliḥ ||",
      en: "The begetters of the divine ṛṣis, saluted by all the worlds, ever the givers of what never perishes — to them I bow with folded hands.",
      tel: "దేవర్షులకు జన్మనిచ్చినవారు, సర్వలోకాలచే నమస్కరింపబడినవారు, సదా అక్షయఫలాన్ని ఇచ్చేవారు అయిన పితరులకు చేతులు జోడించి నమస్కరిస్తున్నాను.",
      hi: "जो देवर्षियों के जन्मदाता, समस्त लोकों द्वारा वन्दित तथा सदा अक्षय फल के दाता हैं, उन पितरों को मैं हाथ जोड़कर प्रणाम करता हूँ।" },
    { s: 0, n: "6",
      deva: "प्रजापतेः कश्यपाय सोमाय वरुणाय च ।\nयोगेश्वरेभ्यश्च सदा नमस्यामि कृताञ्जलिः ॥",
      iast: "prajāpateḥ kaśyapāya somāya varuṇāya ca |\nyogeśvarebhyaśca sadā namasyāmi kṛtāñjaliḥ ||",
      en: "To those of Prajāpati, to Kaśyapa, to Soma and to Varuṇa, and to the lords of yoga, I bow always with folded hands.",
      tel: "ప్రజాపతికి, కశ్యపునికి, సోమునికి, వరుణునికి, యోగేశ్వరులకు సదా చేతులు జోడించి నమస్కరిస్తున్నాను.",
      hi: "प्रजापति, कश्यप, सोम, वरुण तथा योगेश्वरों के रूप में स्थित पितरों को मैं सदा हाथ जोड़कर प्रणाम करता हूँ।" },
    { s: 0, n: "7",
      deva: "नमो गणेभ्यः सप्तभ्यस्तथा लोकेषु सप्तसु ।\nस्वयम्भुवे नमस्यामि ब्रह्मणे योगचक्षुषे ॥",
      iast: "namo gaṇebhyaḥ saptabhyastathā lokeṣu saptasu |\nsvayambhuve namasyāmi brahmaṇe yogacakṣuṣe ||",
      en: "Salutation to the seven companies of forefathers in the seven worlds; I bow to the self-born Brahmā, whose eye is yoga.",
      tel: "ఏడు లోకాలలో ఉన్న ఏడు పితృగణాలకు నమస్కారం. యోగదృష్టి గల స్వయంభువైన బ్రహ్మకు నమస్కరిస్తున్నాను.",
      hi: "सातों लोकों में स्थित सात पितृगणों को नमस्कार है। योगदृष्टि-सम्पन्न स्वयम्भू ब्रह्मा को मैं प्रणाम करता हूँ।" },
    { s: 0, n: "8",
      deva: "सोमाधारान् पितृगणान् योगमूर्त्तिधरांस्तथा ।\nनमस्यामि तथा सोमं पितरं जगतामहम् ॥",
      iast: "somādhārān pitṛgaṇān yogamūrttidharāṁstathā |\nnamasyāmi tathā somaṁ pitaraṁ jagatāmaham ||",
      en: "I bow to the companies of forefathers who rest upon Soma and bear bodies of yoga, and to Soma himself, the father of the worlds.",
      tel: "సోముని ఆధారంగా నిలిచిన, యోగమూర్తులను ధరించిన పితృగణాలకు, జగత్తులకు తండ్రి అయిన సోమునికి కూడా నమస్కరిస్తున్నాను.",
      hi: "चन्द्रमा के आधार पर प्रतिष्ठित तथा योगमूर्तिधारी पितृगणों को तथा सम्पूर्ण जगत् के पिता सोम को भी मैं प्रणाम करता हूँ।" },
    { s: 0, n: "9",
      deva: "अग्निरूपांस्तथैवान्यान् नमस्यामि पितॄनहम् ।\nअग्नीषोममयं विश्वं यत एतदशेषतः ॥",
      iast: "agnirūpāṁstathaivānyān namasyāmi pitṝnaham |\nagnīṣomamayaṁ viśvaṁ yata etadaśeṣataḥ ||",
      en: "And I bow to the other forefathers, whose form is fire — for this whole universe, without remainder, is made of Agni and Soma.",
      tel: "అగ్నిరూపులైన ఇతర పితరులకు కూడా నమస్కరిస్తున్నాను; ఎందుకంటే ఈ విశ్వమంతా సంపూర్ణంగా అగ్నీషోమమయమే.",
      hi: "अग्निस्वरूप अन्य पितरों को भी मैं प्रणाम करता हूँ, क्योंकि यह सम्पूर्ण जगत् अग्नि और सोममय है।" },
    { s: 0, n: "10",
      deva: "ये तु तेजसि ये चैते सोमसूर्याग्निमूर्तयः ।\nजगत्स्वरूपिणश्चैव तथा ब्रह्मस्वरूपिणः ॥",
      iast: "ye tu tejasi ye caite somasūryāgnimūrtayaḥ |\njagatsvarūpiṇaścaiva tathā brahmasvarūpiṇaḥ ||",
      en: "Those who abide in radiance, who appear as moon, sun and fire, whose form is the universe and whose form is brahman —",
      tel: "తేజస్సులో నిలిచినవారు, సోమ-సూర్య-అగ్ని రూపాలుగా కనిపించేవారు, జగత్స్వరూపులు, బ్రహ్మస్వరూపులు అయినవారు —",
      hi: "जो पितर तेज में स्थित हैं, जो चन्द्रमा, सूर्य और अग्नि के रूप में दिखायी देते हैं तथा जो जगत्स्वरूप एवं ब्रह्मस्वरूप हैं —" },
    { s: 0, n: "11",
      deva: "तेभ्योऽखिलेभ्यो योगिभ्यः पितृभ्यो यतमानसः ।\nनमो नमो नमस्ते मे प्रसीदन्तु स्वधाभुजः ॥",
      iast: "tebhyo'khilebhyo yogibhyaḥ pitṛbhyo yatamānasaḥ |\nnamo namo namaste me prasīdantu svadhābhujaḥ ||",
      en: "to all of them, the yogin forefathers, I bow with a collected mind: salutation, salutation, salutation — may they, who feed on svadhā, be gracious to me.",
      tel: "ఆ సమస్త యోగులైన పితరులకు ఏకాగ్రచిత్తంతో మళ్ళీ మళ్ళీ నమస్కారం. స్వధాభోజులైన ఆ పితరులు నాపై ప్రసన్నులగుదురు గాక.",
      hi: "उन सम्पूर्ण योगी पितरों को मैं एकाग्रचित्त होकर प्रणाम करता हूँ। उन्हें बारम्बार नमस्कार है। वे स्वधाभोजी पितर मुझ पर प्रसन्न हों।" },
  ],
},

{
  deities: ["pitr"],
  title: "Pitṛ Stotram (Ruci-kṛtam)",
  blurb: "Before the Rucistava there is this longer and stranger hymn, which works its way through creation asking who feeds the dead: the gods and great ṛṣis in heaven, the siddhas and guhyakas, brāhmaṇas and forest ascetics, kings, vaiśyas and śūdras, the great asuras in Pātāla and the nāgas below them. It then turns to the forefathers themselves — in the moon's rays, in the sun's disc, eating through the bodies of the brāhmaṇas at the meal — and ends by naming all thirty-one of their companies.",
  about: "Garuḍa Purāṇa, Ācāra-kāṇḍa 89.13–48. No Gītā Press witness prints this half; the text rests on GRETIL, on Ṛṣipīṭham (September 2014) and on stotranidhi, with GRETIL governing where they disagree. The Rucistava follows it in the Purāṇa after two verses of Mārkaṇḍeya's narration, and is kept here as a separate text, as the tradition catalogues it.",
  sections: [
    { roman: "Namasye'ham — the worshippers of the forefathers", tel: "నమస్యేऽహం — పితరులను ఆరాధించేవారు" },
    { roman: "Pitṛnnamasye — the forefathers and their offerings", tel: "పితౄన్నమస్యే — పితరులు, వారి హవిస్సులు" },
    { roman: "Pitṛgaṇāḥ — the guardians and the thirty-one companies", tel: "పితృగణాః — దిక్పాలకులు, ముప్పై ఒక్క గణాలు" },
  ],
  verses: [
    { s: 0, n: "1",
      deva: "रुचिरुवाच ।\nनमस्येऽहं पितॄन् भक्त्या ये वसन्त्यधिदेवतम् ।\nदेवैरपि हि तर्प्यन्ते ये श्राद्धेषु स्वधोत्तरैः ॥",
      iast: "ruciruvāca |\nnamasye'haṁ pitṝn bhaktyā ye vasantyadhidevatam |\ndevairapi hi tarpyante ye śrāddheṣu svadhottaraiḥ ||",
      en: "Ruci said: I bow in devotion to the forefathers who dwell as presiding deities, who are satisfied even by the gods at śrāddhas with offerings ending in svadhā.",
      tel: "రుచి పలికెను: అధిదేవతలుగా నివసించేవారు, శ్రాద్ధాలలో స్వధాకారంతో దేవతలచేత కూడా తృప్తిపరచబడేవారు అయిన పితరులకు భక్తితో నమస్కరిస్తున్నాను.",
      hi: "रुचि बोले — जो अधिदेवता रूप में निवास करते हैं और जिन्हें श्राद्धों में स्वधायुक्त अर्पणों से देवता भी तृप्त करते हैं, उन पितरों को मैं भक्तिपूर्वक नमस्कार करता हूँ।" },
    { s: 0, n: "2",
      deva: "नमस्येऽहं पितॄन् स्वर्गे ये तर्प्यन्ते महर्षिभिः ।\nश्राद्धैर्मनोमयैर्भक्त्या भुक्तिमुक्तिमभीप्सुभिः ॥",
      iast: "namasye'haṁ pitṝn svarge ye tarpyante maharṣibhiḥ |\nśrāddhairmanomayairbhaktyā bhuktimuktimabhīpsubhiḥ ||",
      en: "I bow to the forefathers in heaven who are satisfied, in devotion, with śrāddhas made of the mind by the great ṛṣis who seek enjoyment and liberation.",
      tel: "భుక్తిముక్తులను కోరే మహర్షులు భక్తితో మానసిక శ్రాద్ధాలచేత తృప్తిపరచే స్వర్గంలోని పితరులకు నమస్కరిస్తున్నాను.",
      hi: "भोग और मोक्ष की इच्छा रखने वाले महर्षि जिन्हें भक्तिपूर्वक मानसिक श्राद्धों से तृप्त करते हैं, स्वर्ग में स्थित उन पितरों को मैं नमस्कार करता हूँ।" },
    { s: 0, n: "3",
      deva: "नमस्येऽहं पितॄन् स्वर्गे सिद्धाः सन्तर्पयन्ति यान् ।\nश्राद्धेषु दिव्यैः सकलैरुपहारैरनुत्तमैः ॥",
      iast: "namasye'haṁ pitṝn svarge siddhāḥ santarpayanti yān |\nśrāddheṣu divyaiḥ sakalairupahārairanuttamaiḥ ||",
      en: "I bow to the forefathers in heaven whom the siddhas satisfy at śrāddhas with every divine and unsurpassed offering.",
      tel: "సిద్ధులు శ్రాద్ధాలలో దివ్యమైన, సాటిలేని సకల ఉపహారాలతో తృప్తిపరచే స్వర్గంలోని పితరులకు నమస్కరిస్తున్నాను.",
      hi: "सिद्धगण श्राद्धों में सब प्रकार के दिव्य और उत्तम उपहारों से जिन्हें तृप्त करते हैं, स्वर्ग में स्थित उन पितरों को मैं नमस्कार करता हूँ।" },
    { s: 0, n: "4",
      deva: "नमस्येऽहं पितॄन् भक्त्या येऽर्च्यन्ते गुह्यकैर्दिवि ।\nतन्मयत्वेन वाञ्छद्भिरृद्धिमात्यन्तिकीं पराम् ॥",
      iast: "namasye'haṁ pitṝn bhaktyā ye'rcyante guhyakairdivi |\ntanmayatvena vāñchadbhirṛddhimātyantikīṁ parām ||",
      en: "I bow in devotion to the forefathers who are worshipped in heaven by the guhyakas, who long, through absorption in them, for the final and supreme prosperity.",
      tel: "తన్మయత్వంతో ఆత్యంతికమైన పరమ సమృద్ధిని కోరే గుహ్యకులు స్వర్గంలో పూజించే పితరులకు భక్తితో నమస్కరిస్తున్నాను.",
      hi: "तन्मय होकर परम और आत्यन्तिक समृद्धि की कामना करने वाले गुह्यक स्वर्ग में जिनकी पूजा करते हैं, उन पितरों को मैं भक्तिपूर्वक नमस्कार करता हूँ।" },
    { s: 0, n: "5",
      deva: "नमस्येऽहं पितॄन् मर्त्यैरर्च्यन्ते भुवि ये सदा ।\nश्राद्धेषु श्रद्धयाभीष्टलोकपुष्टिप्रदायिनः ॥",
      iast: "namasye'haṁ pitṝn martyairarcyante bhuvi ye sadā |\nśrāddheṣu śraddhayābhīṣṭalokapuṣṭipradāyinaḥ ||",
      en: "I bow to the forefathers who are ever worshipped on earth by mortals at śrāddhas with faith, and who grant the worlds they desire, and nourishment.",
      tel: "భూమిపై మానవులు శ్రద్ధతో శ్రాద్ధాలలో సదా పూజించేవారు, కోరిన లోకాలను, పుష్టిని ప్రసాదించేవారు అయిన పితరులకు నమస్కరిస్తున్నాను.",
      hi: "पृथ्वी पर मनुष्य श्राद्धों में श्रद्धापूर्वक जिनकी सदा पूजा करते हैं और जो अभीष्ट लोक तथा पुष्टि प्रदान करते हैं, उन पितरों को मैं नमस्कार करता हूँ।" },
    { s: 0, n: "6",
      deva: "नमस्येऽहं पितॄन् विप्रैरर्च्यन्ते भुवि ये सदा ।\nवाञ्छिताभीष्टलाभाय प्राजापत्यप्रदायिनः ॥",
      iast: "namasye'haṁ pitṝn viprairarcyante bhuvi ye sadā |\nvāñchitābhīṣṭalābhāya prājāpatyapradāyinaḥ ||",
      en: "I bow to the forefathers who are ever worshipped on earth by brāhmaṇas for the gain of what they wish and desire, and who bestow the world of Prajāpati.",
      tel: "కోరిన అభీష్టాల లాభం కోసం భూమిపై బ్రాహ్మణులు సదా పూజించేవారు, ప్రాజాపత్య లోకాన్ని ప్రసాదించేవారు అయిన పితరులకు నమస్కరిస్తున్నాను.",
      hi: "वांछित अभीष्ट की प्राप्ति के लिए पृथ्वी पर ब्राह्मण जिनकी सदा पूजा करते हैं और जो प्राजापत्य लोक प्रदान करते हैं, उन पितरों को मैं नमस्कार करता हूँ।" },
    { s: 0, n: "7",
      deva: "नमस्येऽहं पितॄन् ये वै तर्प्यन्तेऽरण्यवासिभिः ।\nवन्यैः श्राद्धैर्यताहारैस्तपोनिर्धूतकल्मषैः ॥",
      iast: "namasye'haṁ pitṝn ye vai tarpyante'raṇyavāsibhiḥ |\nvanyaiḥ śrāddhairyatāhāraistaponirdhūtakalmaṣaiḥ ||",
      en: "I bow to the forefathers who are satisfied with śrāddhas of forest fare by forest-dwellers, men of restrained diet whose sins are burnt away by austerity.",
      tel: "నియమిత ఆహారం గలవారు, తపస్సుచేత పాపాలు పోగొట్టుకున్నవారు అయిన వనవాసులు అడవి పదార్థాలతో చేసే శ్రాద్ధాలచేత తృప్తిపొందే పితరులకు నమస్కరిస్తున్నాను.",
      hi: "संयमित आहार वाले, तप से पापरहित वनवासी वन्य पदार्थों के श्राद्धों से जिन्हें तृप्त करते हैं, उन पितरों को मैं नमस्कार करता हूँ।" },
    { s: 0, n: "8",
      deva: "नमस्येऽहं पितॄन् विप्रैर्नैष्ठिकैर्धर्मचारिभिः ।\nये संयतात्मभिर्नित्यं सन्तर्प्यन्ते समाधिभिः ॥",
      iast: "namasye'haṁ pitṝn viprairnaiṣṭhikairdharmacāribhiḥ |\nye saṁyatātmabhirnityaṁ santarpyante samādhibhiḥ ||",
      en: "I bow to the forefathers who are constantly satisfied through meditation by self-controlled brāhmaṇas, lifelong celibates who walk in dharma.",
      tel: "ధర్మాచరణ గల నైష్ఠిక బ్రహ్మచారులైన బ్రాహ్మణులు సంయమంతో సమాధుల ద్వారా నిత్యం తృప్తిపరచే పితరులకు నమస్కరిస్తున్నాను.",
      hi: "धर्मपरायण नैष्ठिक ब्राह्मण संयतचित्त होकर समाधि द्वारा जिन्हें नित्य तृप्त करते हैं, उन पितरों को मैं नमस्कार करता हूँ।" },
    { s: 0, n: "9",
      deva: "नमस्येऽहं पितॄन् श्राद्धै राजन्यास्तर्पयन्ति यान् ।\nकव्यैरशेषैर्विधिवल्लोकद्वयफलप्रदान् ॥",
      iast: "namasye'haṁ pitṝn śrāddhai rājanyāstarpayanti yān |\nkavyairaśeṣairvidhivallokadvayaphalapradān ||",
      en: "I bow to the forefathers whom kṣatriyas satisfy with śrāddhas, with every kavya offering duly made, and who grant the fruit of both worlds.",
      tel: "క్షత్రియులు యథావిధిగా సకల కవ్యాలతో శ్రాద్ధాలు చేసి తృప్తిపరచేవారు, ఇహపరలోకాల ఫలాన్ని ఇచ్చేవారు అయిన పితరులకు నమస్కరిస్తున్నాను.",
      hi: "क्षत्रिय विधिपूर्वक सम्पूर्ण कव्यों वाले श्राद्धों से जिन्हें तृप्त करते हैं और जो दोनों लोकों का फल देते हैं, उन पितरों को मैं नमस्कार करता हूँ।" },
    { s: 0, n: "10",
      deva: "नमस्येऽहं पितॄन् वैश्यैरर्च्यन्ते भुवि ये सदा ।\nस्वकर्माभिरतैर्नित्यं पुष्पधूपान्नवारिभिः ॥",
      iast: "namasye'haṁ pitṝn vaiśyairarcyante bhuvi ye sadā |\nsvakarmābhiratairnityaṁ puṣpadhūpānnavāribhiḥ ||",
      en: "I bow to the forefathers who are ever worshipped on earth by vaiśyas devoted to their own work, constantly, with flowers, incense, food and water.",
      tel: "తమ కర్మలలో నిరతులైన వైశ్యులు పుష్ప, ధూప, అన్న, జలాలతో భూమిపై సదా పూజించే పితరులకు నమస్కరిస్తున్నాను.",
      hi: "अपने कर्म में लगे वैश्य पुष्प, धूप, अन्न और जल से पृथ्वी पर जिनकी सदा पूजा करते हैं, उन पितरों को मैं नमस्कार करता हूँ।" },
    { s: 0, n: "11",
      deva: "नमस्येऽहं पितॄन् श्राद्धे शूद्रैरपि च भक्तितः ।\nसन्तर्प्यन्ते जगत्कृत्स्नं नाम्ना ख्याताः सुकालिनः ॥",
      iast: "namasye'haṁ pitṝn śrāddhe śūdrairapi ca bhaktitaḥ |\nsantarpyante jagatkṛtsnaṁ nāmnā khyātāḥ sukālinaḥ ||",
      en: "I bow to the forefathers who are satisfied at śrāddha by śūdras too, in devotion — known throughout the whole world by the name Sukālins.",
      tel: "శూద్రులచేత కూడా భక్తితో శ్రాద్ధంలో తృప్తిపరచబడేవారు, జగత్తంతా 'సుకాలులు' అనే పేరుతో ప్రసిద్ధులైన పితరులకు నమస్కరిస్తున్నాను.",
      hi: "जिन्हें शूद्र भी भक्तिपूर्वक श्राद्ध में तृप्त करते हैं और जो सारे जगत् में 'सुकाली' नाम से प्रसिद्ध हैं, उन पितरों को मैं नमस्कार करता हूँ।" },
    { s: 0, n: "12",
      deva: "नमस्येऽहं पितॄन् श्राद्धे पाताले ये महासुरैः ।\nसन्तर्प्यन्ते सुधाहारास्त्यक्तदम्भमदैः सदा ॥",
      iast: "namasye'haṁ pitṝn śrāddhe pātāle ye mahāsuraiḥ |\nsantarpyante sudhāhārāstyaktadambhamadaiḥ sadā ||",
      en: "I bow to the forefathers in Pātāla who feed on nectar and are ever satisfied at śrāddha by the great asuras, who have given up hypocrisy and pride.",
      tel: "దంభాన్ని, మదాన్ని విడిచిన మహాసురులు పాతాళంలో శ్రాద్ధంలో సదా తృప్తిపరచే, సుధాహారులైన పితరులకు నమస్కరిస్తున్నాను.",
      hi: "दम्भ और मद छोड़कर महान् असुर पाताल में श्राद्ध द्वारा जिन्हें सदा तृप्त करते हैं, उन सुधाभोजी पितरों को मैं नमस्कार करता हूँ।" },
    { s: 0, n: "13",
      deva: "नमस्येऽहं पितॄन् श्राद्धैरर्च्यन्ते ये रसातले ।\nभोगैरशेषैर्विधिवन्नागैः कामानभीप्सुभिः ॥",
      iast: "namasye'haṁ pitṝn śrāddhairarcyante ye rasātale |\nbhogairaśeṣairvidhivannāgaiḥ kāmānabhīpsubhiḥ ||",
      en: "I bow to the forefathers who are worshipped in Rasātala with śrāddhas, duly and with every enjoyment, by the nāgas who seek their desires.",
      tel: "కోరికలను ఆశించే నాగులు రసాతలంలో యథావిధిగా సకల భోగాలతో శ్రాద్ధాలచేత పూజించే పితరులకు నమస్కరిస్తున్నాను.",
      hi: "कामनाओं की इच्छा रखने वाले नाग रसातल में विधिपूर्वक सम्पूर्ण भोगों वाले श्राद्धों से जिनकी पूजा करते हैं, उन पितरों को मैं नमस्कार करता हूँ।" },
    { s: 0, n: "14",
      deva: "नमस्येऽहं पितॄन् श्राद्धैः सर्पैः सन्तर्पितान्सदा ।\nतत्रैव विधिवन्मन्त्रभोगसम्पत्समन्वितैः ॥",
      iast: "namasye'haṁ pitṝn śrāddhaiḥ sarpaiḥ santarpitānsadā |\ntatraiva vidhivanmantrabhogasampatsamanvitaiḥ ||",
      en: "I bow to the forefathers who are ever satisfied with śrāddhas there too by the serpents, duly, with mantras, enjoyments and wealth.",
      tel: "అక్కడే మంత్ర, భోగ, సంపదలతో కూడిన సర్పాలు యథావిధిగా శ్రాద్ధాలచేత సదా తృప్తిపరచే పితరులకు నమస్కరిస్తున్నాను.",
      hi: "वहीं मन्त्र, भोग और सम्पत्ति से युक्त सर्प विधिपूर्वक श्राद्धों से जिन्हें सदा तृप्त करते हैं, उन पितरों को मैं नमस्कार करता हूँ।" },
    { s: 1, n: "15",
      deva: "पितॄन्नमस्ये निवसन्ति साक्षा-\n-द्ये देवलोकेऽथ महीतले वा ।\nतथाऽन्तरिक्षे च सुरारिपूज्या-\n-स्ते वै प्रतीच्छन्तु मयोपनीतम् ॥",
      iast: "pitṝnnamasye nivasanti sākṣā-\n-dye devaloke'tha mahītale vā |\ntathā'ntarikṣe ca surāripūjyā-\n-ste vai pratīcchantu mayopanītam ||",
      en: "I bow to the forefathers who dwell in person in the world of the gods, or on the earth, or in the mid-air, honoured even by the enemies of the gods — may they accept what I have brought.",
      tel: "దేవలోకంలో గాని, భూతలంలో గాని, అంతరిక్షంలో గాని సాక్షాత్తుగా నివసించేవారు, సురారులచేత కూడా పూజింపబడేవారు అయిన పితరులకు నమస్కరిస్తున్నాను — నేను సమర్పించినదాన్ని వారు స్వీకరింతురు గాక.",
      hi: "जो देवलोक में, पृथ्वी पर अथवा अन्तरिक्ष में साक्षात् निवास करते हैं और असुरों द्वारा भी पूजित हैं, उन पितरों को मैं नमस्कार करता हूँ — वे मेरे द्वारा अर्पित वस्तु को ग्रहण करें।" },
    { s: 1, n: "16",
      deva: "पितॄन्नमस्ये परमार्थभूता\nये वै विमाने निवसन्त्यमूर्ताः ।\nयजन्ति यानस्तमलैर्मनोभि-\n-र्योगीश्वराः क्लेशविमुक्तिहेतून् ॥",
      iast: "pitṝnnamasye paramārthabhūtā\nye vai vimāne nivasantyamūrtāḥ |\nyajanti yānastamalairmanobhi-\n-ryogīśvarāḥ kleśavimuktihetūn ||",
      en: "I bow to the forefathers who are the highest truth, who dwell formless in celestial cars, whom the lords of yoga, with minds free of stain, worship as the cause of release from affliction.",
      tel: "పరమార్థస్వరూపులు, విమానాలలో అమూర్తులుగా నివసించేవారు, నిర్మలమైన మనస్సులతో యోగీశ్వరులు క్లేశవిముక్తికి కారణంగా ఆరాధించేవారు అయిన పితరులకు నమస్కరిస్తున్నాను.",
      hi: "जो परमार्थस्वरूप हैं, विमानों में अमूर्त रूप से निवास करते हैं और जिन्हें योगीश्वर निर्मल मन से क्लेशों से मुक्ति का कारण मानकर पूजते हैं, उन पितरों को मैं नमस्कार करता हूँ।" },
    { s: 1, n: "17",
      deva: "पितॄन्नमस्ये दिवि ये च मूर्ताः\nस्वधाभुजः काम्यफलाभिसन्धौ ।\nप्रदानशक्ताः सकलेप्सितानां\nविमुक्तिदा येऽनभिसंहितेषु ॥",
      iast: "pitṝnnamasye divi ye ca mūrtāḥ\nsvadhābhujaḥ kāmyaphalābhisandhau |\npradānaśaktāḥ sakalepsitānāṁ\nvimuktidā ye'nabhisaṁhiteṣu ||",
      en: "I bow to the forefathers who are embodied in heaven, feeders on svadhā, able to grant every wish to those who seek a desired fruit, and givers of liberation to those who seek nothing.",
      tel: "స్వర్గంలో మూర్తిమంతులు, స్వధాభోజులు, కామ్యఫలాన్ని ఆశించేవారికి సకల అభీష్టాలను ఇవ్వగలవారు, ఏమీ ఆశించనివారికి ముక్తినిచ్చేవారు అయిన పితరులకు నమస్కరిస్తున్నాను.",
      hi: "जो स्वर्ग में मूर्तिमान् हैं, स्वधाभोजी हैं, कामना रखने वालों को सभी अभीष्ट देने में समर्थ हैं और निष्काम जनों को मुक्ति देते हैं, उन पितरों को मैं नमस्कार करता हूँ।" },
    { s: 1, n: "18",
      deva: "तृप्यन्तु तेऽस्मिन्पितरः समस्ता\nइच्छावतां ये प्रदिशन्ति कामान् ।\nसुरत्वमिन्द्रत्वमितोऽधिकं वा\nगजाश्वरत्नानि महागृहाणि ॥",
      iast: "tṛpyantu te'sminpitaraḥ samastā\nicchāvatāṁ ye pradiśanti kāmān |\nsuratvamindratvamito'dhikaṁ vā\ngajāśvaratnāni mahāgṛhāṇi ||",
      en: "May all those forefathers be satisfied by this — they who grant their desires to those who wish: godhood, the rank of Indra or more than that, elephants, horses, jewels, great houses.",
      tel: "కోరికలు గలవారికి దేవత్వాన్ని, ఇంద్రత్వాన్ని, అంతకంటే అధికమైనదాన్ని, ఏనుగులు, గుర్రాలు, రత్నాలు, మహాగృహాలు ఇచ్చే ఆ పితరులందరూ దీనితో తృప్తిపొందుదురు గాక.",
      hi: "जो कामना करने वालों को देवत्व, इन्द्रत्व या उससे भी अधिक, हाथी, घोड़े, रत्न और बड़े-बड़े भवन देते हैं, वे सभी पितर इससे तृप्त हों।" },
    { s: 1, n: "19",
      deva: "सोमस्य ये रश्मिषु येऽर्कबिम्बे\nशुक्ले विमाने च सदा वसन्ति ।\nतृप्यन्तु तेऽस्मिन्पितरोऽन्नतोयै-\n-र्गन्धादिना पुष्टिमितो व्रजन्तु ॥",
      iast: "somasya ye raśmiṣu ye'rkabimbe\nśukle vimāne ca sadā vasanti |\ntṛpyantu te'sminpitaro'nnatoyai-\n-rgandhādinā puṣṭimito vrajantu ||",
      en: "Those who dwell always in the rays of the moon, in the orb of the sun and in the white celestial car — may those forefathers be satisfied here with food and water, and from this, with fragrance and the rest, go on to nourishment.",
      tel: "చంద్రుని కిరణాలలో, సూర్యబింబంలో, శుక్ల విమానంలో సదా నివసించే పితరులు ఇక్కడ అన్నజలాలతో తృప్తిపొంది, గంధాదులతో పుష్టిని పొందుదురు గాక.",
      hi: "जो चन्द्रमा की किरणों में, सूर्य-बिम्ब में और शुक्ल विमान में सदा निवास करते हैं, वे पितर यहाँ अन्न-जल से तृप्त हों और गन्ध आदि से पुष्टि प्राप्त करें।" },
    { s: 1, n: "20",
      deva: "येषां हुतेऽग्नौ हविषा च तृप्ति-\n-र्ये भुञ्जते विप्रशरीरसंस्थाः ।\nये पिण्डदानेन मुदं प्रयान्ति\nतृप्यन्तु तेऽस्मिन्पितरोऽन्नतोयैः ॥",
      iast: "yeṣāṁ hute'gnau haviṣā ca tṛpti-\n-rye bhuñjate vipraśarīrasaṁsthāḥ |\nye piṇḍadānena mudaṁ prayānti\ntṛpyantu te'sminpitaro'nnatoyaiḥ ||",
      en: "Those whose satisfaction comes from oblation poured into the fire, who eat while dwelling in the bodies of brāhmaṇas, who are gladdened by the gift of piṇḍas — may those forefathers be satisfied here with food and water.",
      tel: "అగ్నిలో హవిస్సు హోమం చేయడంతో తృప్తిపొందేవారు, బ్రాహ్మణుల శరీరాలలో ఉండి భుజించేవారు, పిండదానంతో ఆనందించేవారు అయిన పితరులు ఇక్కడ అన్నజలాలతో తృప్తిపొందుదురు గాక.",
      hi: "जिनकी तृप्ति अग्नि में हवन किये हविष्य से होती है, जो ब्राह्मणों के शरीर में स्थित होकर भोजन करते हैं और जो पिण्डदान से प्रसन्न होते हैं, वे पितर यहाँ अन्न-जल से तृप्त हों।" },
    { s: 1, n: "21",
      deva: "ये खड्गमांसेन सुरैरभीष्टैः\nकृष्णैस्तिलैर्दिव्य मनोहरैश्च ।\nकालेन शाकेन महर्षिवर्यैः\nसम्प्रीणितास्ते मुदमत्र यान्तु ॥",
      iast: "ye khaḍgamāṁsena surairabhīṣṭaiḥ\nkṛṣṇaistilairdivya manoharaiśca |\nkālena śākena maharṣivaryaiḥ\nsamprīṇitāste mudamatra yāntu ||",
      en: "Those who are gratified by the gods with the rhinoceros flesh they prize and with black sesame, divine and lovely, and in due season by the best of the great ṛṣis with the kāla-śāka herb — may they find joy here.",
      tel: "దేవతలు ప్రియమైన ఖడ్గమృగ మాంసంతోను, దివ్యమైన మనోహరమైన నల్ల నువ్వులతోను, మహర్షిశ్రేష్ఠులు కాలశాకంతోను ప్రీతిపరచిన ఆ పితరులు ఇక్కడ ఆనందాన్ని పొందుదురు గాక.",
      hi: "जिन्हें देवता प्रिय खड्ग-मांस से तथा दिव्य और मनोहर काले तिलों से, और श्रेष्ठ महर्षि कालशाक से प्रसन्न करते हैं, वे पितर यहाँ आनन्द प्राप्त करें।" },
    { s: 1, n: "22",
      deva: "कव्यान्यशेषाणि च यान्यभीष्टा-\n-न्यतीव तेषां मम पूजितानाम् ।\nतेषाञ्च सान्निध्यमिहास्तु पुष्प-\n-गन्धाम्बुभोज्येषु मया कृतेषु ॥",
      iast: "kavyānyaśeṣāṇi ca yānyabhīṣṭā-\n-nyatīva teṣāṁ mama pūjitānām |\nteṣāñca sānnidhyamihāstu puṣpa-\n-gandhāmbubhojyeṣu mayā kṛteṣu ||",
      en: "Whatever kavya offerings are most dear to those whom I have worshipped — may they be present here, in the flowers, fragrance, water and food I have made ready.",
      tel: "నేను పూజించిన వారికి అత్యంత ప్రియమైన సకల కవ్యాలు ఏవైతే ఉన్నాయో — నేను సమర్పించిన పుష్ప, గంధ, జల, భోజ్యాలలో వారి సాన్నిధ్యం ఇక్కడ ఉండుగాక.",
      hi: "मेरे द्वारा पूजित उन पितरों को जो भी कव्य अत्यन्त प्रिय हैं — मेरे द्वारा अर्पित पुष्प, गन्ध, जल और भोज्य पदार्थों में यहाँ उनका सान्निध्य हो।" },
    { s: 1, n: "23",
      deva: "दिने दिने ये प्रतिगृह्णतेऽर्चां\nमासान्तपूज्या भुवि येऽष्टकासु ।\nये वत्सरान्तेऽभ्युदये च पूज्याः\nप्रयान्तु ते मे पितरोऽत्र तुष्टिम् ॥",
      iast: "dine dine ye pratigṛhṇate'rcāṁ\nmāsāntapūjyā bhuvi ye'ṣṭakāsu |\nye vatsarānte'bhyudaye ca pūjyāḥ\nprayāntu te me pitaro'tra tuṣṭim ||",
      en: "Those who receive worship day by day, who are to be worshipped at the month's end and on earth on the aṣṭakā days, and at the year's end and at joyful rites — may those forefathers of mine find contentment here.",
      tel: "ప్రతిదినమూ పూజను స్వీకరించేవారు, మాసాంతంలోను భూమిపై అష్టకాలలోను, సంవత్సరాంతంలోను అభ్యుదయ కార్యాలలోను పూజింపదగినవారు అయిన నా పితరులు ఇక్కడ సంతుష్టిని పొందుదురు గాక.",
      hi: "जो प्रतिदिन पूजा ग्रहण करते हैं, जो मास के अन्त में और पृथ्वी पर अष्टका तिथियों में, वर्ष के अन्त में और अभ्युदय कर्मों में पूज्य हैं, वे मेरे पितर यहाँ संतुष्ट हों।" },
    { s: 1, n: "24",
      deva: "पूज्या द्विजानां कुमुदेन्दुभासो\nये क्षत्रियाणां ज्वलनार्कवर्णाः ।\nतथा विशां ये कनकावदाता\nनीलीप्रभाः शूद्रजनस्य ये च ॥",
      iast: "pūjyā dvijānāṁ kumudendubhāso\nye kṣatriyāṇāṁ jvalanārkavarṇāḥ |\ntathā viśāṁ ye kanakāvadātā\nnīlīprabhāḥ śūdrajanasya ye ca ||",
      en: "Those worshipped by the twice-born, bright as the water-lily and the moon; those of the kṣatriyas, coloured like fire and the sun; those of the vaiśyas, pure as gold; and those of the śūdra folk, dark as indigo —",
      tel: "ద్విజులకు పూజ్యులైనవారు కలువ, చంద్రుని వంటి కాంతి గలవారు; క్షత్రియులకు అగ్నిసూర్యుల వర్ణం గలవారు; వైశ్యులకు బంగారం వంటి నిర్మల వర్ణం గలవారు; శూద్రజనులకు నీలికాంతి గలవారు —",
      hi: "द्विजों के पूज्य पितर कुमुद और चन्द्रमा के समान कान्तिवाले, क्षत्रियों के अग्नि और सूर्य के वर्ण वाले, वैश्यों के सुवर्ण के समान उज्ज्वल और शूद्रजनों के नील प्रभा वाले हैं —" },
    { s: 1, n: "25",
      deva: "तेऽस्मिन्समस्ता मम पुष्पगन्ध-\n-धूपाम्बुभोज्यादिनिवेदनेन ।\nतथाऽग्निहोमेन च यान्ति तृप्तिं\nसदा पितृभ्यः प्रणतोऽस्मि तेभ्यः ॥",
      iast: "te'sminsamastā mama puṣpagandha-\n-dhūpāmbubhojyādinivedanena |\ntathā'gnihomena ca yānti tṛptiṁ\nsadā pitṛbhyaḥ praṇato'smi tebhyaḥ ||",
      en: "all of them go to satisfaction here through my offering of flowers, fragrance, incense, water, food and the rest, and through the fire-oblation; to those forefathers I bow, always.",
      tel: "వారందరూ నేను సమర్పించే పుష్ప, గంధ, ధూప, జల, భోజ్యాదుల నివేదనతోను, అగ్నిహోమంతోను ఇక్కడ తృప్తిని పొందుతారు; ఆ పితరులకు నేను సదా ప్రణమిల్లుతున్నాను.",
      hi: "वे सभी यहाँ मेरे द्वारा अर्पित पुष्प, गन्ध, धूप, जल, भोज्य आदि के निवेदन से तथा अग्निहोम से तृप्ति प्राप्त करते हैं; उन पितरों को मैं सदा प्रणाम करता हूँ।" },
    { s: 1, n: "26",
      deva: "ये देवपूर्वाण्यभितृप्तिहेतो-\n-रश्नन्ति कव्यानि शुभाहृतानि ।\nतृप्ताश्च ये भूतिसृजो भवन्ति\nतृप्यन्तु तेऽस्मिन्प्रणतोऽस्मि तेभ्यः ॥",
      iast: "ye devapūrvāṇyabhitṛptiheto-\n-raśnanti kavyāni śubhāhṛtāni |\ntṛptāśca ye bhūtisṛjo bhavanti\ntṛpyantu te'sminpraṇato'smi tebhyaḥ ||",
      en: "Those who, for their full satisfaction, eat the kavya offerings rightly brought, with the gods' portion first, and who, once satisfied, become makers of prosperity — may they be satisfied here; to them I bow.",
      tel: "సంపూర్ణ తృప్తి కోసం దేవపూర్వకంగా శుభంగా తెచ్చిన కవ్యాలను భుజించేవారు, తృప్తిపొంది ఐశ్వర్యాన్ని సృష్టించేవారు అయిన పితరులు ఇక్కడ తృప్తిపొందుదురు గాక; వారికి ప్రణమిల్లుతున్నాను.",
      hi: "जो पूर्ण तृप्ति के लिए देवकार्य-पूर्वक शुभ रूप से लाये गये कव्यों का भोजन करते हैं और तृप्त होकर ऐश्वर्य के स्रष्टा बनते हैं, वे यहाँ तृप्त हों; उन्हें मैं प्रणाम करता हूँ।" },
    { s: 1, n: "27",
      deva: "रक्षांसि भूतान्यसुरांस्तथोग्रा-\n-न्निर्नाशयन्तु त्वशिवं प्रजानाम् ।\nआद्याः सुराणाममरेशपूज्या-\n-स्तृप्यन्तु तेऽस्मिन्प्रणतोऽस्मि तेभ्यः ॥",
      iast: "rakṣāṁsi bhūtānyasurāṁstathogrā-\n-nnirnāśayantu tvaśivaṁ prajānām |\nādyāḥ surāṇāmamareśapūjyā-\n-stṛpyantu te'sminpraṇato'smi tebhyaḥ ||",
      en: "May they destroy the rākṣasas, the bhūtas and the fierce asuras, and whatever is inauspicious for creatures; the first of the gods, honoured by the lord of the immortals — may they be satisfied here; to them I bow.",
      tel: "రాక్షసులను, భూతాలను, ఉగ్రులైన అసురులను, ప్రజలకు కలిగే అశుభాన్ని వారు నాశనం చేయుదురు గాక. దేవతలలో ఆద్యులు, దేవేంద్రునిచేత పూజింపబడేవారు అయిన వారు ఇక్కడ తృప్తిపొందుదురు గాక; వారికి ప్రణమిల్లుతున్నాను.",
      hi: "वे राक्षसों, भूतों और उग्र असुरों का तथा प्रजा के अमंगल का नाश करें। देवताओं के भी आदि और देवराज इन्द्र द्वारा पूजित वे पितर यहाँ तृप्त हों; उन्हें मैं प्रणाम करता हूँ।" },
    { s: 2, n: "28",
      deva: "अग्निष्वात्ता बर्हिषद आज्यपाः सोमपास्तथा ।\nव्रजन्तु तृप्तिं श्राद्धेऽस्मिन्पितरस्तर्पिता मया ॥",
      iast: "agniṣvāttā barhiṣada ājyapāḥ somapāstathā |\nvrajantu tṛptiṁ śrāddhe'sminpitarastarpitā mayā ||",
      en: "May the Agniṣvāttas, the Barhiṣads, the Ājyapas and the Somapas — the forefathers I have satisfied — go to satisfaction at this śrāddha.",
      tel: "అగ్నిష్వాత్తులు, బర్హిషదులు, ఆజ్యపులు, సోమపులు అనే — నేను తృప్తిపరచిన — పితరులు ఈ శ్రాద్ధంలో తృప్తిని పొందుదురు గాక.",
      hi: "अग्निष्वात्त, बर्हिषद्, आज्यप और सोमप — मेरे द्वारा तृप्त किये गये पितर — इस श्राद्ध में तृप्ति प्राप्त करें।" },
    { s: 2, n: "29",
      deva: "अग्निष्वात्ताः पितृगणाः प्राचीं रक्षन्तु मे दिशम् ।\nतथा बर्हिषदः पान्तु याम्यां मे पितरः सदा ।\nप्रतीचीमाज्यपास्तद्वदुदीचीमपि सोमपाः ॥",
      iast: "agniṣvāttāḥ pitṛgaṇāḥ prācīṁ rakṣantu me diśam |\ntathā barhiṣadaḥ pāntu yāmyāṁ me pitaraḥ sadā |\npratīcīmājyapāstadvadudīcīmapi somapāḥ ||",
      en: "May the Agniṣvātta companies of forefathers guard my eastern quarter, and the Barhiṣad forefathers always protect my southern one; the Ājyapas likewise the western, and the Somapas the northern.",
      tel: "అగ్నిష్వాత్త పితృగణాలు నా తూర్పు దిక్కును, బర్హిషదులు దక్షిణ దిక్కును సదా రక్షింతురు గాక; అలాగే ఆజ్యపులు పశ్చిమాన్ని, సోమపులు ఉత్తరాన్ని రక్షింతురు గాక.",
      hi: "अग्निष्वात्त पितृगण मेरी पूर्व दिशा की, बर्हिषद् पितर सदा दक्षिण दिशा की, आज्यप पश्चिम की और सोमप उत्तर दिशा की रक्षा करें।" },
    { s: 2, n: "30",
      deva: "रक्षोभूतपिशाचेभ्यस्तथैवासुरदोषतः ।\nसर्वतः पितरो रक्षां कुर्वन्तु मम नित्यशः ॥",
      iast: "rakṣobhūtapiśācebhyastathaivāsuradoṣataḥ |\nsarvataḥ pitaro rakṣāṁ kurvantu mama nityaśaḥ ||",
      en: "From rākṣasas, bhūtas and piśācas, and likewise from the harm of asuras, may the forefathers protect me on every side, always.",
      tel: "రాక్షసులు, భూతాలు, పిశాచాల నుండి, అలాగే అసుర దోషం నుండి పితరులు నన్ను అన్నివైపుల నుండి నిత్యం రక్షింతురు గాక.",
      hi: "राक्षस, भूत, पिशाच तथा असुरों के दोष से पितर सब ओर से नित्य मेरी रक्षा करें।" },
    { s: 2, n: "31",
      deva: "विश्वो विश्वभुगाराध्यो धर्मो धन्यः शुभाननः ।\nभूतिदो भूतिकृद्भूतिः पितॄणां ये गणा नव ॥",
      iast: "viśvo viśvabhugārādhyo dharmo dhanyaḥ śubhānanaḥ |\nbhūtido bhūtikṛdbhūtiḥ pitṝṇāṁ ye gaṇā nava ||",
      en: "Viśva, Viśvabhuk, Ārādhya, Dharma, Dhanya, Śubhānana, Bhūtida, Bhūtikṛt and Bhūti — these are the nine companies of the forefathers.",
      tel: "విశ్వుడు, విశ్వభుక్కు, ఆరాధ్యుడు, ధర్ముడు, ధన్యుడు, శుభాననుడు, భూతిదుడు, భూతికృత్తు, భూతి — ఇవి పితరుల తొమ్మిది గణాలు.",
      hi: "विश्व, विश्वभुक्, आराध्य, धर्म, धन्य, शुभानन, भूतिद, भूतिकृत् और भूति — ये पितरों के नौ गण हैं।" },
    { s: 2, n: "32",
      deva: "कल्याणः कल्यदः कर्ता कल्यः कल्यतराश्रयः ।\nकल्यताहेतुरनघः षडिमे ते गणाः स्मृताः ॥",
      iast: "kalyāṇaḥ kalyadaḥ kartā kalyaḥ kalyatarāśrayaḥ |\nkalyatāheturanaghaḥ ṣaḍime te gaṇāḥ smṛtāḥ ||",
      en: "Kalyāṇa, Kalyada, Kartṛ, Kalya, Kalyatarāśraya and Kalyatāhetu the sinless — these six are remembered as companies.",
      tel: "కల్యాణుడు, కల్యదుడు, కర్త, కల్యుడు, కల్యతరాశ్రయుడు, అనఘుడైన కల్యతాహేతువు — ఈ ఆరు గణాలుగా చెప్పబడినవి.",
      hi: "कल्याण, कल्यद, कर्ता, कल्य, कल्यतराश्रय और निष्पाप कल्यताहेतु — ये छः गण कहे गये हैं।" },
    { s: 2, n: "33",
      deva: "वरो वरेण्यो वरदस्तुष्टिदः पुष्टिदस्तथा ।\nविश्वपाता तथा धाता सप्तैते च गणाः स्मृताः ॥",
      iast: "varo vareṇyo varadastuṣṭidaḥ puṣṭidastathā |\nviśvapātā tathā dhātā saptaite ca gaṇāḥ smṛtāḥ ||",
      en: "Vara, Vareṇya, Varada, Tuṣṭida, Puṣṭida, Viśvapātṛ and Dhātṛ — these seven are remembered as companies.",
      tel: "వరుడు, వరేణ్యుడు, వరదుడు, తుష్టిదుడు, పుష్టిదుడు, విశ్వపాత, ధాత — ఈ ఏడు గణాలుగా చెప్పబడినవి.",
      hi: "वर, वरेण्य, वरद, तुष्टिद, पुष्टिद, विश्वपाता और धाता — ये सात गण कहे गये हैं।" },
    { s: 2, n: "34",
      deva: "महान्महात्मा महितो महिमावान्महाबलः ।\nगणाः पञ्च तथैवैते पितॄणां पापनाशनाः ॥",
      iast: "mahānmahātmā mahito mahimāvānmahābalaḥ |\ngaṇāḥ pañca tathaivaite pitṝṇāṁ pāpanāśanāḥ ||",
      en: "Mahān, Mahātman, Mahita, Mahimāvān and Mahābala — these five companies of the forefathers likewise destroy sin.",
      tel: "మహాన్, మహాత్మ, మహితుడు, మహిమావంతుడు, మహాబలుడు — ఈ ఐదు పితృగణాలు పాపనాశకాలు.",
      hi: "महान्, महात्मा, महित, महिमावान् और महाबल — पितरों के ये पाँच गण भी पापों का नाश करने वाले हैं।" },
    { s: 2, n: "35",
      deva: "सुखदो धनदश्चान्यो धर्मदोऽन्यश्च भूतिदः ।\nपितॄणां कथ्यते चैव तथा गणचतुष्टयम् ॥",
      iast: "sukhado dhanadaścānyo dharmado'nyaśca bhūtidaḥ |\npitṝṇāṁ kathyate caiva tathā gaṇacatuṣṭayam ||",
      en: "Sukhada, Dhanada, another called Dharmada, and another Bhūtida — thus is told the group of four companies of the forefathers.",
      tel: "సుఖదుడు, ధనదుడు, మరొక ధర్మదుడు, మరొక భూతిదుడు — ఇలా పితరుల నాలుగు గణాల సమూహం చెప్పబడుతోంది.",
      hi: "सुखद, धनद, एक और धर्मद तथा एक और भूतिद — इस प्रकार पितरों के चार गणों का समूह कहा जाता है।" },
    { s: 2, n: "36",
      deva: "एकत्रिंशत्पितृगणा यैर्व्याप्तमखिलं जगत् ।\nत एवात्र पितृगणास्तुष्यन्तु च मदाहितात् ॥",
      iast: "ekatriṁśatpitṛgaṇā yairvyāptamakhilaṁ jagat |\nta evātra pitṛgaṇāstuṣyantu ca madāhitāt ||",
      en: "The thirty-one companies of forefathers by whom this whole world is pervaded — may those same companies be pleased here by what I have offered.",
      tel: "ఈ సమస్త జగత్తును వ్యాపించి ఉన్న ముప్పై ఒక్క పితృగణాలు — ఆ గణాలే ఇక్కడ నేను సమర్పించినదానితో సంతుష్టులగుదురు గాక.",
      hi: "जिन इकतीस पितृगणों से यह सम्पूर्ण जगत् व्याप्त है, वे ही पितृगण यहाँ मेरे द्वारा अर्पित वस्तु से संतुष्ट हों।" },
  ],
},

{
  deities: ["pitr"],
  title: "Pitṛ Sūktam (Vājasaneyi)",
  blurb: "The forefathers are called up from three tiers of the dead, lower, middle and higher, and asked to come down the paths the gods use and sit on the grass. Between the calls to them runs a hymn to Soma — the drop that led the ancestors to treasure among the gods and spread out heaven and earth. This is the Yajurveda's Pitṛ Sūkta, the one a North Indian śrāddha recites.",
  about: "Śukla-Yajurveda, Vājasaneyi Saṁhitā (Mādhyandina) 19.49–61 — the North Indian form, and not the Ṛgvedic Pitṛ Sūkta, which is a different hymn kept separately here. Text from Gītā Press, Antya-karma Śrāddha-prakāśa p. 423, which prints it unaccented; the accent is taken from the accented Mādhyandina saṁhitā on sa.wikisource, the same śākhā, which with accents stripped matches the Gītā Press text letter for letter. Gītā Press has it recited before the brāhmaṇas at the śrāddha meal and forbids it in the preta-śrāddha, before sapiṇḍīkaraṇa.",
  sections: [{ roman: "Pitṛ Sūktam", tel: "పితృ సూక్తం" }],
  verses: [
    { s: 0, n: "1",
      deva: "उदी॑रता॒मव॑र॒ उत्परा॑स॒ उन्म॑ध्य॒माः पि॒तर॑ः सो॒म्यास॑ः ।\nअसुं॒ य ई॒युर॑वृ॒का ऋ॑त॒ज्ञास्ते नो॑ऽवन्तु पि॒तरो॒ हवे॑षु ॥",
      iast: "udīratāmavara utparāsa unmadhyamāḥ pitaraḥ somyāsaḥ |\nasuṁ ya īyuravṛkā ṛtajñāste no'vantu pitaro haveṣu ||",
      en: "VS 19.49. Let the forefathers rise up — the lower, the higher and the middle ones, the Soma-worthy; they who have gone to the life beyond, unharmed and knowing the order of truth — may those forefathers protect us at our invocations.",
      tel: "క్రింది, పై, మధ్యలోని సోమార్హులైన పితరులు లేచి రావుదురు గాక. హింసలేనివారై, ఋతాన్ని ఎరిగినవారై పరలోక ప్రాణాన్ని చేరిన ఆ పితరులు మా ఆహ్వానాలలో మమ్మల్ని రక్షింతురు గాక.",
      hi: "नीचे के, ऊपर के और मध्य के सोम-योग्य पितर उठें। जो अहिंसक और ऋत को जानने वाले होकर परलोक के प्राण को प्राप्त हुए हैं, वे पितर हमारे आवाहनों में हमारी रक्षा करें।" },
    { s: 0, n: "2",
      deva: "अङ्गि॑रसो नः पि॒तरो॒ नव॑ग्वा॒ अथ॑र्वाणो॒ भृग॑वः सो॒म्यास॑ः ।\nतेषां॑ व॒यᳪं᳭ सु॑म॒तौ य॒ज्ञिया॑ना॒मपि॑ भ॒द्रे सौ॑मन॒से स्या॑म ॥",
      iast: "aṅgiraso naḥ pitaro navagvā atharvāṇo bhṛgavaḥ somyāsaḥ |\nteṣāṁ vayaṁ sumatau yajñiyānāmapi bhadre saumanase syāma ||",
      en: "VS 19.50. Our forefathers the Aṅgirases, the Navagvas, the Atharvans and the Bhṛgus, worthy of Soma — may we abide in the favour of those who are worthy of sacrifice, and in their auspicious goodwill.",
      tel: "మా పితరులైన అంగిరసులు, నవగ్వులు, అథర్వులు, భృగువులు సోమార్హులు. యజ్ఞార్హులైన వారి అనుగ్రహంలోను, శుభకరమైన సౌమనస్యంలోను మేము ఉందుము గాక.",
      hi: "हमारे पितर अंगिरा, नवग्व, अथर्वा और भृगु सोम के योग्य हैं। यज्ञ के योग्य उन पितरों की कृपा में और उनके मंगलमय सौमनस्य में हम रहें।" },
    { s: 0, n: "3",
      deva: "ये न॒ः पूर्वे॑ पि॒तर॑ः सो॒म्यासो॑ऽनूहि॒रे सो॑मपी॒थं वसि॑ष्ठाः ।\nतेभि॑र्य॒मः स॑ᳪं᳭ररा॒णो ह॒वीᳪं᳭ष्यु॒शन्नु॒शद्भि॑ः प्रतिका॒मम॑त्तु ॥",
      iast: "ye naḥ pūrve pitaraḥ somyāso'nūhire somapīthaṁ vasiṣṭhāḥ |\ntebhiryamaḥ saṁrarāṇo havīṁṣyuśannuśadbhiḥ pratikāmamattu ||",
      en: "VS 19.51. Our former forefathers, Soma-worthy and most excellent, who carried on the drinking of Soma — with them may Yama, sharing their joy, eager with the eager, eat the oblations as he wishes.",
      tel: "సోమపానాన్ని కొనసాగించిన సోమార్హులు, శ్రేష్ఠులు అయిన మా పూర్వ పితరులతో కలిసి ఆనందిస్తూ, ఇష్టపడేవారితో ఇష్టపడుతూ యముడు తన ఇచ్ఛానుసారం హవిస్సులను భుజించుగాక.",
      hi: "सोमपान की परम्परा को आगे बढ़ाने वाले, सोम-योग्य और श्रेष्ठ हमारे पूर्व पितरों के साथ आनन्दित होते हुए, चाहने वालों के साथ चाहते हुए यम इच्छानुसार हवियों का भोजन करें।" },
    { s: 0, n: "4",
      deva: "त्वᳪं᳭ सो॑म॒ प्र चि॑कितो मनी॒षा त्वᳪं᳭ रजि॑ष्ठ॒मनु॑ नेषि॒ पन्था॑म् ।\nतव॒ प्रणी॑ती पि॒तरो॑ न इन्दो दे॒वेषु॒ रत्न॑मभजन्त॒ धीरा॑ः ॥",
      iast: "tvaṁ soma pra cikito manīṣā tvaṁ rajiṣṭhamanu neṣi panthām |\ntava praṇītī pitaro na indo deveṣu ratnamabhajanta dhīrāḥ ||",
      en: "VS 19.52. You, Soma, stand foremost in understanding through insight; you lead along the straightest path. Under your guidance, O drop, our wise forefathers won treasure among the gods.",
      tel: "ఓ సోమా, నీవు బుద్ధితో అన్నిటికంటే ముందుగా ఎరుగుదువు; అత్యంత ఋజుమార్గంలో నడిపిస్తావు. ఓ ఇందూ, నీ మార్గదర్శనంలోనే మా ధీరులైన పితరులు దేవతల మధ్య రత్నాన్ని పొందారు.",
      hi: "हे सोम, तुम बुद्धि से सबसे आगे जानते हो; तुम सबसे सीधे मार्ग पर ले चलते हो। हे इन्दु, तुम्हारे मार्गदर्शन में ही हमारे धीर पितरों ने देवताओं के बीच रत्न प्राप्त किया।" },
    { s: 0, n: "5",
      deva: "त्वया॒ हि न॑ः पि॒तर॑ः सोम॒ पूर्वे॒ कर्मा॑णि च॒क्रुः प॑वमान॒ धीरा॑ः ।\nव॒न्वन्नवा॑तः परि॒धीँ रपो॑र्णु वी॒रेभि॒रश्वै॑र्म॒घवा॑ भवा नः ॥",
      iast: "tvayā hi naḥ pitaraḥ soma pūrve karmāṇi cakruḥ pavamāna dhīrāḥ |\nvanvannavātaḥ paridhīm̐ raporṇu vīrebhiraśvairmaghavā bhavā naḥ ||",
      en: "VS 19.53. For through you, Soma, our wise forefathers of old did their works, O purifying one. Winning, unassailed, throw open the enclosures; be bountiful to us with heroes and with horses.",
      tel: "ఓ పవమాన సోమా, నీ ద్వారానే మా పూర్వ ధీర పితరులు తమ కర్మలను చేశారు. జయిస్తూ, ఎదురులేనివాడవై అడ్డులను తెరువుము; వీరులతోను అశ్వాలతోను మాకు ఉదారుడవగుము.",
      hi: "हे पवमान सोम, तुम्हारे द्वारा ही हमारे प्राचीन धीर पितरों ने अपने कर्म किये। विजयी और अबाध होकर तुम बाधाओं को खोल दो; वीरों और अश्वों के साथ हमारे लिए उदार बनो।" },
    { s: 0, n: "6",
      deva: "त्वᳪं᳭ सो॑म पि॒तृभि॑ः संविदा॒नोऽनु॒ द्यावा॑पृथि॒वी आ त॑तन्थ ।\nतस्मै॑ त इन्दो ह॒विषा॑ विधेम व॒यᳪं᳭ स्या॑म॒ पत॑यो रयी॒णाम् ॥",
      iast: "tvaṁ soma pitṛbhiḥ saṁvidāno'nu dyāvāpṛthivī ā tatantha |\ntasmai ta indo haviṣā vidhema vayaṁ syāma patayo rayīṇām ||",
      en: "VS 19.54. You, Soma, in accord with the forefathers, have spread out heaven and earth. To you, O drop, may we offer with oblation; may we be lords of riches.",
      tel: "ఓ సోమా, నీవు పితరులతో ఏకమై ద్యావాపృథివులను విస్తరించావు. ఓ ఇందూ, నీకు హవిస్సుతో ఆరాధన చేయుదుము గాక; మేము సంపదలకు అధిపతులమగుదుము గాక.",
      hi: "हे सोम, तुमने पितरों के साथ एकमत होकर द्युलोक और पृथ्वी को फैलाया। हे इन्दु, हम तुम्हें हवि से पूजें; हम धन के स्वामी बनें।" },
    { s: 0, n: "7",
      deva: "बर्हि॑षदः पितर ऊ॒त्यर्वागि॒मा वो॑ ह॒व्या च॑कृमा जु॒षध्व॑म् ।\nत आ ग॒ताव॑सा॒ शन्त॑मे॒नाथा॑ न॒ः शं योर॑र॒पो द॑धात ॥",
      iast: "barhiṣadaḥ pitara ūtyarvāgimā vo havyā cakṛmā juṣadhvam |\nta ā gatāvasā śantamenāthā naḥ śaṁ yorarapo dadhāta ||",
      en: "VS 19.55. Forefathers who sit on the sacred grass, come hither with your help; we have made these offerings for you — enjoy them. Come with your most beneficent aid, and grant us welfare and wholeness, free from harm.",
      tel: "బర్హిస్సుపై కూర్చునే పితరులారా, మీ రక్షణతో ఇటు రండి; మీ కోసం ఈ హవిస్సులను సిద్ధం చేశాము — స్వీకరించండి. అత్యంత శుభకరమైన రక్షణతో రండి; మాకు పాపరహితమైన శుభాన్ని, క్షేమాన్ని ఇవ్వండి.",
      hi: "कुशासन पर बैठने वाले पितरो, अपनी रक्षा के साथ इधर आओ; तुम्हारे लिए हमने ये हवियाँ बनायी हैं — इन्हें स्वीकार करो। अत्यन्त कल्याणकारी रक्षा के साथ आओ और हमें निष्पाप सुख और कुशल प्रदान करो।" },
    { s: 0, n: "8",
      deva: "आऽहं पि॒तॄन्त्सु॑वि॒दत्राँ॑ अवित्सि॒ नपा॑तं च वि॒क्रम॑णं च॒ विष्णो॑ः ।\nब॒र्हि॒षदो॒ ये स्व॒धया॑ सु॒तस्य॒ भज॑न्त पि॒त्वस्त इ॒हाग॑मिष्ठाः ॥",
      iast: "ā'haṁ pitṝntsuvidatrām̐ avitsi napātaṁ ca vikramaṇaṁ ca viṣṇoḥ |\nbarhiṣado ye svadhayā sutasya bhajanta pitvasta ihāgamiṣṭhāḥ ||",
      en: "VS 19.56. I have come to know the kindly forefathers, and the offspring and the wide stride of Viṣṇu. Those who, sitting on the sacred grass, partake with svadhā of the pressed drink — they come here most readily.",
      tel: "దయగల పితరులను, విష్ణువు యొక్క సంతతిని, ఆయన విశాలమైన పాదవిక్షేపాన్ని నేను తెలుసుకున్నాను. బర్హిస్సుపై కూర్చుని స్వధతో సోమరసాన్ని పానం చేసేవారు ఇక్కడికి అత్యంత శీఘ్రంగా వస్తారు.",
      hi: "मैंने कृपालु पितरों को, विष्णु की सन्तति को और उनके विस्तृत पाद-विक्षेप को जान लिया है। जो कुश पर बैठकर स्वधा के साथ सोमरस का भाग लेते हैं, वे यहाँ सबसे शीघ्र आते हैं।" },
    { s: 0, n: "9",
      deva: "उप॑हूताः पि॒तर॑ः सो॒म्यासो॑ बर्हि॒ष्ये॒षु नि॒धिषु॑ प्रि॒येषु॑ ।\nत आ ग॑मन्तु॒ त इ॒ह श्रु॑व॒न्त्वधि॑ ब्रुवन्तु॒ ते॑ऽवन्त्व॒स्मान् ॥",
      iast: "upahūtāḥ pitaraḥ somyāso barhiṣyeṣu nidhiṣu priyeṣu |\nta ā gamantu ta iha śruvantvadhi bruvantu te'vantvasmān ||",
      en: "VS 19.57. The Soma-worthy forefathers are invited to the dear treasures laid on the sacred grass. Let them come, let them hear us here, let them speak for us, let them protect us.",
      tel: "సోమార్హులైన పితరులు బర్హిస్సుపై ఉంచిన ప్రియమైన నిధులకు ఆహ్వానింపబడ్డారు. వారు రావుదురు గాక, ఇక్కడ మా మాట వినుదురు గాక, మా పక్షాన మాట్లాడుదురు గాక, మమ్మల్ని రక్షింతురు గాక.",
      hi: "सोम-योग्य पितर कुश पर रखी प्रिय निधियों के लिए आमन्त्रित हैं। वे आयें, यहाँ हमारी सुनें, हमारे पक्ष में बोलें और हमारी रक्षा करें।" },
    { s: 0, n: "10",
      deva: "आय॑न्तु नः पि॒तर॑ः सो॒म्यासो॑ऽग्निष्वा॒त्ताः प॒थिभि॑र्देव॒यानै॑ः ।\nअ॒स्मिन्य॒ज्ञे स्व॒धया॒ मद॒न्तोऽधि॑ ब्रुवन्तु॒ ते॒ऽवन्त्व॒स्मान् ॥",
      iast: "āyantu naḥ pitaraḥ somyāso'gniṣvāttāḥ pathibhirdevayānaiḥ |\nasminyajñe svadhayā madanto'dhi bruvantu te'vantvasmān ||",
      en: "VS 19.58. Let our Soma-worthy forefathers, the Agniṣvāttas, come along the paths the gods travel. Rejoicing in svadhā at this sacrifice, let them speak for us, let them protect us.",
      tel: "సోమార్హులైన మా పితరులు, అగ్నిష్వాత్తులు, దేవయాన మార్గాల గుండా రావుదురు గాక. ఈ యజ్ఞంలో స్వధతో ఆనందిస్తూ మా పక్షాన మాట్లాడుదురు గాక, మమ్మల్ని రక్షింతురు గాక.",
      hi: "हमारे सोम-योग्य पितर, अग्निष्वात्त, देवयान मार्गों से आयें। इस यज्ञ में स्वधा से आनन्दित होते हुए वे हमारे पक्ष में बोलें और हमारी रक्षा करें।" },
    { s: 0, n: "11",
      deva: "अग्नि॑ष्वात्ताः पितर॒ एह ग॑च्छत॒ सद॑ःसदः सदत सुप्रणीतयः ।\nअ॒त्ता ह॒वीᳪं᳭षि॒ प्रय॑तानि ब॒र्हिष्यथा॑ र॒यिᳪं᳭ सर्व॑वीरं दधातन ॥",
      iast: "agniṣvāttāḥ pitara eha gacchata sadaḥsadaḥ sadata supraṇītayaḥ |\nattā havīṁṣi prayatāni barhiṣyathā rayiṁ sarvavīraṁ dadhātana ||",
      en: "VS 19.59. Agniṣvātta forefathers, come hither; sit each in his seat, you who guide well. Eat the oblations set out upon the sacred grass, and then bestow wealth rich in heroes.",
      tel: "అగ్నిష్వాత్త పితరులారా, ఇటు రండి; సునీతులైన మీరు ఒక్కొక్క ఆసనంలో కూర్చోండి. బర్హిస్సుపై ఉంచిన హవిస్సులను భుజించి, వీరులతో కూడిన సంపదను ప్రసాదించండి.",
      hi: "हे अग्निष्वात्त पितरो, इधर आओ; हे उत्तम मार्गदर्शक पितरो, प्रत्येक आसन पर बैठो। कुश पर रखी हवियों का भोजन करो और फिर वीरों से युक्त धन प्रदान करो।" },
    { s: 0, n: "12",
      deva: "ये अ॑ग्निष्वा॒त्ता ये अन॑ग्निष्वात्ता॒ मध्ये॑ दि॒वः स्व॒धया॑ मा॒दय॑न्ते ।\nतेभ्य॑ः स्व॒राडसु॑नीतिमे॒तां य॑थाव॒शं त॒न्वं॒ कल्पयाति ॥",
      iast: "ye agniṣvāttā ye anagniṣvāttā madhye divaḥ svadhayā mādayante |\ntebhyaḥ svarāḍasunītimetāṁ yathāvaśaṁ tanvaṁ kalpayāti ||",
      en: "VS 19.60. Those who are Agniṣvāttas and those who are not, who rejoice with svadhā in the middle of heaven — together with them the self-ruling one shall shape this life and this body as he wills.",
      tel: "అగ్నిష్వాత్తులు, అగ్నిష్వాత్తులు కానివారు, ద్యులోక మధ్యంలో స్వధతో ఆనందించేవారు — వారితో కలిసి స్వరాట్టు ఈ ప్రాణాన్ని, ఈ శరీరాన్ని తన ఇచ్ఛానుసారం కల్పించుగాక.",
      hi: "जो अग्निष्वात्त हैं और जो अग्निष्वात्त नहीं हैं, जो द्युलोक के मध्य स्वधा से आनन्दित होते हैं — उनके साथ स्वराट् इस प्राण और इस शरीर को इच्छानुसार रचे।" },
    { s: 0, n: "13",
      deva: "अ॒ग्नि॒ष्वा॒त्तानृ॑तु॒मतो॑ हवामहे नाराश॒ᳪं᳭से सो॑मपी॒थं य आ॒शुः ।\nते नो॒ विप्रा॑सः सु॒हवा॑ भवन्तु व॒यᳪं᳭ स्या॑म॒ पत॑यो रयी॒णाम् ॥",
      iast: "agniṣvāttānṛtumato havāmahe nārāśaṁse somapīthaṁ ya āśuḥ |\nte no viprāsaḥ suhavā bhavantu vayaṁ syāma patayo rayīṇām ||",
      en: "VS 19.61. We invoke the Agniṣvāttas, keepers of the seasons, who drank the Soma at the Nārāśaṁsa. May those inspired ones be easy for us to call; may we be lords of riches.",
      tel: "ఋతువులకు అధిపతులైన, నారాశంసంలో సోమపానం చేసిన అగ్నిష్వాత్తులను మేము ఆహ్వానిస్తున్నాము. ఆ విప్రులు మాకు సులభంగా ఆహ్వానింపదగినవారగుదురు గాక; మేము సంపదలకు అధిపతులమగుదుము గాక.",
      hi: "ऋतुओं के अधिपति और नाराशंस में सोमपान करने वाले अग्निष्वात्तों का हम आवाहन करते हैं। वे विप्र हमारे लिए सहज आवाहनीय हों; हम धन के स्वामी बनें।" },
  ],
},

{
  deities: ["pitr"],
  title: "Pitṛ Sūktam (Ṛgveda)",
  blurb: "The Ṛgveda's hymn to the dead is gentler and stranger than the Yajurveda's. It asks forgiveness in advance for whatever wrong the living may do the dead \"being human\"; it seats the ancestors in the lap of the red dawns; and at the end it admits it does not know them all — those who are here and those who are not, those we know and those we do not — and leaves the count to Agni, who does.",
  about: "Ṛgveda 10.15, fourteen ṛks; ṛṣi Śaṅkha Yāmāyana, devatā the Pitṛs, triṣṭubh with ṛk 11 in jagatī. Text and accent from the Śākala saṁhitā on sa.wikisource, collated ṛk by ṛk against stotranidhi's accented Ṛgvedic text — the two agree in every word and on every accent position. Not a variant of the Yajurvedic Pitṛ Sūkta: four ṛks are shared outright and the rest differ, and the two are separate hymns of separate Vedas. Recited in Ṛgvedic śrāddha and aṣṭakā rites.",
  sections: [{ roman: "Pitṛ Sūktam", tel: "పితృ సూక్తం" }],
  verses: [
    { s: 0, n: "1",
      deva: "उदी॑रता॒मव॑र॒ उत्परा॑स॒ उन्म॑ध्य॒माः पि॒तरः॑ सो॒म्यासः॑ ।\nअसुं॒ य ई॒युर॑वृ॒का ऋ॑त॒ज्ञास्ते नो॑ऽवंतु पि॒तरो॒ हवे॑षु ॥",
      iast: "udīratāmavara utparāsa unmadhyamāḥ pitaraḥ somyāsaḥ |\nasuṁ ya īyuravṛkā ṛtajñāste no'vaṁtu pitaro haveṣu ||",
      en: "ṚV 10.15.1. Let the forefathers rise up — the lower, the higher and the middle ones, the Soma-worthy; they who have gone to the life beyond, unharmed and knowing the order of truth — may those forefathers protect us at our invocations.",
      tel: "క్రింది, పై, మధ్యలోని సోమార్హులైన పితరులు లేచి రావుదురు గాక. హింసలేనివారై, ఋతాన్ని ఎరిగినవారై పరలోక ప్రాణాన్ని చేరిన ఆ పితరులు మా ఆహ్వానాలలో మమ్మల్ని రక్షింతురు గాక.",
      hi: "नीचे के, ऊपर के और मध्य के सोम-योग्य पितर उठें। जो अहिंसक और ऋत को जानने वाले होकर परलोक के प्राण को प्राप्त हुए हैं, वे पितर हमारे आवाहनों में हमारी रक्षा करें।" },
    { s: 0, n: "2",
      deva: "इ॒दं पि॒तृभ्यो॒ नमो॑ अस्त्व॒द्य ये पूर्वा॑सो॒ य उप॑रास ई॒युः ।\nये पार्थि॑वे॒ रज॒स्या निष॑त्ता॒ ये वा॑ नू॒नं सु॑वृ॒जना॑सु वि॒क्षु ॥",
      iast: "idaṁ pitṛbhyo namo astvadya ye pūrvāso ya uparāsa īyuḥ |\nye pārthive rajasyā niṣattā ye vā nūnaṁ suvṛjanāsu vikṣu ||",
      en: "ṚV 10.15.2. Let this homage be to the forefathers today — to those who went first and those who went after, to those seated in the earthly realm, and to those who now dwell among the well-ordered peoples.",
      tel: "ఈ రోజు పితరులకు ఈ నమస్కారం — ముందుగా వెళ్ళినవారికి, తర్వాత వెళ్ళినవారికి, భూలోకంలో కూర్చుని ఉన్నవారికి, ఇప్పుడు సుసంపన్నమైన జనుల మధ్య నివసించేవారికి.",
      hi: "आज पितरों को यह नमस्कार हो — जो पहले गये और जो बाद में गये, जो पृथ्वी-लोक में स्थित हैं और जो अब सुसम्पन्न प्रजाओं के बीच निवास करते हैं।" },
    { s: 0, n: "3",
      deva: "आहं पि॒तॄन्त्सु॑वि॒दत्राँ॑ अवित्सि॒ नपा॑तं च वि॒क्रम॑णं च॒ विष्णोः॑ ।\nब॒र्हि॒षदो॒ ये स्व॒धया॑ सु॒तस्य॒ भजं॑त पि॒त्वस्त इ॒हाग॑मिष्ठाः ॥",
      iast: "āhaṁ pitṝntsuvidatrām̐ avitsi napātaṁ ca vikramaṇaṁ ca viṣṇoḥ |\nbarhiṣado ye svadhayā sutasya bhajaṁta pitvasta ihāgamiṣṭhāḥ ||",
      en: "ṚV 10.15.3. I have come to know the kindly forefathers, and the offspring and the wide stride of Viṣṇu. Those who, sitting on the sacred grass, partake with svadhā of the pressed drink — they come here most readily.",
      tel: "దయగల పితరులను, విష్ణువు యొక్క సంతతిని, ఆయన విశాలమైన పాదవిక్షేపాన్ని నేను తెలుసుకున్నాను. బర్హిస్సుపై కూర్చుని స్వధతో సోమరసాన్ని పానం చేసేవారు ఇక్కడికి అత్యంత శీఘ్రంగా వస్తారు.",
      hi: "मैंने कृपालु पितरों को, विष्णु की सन्तति को और उनके विस्तृत पाद-विक्षेप को जान लिया है। जो कुश पर बैठकर स्वधा के साथ सोमरस का भाग लेते हैं, वे यहाँ सबसे शीघ्र आते हैं।" },
    { s: 0, n: "4",
      deva: "बर्हि॑षदः पितर ऊ॒त्य१॒॑र्वागि॒मा वो॑ ह॒व्या च॑कृमा जु॒षध्वं॑ ।\nत आ ग॒ताव॑सा॒ शंत॑मे॒नाथा॑ नः॒ शं योर॑र॒पो द॑धात ॥",
      iast: "barhiṣadaḥ pitara ūtyarvāgimā vo havyā cakṛmā juṣadhvaṁ |\nta ā gatāvasā śaṁtamenāthā naḥ śaṁ yorarapo dadhāta ||",
      en: "ṚV 10.15.4. Forefathers who sit on the sacred grass, come hither with your help; we have made these offerings for you — enjoy them. Come with your most beneficent aid, and grant us welfare and wholeness, free from harm.",
      tel: "బర్హిస్సుపై కూర్చునే పితరులారా, మీ రక్షణతో ఇటు రండి; మీ కోసం ఈ హవిస్సులను సిద్ధం చేశాము — స్వీకరించండి. అత్యంత శుభకరమైన రక్షణతో రండి; మాకు పాపరహితమైన శుభాన్ని, క్షేమాన్ని ఇవ్వండి.",
      hi: "कुशासन पर बैठने वाले पितरो, अपनी रक्षा के साथ इधर आओ; तुम्हारे लिए हमने ये हवियाँ बनायी हैं — इन्हें स्वीकार करो। अत्यन्त कल्याणकारी रक्षा के साथ आओ और हमें निष्पाप सुख और कुशल प्रदान करो।" },
    { s: 0, n: "5",
      deva: "उप॑हूताः पि॒तरः॑ सो॒म्यासो॑ बर्हि॒ष्ये॑षु नि॒धिषु॑ प्रि॒येषु॑ ।\nत आ ग॑मंतु॒ त इ॒ह श्रु॑वं॒त्वधि॑ ब्रुवंतु॒ ते॑ऽवंत्व॒स्मान् ॥",
      iast: "upahūtāḥ pitaraḥ somyāso barhiṣyeṣu nidhiṣu priyeṣu |\nta ā gamaṁtu ta iha śruvaṁtvadhi bruvaṁtu te'vaṁtvasmān ||",
      en: "ṚV 10.15.5. The Soma-worthy forefathers are invited to the dear treasures laid on the sacred grass. Let them come, let them hear us here, let them speak for us, let them protect us.",
      tel: "సోమార్హులైన పితరులు బర్హిస్సుపై ఉంచిన ప్రియమైన నిధులకు ఆహ్వానింపబడ్డారు. వారు రావుదురు గాక, ఇక్కడ మా మాట వినుదురు గాక, మా పక్షాన మాట్లాడుదురు గాక, మమ్మల్ని రక్షింతురు గాక.",
      hi: "सोम-योग्य पितर कुश पर रखी प्रिय निधियों के लिए आमन्त्रित हैं। वे आयें, यहाँ हमारी सुनें, हमारे पक्ष में बोलें और हमारी रक्षा करें।" },
    { s: 0, n: "6",
      deva: "आच्या॒ जानु॑ दक्षिण॒तो नि॒षद्ये॒मं य॒ज्ञम॒भि गृ॑णीत॒ विश्वे॑ ।\nमा हिं॑सिष्ट पितरः॒ केन॑ चिन्नो॒ यद्व॒ आगः॑ पुरु॒षता॒ करा॑म ॥",
      iast: "ācyā jānu dakṣiṇato niṣadyemaṁ yajñamabhi gṛṇīta viśve |\nmā hiṁsiṣṭa pitaraḥ kena cinno yadva āgaḥ puruṣatā karāma ||",
      en: "ṚV 10.15.6. Bending the knee and sitting to the south, all of you, welcome this sacrifice. Do not harm us, forefathers, for any fault that we, being human, may commit against you.",
      tel: "మోకాలు వంచి దక్షిణ దిశలో కూర్చుని మీరందరూ ఈ యజ్ఞాన్ని స్వాగతించండి. పితరులారా, మానవులమైన మేము మీ పట్ల ఏ అపరాధం చేసినా దాని వల్ల మమ్మల్ని హింసించకండి.",
      hi: "घुटना मोड़कर दक्षिण दिशा में बैठकर तुम सब इस यज्ञ का स्वागत करो। हे पितरो, मनुष्य होने के कारण हम तुम्हारे प्रति जो भी अपराध करें, उसके लिए हमें हानि न पहुँचाओ।" },
    { s: 0, n: "7",
      deva: "आसी॑नासो अरु॒णीना॑मु॒पस्थे॑ र॒यिं ध॑त्त दा॒शुषे॒ मर्त्या॑य ।\nपु॒त्रेभ्यः॑ पितर॒स्तस्य॒ वस्वः॒ प्र य॑च्छत॒ त इ॒होर्जं॑ दधात ॥",
      iast: "āsīnāso aruṇīnāmupasthe rayiṁ dhatta dāśuṣe martyāya |\nputrebhyaḥ pitarastasya vasvaḥ pra yacchata ta ihorjaṁ dadhāta ||",
      en: "ṚV 10.15.7. Seated in the lap of the ruddy dawns, give wealth to the mortal who worships you; forefathers, give his sons a share of that treasure, and grant strength here.",
      tel: "అరుణ వర్ణపు ఉషస్సుల ఒడిలో కూర్చుని, మిమ్మల్ని ఆరాధించే మానవునికి సంపదను ఇవ్వండి. పితరులారా, ఆ సంపదలో అతని కుమారులకు భాగమివ్వండి, ఇక్కడ బలాన్ని ప్రసాదించండి.",
      hi: "अरुण उषाओं की गोद में बैठकर तुम्हारी पूजा करने वाले मनुष्य को धन दो। हे पितरो, उस धन में उसके पुत्रों को भी भाग दो और यहाँ बल प्रदान करो।" },
    { s: 0, n: "8",
      deva: "ये नः॒ पूर्वे॑ पि॒तरः॑ सो॒म्यासो॑ऽनूहि॒रे सो॑मपी॒थं वसि॑ष्ठाः ।\nतेभि॑र्य॒मः सं॑ररा॒णो ह॒वींष्यु॒शन्नु॒शद्भिः॑ प्रतिका॒मम॑त्तु ॥",
      iast: "ye naḥ pūrve pitaraḥ somyāso'nūhire somapīthaṁ vasiṣṭhāḥ |\ntebhiryamaḥ saṁrarāṇo havīṁṣyuśannuśadbhiḥ pratikāmamattu ||",
      en: "ṚV 10.15.8. Our former forefathers, Soma-worthy and most excellent, who carried on the drinking of Soma — with them may Yama, sharing their joy, eager with the eager, eat the oblations as he wishes.",
      tel: "సోమపానాన్ని కొనసాగించిన సోమార్హులు, శ్రేష్ఠులు అయిన మా పూర్వ పితరులతో కలిసి ఆనందిస్తూ, ఇష్టపడేవారితో ఇష్టపడుతూ యముడు తన ఇచ్ఛానుసారం హవిస్సులను భుజించుగాక.",
      hi: "सोमपान की परम्परा को आगे बढ़ाने वाले, सोम-योग्य और श्रेष्ठ हमारे पूर्व पितरों के साथ आनन्दित होते हुए, चाहने वालों के साथ चाहते हुए यम इच्छानुसार हवियों का भोजन करें।" },
    { s: 0, n: "9",
      deva: "ये ता॑तृ॒षुर्दे॑व॒त्रा जेह॑माना होत्रा॒विदः॒ स्तोम॑तष्टासो अ॒र्कैः ।\nआग्ने॑ याहि सुवि॒दत्रे॑भिर॒र्वाङ्स॒त्यैः क॒व्यैः पि॒तृभि॑र्घर्म॒सद्भिः॑ ॥",
      iast: "ye tātṛṣurdevatrā jehamānā hotrāvidaḥ stomataṣṭāso arkaiḥ |\nāgne yāhi suvidatrebhirarvāṅsatyaiḥ kavyaiḥ pitṛbhirgharmasadbhiḥ ||",
      en: "ṚV 10.15.9. Those who thirsted among the gods, straining toward them, knowers of the oblation, fashioners of praise with their hymns — come, Agni, with these kindly and true forefathers, the eaters of the kavya, who sit by the heated vessel.",
      tel: "దేవతల మధ్య దాహంతో ఆరాటపడినవారు, హోత్రాన్ని ఎరిగినవారు, అర్కాలతో స్తోమాలను రచించినవారు అయిన ఈ దయగల, సత్యవంతులైన, కవ్యభోజులైన, ఘర్మపాత్రం వద్ద కూర్చునే పితరులతో ఓ అగ్నీ, ఇటు రమ్ము.",
      hi: "जो देवताओं के बीच प्यासे होकर उत्सुक रहे, जो होत्र को जानने वाले और स्तुतियों से स्तोम रचने वाले हैं — हे अग्नि, इन कृपालु, सत्यनिष्ठ, कव्यभोजी और घर्म के पास बैठने वाले पितरों के साथ इधर आओ।" },
    { s: 0, n: "10",
      deva: "ये स॒त्यासो॑ हवि॒रदो॑ हवि॒ष्पा इंद्रे॑ण दे॒वैः स॒रथं॒ दधा॑नाः ।\nआग्ने॑ याहि स॒हस्रं॑ देववं॒दैः परैः॒ पूर्वैः॑ पि॒तृभि॑र्घर्म॒सद्भिः॑ ॥",
      iast: "ye satyāso havirado haviṣpā iṁdreṇa devaiḥ sarathaṁ dadhānāḥ |\nāgne yāhi sahasraṁ devavaṁdaiḥ paraiḥ pūrvaiḥ pitṛbhirgharmasadbhiḥ ||",
      en: "ṚV 10.15.10. Those true ones who eat and drink the oblation, riding in one chariot with Indra and the gods — come, Agni, with a thousand of them, praisers of the gods, the ancient and the earlier forefathers who sit by the heated vessel.",
      tel: "హవిస్సును భుజించి పానం చేసే, ఇంద్రునితోను దేవతలతోను ఒకే రథంలో ఉండే సత్యవంతులు — దేవతలను స్తుతించే, ప్రాచీనులు, పూర్వులు, ఘర్మపాత్రం వద్ద కూర్చునే వేయి మంది పితరులతో ఓ అగ్నీ, ఇటు రమ్ము.",
      hi: "जो सत्यनिष्ठ हवि खाते और पीते हैं, जो इन्द्र और देवताओं के साथ एक ही रथ पर रहते हैं — हे अग्नि, देवताओं की वन्दना करने वाले, प्राचीन और पूर्ववर्ती, घर्म के पास बैठने वाले ऐसे हज़ार पितरों के साथ इधर आओ।" },
    { s: 0, n: "11",
      deva: "अग्नि॑ष्वात्ताः पितर॒ एह ग॑च्छत॒ सदः॑सदः सदत सुप्रणीतयः ।\nअ॒त्ता ह॒वींषि॒ प्रय॑तानि ब॒र्हिष्यथा॑ र॒यिं सर्व॑वीरं दधातन ॥",
      iast: "agniṣvāttāḥ pitara eha gacchata sadaḥsadaḥ sadata supraṇītayaḥ |\nattā havīṁṣi prayatāni barhiṣyathā rayiṁ sarvavīraṁ dadhātana ||",
      en: "ṚV 10.15.11. Agniṣvātta forefathers, come hither; sit each in his seat, you who guide well. Eat the oblations set out upon the sacred grass, and then bestow wealth rich in heroes.",
      tel: "అగ్నిష్వాత్త పితరులారా, ఇటు రండి; సునీతులైన మీరు ఒక్కొక్క ఆసనంలో కూర్చోండి. బర్హిస్సుపై ఉంచిన హవిస్సులను భుజించి, వీరులతో కూడిన సంపదను ప్రసాదించండి.",
      hi: "हे अग्निष्वात्त पितरो, इधर आओ; हे उत्तम मार्गदर्शक पितरो, प्रत्येक आसन पर बैठो। कुश पर रखी हवियों का भोजन करो और फिर वीरों से युक्त धन प्रदान करो।" },
    { s: 0, n: "12",
      deva: "त्वम॑ग्न ईळि॒तो जा॑तवे॒दोऽवा॑ड्ढ॒व्यानि॑ सुर॒भीणि॑ कृ॒त्वी ।\nप्रादाः॑ पि॒तृभ्यः॑ स्व॒धया॒ ते अ॑क्षन्न॒द्धि त्वं दे॑व॒ प्रय॑ता ह॒वींषि॑ ॥",
      iast: "tvamagna īḷito jātavedo'vāḍḍhavyāni surabhīṇi kṛtvī |\nprādāḥ pitṛbhyaḥ svadhayā te akṣannaddhi tvaṁ deva prayatā havīṁṣi ||",
      en: "ṚV 10.15.12. You, Agni Jātavedas, being praised, carried the oblations, having made them fragrant; you gave them to the forefathers, and they ate with svadhā. Eat, O god, the offerings set before you.",
      tel: "ఓ జాతవేద అగ్నీ, స్తుతింపబడిన నీవు హవిస్సులను సుగంధభరితంగా చేసి వహించావు; వాటిని పితరులకు ఇచ్చావు, వారు స్వధతో భుజించారు. ఓ దేవా, సమర్పించిన హవిస్సులను నీవు కూడా భుజించుము.",
      hi: "हे जातवेद अग्नि, स्तुति किये जाकर तुमने हवियों को सुगन्धित करके वहन किया; तुमने उन्हें पितरों को दिया और उन्होंने स्वधा के साथ खाया। हे देव, अर्पित हवियों को तुम भी खाओ।" },
    { s: 0, n: "13",
      deva: "ये चे॒ह पि॒तरो॒ ये च॒ नेह यांश्च॑ वि॒द्म याँ उ॑ च॒ न प्र॑वि॒द्म ।\nत्वं वे॑त्थ॒ यति॒ ते जा॑तवेदः स्व॒धाभि॑र्य॒ज्ञं सुकृ॑तं जुषस्व ॥",
      iast: "ye ceha pitaro ye ca neha yāṁśca vidma yām̐ u ca na pravidma |\ntvaṁ vettha yati te jātavedaḥ svadhābhiryajñaṁ sukṛtaṁ juṣasva ||",
      en: "ṚV 10.15.13. The forefathers who are here and those who are not here, those we know and those we do not know — you know how many they are, Jātavedas; accept the well-made sacrifice with the svadhā offerings.",
      tel: "ఇక్కడ ఉన్న పితరులు, ఇక్కడ లేనివారు, మాకు తెలిసినవారు, మాకు తెలియనివారు — ఓ జాతవేదా, వారు ఎంతమందో నీకు తెలుసు; స్వధలతో చక్కగా చేసిన ఈ యజ్ఞాన్ని స్వీకరించుము.",
      hi: "जो पितर यहाँ हैं और जो यहाँ नहीं हैं, जिन्हें हम जानते हैं और जिन्हें नहीं जानते — हे जातवेद, वे कितने हैं यह तुम जानते हो; स्वधाओं के साथ भली-भाँति किये गये इस यज्ञ को स्वीकार करो।" },
    { s: 0, n: "14",
      deva: "ये अ॑ग्निद॒ग्धा ये अन॑ग्निदग्धा॒ मध्ये॑ दि॒वः स्व॒धया॑ मा॒दयं॑ते ।\nतेभिः॑ स्व॒राळसु॑नीतिमे॒तां य॑थाव॒शं त॒न्वं॑ कल्पयस्व ॥",
      iast: "ye agnidagdhā ye anagnidagdhā madhye divaḥ svadhayā mādayaṁte |\ntebhiḥ svarāḷasunītimetāṁ yathāvaśaṁ tanvaṁ kalpayasva ||",
      en: "ṚV 10.15.14. Those who were given to the fire and those who were not, who rejoice with svadhā in the middle of heaven — together with them, self-ruler, shape this life and this body as you will.",
      tel: "అగ్నిలో దహింపబడినవారు, అగ్నిలో దహింపబడనివారు, ద్యులోక మధ్యంలో స్వధతో ఆనందించేవారు — వారితో కలిసి, ఓ స్వరాట్టూ, ఈ ప్రాణాన్ని, ఈ శరీరాన్ని నీ ఇచ్ఛానుసారం కల్పించుము.",
      hi: "जो अग्नि में दग्ध हुए और जो अग्नि में दग्ध नहीं हुए, जो द्युलोक के मध्य स्वधा से आनन्दित होते हैं — हे स्वराट्, उनके साथ इस प्राण और इस शरीर को इच्छानुसार रचो।" },
  ],
},

{
  deities: ["pitr"],
  title: "Pitṛ Stotram (Brahma-kṛtam)",
  blurb: "The shortest of the pitṛ hymns, and the only one addressed to a single living man. Brahmā praises his own father Viṣṇu — and the words are general enough for any son to use: the father is the giver of the rare human body, the sight of him is every pilgrimage at once, and bowing to him is worth a hundred horse-sacrifices.",
  about: "Bṛhaddharma Purāṇa, Pūrvakhaṇḍa 2.23–32, from the Chowkhamba edition (ed. S. N. Khandelwal), collated against stotranidhi. No Gītā Press edition of this text was found, so the printed Purāṇa is the authority. Its pitṛ is singular throughout — this is a hymn to one's own father, not to the ancestral pitṛ-gaṇa, and the phalaśruti has it recited on the father's śrāddha day, on one's own birthday, or standing before a living father.",
  sections: [
    { roman: "Stotram", tel: "స్తోత్రం" },
    { roman: "Phalaśrutiḥ", tel: "ఫలశ్రుతి" },
  ],
  verses: [
    { s: 0, n: "1",
      deva: "ब्रह्मोवाच ।\nॐ नमः पित्रे जन्मदात्रे सर्व्वदेवमयाय च ।\nसुखदाय प्रसन्नाय सुप्रीताय महात्मने ॥",
      iast: "brahmovāca |\noṁ namaḥ pitre janmadātre sarvvadevamayāya ca |\nsukhadāya prasannāya suprītāya mahātmane ||",
      en: "Brahmā said: Oṁ. Salutation to the father, the giver of birth, in whom all the gods are present; to the giver of happiness, the gracious, the well-pleased, the great-souled.",
      tel: "బ్రహ్మ పలికెను: ఓం. జన్మనిచ్చినవాడు, సర్వదేవమయుడు, సుఖాన్ని ఇచ్చేవాడు, ప్రసన్నుడు, సుప్రీతుడు, మహాత్ముడు అయిన తండ్రికి నమస్కారం.",
      hi: "ब्रह्मा बोले — ॐ। जन्म देने वाले, सर्वदेवमय, सुख देने वाले, प्रसन्न, सुप्रीत और महात्मा पिता को नमस्कार है।" },
    { s: 0, n: "2",
      deva: "सर्व्वयज्ञस्वरूपाय स्वर्गाय परमेष्ठिने ।\nसर्व्वतीर्थावलोकाय करुणासागराय च ॥",
      iast: "sarvvayajñasvarūpāya svargāya parameṣṭhine |\nsarvvatīrthāvalokāya karuṇāsāgarāya ca ||",
      en: "To him whose form is every sacrifice, who is heaven itself, the highest; to him the sight of whom is every holy place, an ocean of compassion.",
      tel: "సర్వయజ్ఞస్వరూపుడు, స్వర్గమే అయినవాడు, పరమేష్ఠి, తన దర్శనమే సర్వతీర్థదర్శనమైనవాడు, కరుణాసాగరుడు అయిన తండ్రికి నమస్కారం.",
      hi: "सर्वयज्ञस्वरूप, स्वर्गरूप, परमेष्ठी, जिनका दर्शन सब तीर्थों का दर्शन है और जो करुणा के सागर हैं, उन पिता को नमस्कार है।" },
    { s: 0, n: "3",
      deva: "नमः सदाशुतोषाय शिवरूपाय ते नमः ।\nसदापराधक्षमिणे सुखाय सुखदाय च ॥",
      iast: "namaḥ sadāśutoṣāya śivarūpāya te namaḥ |\nsadāparādhakṣamiṇe sukhāya sukhadāya ca ||",
      en: "Salutation to you who are always quickly pleased, whose form is auspicious — salutation; to him who always forgives offences, who is happiness and the giver of happiness.",
      tel: "సదా శీఘ్రంగా సంతుష్టుడయ్యేవాడు, శివరూపుడు అయిన నీకు నమస్కారం. సదా అపరాధాలను క్షమించేవాడు, సుఖరూపుడు, సుఖాన్ని ఇచ్చేవాడు అయిన తండ్రికి నమస్కారం.",
      hi: "सदा शीघ्र प्रसन्न होने वाले, शिवरूप, आपको नमस्कार है। सदा अपराध क्षमा करने वाले, सुखरूप और सुख देने वाले पिता को नमस्कार है।" },
    { s: 0, n: "4",
      deva: "दुर्लभं मानुषमिदं येन लब्धं मया वपुः ।\nसम्भावनीयं धर्म्मार्थे तस्मै पित्रे नमोनमः ॥",
      iast: "durlabhaṁ mānuṣamidaṁ yena labdhaṁ mayā vapuḥ |\nsambhāvanīyaṁ dharmmārthe tasmai pitre namonamaḥ ||",
      en: "To the father through whom I obtained this human body, so hard to win, worthy to be honoured for the sake of dharma — salutation, salutation.",
      tel: "దుర్లభమైన, ధర్మాచరణకు యోగ్యమైన ఈ మానవ శరీరాన్ని ఎవరి వలన నేను పొందానో ఆ తండ్రికి మళ్ళీ మళ్ళీ నమస్కారం.",
      hi: "जिनके कारण मैंने धर्म के लिए उपयोगी यह दुर्लभ मनुष्य-शरीर प्राप्त किया, उन पिता को बारम्बार नमस्कार है।" },
    { s: 0, n: "5",
      deva: "तीर्थस्नान-तपोहोम-जपादि यस्य दर्शनम् ।\nमहागुरोश्च गुरवे तस्मै पित्रे नमोनमः ॥",
      iast: "tīrthasnāna-tapohoma-japādi yasya darśanam |\nmahāgurośca gurave tasmai pitre namonamaḥ ||",
      en: "To the father the mere sight of whom is bathing at a tīrtha, austerity, homa and japa; to the guru even of the great guru — salutation, salutation.",
      tel: "ఎవరి దర్శనమే తీర్థస్నానం, తపస్సు, హోమం, జపం మొదలైనవో, మహాగురువుకు కూడా గురువైన ఆ తండ్రికి మళ్ళీ మళ్ళీ నమస్కారం.",
      hi: "जिनका दर्शन ही तीर्थस्नान, तप, होम और जप आदि है, महागुरु के भी गुरु उन पिता को बारम्बार नमस्कार है।" },
    { s: 0, n: "6",
      deva: "यस्य प्रणामस्तवनात् कोटिशः पितृतर्पणम् ।\nअश्वमेधशतैस्तुल्यं तस्मै पित्रे नमोनमः ॥",
      iast: "yasya praṇāmastavanāt koṭiśaḥ pitṛtarpaṇam |\naśvamedhaśataistulyaṁ tasmai pitre namonamaḥ ||",
      en: "To the father, bowing to and praising whom is tarpaṇa to the forefathers ten-million-fold, equal to a hundred horse-sacrifices — salutation, salutation.",
      tel: "ఎవరికి ప్రణమిల్లి స్తుతించడం కోటిరెట్లు పితృతర్పణానికి, వంద అశ్వమేధాలకు సమానమో ఆ తండ్రికి మళ్ళీ మళ్ళీ నమస్కారం.",
      hi: "जिन्हें प्रणाम करने और जिनकी स्तुति करने से करोड़ों पितृतर्पण का फल मिलता है और जो सैकड़ों अश्वमेधों के समान है, उन पिता को बारम्बार नमस्कार है।" },
    { s: 1, n: "7",
      deva: "इदं स्तोत्रं पितुः पुण्यं यः पठेत् प्रयतो नरः ।\nप्रत्यहं प्रातरुत्थाय पितृश्राद्धदिनेऽपि च ॥",
      iast: "idaṁ stotraṁ pituḥ puṇyaṁ yaḥ paṭhet prayato naraḥ |\npratyahaṁ prātarutthāya pitṛśrāddhadine'pi ca ||",
      en: "The man who, self-controlled, recites this holy hymn to the father, rising early every day, and on the day of his father's śrāddha too —",
      tel: "తండ్రిని గూర్చిన ఈ పుణ్యస్తోత్రాన్ని నియమంతో ప్రతిరోజూ ప్రాతఃకాలంలో లేచి, తండ్రి శ్రాద్ధ దినాన కూడా పఠించే మనిషికి —",
      hi: "जो मनुष्य पवित्र होकर इस पुण्य पितृस्तोत्र को प्रतिदिन प्रातःकाल उठकर तथा पिता के श्राद्ध के दिन भी पढ़ता है —" },
    { s: 1, n: "8",
      deva: "स्वजन्मदिवसे साक्षात् पितुरग्रे स्थितोऽपि वा ।\nन तस्य दुर्लभं किञ्चित् सर्व्वज्ञतादिवाञ्छितम् ॥",
      iast: "svajanmadivase sākṣāt pituragre sthito'pi vā |\nna tasya durlabhaṁ kiñcit sarvvajñatādivāñchitam ||",
      en: "or on his own birthday, or standing before his father in person — for him nothing is hard to obtain, even omniscience or whatever else he desires.",
      tel: "లేదా తన జన్మదినాన, లేదా తండ్రి ఎదుట సాక్షాత్తుగా నిలిచి పఠించేవానికి — సర్వజ్ఞత్వం మొదలుకొని కోరినది ఏదీ దుర్లభం కాదు.",
      hi: "या अपने जन्मदिन पर, या पिता के सामने साक्षात् खड़ा होकर पढ़ता है — उसके लिए सर्वज्ञता आदि कोई भी इच्छित वस्तु दुर्लभ नहीं है।" },
    { s: 1, n: "9",
      deva: "नानापकर्म कृत्वापि यः स्तौति पितरं सुतः ।\nस ध्रुवं प्रविधायैव प्रायश्चित्तं सुखी भवेत् ।\nपितुः प्रीतिकरो नित्यं सर्वकर्म्माण्यथार्हति ॥",
      iast: "nānāpakarma kṛtvāpi yaḥ stauti pitaraṁ sutaḥ |\nsa dhruvaṁ pravidhāyaiva prāyaścittaṁ sukhī bhavet |\npituḥ prītikaro nityaṁ sarvakarmmāṇyathārhati ||",
      en: "The son who, even after many misdeeds, praises his father thus becomes happy as surely as if he had performed the expiation; doing always what pleases his father, he becomes fit for every rite.",
      tel: "అనేక అపకర్మలు చేసినప్పటికీ తండ్రిని ఇలా స్తుతించే కుమారుడు ప్రాయశ్చిత్తం చేసినట్లుగానే నిశ్చయంగా సుఖి అవుతాడు. సదా తండ్రికి ప్రీతి కలిగించేవాడు సకల కర్మలకు అర్హుడవుతాడు.",
      hi: "जो पुत्र अनेक अपकर्म करके भी पिता की इस प्रकार स्तुति करता है, वह मानो प्रायश्चित्त करके निश्चय ही सुखी हो जाता है। सदा पिता को प्रसन्न करने वाला पुत्र सब कर्मों का अधिकारी होता है।" },
  ],
},];
