/* ============================================================
   STUTI — Subrahmaṇya full texts (desktop batch, files 08/09/10/11)
   Vajrapañjara Kavacam · Kārtikeya Karāvalamba · Kārtikeya Pañcakam · Kārtikeya Stotram
   Converted verbatim from the user's sourced dossier files —
   Devanāgarī is the source of truth; verses carry en/tel/hi glosses
   inline. Titles must match STOTRA_INDEX exactly.
   ============================================================ */
export const extra = [{
  deities: ["subrahmanya"],
  title: "Subrahmaṇya Vajrapañjara Kavacam",
  blurb: "The diamond cage — Agastya teaches Nārada a kavaca of finer mesh than most: palate and gums, jaw and wrist, then outward to house, field and cattle. From the Skanda Purāṇa.",
  colophon: { deva: "इति स्कान्दे अगस्त्यनारदसंवादे सुब्रह्मण्य कवचम् ।", iast: "iti skānde agastyanāradasaṁvāde subrahmaṇya kavacam |" },
  sections: [{ tel: "వినియోగం", roman: "Viniyoga" }, { tel: "న్యాసః", roman: "Nyāsaḥ" }, { tel: "ధ్యానం", roman: "Dhyānam" }, { tel: "పంచపూజ", roman: "Pañcapūjā" }, { tel: "కవచం", roman: "The Armour" }, { tel: "ఫలశ్రుతి", roman: "The Fruit of Recitation" }],
  verses: [
    { s: 0, n: null,
      deva: "अस्य श्री सुब्रह्मण्य कवचस्तोत्र महामन्त्रस्य अगस्त्यो भगवान् ऋषिः अनुष्टुप्छन्दः श्री सुब्रह्मण्यो देवता\nसं बीजं स्वाहा शक्तिः सः कीलकं\nश्री सुब्रह्मण्यप्रसादसिद्ध्यर्थे जपे विनियोगः ॥",
      iast: "asya śrī subrahmaṇya kavacastotra mahāmantrasya agastyo bhagavān ṛṣiḥ anuṣṭupchandaḥ śrī subrahmaṇyo devatā\nsaṁ bījaṁ svāhā śaktiḥ saḥ kīlakaṁ\nśrī subrahmaṇyaprasādasiddhyarthe jape viniyogaḥ ||",
      en: "For this great mantra, the Śrī Subrahmaṇya Kavaca Stotra, the blessed Agastya is the ṛṣi, the anuṣṭubh is the chandas, Śrī Subrahmaṇya is the devatā; \"saṁ\" is the bīja, \"svāhā\" is the śakti, \"saḥ\" is the kīlaka; its viniyoga is for japa undertaken to attain the grace of Śrī Subrahmaṇya.",
      tel: "ఈ మహామంత్రమైన శ్రీ సుబ్రహ్మణ్య కవచ స్తోత్రానికి భగవానుడైన అగస్త్యుడు ఋషి, అనుష్టుప్పు ఛందస్సు, శ్రీ సుబ్రహ్మణ్యుడు దేవత; \"సం\" బీజం, \"స్వాహా\" శక్తి, \"సః\" కీలకం; శ్రీ సుబ్రహ్మణ్యుని అనుగ్రహసిద్ధి కోసం చేసే జపంలో దీని వినియోగం.",
      hi: "इस महामंत्र, श्री सुब्रह्मण्य कवच स्तोत्र के, भगवान अगस्त्य ऋषि हैं, अनुष्टुप् छंद है, श्री सुब्रह्मण्य देवता हैं; \"सं\" बीज है, \"स्वाहा\" शक्ति है, \"सः\" कीलक है; श्री सुब्रह्मण्य की कृपा-सिद्धि हेतु किए जाने वाले जप में इसका विनियोग है।" },
    { s: 1, n: null,
      deva: "न्यासः –\nहिरण्यशरीराय अङ्गुष्ठाभ्यां नमः ।\nइक्षुधनुर्धराय तर्जनीभ्यां नमः ।\nशरवणभवाय मध्यमाभ्यां नमः ।\nशिखिवाहनाय अनामिकाभ्यां नमः ।\nशक्तिहस्ताय कनिष्ठिकाभ्यां नमः ।\nसकलदुरितमोचनाय करतलकरपृष्ठाभ्यां नमः ।\nएवं हृदयादि न्यासः ॥",
      iast: "nyāsaḥ –\nhiraṇyaśarīrāya aṅguṣṭhābhyāṁ namaḥ |\nikṣudhanurdharāya tarjanībhyāṁ namaḥ |\nśaravaṇabhavāya madhyamābhyāṁ namaḥ |\nśikhivāhanāya anāmikābhyāṁ namaḥ |\nśaktihastāya kaniṣṭhikābhyāṁ namaḥ |\nsakaladuritamocanāya karatalakarapṛṣṭhābhyāṁ namaḥ |\nevaṁ hṛdayādi nyāsaḥ ||",
      en: "The nyāsa touches the thumbs while naming him Hiraṇyaśarīra (golden-bodied), the forefingers while naming him Ikṣudhanurdhara (bearer of the sugarcane bow), the middle fingers while naming him Śaravaṇabhava (born in the reed-thicket), the ring fingers while naming him Śikhivāhana (peacock-mounted), the little fingers while naming him Śaktihasta (spear in hand), and both sides of the palms while naming him Sakaladuritamocana (releaser from every sin); the same six names are then touched again to the heart and remaining limbs (hṛdayādi nyāsa), abbreviated here to \"evaṁ\" (\"and so on\").",
      tel: "న్యాసంలో బొటనవేళ్ళను తాకుతూ ఆయనను హిరణ్యశరీర (బంగారు శరీరం కలవాడు) అని, చూపుడువేళ్ళను తాకుతూ ఇక్షుధనుర్ధర (చెరకువింటిని ధరించినవాడు) అని, మధ్యవేళ్ళను తాకుతూ శరవణభవ (రెల్లువనంలో పుట్టినవాడు) అని, ఉంగరపువేళ్ళను తాకుతూ శిఖివాహన (నెమలివాహనుడు) అని, చిటికెనవేళ్ళను తాకుతూ శక్తిహస్త (చేతిలో శక్త్యాయుధం కలవాడు) అని, అరచేతుల రెండువైపులను తాకుతూ సకలదురితమోచన (సకల పాపాలనుండి విడిపించేవాడు) అని పేర్కొంటారు; అవే ఆరు పేర్లు హృదయం మొదలైన మిగిలిన అవయవాలకూ తాకి పఠించాలి (హృదయాది న్యాసం), ఇక్కడ \"ఏవం\" (ఇత్యాదిగా) అని సంక్షిప్తీకరించారు.",
      hi: "न्यास में अंगूठों को स्पर्श करते हुए उन्हें हिरण्यशरीर (स्वर्ण-देह वाले), तर्जनियों को स्पर्श करते हुए इक्षुधनुर्धर (गन्ने का धनुष धारण करने वाले), मध्यमाओं को स्पर्श करते हुए शरवणभव (सरकंडे के वन में जन्मे), अनामिकाओं को स्पर्श करते हुए शिखिवाहन (मयूर-वाहन), कनिष्ठिकाओं को स्पर्श करते हुए शक्तिहस्त (हाथ में शक्ति-आयुध धारण करने वाले), तथा दोनों हथेलियों को स्पर्श करते हुए सकलदुरितमोचन (समस्त पापों से मुक्त करने वाले) कहा जाता है; वही छह नाम हृदय आदि शेष अंगों पर भी स्पर्श करके दोहराए जाते हैं (हृदयादि न्यास), यहाँ \"एवं\" (इत्यादि रूप में) कहकर संक्षिप्त किया गया है।" },
    { s: 2, n: null,
      deva: "ध्यानम् ।\nकनककुण्डलमण्डितषण्मुखं\nवनजराजि विराजित लोचनम् ।\nनिशित शस्त्रशरासनधारिणं\nशरवणोद्भवमीशसुतं भजे ॥",
      iast: "dhyānam |\nkanakakuṇḍalamaṇḍitaṣaṇmukhaṁ\nvanajarāji virājita locanam |\nniśita śastraśarāsanadhāriṇaṁ\nśaravaṇodbhavamīśasutaṁ bhaje ||",
      en: "I worship Śaravaṇodbhava, son of Īśa (Śiva) — his six faces adorned with golden earrings, his eyes shining like a row of lotuses, bearing sharp weapons and a bow.",
      tel: "బంగారు కుండలాలతో అలంకరించబడిన ఆరు ముఖాలు కలవాడు, పద్మాల వరుసలా ప్రకాశించే కళ్ళు కలవాడు, వాడియైన ఆయుధాలను, ధనుస్సును ధరించినవాడు అయిన శరవణోద్భవుడు, ఈశ్వరుని కుమారుడైన ఆయనను భజిస్తున్నాను.",
      hi: "स्वर्ण-कुंडलों से अलंकृत छह मुखों वाले, कमल-पंक्ति समान चमकते नेत्रों वाले, तीक्ष्ण अस्त्र व धनुष धारण करने वाले, ईश-पुत्र शरवणोद्भव का मैं भजन करता हूँ।" },
    { s: 3, n: null,
      deva: "लमित्यादि पञ्चपूजा कुर्यात् ॥",
      iast: "lamityādi pañcapūjā kuryāt ||",
      en: "One should then perform the five-fold worship beginning with the syllable \"lam\" — the same pañcapūjā given in full in this collection's Subrahmaṇya Kavaca Stotra (item 7) is abbreviated here to its opening word.",
      tel: "అనంతరం \"లం\" అనే అక్షరంతో మొదలయ్యే పంచపూజను చేయాలి — ఈ సంకలనంలోని ఏడవ గ్రంథం (సుబ్రహ్మణ్య కవచ స్తోత్రం)లో పూర్తిగా ఇవ్వబడిన అదే పంచపూజను ఇక్కడ దాని ఆరంభ పదానికి సంక్షిప్తీకరించారు.",
      hi: "तत्पश्चात् \"लं\" अक्षर से आरंभ होने वाली पंचपूजा करनी चाहिए — इस संकलन की सातवीं रचना (सुब्रह्मण्य कवच स्तोत्र) में पूर्ण रूप से दी गई वही पंचपूजा यहाँ अपने आरंभिक शब्द तक संक्षिप्त कर दी गई है।" },
    { s: 4, n: "1",
      deva: "अगस्त्य उवाच ।\nस्कन्दस्य कवचं दिव्यं नाना रक्षाकरं परम् ।\nपुरा पिनाकिना प्रोक्तं ब्रह्मणोऽनन्तशक्तये ॥",
      iast: "agastya uvāca |\nskandasya kavacaṁ divyaṁ nānā rakṣākaraṁ param |\npurā pinākinā proktaṁ brahmaṇo'nantaśaktaye ||",
      en: "Agastya said: \"This divine kavaca of Skanda, supreme and manifold in the protection it confers, was once spoken by Pinākin (Śiva, bearer of the Pināka bow) to Brahmā, of boundless power.\"",
      tel: "అగస్త్యుడు చెప్పాడు: \"స్కందుని ఈ దివ్యమైన కవచం, అనేకరకాల రక్షణలను ఇచ్చే శ్రేష్ఠమైనది, పూర్వం పినాకి (శివుడు) అనంతశక్తి కల బ్రహ్మకు చెప్పాడు.\"",
      hi: "अगस्त्य ने कहा: \"स्कंद का यह दिव्य कवच, अनेक प्रकार की रक्षा देने वाला परम श्रेष्ठ है, पूर्वकाल में पिनाकी (शिव) ने अनंत-शक्ति वाले ब्रह्मा को कहा था।\"" },
    { s: 4, n: "2",
      deva: "तदहं सम्प्रवक्ष्यामि भद्रं ते शृणु नारद ।\nअस्ति गुह्यं महापुण्यं सर्वप्राणि प्रियङ्करम् ॥",
      iast: "tadahaṁ sampravakṣyāmi bhadraṁ te śṛṇu nārada |\nasti guhyaṁ mahāpuṇyaṁ sarvaprāṇi priyaṅkaram ||",
      en: "\"That very kavaca I shall now declare — may good befall you, listen, O Nārada; it is a secret thing, greatly meritorious, dear to every living being.\"",
      tel: "\"ఆ కవచాన్నే నేను ఇప్పుడు చెప్పబోతున్నాను — నీకు శుభమగుగాక, వినుము నారదా; ఇది రహస్యమైనది, మహాపుణ్యకరమైనది, సకల ప్రాణులకూ ప్రియమైనది.\"",
      hi: "\"उसी कवच को अब मैं कहता हूँ — तुम्हारा भला हो, सुनो नारद; यह गुह्य है, महापुण्यकारी है, समस्त प्राणियों को प्रिय है।\"" },
    { s: 4, n: "3",
      deva: "जपमात्रेण पापघ्नं सर्वकामफलप्रदम् ।\nमन्त्रप्राणमिदं ज्ञेयं सर्वविद्यादिकारकम् ॥",
      iast: "japamātreṇa pāpaghnaṁ sarvakāmaphalapradam |\nmantraprāṇamidaṁ jñeyaṁ sarvavidyādikārakam ||",
      en: "\"By mere recitation it destroys sin and grants the fruit of every desire; know it to be the very life-breath of mantras, the cause of all learning.\"",
      tel: "\"కేవలం జపించడం వలననే పాపాన్ని నశింపజేస్తుంది, సకల కోరికల ఫలాన్ని ఇస్తుంది; దీనిని మంత్రాలకు ప్రాణం వంటిదిగా, సకల విద్యలకు కారణమైనదిగా తెలుసుకొనుము.\"",
      hi: "\"केवल जप मात्र से पाप का नाश करता है, सभी कामनाओं का फल देता है; इसे मंत्रों का प्राण जानो, समस्त विद्याओं का कारक।\"" },
    { s: 4, n: "4",
      deva: "स्कन्दस्य कवचं दिव्यं पठनाद्व्याधिनाशनम् ।\nपिशाचघोरभूतानां स्मरणादेव शान्तिदम् ॥",
      iast: "skandasya kavacaṁ divyaṁ paṭhanādvyādhināśanam |\npiśācaghorabhūtānāṁ smaraṇādeva śāntidam ||",
      en: "\"This divine kavaca of Skanda destroys disease by mere recitation; by mere remembrance it brings peace from piśācas and terrible bhūtas.\"",
      tel: "\"స్కందుని ఈ దివ్య కవచం పఠనమాత్రం చేతనే వ్యాధులను నశింపజేస్తుంది; స్మరణ మాత్రం చేతనే పిశాచాలనుండి, భయంకర భూతాలనుండి శాంతిని ప్రసాదిస్తుంది.\"",
      hi: "\"स्कंद का यह दिव्य कवच पाठ मात्र से व्याधि का नाश करता है; स्मरण मात्र से ही पिशाच व घोर भूतों से शांति देता है।\"" },
    { s: 4, n: "5",
      deva: "पठितं स्कन्दकवचं श्रद्धयानन्यचेतसा ।\nतेषां दारिद्र्यदुरितं न कदाचिद्भविष्यति ॥",
      iast: "paṭhitaṁ skandakavacaṁ śraddhayānanyacetasā |\nteṣāṁ dāridryaduritaṁ na kadācidbhaviṣyati ||",
      en: "\"For those who recite the Skanda-kavaca with faith and an undistracted mind, the affliction of poverty will never arise.\"",
      tel: "\"శ్రద్ధతో, ఏకాగ్రచిత్తంతో స్కంద కవచాన్ని పఠించేవారికి దారిద్ర్యదోషం ఎన్నడూ కలుగదు.\"",
      hi: "\"श्रद्धा से, अनन्य चित्त से स्कंद-कवच का पाठ करने वालों को दरिद्रता का दोष कभी नहीं होगा।\"" },
    { s: 4, n: "6",
      deva: "भूयः साम्राज्यसंसिद्धिरन्ते कैवल्यमक्षयम् ।\nदीर्घायुष्यं भवेत्तस्य स्कन्दे भक्तिश्च जायते ॥",
      iast: "bhūyaḥ sāmrājyasaṁsiddhirante kaivalyamakṣayam |\ndīrghāyuṣyaṁ bhavettasya skande bhaktiśca jāyate ||",
      en: "\"Moreover, he attains the accomplishment of sovereignty, and at the end, imperishable liberation; long life comes to him, and devotion to Skanda is born in him.\"",
      tel: "\"ఇంకా, అతనికి సామ్రాజ్య సిద్ధి కలుగుతుంది, అంతమున అక్షయమైన కైవల్యం లభిస్తుంది; అతనికి దీర్ఘాయుష్షు కలుగుతుంది, స్కందునిపై భక్తి జనిస్తుంది.\"",
      hi: "\"इसके अतिरिक्त, उसे साम्राज्य की सिद्धि प्राप्त होती है, अंत में अक्षय कैवल्य मिलता है; उसे दीर्घायु प्राप्त होती है, तथा स्कंद के प्रति भक्ति उत्पन्न होती है।\"" },
    { s: 4, n: "7",
      deva: "अथ कवचम् ।\nशिखां रक्षेत्कुमारस्तु कार्तिकेयः शिरोऽवतु ।\nललाटं पार्वतीसूनुः विशाखो भ्रूयुगं मम ॥",
      iast: "atha kavacam |\nśikhāṁ rakṣetkumārastu kārtikeyaḥ śiro'vatu |\nlalāṭaṁ pārvatīsūnuḥ viśākho bhrūyugaṁ mama ||",
      en: "Now begins the kavaca proper. May Kumāra protect the tuft (śikhā), may Kārtikeya guard the head; may Pārvatī's son protect the forehead, may Viśākha protect my pair of eyebrows.",
      tel: "ఇక కవచం ప్రారంభం. కుమారుడు శిఖను రక్షించుగాక, కార్తికేయుడు శిరస్సును కాపాడుగాక; పార్వతీసూనుడు నుదుటిని రక్షించుగాక, విశాఖుడు నా కనుబొమల జంటను రక్షించుగాక.",
      hi: "अब कवच आरंभ होता है। कुमार शिखा की रक्षा करें, कार्तिकेय सिर की रक्षा करें; पार्वती-पुत्र ललाट की रक्षा करें, विशाख मेरी दोनों भौंहों की रक्षा करें।" },
    { s: 4, n: "8",
      deva: "लोचने क्रौञ्चभेदी च नासिकां शिखिवाहनः ।\nकर्णद्वयं शक्तिधरः कर्णमूलं षडाननः ॥",
      iast: "locane krauñcabhedī ca nāsikāṁ śikhivāhanaḥ |\nkarṇadvayaṁ śaktidharaḥ karṇamūlaṁ ṣaḍānanaḥ ||",
      en: "May the pierced of Mount Krauñca protect my eyes, may the peacock-mounted one protect my nose; may the bearer of the śakti protect my two ears, may the six-faced one protect the base of my ears.",
      tel: "క్రౌంచభేది నా కళ్ళను రక్షించుగాక, శిఖివాహనుడు నాసికను రక్షించుగాక; శక్తిధరుడు రెండు చెవులను రక్షించుగాక, షడాననుడు చెవుల మూలభాగాన్ని రక్షించుగాక.",
      hi: "क्रौंचभेदी मेरे नेत्रों की रक्षा करें, शिखिवाहन नासिका की रक्षा करें; शक्तिधर दोनों कानों की रक्षा करें, षडानन कानों के मूल भाग की रक्षा करें।" },
    { s: 4, n: "9",
      deva: "गण्डयुग्मं महासेनः कपोलौ तारकान्तकः ।\nओष्ठद्वयं च सेनानीः रसनां शिखिवाहनः ॥",
      iast: "gaṇḍayugmaṁ mahāsenaḥ kapolau tārakāntakaḥ |\noṣṭhadvayaṁ ca senānīḥ rasanāṁ śikhivāhanaḥ ||",
      en: "May Mahāsena protect my pair of jaws, may the ender of Tāraka protect my cheeks; may Senānī protect my two lips, may the peacock-mounted one protect my tongue.",
      tel: "మహాసేనుడు రెండు దవడలను రక్షించుగాక, తారకాంతకుడు చెక్కిళ్ళను రక్షించుగాక; సేనానీ రెండు పెదవులను రక్షించుగాక, శిఖివాహనుడు నాలుకను రక్షించుగాక.",
      hi: "महासेन मेरी दोनों जबड़ों की रक्षा करें, तारकांतक गालों की रक्षा करें; सेनानी दोनों ओठों की रक्षा करें, शिखिवाहन जिह्वा की रक्षा करें।" },
    { s: 4, n: "10",
      deva: "तालू कलानिधिः पातु दन्तान् देवशिखामणिः ।\nगाङ्गेयश्चुबुकं पातु मुखं पातु शरोद्भवः ॥",
      iast: "tālū kalānidhiḥ pātu dantān devaśikhāmaṇiḥ |\ngāṅgeyaścubukaṁ pātu mukhaṁ pātu śarodbhavaḥ ||",
      en: "May Kalānidhi (treasury of arts) protect the palate, may Devaśikhāmaṇi (crest-jewel of the gods) protect the teeth; may Gāṅgeya protect the chin, may Śarodbhava protect the mouth.",
      tel: "కళానిధి తాలువును రక్షించుగాక, దేవశిఖామణి దంతాలను రక్షించుగాక; గాంగేయుడు గడ్డాన్ని రక్షించుగాక, శరోద్భవుడు నోటిని రక్షించుగాక.",
      hi: "कलानिधि तालु की रक्षा करें, देवशिखामणि दाँतों की रक्षा करें; गांगेय ठुड्डी की रक्षा करें, शरोद्भव मुख की रक्षा करें।" },
    { s: 4, n: "11",
      deva: "हनू हरसुतः पातु कण्ठं कारुण्यवारिधिः ।\nस्कन्धावुमासुतः पातु बाहुलेयो भुजद्वयम् ॥",
      iast: "hanū harasutaḥ pātu kaṇṭhaṁ kāruṇyavāridhiḥ |\nskandhāvumāsutaḥ pātu bāhuleyo bhujadvayam ||",
      en: "May Hara's son protect my jaws, may the ocean of compassion protect my throat; may Umā's son protect my shoulders, may Bāhuleya protect my pair of arms.",
      tel: "హరసుతుడు దవడలను రక్షించుగాక, కారుణ్యవారిధి కంఠాన్ని రక్షించుగాక; ఉమాసుతుడు భుజాలను రక్షించుగాక, బాహులేయుడు రెండు బాహువులను రక్షించుగాక.",
      hi: "हरसुत जबड़ों की रक्षा करें, करुणा-सागर कंठ की रक्षा करें; उमासुत कंधों की रक्षा करें, बाहुलेय दोनों भुजाओं की रक्षा करें।" },
    { s: 4, n: "12",
      deva: "बाहू भवेद्भवः पातु स्तनौ पातु महोरगः ।\nमध्यं जगद्विभुः पातु नाभिं द्वादशलोचनः ॥",
      iast: "bāhū bhavedbhavaḥ pātu stanau pātu mahoragaḥ |\nmadhyaṁ jagadvibhuḥ pātu nābhiṁ dvādaśalocanaḥ ||",
      en: "May Bhava protect my forearms, may Mahoraga (the great serpent-associated one) protect my chest; may Jagadvibhu (lord of the world) protect my midriff, may the twelve-eyed one protect my navel.",
      tel: "భవుడు ముంజేతులను రక్షించుగాక, మహోరగుడు వక్షస్థలాన్ని రక్షించుగాక; జగద్విభుడు నడుము మధ్యభాగాన్ని రక్షించుగాక, ద్వాదశలోచనుడు నాభిని రక్షించుగాక.",
      hi: "भव मेरी बाहों की रक्षा करें, महोरग वक्षस्थल की रक्षा करें; जगद्विभु कटि-मध्य की रक्षा करें, द्वादशलोचन नाभि की रक्षा करें।" },
    { s: 4, n: "13",
      deva: "कटिं द्विषड्भुजः पातु गुह्यं गङ्गासुतोऽवतु ।\nजघनं जाह्नवीसूनुः पृष्ठभागं परन्तपः ॥",
      iast: "kaṭiṁ dviṣaḍbhujaḥ pātu guhyaṁ gaṅgāsuto'vatu |\njaghanaṁ jāhnavīsūnuḥ pṛṣṭhabhāgaṁ parantapaḥ ||",
      en: "May the twelve-armed one protect my waist, may Gaṅgā's son protect my private parts; may Jāhnavī's son protect my hips, may Parantapa (scorcher of foes) protect my back.",
      tel: "ద్విషడ్భుజుడు (పన్నెండు భుజాలు కలవాడు) నడుమును రక్షించుగాక, గంగాసుతుడు గుహ్యభాగాన్ని రక్షించుగాక; జాహ్నవీసూనుడు జఘనభాగాన్ని రక్షించుగాక, పరంతపుడు వీపును రక్షించుగాక.",
      hi: "द्विषड्भुज (बारह भुजाओं वाले) मेरी कमर की रक्षा करें, गंगासुत गुह्यभाग की रक्षा करें; जाह्नवीसुत जघन की रक्षा करें, परंतप पीठ की रक्षा करें।" },
    { s: 4, n: "14",
      deva: "ऊरू रक्षेदुमापुत्रः जानुयुग्मं जगद्धरः ।\nजङ्घे पातु जगत्पूज्यः गुल्फौ पातु महाबलः ॥",
      iast: "ūrū rakṣedumāputraḥ jānuyugmaṁ jagaddharaḥ |\njaṅghe pātu jagatpūjyaḥ gulphau pātu mahābalaḥ ||",
      en: "May Umā's son protect my thighs, may Jagaddhara (bearer of the world) protect my pair of knees; may Jagatpūjya (worshipped by the world) protect my shins, may Mahābala protect my ankles.",
      tel: "ఉమాపుత్రుడు తొడలను రక్షించుగాక, జగద్ధరుడు మోకాళ్ళ జంటను రక్షించుగాక; జగత్పూజ్యుడు పిక్కలను రక్షించుగాక, మహాబలుడు చీలమండలను రక్షించుగాక.",
      hi: "उमापुत्र मेरी जंघाओं की रक्षा करें, जगद्धर दोनों घुटनों की रक्षा करें; जगत्पूज्य पिंडलियों की रक्षा करें, महाबल टखनों की रक्षा करें।" },
    { s: 4, n: "15",
      deva: "पादौ पातु परञ्ज्योतिः सर्वाङ्गं कुक्कुटध्वजः ।\nऊर्ध्वं पातु महोदारः अधस्तात्पातु शाङ्करिः ॥",
      iast: "pādau pātu parañjyotiḥ sarvāṅgaṁ kukkuṭadhvajaḥ |\nūrdhvaṁ pātu mahodāraḥ adhastātpātu śāṅkariḥ ||",
      en: "May Parañjyoti (supreme light) protect my feet, may the cock-bannered one protect my whole body; may Mahodāra protect me from above, may Śāṅkari protect me from below.",
      tel: "పరంజ్యోతి పాదాలను రక్షించుగాక, కుక్కుటధ్వజుడు సర్వాంగాన్ని రక్షించుగాక; మహోదారుడు పైనుండి రక్షించుగాక, శాంకరి క్రిందనుండి రక్షించుగాక.",
      hi: "परंज्योति मेरे पैरों की रक्षा करें, कुक्कुटध्वज संपूर्ण शरीर की रक्षा करें; महोदार ऊपर से रक्षा करें, शांकरि नीचे से रक्षा करें।" },
    { s: 4, n: "16",
      deva: "पार्श्वयोः पातु शत्रुघ्नः सर्वदा पातु शाश्वतः ।\nप्रातः पातु परं ब्रह्म मध्याह्ने युद्धकौशलः ॥",
      iast: "pārśvayoḥ pātu śatrughnaḥ sarvadā pātu śāśvataḥ |\nprātaḥ pātu paraṁ brahma madhyāhne yuddhakauśalaḥ ||",
      en: "May Śatrughna (slayer of enemies) protect my two sides, may the Eternal One protect me always; may the supreme Brahman protect me at dawn, may the one skilled in war protect me at noon.",
      tel: "శత్రుఘ్నుడు రెండు పార్శ్వాలను రక్షించుగాక, శాశ్వతుడు ఎల్లప్పుడూ రక్షించుగాక; పరబ్రహ్మ ఉదయకాలంలో రక్షించుగాక, యుద్ధకౌశలుడు మధ్యాహ్నకాలంలో రక్షించుగాక.",
      hi: "शत्रुघ्न मेरी दोनों करवटों की रक्षा करें, शाश्वत सदा रक्षा करें; परब्रह्म प्रातःकाल रक्षा करें, युद्धकौशल मध्याह्न में रक्षा करें।" },
    { s: 4, n: "17",
      deva: "अपराह्णे गुहः पातु रात्रौ दैत्यान्तकोऽवतु ।\nत्रिसन्ध्यं तु त्रिकालज्ञः अन्तस्थं पात्वरिन्दमः ॥",
      iast: "aparāhṇe guhaḥ pātu rātrau daityāntako'vatu |\ntrisandhyaṁ tu trikālajñaḥ antasthaṁ pātvarindamaḥ ||",
      en: "May Guha protect me in the afternoon, may the ender of daityas protect me at night; may the knower of the three times protect me at the three twilights, may Arindama (subduer of foes) protect me when I am within (indoors, or in my inner being).",
      tel: "గుహుడు అపరాహ్ణ కాలంలో రక్షించుగాక, దైత్యాంతకుడు రాత్రిపూట రక్షించుగాక; త్రికాలజ్ఞుడు మూడు సంధ్యాకాలాలలో రక్షించుగాక, అరిందముడు నేను లోపల ఉన్నప్పుడు (ఇంటిలో లేదా అంతరంగంలో) రక్షించుగాక.",
      hi: "गुह अपराह्न-काल में रक्षा करें, दैत्यांतक रात्रि में रक्षा करें; त्रिकालज्ञ तीनों संध्याओं में रक्षा करें, अरिंदम मेरे भीतर (घर में अथवा अंतःकरण में) रहने पर रक्षा करें।" },
    { s: 4, n: "18",
      deva: "बहिःस्थितं पातु खड्गी निषण्णं कृत्तिकासुतः ।\nव्रजन्तं प्रथमाधीशः तिष्ठन्तं पातु पाशभृत् ॥",
      iast: "bahiḥsthitaṁ pātu khaḍgī niṣaṇṇaṁ kṛttikāsutaḥ |\nvrajantaṁ prathamādhīśaḥ tiṣṭhantaṁ pātu pāśabhṛt ||",
      en: "May the sword-bearer protect me when I am outside, may Kṛttikāsuta protect me when I am seated; may the first lord protect me when I am walking, may the noose-bearer protect me when I am standing.",
      tel: "ఖడ్గి నేను బయట ఉన్నప్పుడు రక్షించుగాక, కృత్తికాసుతుడు కూర్చున్నప్పుడు రక్షించుగాక; ప్రథమాధీశుడు నడుస్తున్నప్పుడు రక్షించుగాక, పాశభృత్తు నిలబడి ఉన్నప్పుడు రక్షించుగాక.",
      hi: "खड्गी बाहर रहने पर रक्षा करें, कृत्तिकासुत बैठे रहने पर रक्षा करें; प्रथमाधीश चलते समय रक्षा करें, पाशभृत् खड़े रहने पर रक्षा करें।" },
    { s: 4, n: "19",
      deva: "शयने पातु मां शूरः मार्गे मां पातु शूरजित् ।\nउग्रारण्ये वज्रधरः सदा रक्षतु मां वटुः ॥",
      iast: "śayane pātu māṁ śūraḥ mārge māṁ pātu śūrajit |\nugrāraṇye vajradharaḥ sadā rakṣatu māṁ vaṭuḥ ||",
      en: "May Śūra protect me lying down, may Śūrajit protect me on the road; may the wielder of the vajra protect me in a fearsome forest — may the eternal youth (vaṭu, boy-ascetic) always protect me. This closes the body-and-circumstance litany begun at v.7.",
      tel: "శూరుడు నేను శయనించి ఉన్నప్పుడు రక్షించుగాక, శూరజిత్తు మార్గంలో ఉన్నప్పుడు రక్షించుగాక; వజ్రధరుడు భయంకర అరణ్యంలో రక్షించుగాక — వటుడు (శాశ్వత బాలయోగి) నన్ను ఎల్లప్పుడూ రక్షించుగాక. 7వ శ్లోకంతో మొదలైన అవయవ-సందర్భ పట్టిక ఇక్కడ ముగుస్తుంది.",
      hi: "शूर मेरे शयन के समय रक्षा करें, शूरजित् मार्ग में रक्षा करें; वज्रधर भयंकर वन में रक्षा करें — वटु (शाश्वत बाल-योगी) सदा मेरी रक्षा करें। श्लोक 7 से आरंभ हुई अंग-प्रसंग सूची यहाँ पूर्ण होती है।" },
    { s: 5, n: "20",
      deva: "फलश्रुतिः ।\nसुब्रह्मण्यस्य कवचं धर्मकामार्थमोक्षदम् ।\nमन्त्राणां परमं मन्त्रं रहस्यं सर्वदेहिनाम् ॥",
      iast: "phalaśrutiḥ |\nsubrahmaṇyasya kavacaṁ dharmakāmārthamokṣadam |\nmantrāṇāṁ paramaṁ mantraṁ rahasyaṁ sarvadehinām ||",
      en: "The phalaśruti (fruits of recitation) begins: This kavaca of Subrahmaṇya grants dharma, kāma, artha and mokṣa (all four aims of life); it is the supreme mantra among mantras, the secret possession of all embodied beings.",
      tel: "ఫలశ్రుతి ఆరంభం: సుబ్రహ్మణ్యుని ఈ కవచం ధర్మ కామ అర్థ మోక్షాలను (చతుర్విధ పురుషార్థాలను) ప్రసాదిస్తుంది; మంత్రాలలో పరమమైన మంత్రం ఇది, సకల దేహధారులకు రహస్యమైనది.",
      hi: "फलश्रुति आरंभ होती है: सुब्रह्मण्य का यह कवच धर्म, काम, अर्थ और मोक्ष (चारों पुरुषार्थ) प्रदान करता है; यह मंत्रों में परम मंत्र है, समस्त देहधारियों का गुह्य रहस्य है।" },
    { s: 5, n: "21",
      deva: "सर्वरोगप्रशमनं सर्वव्याधिविनाशनम् ।\nसर्वपुण्यप्रदं दिव्यं सुभगैश्वर्यवर्धनम् ॥",
      iast: "sarvarogapraśamanaṁ sarvavyādhivināśanam |\nsarvapuṇyapradaṁ divyaṁ subhagaiśvaryavardhanam ||",
      en: "It pacifies every illness and destroys every disease; divine, it grants every merit and increases auspicious prosperity.",
      tel: "ఇది సకల రోగాలను శమింపజేస్తుంది, సకల వ్యాధులను నశింపజేస్తుంది; దివ్యమైనది, సకల పుణ్యాన్ని ప్రసాదిస్తుంది, శుభకరమైన ఐశ్వర్యాన్ని వృద్ధి చేస్తుంది.",
      hi: "यह समस्त रोगों को शांत करता है, समस्त व्याधियों का नाश करता है; दिव्य है, समस्त पुण्य प्रदान करता है, शुभ ऐश्वर्य की वृद्धि करता है।" },
    { s: 5, n: "22",
      deva: "सर्वत्र शुभदं नित्यं यः पठेद्वज्रपञ्जरम् ।\nसुब्रह्मण्यः सुसम्प्रीतो वाञ्छितार्थान् प्रयच्छति ।\nदेहान्ते मुक्तिमाप्नोति स्कन्दवर्मानुभावतः ॥",
      iast: "sarvatra śubhadaṁ nityaṁ yaḥ paṭhedvajrapañjaram |\nsubrahmaṇyaḥ susamprīto vāñchitārthān prayacchati |\ndehānte muktimāpnoti skandavarmānubhāvataḥ ||",
      en: "Ever bestowing good fortune everywhere — whoever recites this Vajrapañjara, to him Subrahmaṇya, greatly pleased, grants his desired ends; at the end of the body he attains liberation, by the power of Skanda's armor. This is the closing verse.",
      tel: "ఎల్లప్పుడూ, అన్నిచోట్లా శుభాన్ని ప్రసాదించే ఈ వజ్రపంజరాన్ని ఎవరు పఠిస్తారో, వారికి సుబ్రహ్మణ్యుడు మిక్కిలి ప్రసన్నుడై కోరిన అర్థాలను ప్రసాదిస్తాడు; దేహాంతమున స్కంద కవచం యొక్క ప్రభావం చేత మోక్షాన్ని పొందుతాడు. ఇది ముగింపు శ్లోకం.",
      hi: "सदा, सर्वत्र शुभ प्रदान करने वाले इस वज्रपंजर का जो पाठ करता है, उससे सुब्रह्मण्य अत्यंत प्रसन्न होकर वांछित अर्थ प्रदान करते हैं; देहांत में स्कंद-कवच के प्रभाव से वह मुक्ति प्राप्त करता है। यह समापन श्लोक है।" },
  ],
},

{
  deities: ["subrahmanya"],
  title: "Kārtikeya Karāvalamba Stotram",
  blurb: "Five vasantatilakā verses, each ending in the same plea — reach down your hand. A shorter, sharper cousin of the Karāvalamba everyone knows.",
  colophon: { deva: "इति श्रीकार्तिकेयकरावलम्बस्तोत्रं सम्पूर्णम् ।", iast: "iti śrīkārtikeyakarāvalambastotraṁ sampūrṇam |" },
  verses: [
    { s: 0, n: "1",
      deva: "ओङ्काररूप शरणाश्रय शर्वसूनो\nश‍ृङ्गारवेष सकलेश्वर दीनबन्धो ।\nसन्तापनाशन सनातन शक्तिहस्त\nश्रीकार्तिकेय मम देहि करावलम्बम् ॥",
      iast: "oṅkārarūpa śaraṇāśraya śarvasūno\nśṛṅgāraveṣa sakaleśvara dīnabandho |\nsantāpanāśana sanātana śaktihasta\nśrīkārtikeya mama dehi karāvalambam ||",
      en: "O you whose very form is the syllable Oṁ, refuge of those who take shelter in you, son of Śarva (Śiva); of splendid, beautifully-adorned bearing, lord of all, friend of the humble; destroyer of anguish, eternal one, holding the śakti-spear in hand — O Śrī Kārtikeya, grant me the support of your hand.",
      tel: "ఓంకార స్వరూపుడవు, శరణాగతులకు ఆశ్రయమైనవాడవు, శర్వుని కుమారుడవు; సుందర శృంగార వేషధారివి, సకలేశ్వరుడవు, దీనబంధువు; సంతాపనాశకుడవు, సనాతనుడవు, శక్తిని చేతిలో ధరించినవాడవు — ఓ శ్రీ కార్తికేయా, నాకు నీ కరావలంబాన్ని (చేయూతను) ప్రసాదించు.",
      hi: "हे ओंकार-स्वरूप, शरणागतों के आश्रय, शर्व (शिव) के पुत्र; सुंदर शृंगार-वेष धारण करने वाले, सकल के ईश्वर, दीनबंधु; संताप के नाशक, सनातन, हाथ में शक्ति धारण करने वाले — हे श्री कार्तिकेय, मुझे अपना करावलंब (हाथ का सहारा) प्रदान करो।" },
    { s: 0, n: "2",
      deva: "पञ्चाद्रिवास सहजा सुरसैन्यनाथ\nपञ्चामृतप्रिय गुहासकलाधिवास ।\nगङ्गेन्दु मौलि तनय मयिल्वाहनस्थ\nश्रीकार्तिकेय मम देहि करावलम्बम् ॥",
      iast: "pañcādrivāsa sahajā surasainyanātha\npañcāmṛtapriya guhāsakalādhivāsa |\ngaṅgendu mauli tanaya mayilvāhanastha\nśrīkārtikeya mama dehi karāvalambam ||",
      en: "Dweller of the five mountains, twin-born, lord of the army of the gods; fond of the fivefold nectar-offering (pañcāmṛta), O Guha who pervades everything; son of the one crowned with the Gaṅgā and the moon (Śiva), mounted on a peacock — O Śrī Kārtikeya, grant me the support of your hand.",
      tel: "పంచగిరులలో నివసించువాడా, సహజంగా (కవలగా) జన్మించినవాడా, దేవసేనలకు నాథుడా; పంచామృతప్రియుడా, ఓ గుహా — సర్వత్రా వ్యాపించినవాడా; గంగను చంద్రుని శిరస్సున ధరించిన శివుని కుమారుడా, నెమలిని వాహనంగా కలవాడా — ఓ శ్రీ కార్తికేయా, నాకు నీ కరావలంబాన్ని ప్రసాదించు.",
      hi: "हे पंच पर्वतों के वासी, सहज (साथ) जन्मे, देवसेना के स्वामी; पंचामृत-प्रिय, हे गुह — सर्वत्र व्याप्त रहने वाले; गंगा व चंद्र को शिर पर धारण करने वाले शिव के पुत्र, मयूर-वाहन वाले — हे श्री कार्तिकेय, मुझे अपना करावलंब प्रदान करो।" },
    { s: 0, n: "3",
      deva: "आपद्विनाशक कुमारक चारुमूर्ते\nतापत्रयान्तक दयापर तारकारे ।\nआर्ताऽभयप्रद गुणत्रय भव्यराशे\nश्रीकार्तिकेय मम देहि करावलम्बम् ॥",
      iast: "āpadvināśaka kumāraka cārumūrte\ntāpatrayāntaka dayāpara tārakāre |\nārtā'bhayaprada guṇatraya bhavyarāśe\nśrīkārtikeya mama dehi karāvalambam ||",
      en: "Destroyer of calamities, dear young prince, beautiful of form; ender of the threefold affliction, full of compassion, foe of Tāraka; granter of fearlessness to the afflicted, O mass of auspiciousness holding the three guṇas — O Śrī Kārtikeya, grant me the support of your hand.",
      tel: "ఆపదలను నశింపజేయువాడా, ముద్దుల కుమారా, సుందర స్వరూపుడా; త్రితాపాలను అంతం చేయువాడా, దయాపరుడా, తారకాసుర శత్రువా; ఆర్తులకు అభయమిచ్చువాడా, త్రిగుణాత్మకమైన శుభరాశీ — ఓ శ్రీ కార్తికేయా, నాకు నీ కరావలంబాన్ని ప్రసాదించు.",
      hi: "हे आपत्तियों के नाशक, प्रिय कुमार, सुंदर स्वरूप वाले; त्रिविध ताप के अंतक, दयालु, तारकासुर के शत्रु; पीड़ितों को अभय देने वाले, त्रिगुणात्मक शुभ-राशि — हे श्री कार्तिकेय, मुझे अपना करावलंब प्रदान करो।" },
    { s: 0, n: "4",
      deva: "वल्लीपते सुकृतदायक पुण्यमूर्ते\nस्वर्लोकनाथपरिसेवित शम्भुसूनो ।\nत्रैलोक्यनायक षडानन भूतपाद\nश्रीकार्तिकेय मम देहि करावलम्बम् ॥",
      iast: "vallīpate sukṛtadāyaka puṇyamūrte\nsvarlokanāthaparisevita śambhusūno |\ntrailokyanāyaka ṣaḍānana bhūtapāda\nśrīkārtikeya mama dehi karāvalambam ||",
      en: "O husband of Vallī, giver of the fruit of good deeds, embodiment of holiness; attended upon by the lords of the heavenly world, O son of Śambhu (Śiva); leader of the three worlds, six-faced one, at whose feet all beings bow — O Śrī Kārtikeya, grant me the support of your hand.",
      tel: "వల్లీదేవి పతీ, సత్కర్మఫలదాతా, పుణ్యస్వరూపుడా; స్వర్గలోకనాథులచే సేవింపబడువాడా, శంభుని కుమారా; ముల్లోకాలకు నాయకుడా, షడాననా, సర్వభూతములు పాదాలచెంత మ్రొక్కు దైవమా — ఓ శ్రీ కార్తికేయా, నాకు నీ కరావలంబాన్ని ప్రసాదించు.",
      hi: "हे वल्ली के पति, सत्कर्म-फलदाता, पुण्य-स्वरूप; स्वर्गलोक के स्वामियों द्वारा सेवित, शंभु-पुत्र; त्रिलोक के नायक, षडानन, जिनके चरणों में समस्त भूत नमन करते हैं — हे श्री कार्तिकेय, मुझे अपना करावलंब प्रदान करो।" },
    { s: 0, n: "5",
      deva: "ज्ञानस्वरूप सकलात्मक वेदवेद्य\nज्ञानप्रियाऽखिलदुरन्त महावनाग्ने ।\nदीनावनप्रिय निरामय दानसिन्धो\nश्रीकार्तिकेय मम देहि करावलम्बम् ॥",
      iast: "jñānasvarūpa sakalātmaka vedavedya\njñānapriyā'khiladuranta mahāvanāgne |\ndīnāvanapriya nirāmaya dānasindho\nśrīkārtikeya mama dehi karāvalambam ||",
      en: "Whose very form is knowledge, the self of all, knowable through the Vedas; dear to true wisdom, the fire that consumes the boundless great forest [of ignorance]; fond of protecting the humble, free of affliction, O ocean of generosity — O Śrī Kārtikeya, grant me the support of your hand.",
      tel: "జ్ఞానమే స్వరూపముగా కలవాడా, సర్వాత్మకుడా, వేదములచే తెలియదగినవాడా; జ్ఞానప్రియుడా, అంతులేని మహారణ్యాన్ని దహించు అగ్నివంటివాడా; దీనులను రక్షించుటలో ప్రీతి కలవాడా, రోగరహితుడా, దానసముద్రుడా — ఓ శ్రీ కార్తికేయా, నాకు నీ కరావలంబాన్ని ప్రసాదించు.",
      hi: "हे ज्ञान-स्वरूप, सर्वात्मक, वेदों द्वारा जानने योग्य; ज्ञान-प्रिय, अनंत महावन को दहन करने वाली अग्नि के समान; दीनों की रक्षा में रुचि रखने वाले, नीरोग, दान के सागर — हे श्री कार्तिकेय, मुझे अपना करावलंब प्रदान करो।" },
  ],
},

{
  deities: ["subrahmanya"],
  title: "Kārtikeya Pañcakam",
  blurb: "Five verses of chained epithets — the spotless lotus feet, the birth in the reed-thicket, Guha, Vallī's lord — closed by the fruit of morning recitation.",
  sections: [{ tel: "కార్తికేయ పంచకం", roman: "The Five Verses" }, { tel: "ఫలశ్రుతి", roman: "The Fruit of Recitation" }],
  verses: [
    { s: 0, n: "1",
      deva: "विमलनिजपदाब्जं वेदवेदान्तवेद्यं\nमम कुलगुरुनाथं वाद्यगानप्रमोदम् ।\nरमणसुगुणजालं रङ्गराड्भागिनेयं\nकमलजनुतपादं कार्तिकेयं नमामि ॥",
      iast: "vimalanijapadābjaṁ vedavedāntavedyaṁ\nmama kulagurunāthaṁ vādyagānapramodam |\nramaṇasuguṇajālaṁ raṅgarāḍbhāgineyaṁ\nkamalajanutapādaṁ kārtikeyaṁ namāmi ||",
      en: "I bow to Kārtikeya: his own lotus feet are spotless, he is knowable through the Vedas and the Vedānta, he is the lord and guru of our family lineage, he delights in instrumental music and song, he possesses a mass of lovely virtues, he is the nephew (bhāgineya) of Raṅgarāj — Śrī Raṅganātha, i.e. Viṣṇu — and his feet are praised by the lotus-born one (Brahmā).",
      tel: "నిర్మలమైన సొంత పాదపద్మాలు కలవాడు, వేదవేదాంతాల ద్వారా తెలియదగినవాడు, మా వంశానికి గురువు మరియు నాథుడు, వాద్యగానం పట్ల ఆనందం కలవాడు, అందమైన సద్గుణాల సమూహం కలవాడు, రంగరాజు (శ్రీరంగనాథుడు, విష్ణువు) మేనల్లుడు, పద్మసంభవుడైన బ్రహ్మ చేత స్తుతింపబడే పాదాలు కలవాడు అయిన కార్తికేయునికి నమస్కరిస్తున్నాను.",
      hi: "जिनके अपने चरण-कमल निर्मल हैं, जो वेद-वेदांत द्वारा जानने योग्य हैं, जो हमारे कुल के गुरु और नाथ हैं, जिन्हें वाद्य-गान में आनंद आता है, जिनमें सुंदर सद्गुणों का समूह है, जो रंगराज (श्री रंगनाथ, विष्णु) के भांजे हैं, जिनके चरणों की स्तुति कमल से उत्पन्न ब्रह्मा करते हैं, उन कार्तिकेय को मैं नमस्कार करता हूँ।" },
    { s: 0, n: "2",
      deva: "शिवशरवणजातं शैवयोगप्रभावं\nभवहितगुरुनाथं भक्तबृन्दप्रमोदम् ।\nनवरसमृदुपादं नाथ ह्रीङ्काररूपं\nकवनमधुरसारं कार्तिकेयं भजामि ॥",
      iast: "śivaśaravaṇajātaṁ śaivayogaprabhāvaṁ\nbhavahitagurunāthaṁ bhaktabṛndapramodam |\nnavarasamṛdupādaṁ nātha hrīṅkārarūpaṁ\nkavanamadhurasāraṁ kārtikeyaṁ bhajāmi ||",
      en: "I worship Kārtikeya: born of Śiva in the reed-thicket (śaravaṇa), his power is that of Śaiva yoga, he is the guru-lord who does good to those caught in worldly existence (bhava), he delights the whole multitude of devotees, his feet are tender and hold the nine rasas, O Lord who takes the very form of the seed-syllable hrīṁ, he is the sweet essence of poetry itself.",
      tel: "శివుని నుండి శరవణంలో జన్మించినవాడు, శైవయోగ ప్రభావం కలవాడు, సంసారబద్ధులకు హితం చేసే గురునాథుడు, భక్తసమూహానికి ఆనందం కలిగించేవాడు, నవరసాలతో కూడిన మృదుపాదాలు కలవాడు, హ్రీంకార బీజాక్షర స్వరూపుడైన ప్రభూ, మధురమైన కవిత్వానికే సారమైనవాడు అయిన కార్తికేయుని భజిస్తున్నాను.",
      hi: "जो शिव से शरवण में उत्पन्न हुए, जिनका प्रभाव शैव योग का है, जो संसार में फँसे हुओं के हितकारी गुरु-नाथ हैं, जो भक्तवृंद को आनंद देते हैं, जिनके चरण नवरसों से युक्त कोमल हैं, हे नाथ, जो ह्रींकार बीजाक्षर के स्वरूप हैं, जो मधुर काव्य के सार-स्वरूप हैं, उन कार्तिकेय का मैं भजन करता हूँ।" },
    { s: 0, n: "3",
      deva: "पाकारातिसुतामुखाब्जमधुपं बालेन्दुमौलीश्वरं\nलोकानुग्रहकारणं शिवसुतं लोकेशतत्त्वप्रदम् ।\nराकाचन्द्रसमानचारुवदनं रम्भोरुवल्लीश्वरं\nह्रीङ्कारप्रणवस्वरूपलहरीं श्रीकार्तिकेयं भजे ॥",
      iast: "pākārātisutāmukhābjamadhupaṁ bālendumaulīśvaraṁ\nlokānugrahakāraṇaṁ śivasutaṁ lokeśatattvapradam |\nrākācandrasamānacāruvadanaṁ rambhoruvallīśvaraṁ\nhrīṅkārapraṇavasvarūpalaharīṁ śrīkārtikeyaṁ bhaje ||",
      en: "I worship Śrī Kārtikeya: he is the bee at the lotus-face of Indra's daughter (Devasenā, since pākārāti — \"enemy of Pāka\" — is an epithet of Indra), his crest bears the young moon, he exists for no cause but to bless the worlds, he is Śiva's son who grants the very truth of lordship over the worlds, his lovely face equals the moon of a full-moon night, he is the husband of Vallī whose thighs are like plantain-stems, and he is the very billowing wave that takes the form of the praṇava and the seed-syllable hrīṁ.",
      tel: "ఇంద్రుని కుమార్తె (దేవసేన) ముఖపద్మానికి తుమ్మెద వంటివాడు, శిరస్సున బాలచంద్రుడిని ధరించినవాడు, లోకాలను అనుగ్రహించడమే పరమావధిగా కలవాడు, లోకాధిపత్య తత్త్వాన్ని ప్రసాదించే శివపుత్రుడు, నిండుపున్నమి చంద్రునితో సమానమైన అందమైన ముఖం కలవాడు, అరటిబోదెల వంటి తొడలు కలిగిన వల్లీదేవికి ప్రాణనాథుడు, ప్రణవ-హ్రీంకార స్వరూపమైన తరంగం వంటివాడు అయిన శ్రీ కార్తికేయుని భజిస్తున్నాను.",
      hi: "जो इंद्र-पुत्री (देवसेना) के मुख-कमल पर भ्रमर के समान हैं, जिनके मस्तक पर बाल-चंद्र सुशोभित है, जो केवल लोकों पर अनुग्रह करने के लिए विद्यमान हैं, जो शिव-पुत्र हैं और लोकेश्वर-तत्त्व प्रदान करते हैं, जिनका सुंदर मुख पूर्णिमा के चंद्रमा के समान है, जो कदली-स्तंभ समान जंघाओं वाली वल्ली देवी के स्वामी हैं, जो प्रणव और ह्रींकार के स्वरूप की लहर हैं, उन श्री कार्तिकेय का मैं भजन करता हूँ।" },
    { s: 0, n: "4",
      deva: "महादेवाज्जातं शरवणभवं मन्त्रशरभं\nमहत्तत्त्वानन्दं परमलहरी मन्त्रमधुरम् ।\nमहादेवातीतं सुरगणयुतं मन्त्रवरदं\nगुहं वल्लीनाथं मम हृदि भजे गृध्रगिरिशम् ॥",
      iast: "mahādevājjātaṁ śaravaṇabhavaṁ mantraśarabhaṁ\nmahattattvānandaṁ paramalaharī mantramadhuram |\nmahādevātītaṁ suragaṇayutaṁ mantravaradaṁ\nguhaṁ vallīnāthaṁ mama hṛdi bhaje gṛdhragiriśam ||",
      en: "In my heart I worship Guha, lord of Vallī, the lord enthroned on Gṛdhragiri (Vulture Hill, a hill-shrine of the god): he is born of Mahādeva, born in the śaravaṇa reed-thicket, the śarabha — the all-powerful sovereign beast of legend — among mantras, the bliss of the mahat-tattva (the first principle of manifest creation in Sāṅkhya cosmology), the supreme wave sweet as mantra itself, one who transcends even Mahādeva, attended by hosts of gods, the giver of boons through mantra.",
      tel: "మహాదేవుని నుండి ఉద్భవించినవాడు, శరవణంలో జన్మించినవాడు, మంత్రాలకే శరభం (అమిత శక్తిమంతుడు) వంటివాడు, మహత్తత్త్వానికి ఆనందస్వరూపుడు, మంత్రమాధుర్యంతో కూడిన పరమతరంగం వంటివాడు, మహాదేవుని తత్త్వాన్ని కూడా అతిక్రమించినవాడు, దేవగణాలతో కూడినవాడు, మంత్రాల ద్వారా వరాలిచ్చేవాడు అయిన గుహుడిని, వల్లీనాథుడిని, గృధ్రగిరి (గద్దల కొండ) పై వెలసినవాడిని నా హృదయంలో భజిస్తున్నాను.",
      hi: "जो महादेव से उत्पन्न हुए, शरवण में जन्मे, जो मंत्रों के लिए शरभ के समान (परम शक्तिशाली) हैं, जो महत्तत्त्व के आनंद-स्वरूप हैं, जो मंत्र-माधुर्य से युक्त परम लहर हैं, जो महादेव के तत्त्व से भी परे हैं, जो देवगणों से युक्त हैं, जो मंत्रों द्वारा वर देने वाले हैं, उन गुह को, वल्लीनाथ को, गृध्रगिरि (गिद्ध-पर्वत) पर विराजमान को, मैं अपने हृदय में भजता हूँ।" },
    { s: 0, n: "5",
      deva: "नित्याकारं निखिलवरदं निर्मलं ब्रह्मतत्त्वं\nनित्यं देवैर्विनुतचरणं निर्विकल्पादियोगम् ।\nनित्यानन्दं निगमविदितं निर्गुणं देवदेवं\nनित्यं वन्दे मम गुरुवरं निर्ममं कार्तिकेयम् ॥",
      iast: "nityākāraṁ nikhilavaradaṁ nirmalaṁ brahmatattvaṁ\nnityaṁ devairvinutacaraṇaṁ nirvikalpādiyogam |\nnityānandaṁ nigamaviditaṁ nirguṇaṁ devadevaṁ\nnityaṁ vande mama guruvaraṁ nirmamaṁ kārtikeyam ||",
      en: "Eternally I bow to Kārtikeya, my supreme guru: his form is eternal, he grants every boon, he is pure, he is the very essence of brahman; his feet are eternally praised by the gods, he abides in nirvikalpa (undifferentiated) and other yogic states; he is eternal bliss, known through the Vedic scriptures (nigama), free of attributes (nirguṇa), the god of gods, free of all possessiveness (nirmama). Nearly every word of this verse itself opens with nitya- (\"eternal\") or nir- (\"free of\"), an alliterative device the Sanskrit foregrounds rather than merely a translator's flourish.",
      tel: "శాశ్వతస్వరూపుడు, సమస్తవరాలను ఇచ్చేవాడు, నిర్మలుడు, బ్రహ్మతత్త్వమే అయినవాడు, దేవతలచే నిత్యం స్తుతింపబడే పాదాలు కలవాడు, నిర్వికల్పాది యోగస్థితిలో ఉన్నవాడు, నిత్యానందస్వరూపుడు, వేదాలచే తెలియబడినవాడు, గుణాతీతుడు, దేవదేవుడు, మమకారరహితుడు అయిన కార్తికేయుడిని, నా శ్రేష్ఠగురువును, నిత్యం వందిస్తున్నాను. ఈ శ్లోకంలో దాదాపు ప్రతి పదం 'నిత్య-' లేదా 'నిర్-' తో మొదలవడం గమనించదగినది.",
      hi: "जो नित्य-स्वरूप हैं, समस्त वर देने वाले हैं, निर्मल हैं, ब्रह्मतत्त्व ही हैं, जिनके चरणों की देवगण नित्य वंदना करते हैं, जो निर्विकल्प आदि योग-स्थिति में स्थित हैं, जो नित्यानंद-स्वरूप हैं, वेदों द्वारा ज्ञात हैं, निर्गुण हैं, देवों के देव हैं, ममता-रहित हैं, उन कार्तिकेय को, अपने श्रेष्ठ गुरु को, मैं नित्य वंदन करता हूँ। इस श्लोक के लगभग हर शब्द का आरंभ 'नित्य-' या 'निर्-' से होना उल्लेखनीय है।" },
    { s: 1, n: "6",
      deva: "पञ्चकं कार्तिकेयस्य यः पठेच्छृणुयादपि ।\nकार्तिकेय प्रसादात्स सर्वाभीष्टमवाप्नुयात् ॥",
      iast: "pañcakaṁ kārtikeyasya yaḥ paṭhecchṛṇuyādapi |\nkārtikeya prasādātsa sarvābhīṣṭamavāpnuyāt ||",
      en: "Whoever recites this pañcakam of Kārtikeya, or even only hears it, obtains all his desired wishes through Kārtikeya's grace.",
      tel: "కార్తికేయుని ఈ పంచకాన్ని ఎవరు పఠించినా లేదా విన్నా, వారు కార్తికేయుని అనుగ్రహం వల్ల తమ కోరికలన్నింటినీ పొందుతారు.",
      hi: "जो कार्तिकेय के इस पंचक का पाठ करे या केवल सुने भी, वह कार्तिकेय की कृपा से अपनी समस्त इच्छित वस्तुएँ प्राप्त कर लेता है।\n\n---\nRecension note: This text is not on vignanam.org — several slug guesses (kartikeya-panchakam, subrahmanya-pancha-ratna-stotram, and variants) were tried and none carried it. vignanam.org does host a page titled \"Subrahmanya Pancha Ratna Stotram\" (vignanam.org/veda/subrahmanya-pancha-ratna-stotram-english.html), but its text opens ṣaḍānanaṁ candanalepitāṅgaṁ with the refrain brahmaṇyadevaṁ śaraṇaṁ prapadye — a different composition, matching sanskritdocuments.org's separately catalogued \"subrahmaṇyapañcaratnam 2,\" not this one — so it was set aside. Base text is stotranidhi.com's Devanāgarī edition (fetched via browser rendering, since stotranidhi.com returns 403 to direct WebFetch), which agrees word for word with stotranidhi's own parallel English (IAST) edition. sanskritdocuments.org's doc_subrahmanya catalog independently confirms this is the correct text by title and opening-line fingerprint, listing \"subrahmaṇyapañcaratnam 1 kārtikeyapañcakam (vimalanijapadābjam)\" — matching this text's opening line exactly — though the catalog's own linked file was not itself fetched for a full collation, so this served only as a title/fingerprint check rather than a second independently-sourced text. hariome.com's Telugu-script \"Sri Karthikeya Panchakam\" page was located and independently confirms the same five-verse-plus-phalaśruti structure, but its content could not be quoted verbatim for word-by-word collation (the fetch tool declined to reproduce it, citing copyright). Taken together this is one primary source (stotranidhi) cross-checked against its own parallel Devanāgarī/IAST editions, plus two independent title/structure confirmations from sanskritdocuments and hariome — not a full second line-by-line-sourced collation, so flagged here as reduced cross-checking, in the manner of file 08 in this corpus. On verse count: the source itself numbers six verses (१-६); verses 1-5 are the pañcakam proper and verse 6 is a phalaśruti couplet folded into the same running numbering rather than left unnumbered, reproduced here as its own numbered verse under a separate Phalaśruti section rather than silently dropped or renumbered. No variant readings were encountered between the Devanāgarī and IAST editions collated. Transliteration note: anusvāra is rendered ṁ throughout, matching this corpus's convention; e and o are used without macrons (never ē/ō) per the corpus's classical-IAST convention for Sanskrit texts, even though stotranidhi's own source pages render them ē/ō in a Telugu-influenced romanization." },
  ],
},

{
  deities: ["subrahmanya"],
  title: "Kārtikeya Stotram",
  blurb: "The gods speak the moment Tāraka falls — five verses from the Śiva Purāṇa, praise still catching its breath after the battle.",
  colophon: { deva: "इति शिवपुराणे रुद्रसंहितायां कुमारखण्डे षष्ठाध्यायान्तर्गतं देवैः कृतं कार्तिकेयस्तोत्रं समाप्तम् ॥", iast: "iti śivapurāṇe rudrasaṁhitāyāṁ kumārakhaṇḍe ṣaṣṭhādhyāyāntargataṁ devaiḥ kṛtaṁ kārtikeyastotraṁ samāptam ||" },
  sections: [{ tel: "ఉవాచ", roman: "The Speakers' Frame" }, { tel: "స్తోత్రం", roman: "The Hymn" }],
  verses: [
    { s: 0, n: null,
      deva: "देवा ऊचुः ।",
      iast: "devā ūcuḥ |",
      en: "The gods said — the speech-attribution introducing the hymn that follows.",
      tel: "దేవతలు ఇలా పలికారు — తరువాతి స్తోత్రాన్ని పలికే ముందు వాడిన వాక్యం.",
      hi: "देवताओं ने कहा — आगे के स्तोत्र से पहले प्रयुक्त वाक्य।" },
    { s: 1, n: "2",
      deva: "नमः कल्याणरूपाय नमस्ते विश्वमङ्गल ।\nविश्वबन्धो नमस्तेऽस्तु नमस्ते विश्वभावन ॥",
      iast: "namaḥ kalyāṇarūpāya namaste viśvamaṅgala |\nviśvabandho namaste'stu namaste viśvabhāvana ||",
      en: "Salutation to you of auspicious form; salutation to you, O auspiciousness of the universe (viśvamaṅgala); O bond/kinsman of the universe (viśvabandhu), let there be salutation to you; salutation to you, O nurturer of the universe (viśvabhāvana).",
      tel: "మంగళరూపుడా, నీకు నమస్కారం; విశ్వానికి మంగళకరుడవైన వాడా, నీకు నమస్కారం; విశ్వబంధువా, నీకు నమస్కారమగుగాక; విశ్వాన్ని పోషించువాడా, నీకు నమస్కారం.",
      hi: "मंगलरूप वाले, आपको नमस्कार; विश्व के मंगलस्वरूप, आपको नमस्कार; विश्वबन्धु, आपको नमस्कार हो; विश्व का पोषण करने वाले, आपको नमस्कार।" },
    { s: 1, n: "3",
      deva: "नमोऽस्तु ते दानववर्यहन्त्रे बाणासुरप्राणहराय देव ।\nप्रलम्बनाशाय पवित्ररूपिणे नमो नमश्शङ्करतात तुभ्यम् ॥",
      iast: "namo'stu te dānavavaryahantre bāṇāsuraprāṇaharāya deva |\npralambanāśāya pavitrarūpiṇe namo namaśśaṅkaratāta tubhyam ||",
      en: "Salutation be to you, slayer of the chief of demons, O god who has taken the life-breath of the demon Bāṇāsura; to the destroyer of the demon Pralamba, of pure form — obeisance, obeisance again to you, O dear one born of Śaṅkara.",
      tel: "దానవశ్రేష్ఠుని సంహరించిన నీకు నమస్కారమగుగాక, బాణాసురుని ప్రాణాలను తీసిన దేవా; ప్రలంబాసురుని నశింపజేసిన, పవిత్రరూపుడవైన నీకు మళ్ళీ మళ్ళీ నమస్కారం, శంకరుని ప్రియతనయా.",
      hi: "दानवश्रेष्ठ का संहार करने वाले आपको नमस्कार हो, बाणासुर के प्राण हरने वाले देव; प्रलंबासुर का नाश करने वाले, पवित्ररूप आपको बार-बार नमस्कार, शंकर के प्रिय पुत्र।" },
    { s: 1, n: "4",
      deva: "त्वमेव कर्त्ता जगतां च भर्त्ता त्वमेव हर्त्ता शुचिज प्रसीद ।\nप्रपञ्चभूतस्तव लोकबिम्बः प्रसीद शम्भ्वात्मज दीनबन्धो ॥",
      iast: "tvameva karttā jagatāṁ ca bharttā tvameva harttā śucija prasīda |\nprapañcabhūtastava lokabimbaḥ prasīda śambhvātmaja dīnabandho ||",
      en: "You alone are the creator of the worlds, and you alone their sustainer; you alone are also their destroyer — O pure-born one, be gracious. This visible world is your own reflected image (lokabimba); be gracious, O son of Śambhu, O friend of the humble.",
      tel: "నీవే లోకాలకు సృష్టికర్తవు, నీవే వాటికి పోషకుడవు; నీవే వాటిని లయం చేయువాడవు కూడా — పవిత్రజన్ముడా, ప్రసన్నుడవు కమ్ము. ఈ కనిపించే ప్రపంచం నీ ప్రతిబింబమే; ప్రసన్నుడవు కమ్ము, శంభుపుత్రా, దీనబంధూ.",
      hi: "तुम्हीं जगत् के कर्ता हो, और तुम्हीं उनके भर्ता (पालक) हो; तुम्हीं उनका संहार भी करने वाले हो — पवित्रजन्मा, प्रसन्न हों। यह दिखने वाला संसार तुम्हारा ही प्रतिबिम्ब है; प्रसन्न हों, शम्भुपुत्र, दीनबन्धु।" },
    { s: 1, n: "5",
      deva: "देवरक्षाकर स्वामिन् रक्ष नस्सर्वदा प्रभो ।\nदेवप्राणावनकर प्रसीद करुणाकर ॥",
      iast: "devarakṣākara svāmin rakṣa nassarvadā prabho |\ndevaprāṇāvanakara prasīda karuṇākara ||",
      en: "O master who is the protector of the gods, protect us always, O lord; O guardian of the very life-breath of the gods, be gracious, O fount of compassion.",
      tel: "దేవతల రక్షకుడవైన స్వామీ, మమ్మల్ని ఎల్లప్పుడూ రక్షించు, ప్రభూ; దేవతల ప్రాణాలను కాపాడువాడా, ప్రసన్నుడవు కమ్ము, కరుణాకరా.",
      hi: "देवताओं के रक्षक स्वामी, हमारी सदा रक्षा करें, प्रभो; देवताओं के प्राणों की रक्षा करने वाले, प्रसन्न हों, करुणाकर।" },
    { s: 1, n: "6",
      deva: "हत्वा ते तारकं दैत्यं परिवारयुतं विभो ।\nमोचितास्सकला देवा विपद्भ्यः परमेश्वर ॥",
      iast: "hatvā te tārakaṁ daityaṁ parivārayutaṁ vibho |\nmocitāssakalā devā vipadbhyaḥ parameśvara ||",
      en: "By your slaying, O mighty one, the demon Tāraka together with his retinue, all the gods have been freed from calamity, O supreme lord.",
      tel: "నీవు తారకాసురుని అతని పరివారంతో సహా సంహరించడం వల్ల, విభూ, దేవతలందరూ ఆపదల నుండి విముక్తులయ్యారు, పరమేశ్వరా.",
      hi: "हे विभो, आपके द्वारा परिवार सहित तारकासुर के वध हो जाने पर, समस्त देवता विपत्तियों से मुक्त हो गए, हे परमेश्वर।" },
  ],
},];
