/* ============================================================
   STUTI — Śiva full texts, part 2
   Śiva Tāṇḍava Stotram · Kālabhairavāṣṭakam
   · Dvādaśa Jyotirliṅga Stotram
   Devanāgarī is the source of truth; other scripts are derived at
   read time. `tel` carries the Telugu meaning (అర్థం).
   ============================================================ */
export const extra = [{
  deities: ["shiva"],
  title: "Śiva Tāṇḍava Stotram",
  blurb: "Rāvaṇa's hymn from under the mountain — pañcacāmara metre that beats like the ḍamaru it describes, and the sound is half the meaning.",
  sections: [{ tel: "స్తోత్రం", roman: "The Hymn" }, { tel: "ఫలశ్రుతి", roman: "The Fruit of Recitation" }],
  verses: [
    { s: 0, n: "1",
      deva: "जटाटवीगलज्जलप्रवाहपावितस्थले\nगलेऽवलम्ब्य लम्बितां भुजङ्गतुङ्गमालिकाम् ।\nडमड्डमड्डमड्डमन्निनादवड्डमर्वयं\nचकार चण्डताण्डवं तनोतु नः शिवः शिवम् ॥",
      iast: "jaṭāṭavī-galaj-jala-pravāha-pāvita-sthale\ngale'valambya lambitāṁ bhujaṅga-tuṅga-mālikām ।\nḍamaḍ-ḍamaḍ-ḍamaḍ-ḍaman-ninādavaḍ-ḍamarvayaṁ\ncakāra caṇḍa-tāṇḍavaṁ tanotu naḥ śivaḥ śivam ॥",
      en: "On ground made holy by the water streaming down from the forest of his matted hair, with a tall garland of serpents hanging at his throat, to the ḍamaru sounding ḍamaḍ-ḍamaḍ-ḍamaḍ-ḍaman he danced the fierce tāṇḍava — may that Śiva spread auspiciousness upon us.",
      tel: "జటల అడవి నుండి కారుతున్న గంగా ప్రవాహముచే పవిత్రమైన నేలపై, కంఠమునందు వేలాడుతున్న ఎత్తైన సర్పమాలను ధరించి, డమడ్-డమడ్-డమడ్-డమన్ అను ధ్వనితో డమరుకము మ్రోగుచుండగా ప్రచండ తాండవమును చేసిన ఆ శివుడు మనకు శుభమును విస్తరింపజేయుగాక." },
    { s: 0, n: "2",
      deva: "जटाकटाहसम्भ्रमभ्रमन्निलिम्पनिर्झरी-\nविलोलवीचिवल्लरीविराजमानमूर्धनि ।\nधगद्धगद्धगज्ज्वलल्ललाटपट्टपावके\nकिशोरचन्द्रशेखरे रतिः प्रतिक्षणं मम ॥",
      iast: "jaṭā-kaṭāha-sambhrama-bhraman-nilimpa-nirjharī-\nvilola-vīci-vallarī-virājamāna-mūrdhani ।\ndhagad-dhagad-dhagaj-jvalal-lalāṭa-paṭṭa-pāvake\nkiśora-candra-śekhare ratiḥ pratikṣaṇaṁ mama ॥",
      en: "His head made splendid by the celestial river whirling and swirling in the cauldron of his matted locks, its restless waves like creepers; fire blazing dhagad-dhagad-dhagad on the tablet of his brow; the young moon on his crown — in him, every instant, is my delight.",
      tel: "జటాజూటమనే కుండములో సంభ్రమముతో తిరుగుతున్న ఆకాశగంగ — దాని చంచల తరంగముల తీగలతో ప్రకాశించే శిరస్సు కలవాడు; ధగద్-ధగద్-ధగద్ అని మండుతున్న లలాటాగ్ని కలవాడు; బాలచంద్రుని శిరసున ధరించినవాడు — అట్టివానియందు ప్రతిక్షణము నా ప్రీతి." },
    { s: 0, n: "3",
      deva: "धराधरेन्द्रनन्दिनीविलासबन्धुबन्धुर-\nस्फुरद्दिगन्तसन्ततिप्रमोदमानमानसे ।\nकृपाकटाक्षधोरणीनिरुद्धदुर्धरापदि\nक्वचिद्दिगम्बरे मनो विनोदमेतु वस्तुनि ॥",
      iast: "dharādharendra-nandinī-vilāsa-bandhu-bandhura-\nsphurad-diganta-santati-pramodamāna-mānase ।\nkṛpā-kaṭākṣa-dhoraṇī-niruddha-durdharāpadi\nkvacid-digambare mano vinodam-etu vastuni ॥",
      en: "In him whose mind rejoices in the play of the mountain-king's daughter, a joy that shines to the ends of the sky; in him whose unbroken glance of grace holds back calamities that cannot otherwise be held — in that one clad in the directions, that indescribable Reality, may my mind find its delight.",
      tel: "పర్వతరాజ పుత్రిక విలాసములతో బంధువై, దిగంతముల వరకు వ్యాపించే ఆనందముతో ప్రకాశించే మనస్సు కలవాడు; కృపాకటాక్షముల ధారచేత ఎదురులేని ఆపదలను అడ్డగించువాడు; దిగంబరుడైన ఆ అనిర్వచనీయ వస్తువునందు నా మనస్సు ఆనందించుగాక." },
    { s: 0, n: "4",
      deva: "जटाभुजङ्गपिङ्गलस्फुरत्फणामणिप्रभा-\nकदम्बकुङ्कुमद्रवप्रलिप्तदिग्वधूमुखे ।\nमदान्धसिन्धुरस्फुरत्त्वगुत्तरीयमेदुरे\nमनो विनोदमद्भुतं बिभर्तु भूतभर्तरि ॥",
      iast: "jaṭā-bhujaṅga-piṅgala-sphurat-phaṇā-maṇi-prabhā-\nkadamba-kuṅkuma-drava-pralipta-dig-vadhū-mukhe ।\nmadāndha-sindhura-sphurat-tvag-uttarīya-medure\nmano vinodam-adbhutaṁ bibhartu bhūta-bhartari ॥",
      en: "The tawny serpents in his hair flash the light of the gems on their hoods, and that mass of light smears the faces of the maidens of the quarters as with liquid kumkuma; his upper garment is the glistening hide of the rut-blind elephant — in that sustainer of all beings may my mind bear a wondrous joy.",
      tel: "జటలలోని పింగళవర్ణ సర్పముల పడగలపై మణుల కాంతి కదంబముగా వ్యాపించి, దిక్కులనెడి వధువుల ముఖములకు కుంకుమ ద్రవమును పూసినట్లున్నది; మదముచే గ్రుడ్డియైన గజచర్మము మెరుస్తూ ఉత్తరీయమై దట్టముగా ఉన్నది — అట్టి భూతభర్తయందు నా మనస్సు అద్భుతమైన ఆనందమును పొందుగాక." },
    { s: 0, n: "5",
      deva: "सहस्रलोचनप्रभृत्यशेषलेखशेखर-\nप्रसूनधूलिधोरणी विधूसराङ्घ्रिपीठभूः ।\nभुजङ्गराजमालया निबद्धजाटजूटकः\nश्रियै चिराय जायतां चकोरबन्धुशेखरः ॥",
      iast: "sahasra-locana-prabhṛty-aśeṣa-lekha-śekhara-\nprasūna-dhūli-dhoraṇī vidhūsarāṅghri-pīṭha-bhūḥ ।\nbhujaṅga-rāja-mālayā nibaddha-jāṭa-jūṭakaḥ\nśriyai cirāya jāyatāṁ cakora-bandhu-śekharaḥ ॥",
      en: "The floor beneath his feet is grey with the pollen fallen from the crowns of all the gods, beginning with the thousand-eyed Indra, as they bow; his matted crest is bound with a garland that is the king of serpents — may he who wears the friend of the cakora bird upon his head bring us lasting good fortune.",
      tel: "సహస్రాక్షుడైన ఇంద్రుడు మొదలైన సమస్త దేవతలు నమస్కరించగా, వారి కిరీటముల పుష్పధూళి రాశిచే ఆయన పాదపీఠము ధూసరవర్ణమైనది; సర్పరాజు మాలగా జటాజూటము కట్టబడినది — చంద్రుని శిరసున ధరించిన ఆ స్వామి మనకు చిరకాల సంపదను కలిగించుగాక." },
    { s: 0, n: "6",
      deva: "ललाटचत्वरज्वलद्धनञ्जयस्फुलिङ्गभा-\nनिपीतपञ्चसायकं नमन्निलिम्पनायकम् ।\nसुधामयूखलेखया विराजमानशेखरं\nमहाकपालिसम्पदेशिरोजटालमस्तु नः ॥",
      iast: "lalāṭa-catvara-jvalad-dhanañjaya-sphuliṅga-bhā-\nnipīta-pañca-sāyakaṁ naman-nilimpa-nāyakam ।\nsudhā-mayūkha-lekhayā virājamāna-śekharaṁ\nmahā-kapāli-sampade-śiro-jaṭālam-astu naḥ ॥",
      en: "The spark of the fire blazing in the courtyard of his brow drank up the god of the five arrows; the lords of the gods bow before him; the streak of the nectar-rayed moon makes his crown shine — may the matted head of the great skull-bearer be for our prosperity.",
      tel: "లలాట ప్రదేశమున మండుతున్న అగ్ని స్ఫులింగము పంచబాణుడైన మన్మథుని దహించివేసినది; దేవతానాయకులు నమస్కరించుచున్నారు; అమృతకిరణుడైన చంద్రరేఖచే శిరస్సు ప్రకాశించుచున్నది — ఆ మహాకపాలి జటాజూటము మనకు సంపదను కలిగించుగాక." },
    { s: 0, n: "7",
      deva: "करालभालपट्टिकाधगद्धगद्धगज्ज्वल-\nद्धनञ्जयाहुतीकृतप्रचण्डपञ्चसायके ।\nधराधरेन्द्रनन्दिनीकुचाग्रचित्रपत्रक-\nप्रकल्पनैकशिल्पिनि त्रिलोचने रतिर्मम ॥",
      iast: "karāla-bhāla-paṭṭikā-dhagad-dhagad-dhagaj-jvala-\nd-dhanañjayāhutī-kṛta-pracaṇḍa-pañca-sāyake ।\ndharādharendra-nandinī-kucāgra-citra-patraka-\nprakalpanaika-śilpini trilocane ratir-mama ॥",
      en: "In him who made an oblation of the fierce five-arrowed god in the fire blazing dhagad-dhagad-dhagad on the terrible tablet of his brow; who is the one artist who paints the delicate designs on the breast of the mountain-king's daughter — in that three-eyed one is my delight.",
      tel: "భయంకరమైన లలాటఫలకమున ధగద్-ధగద్-ధగద్ అని మండుతున్న అగ్నియందు ప్రచండుడైన పంచసాయకుని ఆహుతిగా చేసినవాడు; పర్వతరాజ పుత్రిక వక్షమున చిత్రపత్రములను రచించే ఏకైక శిల్పి — ఆ త్రిలోచనునియందు నా ప్రీతి." },
    { s: 0, n: "8",
      deva: "नवीनमेघमण्डली निरुद्धदुर्धरस्फुरत्-\nकुहूनिशीथिनीतमः प्रबन्धबद्धकन्धरः ।\nनिलिम्पनिर्झरीधरस्तनोतु कृत्तिसिन्धुरः\nकलानिधानबन्धुरः श्रियं जगद्धुरन्धरः ॥",
      iast: "navīna-megha-maṇḍalī niruddha-durdhara-sphurat-\nkuhū-niśīthinī-tamaḥ prabandha-baddha-kandharaḥ ।\nnilimpa-nirjharī-dharas-tanotu kṛtti-sindhuraḥ\nkalā-nidhāna-bandhuraḥ śriyaṁ jagad-dhurandharaḥ ॥",
      en: "His throat is dark as the impenetrable midnight of the new moon held fast within a bank of fresh rain-clouds; he bears the celestial river, wears the elephant's hide, is graced by the storehouse of digits — may he who carries the burden of the world grant us prosperity.",
      tel: "క్రొత్త మేఘమండలముచే నిరోధించబడిన అమావాస్య అర్ధరాత్రి చీకటివలె నల్లనైన కంఠము కలవాడు; ఆకాశగంగను ధరించినవాడు, గజచర్మధారి, కళానిధియైన చంద్రునిచే సుందరుడు — జగద్భారమును వహించే ఆ స్వామి మనకు సంపదను ఇచ్చుగాక." },
    { s: 0, n: "9",
      deva: "प्रफुल्लनीलपङ्कजप्रपञ्चकालिमप्रभा-\nवलम्बिकण्ठकन्दलीरुचिप्रबद्धकन्धरम् ।\nस्मरच्छिदं पुरच्छिदं भवच्छिदं मखच्छिदं\nगजच्छिदान्धकच्छिदं तमन्तकच्छिदं भजे ॥",
      iast: "praphulla-nīla-paṅkaja-prapañca-kālima-prabhā-\nvalambi-kaṇṭha-kandalī-ruci-prabaddha-kandharam ।\nsmara-cchidaṁ pura-cchidaṁ bhava-cchidaṁ makha-cchidaṁ\ngaja-cchidāndhaka-cchidaṁ tam-antaka-cchidaṁ bhaje ॥",
      en: "His neck holds the beauty of a shoot dark as the spreading blue of a full-blown lotus. Sunderer of Kāma, of the Three Cities, of worldly existence, of Dakṣa's sacrifice; slayer of the elephant demon and of Andhaka, and cutter of Death himself — him I worship.",
      tel: "వికసించిన నల్లకలువల నలుపు కాంతి వంటి శోభతో అలరారే కంఠము కలవాడు; మన్మథుని ఛేదించినవాడు, త్రిపురములను ఛేదించినవాడు, సంసారమును ఛేదించువాడు, దక్షయజ్ఞమును ఛేదించినవాడు; గజాసురుని, అంధకాసురుని సంహరించినవాడు, యముని జయించినవాడు — అట్టివానిని భజించుచున్నాను." },
    { s: 0, n: "10",
      deva: "अखर्वसर्वमङ्गलाकलाकदम्बमञ्जरी-\nरसप्रवाहमाधुरीविजृम्भणामधुव्रतम् ।\nस्मरान्तकं पुरान्तकं भवान्तकं मखान्तकं\nगजान्तकान्धकान्तकं तमन्तकान्तकं भजे ॥",
      iast: "akharva-sarva-maṅgalā-kalā-kadamba-mañjarī-\nrasa-pravāha-mādhurī-vijṛmbhaṇā-madhuvratam ।\nsmarāntakaṁ purāntakaṁ bhavāntakaṁ makhāntakaṁ\ngajāntakāndhakāntakaṁ tam-antakāntakaṁ bhaje ॥",
      en: "He is the bee that drinks the swelling sweetness flowing from the kadamba-cluster of arts belonging to Pārvatī, whose auspiciousness is undiminished. Ender of Kāma, of the Three Cities, of worldly existence, of the sacrifice; ender of the elephant demon and of Andhaka, and the end of Death — him I worship.",
      tel: "తరుగని సర్వమంగళయైన పార్వతి కళలనెడి కదంబ మంజరి నుండి ప్రవహించే మధురరసమును గ్రోలే తుమ్మెద ఆయన; మన్మథాంతకుడు, త్రిపురాంతకుడు, భవాంతకుడు, మఖాంతకుడు; గజాంతకుడు, అంధకాంతకుడు, యమునకే అంతకుడు — అట్టివానిని భజించుచున్నాను." },
    { s: 0, n: "11",
      deva: "जयत्वदभ्रविभ्रमभ्रमद्भुजङ्गमश्वस-\nद्विनिर्गमत्क्रमस्फुरत्करालभालहव्यवाट् ।\nधिमिद्धिमिद्धिमिध्वनन्मृदङ्गतुङ्गमङ्गल-\nध्वनिक्रमप्रवर्तितप्रचण्डताण्डवः शिवः ॥",
      iast: "jayatv-adabhra-vibhrama-bhramad-bhujaṅgama-śvasa-\nd-vinirgamat-krama-sphurat-karāla-bhāla-havyavāṭ ।\ndhimid-dhimid-dhimi-dhvanan-mṛdaṅga-tuṅga-maṅgala-\ndhvani-krama-pravartita-pracaṇḍa-tāṇḍavaḥ śivaḥ ॥",
      en: "Victory to Śiva, on whose terrible brow the fire leaps higher with each breath of the serpents whirling in their great dance; who set the fierce tāṇḍava going to the rising auspicious beat of the mṛdaṅga sounding dhimi-dhimi-dhimi.",
      tel: "గొప్ప విన్యాసముతో తిరుగుతున్న సర్పముల ఊర్పులతో లలాటాగ్ని క్రమముగా ఎగసి మండుచుండగా; ధిమి-ధిమి-ధిమి అని మ్రోగుతున్న మృదంగపు మంగళ ధ్వని క్రమమునకు ప్రచండ తాండవమును సాగించిన శివునకు జయమగుగాక." },
    { s: 0, n: "12",
      deva: "दृषद्विचित्रतल्पयोर्भुजङ्गमौक्तिकस्रजोर्-\nगरिष्ठरत्नलोष्ठयोः सुहृद्विपक्षपक्षयोः ।\nतृष्णारविन्दचक्षुषोः प्रजामहीमहेन्द्रयोः\nसमं प्रवर्तयन्मनः कदा सदाशिवं भजे ॥",
      iast: "dṛṣad-vicitra-talpayor-bhujaṅga-mauktika-srajor-\ngariṣṭha-ratna-loṣṭhayoḥ suhṛd-vipakṣa-pakṣayoḥ ।\ntṛṣṇāravinda-cakṣuṣoḥ prajā-mahī-mahendrayoḥ\nsamaṁ pravartayan-manaḥ kadā sadāśivaṁ bhaje ॥",
      en: "When shall I worship Sadāśiva, holding my mind level between a stone and a splendid bed, a serpent and a pearl necklace, a precious gem and a clod of earth, the side of a friend and the side of a foe, a lotus and an eye, the common folk and the lord of the earth?",
      tel: "రాతిపైనైనను, చిత్రమైన పాన్పుపైనను; సర్పమునందైనను, ముత్యాలహారమునందైనను; విలువైన రత్నమునందైనను, మట్టిగడ్డయందైనను; మిత్రపక్షమునందైనను, శత్రుపక్షమునందైనను; కలువయందైనను, కంటియందైనను; సామాన్య ప్రజలయందైనను, మహారాజునందైనను — సమభావముతో మనస్సును నిలిపి ఎప్పుడు సదాశివుని భజించెదను?" },
    { s: 0, n: "13",
      deva: "कदा निलिम्पनिर्झरीनिकुञ्जकोटरे वसन्\nविमुक्तदुर्मतिः सदा शिरःस्थमञ्जलिं वहन् ।\nविमुक्तलोललोचनो ललामभाललग्नकः\nशिवेति मन्त्रमुच्चरन् कदा सुखी भवाम्यहम् ॥",
      iast: "kadā nilimpa-nirjharī-nikuñja-koṭare vasan\nvimukta-durmatiḥ sadā śiraḥ-stham-añjaliṁ vahan ।\nvimukta-lola-locano lalāma-bhāla-lagnakaḥ\nśiveti mantram-uccaran kadā sukhī bhavāmy-aham ॥",
      en: "When, dwelling in a hollow among the thickets by the celestial river, free of an evil mind, my hands always joined above my head, my restless eyes stilled, my thought fixed on the one with the beautiful brow, uttering the mantra ‘Śiva' — when shall I become happy?",
      tel: "ఆకాశగంగ ఒడ్డున పొదల మధ్య ఒక గుహలో నివసిస్తూ, దుర్బుద్ధిని విడిచి, సదా శిరస్సుపై అంజలి ధరించి, చంచల దృష్టిని విడిచి, సుందర లలాటుడైన శివునియందే మనస్సు నిలిపి, 'శివ' అను మంత్రమును ఉచ్చరించుచు — నేను ఎప్పుడు సుఖిని అగుదును?" },
    { s: 1, n: "14",
      deva: "इदं हि नित्यमेवमुक्तमुत्तमोत्तमं स्तवं\nपठन्स्मरन्ब्रुवन्नरो विशुद्धिमेति सन्ततम् ।\nहरे गुरौ सुभक्तिमाशु याति नान्यथा गतिं\nविमोहनं हि देहिनां सुशङ्करस्य चिन्तनम् ॥",
      iast: "idaṁ hi nityam-evam-uktam-uttamottamaṁ stavaṁ\npaṭhan-smaran-bruvan-naro viśuddhim-eti santatam ।\nhare gurau subhaktim-āśu yāti nānyathā gatiṁ\nvimohanaṁ hi dehināṁ suśaṅkarasya cintanam ॥",
      en: "One who daily reads, remembers or recites this best of hymns, spoken thus, is continually purified; he swiftly gains true devotion to Hara and to the guru, and takes no other course — for the contemplation of the gracious Śaṅkara scatters the delusion of embodied beings.",
      tel: "ఈ ఉత్తమోత్తమమైన స్తవమును ప్రతిదినము పఠించువాడు, స్మరించువాడు, ఉచ్చరించువాడు నిరంతరము శుద్ధిని పొందును; హరునియందు, గురువునందు శీఘ్రముగా భక్తిని పొంది, వేరొక గతిని పొందడు — శంకరుని చింతనము దేహధారుల మోహమును పోగొట్టును." },
    { s: 1, n: "15",
      deva: "पूजावसानसमये दशवक्त्रगीतं\nयः शम्भुपूजनपरं पठति प्रदोषे ।\nतस्य स्थिरां रथगजेन्द्रतुरङ्गयुक्तां\nलक्ष्मीं सदैव सुमुखीं प्रददाति शम्भुः ॥",
      iast: "pūjāvasāna-samaye daśa-vaktra-gītaṁ\nyaḥ śambhu-pūjana-paraṁ paṭhati pradoṣe ।\ntasya sthirāṁ ratha-gajendra-turaṅga-yuktāṁ\nlakṣmīṁ sadaiva sumukhīṁ pradadāti śambhuḥ ॥",
      en: "To one who, at the close of worship in the pradoṣa hour, recites this song of the ten-faced one, given wholly to the worship of Śambhu, Śambhu grants a steady and gracious fortune — with chariots, great elephants and horses.",
      tel: "పూజ ముగింపు సమయమున, ప్రదోష కాలమునందు, శంభుపూజాపరుడై ఈ దశకంఠుని గీతమును ఎవరు పఠించెదరో — వారికి రథములు, గజేంద్రములు, అశ్వములతో కూడిన స్థిరమైన, ప్రసన్నమైన లక్ష్మిని శంభుడు సదా ప్రసాదించును." },
  ],
},

{
  deities: ["shiva"],
  title: "Kālabhairavāṣṭakam",
  blurb: "Eight verses to the guardian of Kāśī — the one who keeps the city's ledger of merit and sin, terrible and gracious in the same breath.",
  sections: [{ tel: "స్తోత్రం", roman: "The Eight Verses" }, { tel: "ఫలశ్రుతి", roman: "The Fruit of Recitation" }],
  verses: [
    { s: 0, n: "1",
      deva: "देवराजसेव्यमानपावनाङ्घ्रिपङ्कजं\nव्यालयज्ञसूत्रमिन्दुशेखरं कृपाकरम् ।\nनारदादियोगिवृन्दवन्दितं दिगम्बरं\nकाशिकापुराधिनाथकालभैरवं भजे ॥",
      iast: "devarāja-sevyamāna-pāvanāṅghri-paṅkajaṁ\nvyāla-yajña-sūtram-indu-śekharaṁ kṛpākaram ।\nnāradādi-yogi-vṛnda-vanditaṁ digambaraṁ\nkāśikā-purādhinātha-kālabhairavaṁ bhaje ॥",
      en: "His holy lotus feet are served by the king of the gods; a serpent is his sacred thread, the moon his crest, and he is a mine of grace; Nārada and the throng of yogins bow to him, and he is clad in the directions — I worship Kālabhairava, the sovereign of the city of Kāśī.",
      tel: "దేవరాజు సేవించే పవిత్ర పాదపద్మములు కలవాడు; సర్పమే యజ్ఞోపవీతము, చంద్రుడు శిరోభూషణము, కృపకు నిధియైనవాడు; నారదాది యోగివృందముచే వందించబడినవాడు, దిగంబరుడు — కాశికాపురాధినాథుడైన కాలభైరవుని భజించుచున్నాను." },
    { s: 0, n: "2",
      deva: "भानुकोटिभास्वरं भवाब्धितारकं परं\nनीलकण्ठमीप्सितार्थदायकं त्रिलोचनम् ।\nकालकालमम्बुजाक्षमक्षशूलमक्षरं\nकाशिकापुराधिनाथकालभैरवं भजे ॥",
      iast: "bhānu-koṭi-bhāsvaraṁ bhavābdhi-tārakaṁ paraṁ\nnīlakaṇṭham-īpsitārtha-dāyakaṁ trilocanam ।\nkāla-kālam-ambujākṣam-akṣa-śūlam-akṣaraṁ\nkāśikā-purādhinātha-kālabhairavaṁ bhaje ॥",
      en: "Blazing as ten million suns, the ferryman across the ocean of birth, the supreme one; blue-throated, giver of what is longed for, three-eyed; Death to Death himself, lotus-eyed, bearing the trident, imperishable — I worship Kālabhairava, the sovereign of the city of Kāśī.",
      tel: "కోటి సూర్యుల కాంతితో ప్రకాశించువాడు, భవసాగరమును దాటించువాడు, పరముడు; నీలకంఠుడు, కోరిన అర్థములనిచ్చువాడు, త్రిలోచనుడు; కాలునికే కాలుడు, పద్మనేత్రుడు, శూలధారి, అక్షరుడు — కాశికాపురాధినాథుడైన కాలభైరవుని భజించుచున్నాను." },
    { s: 0, n: "3",
      deva: "शूलटङ्कपाशदण्डपाणिमादिकारणं\nश्यामकायमादिदेवमक्षरं निरामयम् ।\nभीमविक्रमं प्रभुं विचित्रताण्डवप्रियं\nकाशिकापुराधिनाथकालभैरवं भजे ॥",
      iast: "śūla-ṭaṅka-pāśa-daṇḍa-pāṇim-ādi-kāraṇaṁ\nśyāma-kāyam-ādi-devam-akṣaraṁ nirāmayam ।\nbhīma-vikramaṁ prabhuṁ vicitra-tāṇḍava-priyaṁ\nkāśikā-purādhinātha-kālabhairavaṁ bhaje ॥",
      en: "Trident, axe, noose and staff in his hands, the first cause of all; dark of body, the primordial god, imperishable, without affliction; of terrible valour, the Lord, who loves the wondrous tāṇḍava — I worship Kālabhairava, the sovereign of the city of Kāśī.",
      tel: "శూలము, టంకము, పాశము, దండము చేతులలో ధరించినవాడు, ఆదికారణుడు; నల్లని దేహము కలవాడు, ఆదిదేవుడు, అక్షరుడు, నిరామయుడు; భయంకర పరాక్రముడు, ప్రభువు, విచిత్ర తాండవప్రియుడు — కాశికాపురాధినాథుడైన కాలభైరవుని భజించుచున్నాను." },
    { s: 0, n: "4",
      deva: "भुक्तिमुक्तिदायकं प्रशस्तचारुविग्रहं\nभक्तवत्सलं स्थितं समस्तलोकविग्रहम् ।\nविनिक्वणन्मनोज्ञहेमकिङ्किणीलसत्कटिं\nकाशिकापुराधिनाथकालभैरवं भजे ॥",
      iast: "bhukti-mukti-dāyakaṁ praśasta-cāru-vigrahaṁ\nbhakta-vatsalaṁ sthitaṁ samasta-loka-vigraham ।\nvinikvaṇan-manojña-hema-kiṅkiṇī-lasat-kaṭiṁ\nkāśikā-purādhinātha-kālabhairavaṁ bhaje ॥",
      en: "Giver of enjoyment and of liberation, of a form both praised and lovely; tender to his devotees, steady, his body all the worlds; his waist bright with little golden bells that chime sweetly — I worship Kālabhairava, the sovereign of the city of Kāśī.",
      tel: "భుక్తిని, ముక్తిని ఇచ్చువాడు, ప్రశస్తమైన సుందర విగ్రహము కలవాడు; భక్తవత్సలుడు, స్థిరుడు, సమస్త లోకములే తన స్వరూపముగా కలవాడు; మనోహరముగా మ్రోగే బంగారు గజ్జెలతో ప్రకాశించే కటిప్రదేశము కలవాడు — కాశికాపురాధినాథుడైన కాలభైరవుని భజించుచున్నాను." },
    { s: 0, n: "5",
      deva: "धर्मसेतुपालकं त्वधर्ममार्गनाशकं\nकर्मपाशमोचकं सुशर्मदायकं विभुम् ।\nस्वर्णवर्णशेषपाशशोभिताङ्गमण्डलं\nकाशिकापुराधिनाथकालभैरवं भजे ॥",
      iast: "dharma-setu-pālakaṁ tv-adharma-mārga-nāśakaṁ\nkarma-pāśa-mocakaṁ suśarma-dāyakaṁ vibhum ।\nsvarṇa-varṇa-śeṣa-pāśa-śobhitāṅga-maṇḍalaṁ\nkāśikā-purādhinātha-kālabhairavaṁ bhaje ॥",
      en: "Keeper of the causeway of dharma, destroyer of the road of adharma; loosener of the bonds of karma, giver of true refuge, the all-pervading; his body adorned by the golden-hued serpent Śeṣa as a cord — I worship Kālabhairava, the sovereign of the city of Kāśī.",
      tel: "ధర్మసేతువును కాపాడువాడు, అధర్మ మార్గమును నాశనము చేయువాడు; కర్మపాశములను విడిపించువాడు, శుభమైన ఆశ్రయమునిచ్చువాడు, విభుడు; బంగారు వర్ణపు శేషనాగము పాశముగా అలంకరించిన శరీరము కలవాడు — కాశికాపురాధినాథుడైన కాలభైరవుని భజించుచున్నాను." },
    { s: 0, n: "6",
      deva: "रत्नपादुकाप्रभाभिरामपादयुग्मकं\nनित्यमद्वितीयमिष्टदैवतं निरञ्जनम् ।\nमृत्युदर्पनाशनं करालदंष्ट्रभूषणं\nकाशिकापुराधिनाथकालभैरवं भजे ॥",
      iast: "ratna-pādukā-prabhābhirāma-pāda-yugmakaṁ\nnityam-advitīyam-iṣṭa-daivataṁ nirañjanam ।\nmṛtyu-darpa-nāśanaṁ karāla-daṁṣṭra-bhūṣaṇaṁ\nkāśikā-purādhinātha-kālabhairavaṁ bhaje ॥",
      en: "His pair of feet beautiful with the light of jewelled sandals; eternal, without a second, the chosen deity, untouched by stain; destroyer of the pride of Death, adorned with terrible fangs — I worship Kālabhairava, the sovereign of the city of Kāśī.",
      tel: "రత్నపాదుకల కాంతితో అభిరామమైన పాదద్వయము కలవాడు; నిత్యుడు, అద్వితీయుడు, ఇష్టదైవము, నిరంజనుడు; మృత్యువు గర్వమును నాశనము చేయువాడు, కరాళమైన కోరలే భూషణముగా కలవాడు — కాశికాపురాధినాథుడైన కాలభైరవుని భజించుచున్నాను." },
    { s: 0, n: "7",
      deva: "अट्टहासभिन्नपद्मजाण्डकोशसन्ततिं\nदृष्टिपातनष्टपापजालमुग्रशासनम् ।\nअष्टसिद्धिदायकं कपालमालिकाधरं\nकाशिकापुराधिनाथकालभैरवं भजे ॥",
      iast: "aṭṭahāsa-bhinna-padmajāṇḍa-kośa-santatiṁ\ndṛṣṭi-pāta-naṣṭa-pāpa-jālam-ugra-śāsanam ।\naṣṭa-siddhi-dāyakaṁ kapāla-mālikā-dharaṁ\nkāśikā-purādhinātha-kālabhairavaṁ bhaje ॥",
      en: "His roar of laughter splits the shells of Brahmā's egg, world upon world; the fall of his glance destroys the whole net of sin; his rule is fierce; he grants the eight powers and wears the garland of skulls — I worship Kālabhairava, the sovereign of the city of Kāśī.",
      tel: "అట్టహాసముచే బ్రహ్మాండ కోశముల పరంపరను భేదించువాడు; దృష్టిపాతముచేతనే పాపసముదాయమును నశింపజేయువాడు, ఉగ్రమైన శాసనము కలవాడు; అష్టసిద్ధులనిచ్చువాడు, కపాలమాలను ధరించినవాడు — కాశికాపురాధినాథుడైన కాలభైరవుని భజించుచున్నాను." },
    { s: 0, n: "8",
      deva: "भूतसङ्घनायकं विशालकीर्तिदायकं\nकाशिवासलोकपुण्यपापशोधकं विभुम् ।\nनीतिमार्गकोविदं पुरातनं जगत्पतिं\nकाशिकापुराधिनाथकालभैरवं भजे ॥",
      iast: "bhūta-saṅgha-nāyakaṁ viśāla-kīrti-dāyakaṁ\nkāśi-vāsa-loka-puṇya-pāpa-śodhakaṁ vibhum ।\nnīti-mārga-kovidaṁ purātanaṁ jagat-patiṁ\nkāśikā-purādhinātha-kālabhairavaṁ bhaje ॥",
      en: "Leader of the hosts of spirits, giver of far-reaching fame; the one who audits the merit and sin of the people who dwell in Kāśī, the all-pervading; versed in the way of right conduct, ancient, lord of the world — I worship Kālabhairava, the sovereign of the city of Kāśī.",
      tel: "భూతగణములకు నాయకుడు, విశాలమైన కీర్తినిచ్చువాడు; కాశీలో నివసించే జనుల పుణ్యపాపములను శోధించువాడు, విభుడు; నీతిమార్గమునందు నిపుణుడు, పురాతనుడు, జగత్పతి — కాశికాపురాధినాథుడైన కాలభైరవుని భజించుచున్నాను." },
    { s: 1, n: null,
      deva: "कालभैरवाष्टकं पठन्ति ये मनोहरं\nज्ञानमुक्तिसाधनं विचित्रपुण्यवर्धनम् ।\nशोकमोहदैन्यलोभकोपतापनाशनं\nते प्रयान्ति कालभैरवाङ्घ्रिसन्निधिं ध्रुवम् ॥",
      iast: "kālabhairavāṣṭakaṁ paṭhanti ye manoharaṁ\njñāna-mukti-sādhanaṁ vicitra-puṇya-vardhanam ।\nśoka-moha-dainya-lobha-kopa-tāpa-nāśanaṁ\nte prayānti kālabhairavāṅghri-sannidhiṁ dhruvam ॥",
      en: "Those who recite this lovely Kālabhairavāṣṭaka — a means to knowledge and release, increasing merit in wonderful ways, destroying grief, delusion, meanness, greed, anger and fever — go without fail to the presence of Kālabhairava's feet.",
      tel: "జ్ఞానమునకు, ముక్తికి సాధనమై, విచిత్రముగా పుణ్యమును వృద్ధిచేసి, శోకము, మోహము, దైన్యము, లోభము, కోపము, తాపములను నశింపజేసే ఈ మనోహరమైన కాలభైరవాష్టకమును ఎవరు పఠించెదరో, వారు నిశ్చయముగా కాలభైరవుని పాదసన్నిధిని చేరుదురు." },
  ],
},

{
  deities: ["shiva"],
  title: "Dvādaśa Jyotirliṅga Stotram",
  blurb: "Four verses that name the twelve liṅgas of light and where each one stands — a pilgrimage the length of India, recited morning and evening.",
  sections: [{ tel: "ద్వాదశ జ్యోతిర్లింగములు", roman: "The Twelve" }, { tel: "ఫలశ్రుతి", roman: "The Fruit of Recitation" }],
  verses: [
    { s: 0, n: "1",
      deva: "सौराष्ट्रे सोमनाथं च श्रीशैले मल्लिकार्जुनम् ।\nउज्जयिन्यां महाकालमोंकारममलेश्वरम् ॥",
      iast: "saurāṣṭre somanāthaṁ ca śrīśaile mallikārjunam ।\nujjayinyāṁ mahākālam-oṁkāram-amaleśvaram ॥",
      en: "Somanātha in Saurāṣṭra, Mallikārjuna on Śrīśaila, Mahākāla at Ujjayinī, Oṁkāra — that is, Amaleśvara.",
      tel: "సౌరాష్ట్రమునందు సోమనాథుడు, శ్రీశైలమునందు మల్లికార్జునుడు, ఉజ్జయినిలో మహాకాలుడు, ఓంకారుడు — అనగా అమలేశ్వరుడు." },
    { s: 0, n: "2",
      deva: "परल्यां वैद्यनाथं च डाकिन्यां भीमशंकरम् ।\nसेतुबन्धे तु रामेशं नागेशं दारुकावने ॥",
      iast: "paralyāṁ vaidyanāthaṁ ca ḍākinyāṁ bhīmaśaṅkaram ।\nsetubandhe tu rāmeśaṁ nāgeśaṁ dārukāvane ॥",
      en: "Vaidyanātha at Paralī, Bhīmaśaṅkara in Ḍākinī, Rāmeśa at the bridge of Setu, and Nāgeśa in the Dāruka forest.",
      tel: "పరళిలో వైద్యనాథుడు, డాకినిలో భీమశంకరుడు, సేతుబంధమునందు రామేశ్వరుడు, దారుకావనమునందు నాగేశ్వరుడు." },
    { s: 0, n: "3",
      deva: "वाराणस्यां तु विश्वेशं त्र्यम्बकं गौतमीतटे ।\nहिमालये तु केदारं घुश्मेशं च शिवालये ॥",
      iast: "vārāṇasyāṁ tu viśveśaṁ tryambakaṁ gautamī-taṭe ।\nhimālaye tu kedāraṁ ghuśmeśaṁ ca śivālaye ॥",
      en: "Viśveśa at Vārāṇasī, Tryambaka on the bank of the Gautamī, Kedāra in the Himālaya, and Ghuśmeśa at Śivālaya.",
      tel: "వారాణసిలో విశ్వేశ్వరుడు, గౌతమీ నదీ తీరమున త్ర్యంబకుడు, హిమాలయమునందు కేదారుడు, శివాలయమునందు ఘుశ్మేశ్వరుడు." },
    { s: 1, n: "4",
      deva: "एतानि ज्योतिर्लिङ्गानि सायं प्रातः पठेन्नरः ।\nसप्तजन्मकृतं पापं स्मरणेन विनश्यति ॥",
      iast: "etāni jyotirliṅgāni sāyaṁ prātaḥ paṭhen-naraḥ ।\nsapta-janma-kṛtaṁ pāpaṁ smaraṇena vinaśyati ॥",
      en: "Whoever recites these jyotirliṅgas evening and morning — by that remembrance the sin done in seven births is destroyed.",
      tel: "ఈ జ్యోతిర్లింగముల నామములను సాయంకాలము, ఉదయము ఎవరు పఠించెదరో — ఆ స్మరణము చేత ఏడు జన్మలలో చేసిన పాపము నశించును." },
  ],
},];
