// Brings the Google Fonts the design loads into the app itself, so no reader's
// device asks Google for them (their IP would go with the request, which GDPR
// counts as personal data) and the fonts work offline from the first launch.
// Run once, and again only if the design's font list changes:
//   node tools/fonts-local.mjs
// Writes public/fonts/google/*.woff2 and public/fonts/google/fonts.css. Only the
// scripts the app shows are kept: latin, latin-ext, devanagari, telugu.
// tools/codemod/fix-local-fonts.mjs then points the generated files at fonts.css.
import { mkdirSync, writeFileSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "public/fonts/google");
const KEEP = new Set(["latin", "latin-ext", "devanagari", "telugu"]);
const UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36";

/* the families: whatever stuti.css imports, plus the one index.html links */
const css = readFileSync(join(ROOT, "../design_handoff_stuti/app/stuti.css"), "utf8");
const m = css.match(/@import url\('(https:\/\/fonts\.googleapis\.com\/css2\?[^']+)'\)/);
if (!m) throw new Error("fonts-local: no Google Fonts @import in design stuti.css");
const urls = [m[1], "https://fonts.googleapis.com/css2?family=Mallanna&display=swap"];

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });
let out = "/* Generated by tools/fonts-local.mjs from Google Fonts (SIL Open Font License). Do not edit. */\n";
let files = 0, bytes = 0;
for (const u of urls) {
  const r = await fetch(u, { headers: { "User-Agent": UA } });
  if (!r.ok) throw new Error("fonts-local: " + r.status + " " + u);
  const text = await r.text();
  for (const block of text.split(/(?=\/\* [a-z-]+ \*\/)/)) {
    const sub = (block.match(/^\/\* ([a-z-]+) \*\//) || [])[1];
    if (!sub || !KEEP.has(sub)) continue;
    const src = block.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/);
    if (!src) continue;
    const fam = (block.match(/font-family: '([^']+)'/) || [])[1].replace(/\s+/g, "");
    const wt = (block.match(/font-weight: ([\d ]+);/) || [])[1].trim().replace(" ", "-");
    const name = `${fam}-${wt}-${sub}.woff2`;
    const f = await fetch(src[1]);
    if (!f.ok) throw new Error("fonts-local: " + f.status + " " + src[1]);
    const buf = Buffer.from(await f.arrayBuffer());
    writeFileSync(join(OUT, name), buf);
    files++; bytes += buf.length;
    out += block.replace(src[1], name).trim() + "\n";
  }
}
writeFileSync(join(OUT, "fonts.css"), out);
console.log(`fonts-local: ${files} files, ${(bytes / 1048576).toFixed(1)} MB`);
